### ISSUE TITLE
Option to not use wallet info

### ISSUE THREAD

**Issue by Pascal66** [Creepsky/creepMiner#101]
As the wallet info is only needed for alias and winner, it can be usefull to not use that as an false/true option. Can avoid multiple call to the api when nobody listen tothis info after some time, and allready availble to the miner website.

**Comment by Creepsky** [comment]
You can leave the setting for the wallet blank.
Then the miner will not gather informations from the wallet.

**Comment by Pascal66** [comment]
👍
