### ISSUE TITLE
Question - what are verifier threads?

### ISSUE THREAD

**Issue by Axadiw** [Creepsky/creepMiner#102]
Hi,

I have been reading wiki page describing miner configuration, and I've found description of **miningIntensity** option:

```
The mining intensity sets the amount of verifier threads, that verify plot files asynchronously read by the plotfile-reader.
```

Could you explan what exactly those verifier threads are doing, and how it's affecting mining process. Could I potentially increase mining performance by increasing / decreasing this value?

**Comment by Creepsky** [comment]
Hi,

here is a picture to explain it:

![read-process](https://cloud.githubusercontent.com/assets/8005422/25302442/6258f808-273e-11e7-857f-e838ee85ad2a.png)

Verifiers (miningIntensity) and readers (maxPlotReaders) are each executed in a separate thread and perform their work simultaneously.

The principle is quite simple: the readers read the files in chunks and put their work on a common stack.
They do this as long as there is still enough memory (maxBufferSizeMB).
The verifiers now wait for the work of the readers and take them as soon as they appear on the stack.
All found nonces inside the plot chunk are sent to the miner, which then processes them further.

To optimize the entire process, the three settings **maxBufferSizeMB**, **maxPlotReaders** and **miningIntensity** must be compatible with one another.

| Setting | Too low |
| -------- | -------- |
| maxBufferSizeMB | plot readers have to wait for free memory (freed by the verifiers) |
| maxPlotReaders | the stack is filled too slow and verifiers have to wait for work |
| miningIntensity | the stack is cleared too slow and readers have to wait for free memory |

"Too high" would mean that system capacities have been exceeded. In this case, the system would react very sluggishly.

Other things that you have to consider in the calculation:
- CPU limits (cores)
- plot dir types (parallel, sequential, #86) and speed
- operating system (on Linux threads are more lightweight then on Windows)

Hope this helps a little bit... all in all its a very complex topic, but to answer your question if you could potentially increase your mining performance by increasing/decreasing the mining intensity: yes, there is a chance!

**Comment by Axadiw** [comment]
Thanks, that explanation is awesome. I will experiment with *miningIntensity* :)

I guess that this kind of explanation could be added to wiki, don't you think?:)
