### ISSUE TITLE
Miner stops working after some time

### ISSUE THREAD

**Issue by fayf** [Creepsky/creepMiner#105]
Currently using the 1.6.0 release compiled on Ubuntu 16.04. After the miner has been running for an arbitrary amount of time, it gets stuck in a state where it does nothing. It seems to have a problem in trying to stop the plot reader.

Snippet from attached log:
```
09.05.2017 20:32:30 (0, src/Miner.cpp, 172, Debug): Clearing queues, plot-read-queue: 1, verification-queue: 0
09.05.2017 20:32:30 (0, src/Miner.cpp, 175, Debug): Deallocating memory, used: 0.0 MB
09.05.2017 20:32:30 (0, src/Miner.cpp, 177, Debug): Verification queue cleared.
```

From this point, this just repeats for every new block, and no plotfiles are read ever again, until I restart the miner. This has happened on 3 occasions in the past 2 weeks of 24/7 mining now.

[creepMiner_20170508_085645.204225.txt](https://github.com/Creepsky/creepMiner/files/988550/creepMiner_20170508_085645.204225.txt)

**Comment by Creepsky** [comment]
Thought I fixed this in #82, but apparently it is still there.
Will take a closer look.

**Comment by Creepsky** [comment]
Can you please try the branch https://github.com/Creepsky/creepMiner/tree/unstuck-reader.

**Comment by BurnMe2** [comment]
Hi,

creepsky here is my log file. On Burstcoin Forum the upload didn't worked (BurnMe). So one thing i mentioned in the log is that the logfile is 2 hours behind my system time. I don't know if this matter but i wanted to say it to you. I will try the branch. Am i right just downlaoding and replacing the files in the CreeMiner directionary ?

Look at my post in Burstcoin Fourm i don't want to post it again. Now i will post on github. It's more efficient for troubleshooting. When there is a solution then we can post it on Burstcoin. 

[CreeMinerlog.txt](https://github.com/Creepsky/creepMiner/files/1006782/CreeMinerlog.txt)

Thanks for all your troubleshooting !!!!!!!!

BurnMe

**Comment by BurnMe2** [comment]
hi i'm testing the branch here my first results.

1.  
The CreepMiner starts a lot of block behind from the actual block but then very fast springs from block to block until it reaches the actuell block (very godd :))

2. 
Very slow plot reading about 12 MB/s (the same drive the same block should run with over 100 MB/s)

3.
No nonces are found or submitted.

The block Problem is solved but point 2 and point 3 is a problem, so the branch solves point 1 but brings point 2 and point 3. Its a bit freaky on troubleshooting one problem solved to other problems appears. Perhaps you have an easy soution for point 2 and point 3.

**Comment by BurnMe2** [comment]
Here is the log file. the starting block is ver behind the actual block, but here it is displayed that a nonce has been found.  But on the actual blocks nothing is found furthermore.
[creepMiner_20170517_073605.291064.txt](https://github.com/Creepsky/creepMiner/files/1006973/creepMiner_20170517_073605.291064.txt)

**Comment by BurnMe2** [comment]
point 2 solved:

with a higher setting of the Buffersize (RAM): With buffersize 4000 the plot reading is the fastest i have ever seen. 

now please solve point 3 and it is the best linux miner in the world. i wish it would be.

**Comment by fayf** [comment]
Hey @BurnMe2 are you talking about the same issue I posted about? If not, could you please file your own issue so that it doesn't confuse everyone?

**Comment by fayf** [comment]
Anyway @Creepsky, I tried out the branch for about 6 hours or so before my linux system became non-functional for other reasons, so I couldn't test it out for longer unfortunately.

**Comment by Creepsky** [comment]
@fayf ok thanks for the information. Let me know if you have new infos on this.
I think @BurnMe speaks about the same issue (miner is stuck).

I updated the [branch](https://github.com/Creepsky/creepMiner/tree/unstuck-reader) - please try it again, it should solve your problem nr. 3 :)

Also I build in a mechanism to avoid problem nr. 2 that you had. You now can set the buffersize to a lower value without the drawback of a low read-speed.

**Comment by BurnMe2** [comment]
@fayf Yes i am speaking about the same issue (and some more problems) like you. But all in all, im talking about a stuck miner like you and i think we have the same issue. I had to solve some more problems but in the end when all other issues got troubleshooted its almost the same. The miner suddenly stucked even when there is no error with my wallet 1.2.8,  its a bit more complex, but don't be confused. That my Miner gets stucked is the same like your issue you posted.

@Creepsky  you are really fast, i will try the new branch and tell you my results. (Actually i'm testing Miner 1.5.2 and the nxt.myAdreesse=false setting in the wallet config and it runs without any error). I will test the new branch with set to true to provocate the "block not accepted" issue and see if the miner gets stuck again.

**Comment by BurnMe2** [comment]
OK my first impression for the new branch.

1. Nonce are found and submitted   👍 
2. Read time of the plots are normal   👍 

If it gets stuck i  till now don't know  i will test for the some hours to see.

I got one new error message in the terminal displayed right on starting process. I didn't changed the config setting for the wallet, so it seems to be a new error message.

23:14:28: using config file mining.conf
**23:14:28: Error while creating local http server on port 8125!**

**Comment by BurnMe2** [comment]
@Creepsky 
 The CreepMiner suddenly stucks again (exactly at the message "Block not accepted" from the wallet terminal) to make it more clear it tell it in Steps again.

1. The wallet messages terminal messages Block not accepted and CreepMiner stucks

2. Restarting only the CreepMiner: 
The Miner takes the wrong Block (behind the actual) and doesn't spring to the right actual block

3. First restarting the Wallet and then restarting the CreepMiner:
The Miner takes the wrong Block (behind the actual) but now he is springin fast to the actual block (this behaviour is new and good, nonces are found and submitted 👍 )

So still i have to restart wallet and the creepMiner and the Miner suddenly stucks. Good and new is that the creepminer is searching the right block after restarting the wallet. The Miner hasn't done this before so I had to pop off some blocks on the wallet. Perhaps in some time you find a solution 👍 

Here is a part of the log with the last entry
[creepMiner_20170517_212302.137394.txt](https://github.com/Creepsky/creepMiner/files/1009971/creepMiner_20170517_212302.137394.txt)

**Comment by BurnMe2** [comment]
@Creepsky 

I did some more testing. I started the wallet and the miner and then i terminated the Wallet by closing the terminal of the wallet. Herr it is in steps again for better understanding.

1. Closing the wallet terminal during the Creep Miner is running.

2. The CreepMiner says that it can't get block information

3. Closing the Miner

4. Restarting the wallet

5. Restarting the Miner:
    The Miner starting with the wrong block and doesn't spring to to the right one.

This is what i'm thinking of: 
Somehow the miner can't handle the message "Block not accepted" from the Wallet and get stuck. By forcing/terminating the Wallet Process i can create the same behaviour of the CreepMiner, it get stuck and restarts with the wrong block (and here the Miner doesn't spring to to right block anymore).

I think when the wallet is crashing the miner gets confused (like me) :)

**Comment by BurnMe2** [comment]
update:
 
after doing this above and writing the last comment i restartet again, and everything is working fine. The Miner starts at the right block (its confusing)

This i what i think of: 

When i check the process with systemmonitor i can see that the java process (for the wallet) often still is active although deactivating the wallet. Perhaps it could be an java issue the crashes the wallet and then the miner gets stuck and can't handle this.

After some time (after terminating the wallet) the java process disappears in the systemmonitor. And when you then restart the Wallet and the creepMiner everything is working. But when restart the wallet and the creepMiner before the java process gets terminated the Miner starts with the wrong block again.

**Comment by Creepsky** [comment]
@BurnMe2 I think that the problem you describe now is not directly related to this issue,
Can you please open a new issue and copy all wallet-miner things in it so we can separate them.

**Comment by BurnMe2** [comment]
yes i can. i make a new issue ciopy everything and then delete my posts int this issue. 

thanks.

**Comment by fayf** [comment]
Update: Miner has been running for 3 days continuously.

**Comment by nop99** [comment]
HI, I am running version 1.6.0 on Ubuntu 16.04.2 LTS on multiple miners with Internal SATA 8TB disks. After a random amount of time the reading speeds drops below 2MB/s (around 25Mb/s under normal operation). If i kill the miner and run it again, speeds gets back to normal until issue hits again. Could the issue be related to this bug?

**Comment by hheexx** [comment]
compile from development-master. It is fixed.

**Comment by Creepsky** [comment]
@nop99 no thats a different bug.
1.6.0 is still developed and can be unstable. Try the newest version (branch `development-master`).
If the problem still persists, please open a new issue for it.
