### ISSUE TITLE
CreepMiner get stuck on Wallet message "Block not accepted"

### ISSUE THREAD

**Issue by BurnMe2** [Creepsky/creepMiner#110]
Hi,

creepsky here is my log file. On Burstcoin Forum the upload didn't worked (BurnMe). So one thing i mentioned in the log is that the logfile is 2 hours behind my system time. I don't know if this matter but i wanted to say it to you. I will try the branch. Am i right just downlaoding and replacing the files in the CreeMiner directionary ?

Look at my post in Burstcoin Fourm i don't want to post it again. Now i will post on github. It's more efficient for troubleshooting. When there is a solution then we can post it on Burstcoin. 

Thanks for all your troubleshooting !!!!!!!!

BurnMe (for security reasons i set instead of my adress  .... . So when you see ... in the log its normal)

**Comment by BurnMe2** [comment]
hi i'm testing the branch here my first results.

The CreepMiner starts a lot of block behind from the actual block but then very fast springs from block to block until it reaches the actuell block (very good !!!!! :))

Very slow plot reading about 12 MB/s (the same drive the same block should run with over 100 MB/s)

No nonces are found or submitted.

The block Problem is solved but point 2 and point 3 is a problem, so the branch solves point 1 but brings point 2 and point 3. Its a bit freaky on troubleshooting one problem solved to other problems appears. Perhaps you have an easy solution for point 2 and point 3.

**Comment by BurnMe2** [comment]
Here is the log file. the starting block is very behind the actual block, but here it is displayed that a nonce has been found. But on the actual blocks nothing is found furthermore.

(log file has been deleted for security reasons )

**Comment by BurnMe2** [comment]
point 2 solved:

with a higher setting of the Buffersize (RAM): With buffersize 4000 MB the plot reading is the fastest i have ever seen.

now please solve point 3 and it is the best linux miner in the world. i wish it would be.

by the the way im using mint linux lmde with kernel 3.16, could this old kernel cause all these problems ? everything else is running fine.

**Comment by BurnMe2** [comment]
@fayf Yes i am speaking about the same issue (and some more problems) like you. But all in all, im talking about a stuck miner like you and i think we have the same issue. I had to solve some more problems but in the end when all other issues got troubleshooted its almost the same. The miner suddenly stucked even when there is no error with my wallet 1.2.8, its a bit more complex, but don't be confused. That my Miner gets stucked is the same like your issue you posted.

@Creepsky you are really fast, i will try the new branch and tell you my results. (Actually i'm testing Miner 1.5.2 and the nxt.myAdreesse=false setting in the wallet config and it runs without any error). I will test the new branch with set to true to provocate the "block not accepted" issue and see if the miner gets stuck again.

**Comment by BurnMe2** [comment]
OK my first impression for the new branch.

    Nonce are found and submitted 👍
    Read time of the plots are normal 👍

**Comment by BurnMe2** [comment]
@Creepsky
The CreepMiner suddenly stucks again (exactly at the message "Block not accepted" from the wallet terminal) to make it more clear it tell it in Steps again.

    The wallet messages terminal messages Block not accepted and CreepMiner stucks

    Restarting only the CreepMiner:
    The Miner takes the wrong Block (behind the actual) and doesn't spring to the right actual block

    First restarting the Wallet and then restarting the CreepMiner:
    The Miner takes the wrong Block (behind the actual) but now he is springin fast to the actual block (this behaviour is new and good, nonces are found and submitted 👍 )

So still i have to restart wallet and the creepMiner and the Miner suddenly stucks. Good and new is that the creepminer is searching the right block after restarting the wallet. The Miner hasn't done this before so I had to pop off some blocks on the wallet. Perhaps in some time you find a solution 👍

Here is a part of the log with the last entry
creepMiner_20170517_212302.137394.txt

**Comment by BurnMe2** [comment]
@Creepsky

I did some more testing. I started the wallet and the miner and then i terminated the Wallet by closing the terminal of the wallet. Herr it is in steps again for better understanding.

    Closing the wallet terminal during the Creep Miner is running.

    The CreepMiner says that it can't get block information

    Closing the Miner

    Restarting the wallet

    Restarting the Miner:
    The Miner starting with the wrong block and doesn't spring to to the right one.

This is what i'm thinking of:
Somehow the miner can't handle the message "Block not accepted" from the Wallet and get stuck. By forcing/terminating the Wallet Process i can create the same behaviour of the CreepMiner, it get stuck and restarts with the wrong block (and here the Miner doesn't spring to to right block anymore).

I think when the wallet is crashing the miner gets confused (like me) :)

**Comment by BurnMe2** [comment]
update:

after doing this above and writing the last comment i restartet again, and everything is working fine. The Miner starts at the right block (its confusing)

This i what i think of:

When i check the process with systemmonitor i can see that the java process (for the (last running) wallet) often still is active although deactivating the wallet. Perhaps it could be an java issue that crashes the wallet and then the miner gets stuck and can't handle this.

After some time (after terminating the wallet) the java process disappears in the systemmonitor. And when you then restart the Wallet and the creepMiner everything is working. But when restart the wallet and the creepMiner before the (old) java process gets terminatet the Miner starts with the wrong block again.

**Comment by BurnMe2** [comment]
Now im testing the CreepMiner branch with wallet setting nxt.myAdress=false. Then the Wallet never shows the "Block not accepted" message and is working. In testing this with Miner 1.5.2 the Miner suddenly stoped working like in issue 7. I will post my results, when i get an error or after 24 h testing with no error.

**Comment by BurnMe2** [comment]
update testing:  during testing with the wallet disabled peer notworking by setting ...myAdresse=false  The message "Block not accepted" is displayed too (the first time it does with setting to false). But now the CreepMiner doesn't matter and still is working on 👍 

Please look at the logfile. Short time after this message the Miner logs something like you can see at the bottom. The message appears at "017-05-18 09:47:20 INFO: Block not accepted"

The logfile time of the miner is 2 h behind my system time, so the wallettime 09:47 with the message block not accepted is the miner log time 07:47, so look what happens at 07:047. 

Here is a part of the log, you can download more of the log. I uploaded the part at this time.
[Miner log.txt](https://github.com/Creepsky/creepMiner/files/1010646/Miner.log.txt)


18.05.2017 07:47:35 (4, src/Wallet.cpp, 162, Debug): Sending wallet request '/burst?requestType=getAccount&account=12396899410079302909'
18.05.2017 07:47:35 (4, src/Wallet.cpp, 173, Debug): Got response for wallet request '/burst?requestType=getAccount&account=12396899410079302909'
{"publicKey":"9646a7a0234c85e0d47104b6121ef1878482a176a69dade6641daaa788043444","requestProcessingTime":311,"assetBalances":[{"asset":"942954888627932030","balanceQNT":"413000406330"},{"asset":"6240960782340140583","balanceQNT":"421900"},{"asset":"5567986790414164482","balanceQNT":"400000"},{"asset":"299666019742559243","balanceQNT":"224497"},{"asset":"2264511436216725766","balanceQNT":"4000"},{"asset":"4573175367072955417","balanceQNT":"3188"},{"asset":"6503640249706792397","balanceQNT":"3159"},{"asset":"12532751834119208533","balanceQNT":"2100"},{"asset":"1231812944272348986","balanceQNT":"224"},{"asset":"16531555643066003940","balanceQNT":"100"},{"asset":"3509939581101213262","balanceQNT":"9"},{"asset":"11188744773544606055","balanceQNT":"1"},{"asset":"11675298348805434492","balanceQNT":"1"},{"asset":"13269487616284934988","balanceQNT":"1"},{"asset":"16638626464928840929","balanceQNT":"1"},{"asset":"17127994469745679233","balanceQNT":"1"},{"asset":"1605211475111316015","balanceQNT":"1"},{"asset":"4927069239441381569","balanceQNT":"1"},{"asset":"8533712502250986824","balanceQNT":"1"}],"guaranteedBalanceNQT":"2073025225397","balanceNQT":"2073025225397","name":"Thomeefl69","accountRS":"BURST-FK9X-CMV2-4Q7Q-C4P4S","unconfirmedAssetBalances":[{"unconfirmedBalanceQNT":"413000406330","asset":"942954888627932030"},{"unconfirmedBalanceQNT":"421900","asset":"6240960782340140583"},{"unconfirmedBalanceQNT":"400000","asset":"5567986790414164482"},{"unconfirmedBalanceQNT":"224497","asset":"299666019742559243"},{"unconfirmedBalanceQNT":"4000","asset":"2264511436216725766"},{"unconfirmedBalanceQNT":"3188","asset":"4573175367072955417"},{"unconfirmedBalanceQNT":"3159","asset":"6503640249706792397"},{"unconfirmedBalanceQNT":"2100","asset":"12532751834119208533"},{"unconfirmedBalanceQNT":"224","asset":"1231812944272348986"},{"unconfirmedBalanceQNT":"100","asset":"16531555643066003940"},{"unconfirmedBalanceQNT":"9","asset":"3509939581101213262"},{"unconfirmedBalanceQNT":"1","asset":"11188744773544606055"},{"unconfirmedBalanceQNT":"1","asset":"11675298348805434492"},{"unconfirmedBalanceQNT":"1","asset":"13269487616284934988"},{"unconfirmedBalanceQNT":"1","asset":"16638626464928840929"},{"unconfirmedBalanceQNT":"1","asset":"17127994469745679233"},{"unconfirmedBalanceQNT":"1","asset":"1605211475111316015"},{"unconfirmedBalanceQNT":"1","asset":"4927069239441381569"},{"unconfirmedBalanceQNT":"1","asset":"8533712502250986824"}],"account":"12396899410079302909","effectiveBalanceNXT":2073025225397,"unconfirmedBalanceNQT":"2067025225397","forgedBalanceNQT":"0"}
18.05.2017 07:47:35 (23, src/MinerData.cpp, 280, Information): --------------------------------------------------
last block winner: 
block#             361236
winner-numeric     12396899410079302909
winner-address     FK9X-CMV2-4Q7Q-C4P4S
winner-name        Thomeefl69
--------------------------------------------------
18.05.2017 07:47:39 (10, src/PlotReader.cpp, 193, Information): /mnt/HDD2/plots/13882976725566470870_28672002_9011200_9011200 (2.15 TB) read in 4.207s (~130.72 MB/s)
18.05.2017 07:47:39 (10, src/PlotReader.cpp, 225, Information): Dir /mnt/HDD2/plots read (1 files, 2.15 TB total) in 4.207s (~130.71 MB/s)
18.05.2017 07:47:43 (9, src/PlotReader.cpp, 193, Information): /mnt/HDD1/plots/13882976725566470870_0_14336000_14336000 (3.42 TB) read in 7.597s (~115.17 MB/s)
18.05.2017 07:47:49 (9, src/PlotReader.cpp, 193, Information): /mnt/HDD1/plots/13882976725566470870_14336001_14336000_14336000 (3.42 TB) read in 6.213s (~140.82 MB/s)
18.05.2017 07:47:49 (9, src/PlotReader.cpp, 225, Information): Dir /mnt/HDD1/plots read (2 files, 6.84 TB total) in 13.811s (~126.71 MB/s)
18.05.2017 07:48:41 (0, src/Miner.cpp, 172, Debug): Plot-read-queue: 0, verification-queue: 0
18.05.2017 07:48:41 (0, src/Miner.cpp, 173, Debug): Allocated memory: 0.0 MB
18.05.2017 07:48:41 (0, src/Miner.cpp, 198, Notice): --------------------------------------------------

**Comment by BurnMe2** [comment]
Update 2: everything is running fine at the moment. Anyway, i cannot get off thinking that all problems are caused by the java installation which is a need for the wallet installation.

So look how you can improve the creep Miner, perhaps its a combination of all (java vs wallet vs CreepMiner) and i will make a new installation of my Linux and change from debian Mintlinux LMDE to Mintlinux Cinnamon 18.1. I will run it with the newest Kernel and make a new clean java installation and new wallet and test the branch of the CreepMiner (the unstuck-reader)

It would be freaky if this is solving my problems but i have to try. I tell you my results but i need some days time to make a new clean Linux and java installation.

**Comment by Creepsky** [comment]
For me it looks like there is an issue with the wallet and your Linux.
What kind of JDK (Java) have you installed on your machine (OpenJDK, Oracle Java, GNU Java)?

You could try the following things:

1. change/update your JDK
2. mine on a pool to test everything (don't forget to remove your encrypted passphrase, otherwise it will be sent to the pool)
3. install the wallet on Windows (virtual machine?) and connect your miner on Linux to the wallet on Windows
4. upgrade/update your Linux

Step 3. and 4. are very costly and I advice to test 1. and 2. first. Only if you really want to mine solo, you should do 3./4.

If these steps do not end with the same error you already have, then this has something to do with your Wallet/JDK/Linux/...

**Comment by BurnMe2** [comment]
Thanks some goog adivices. I will try all of them. But first 1.2.4 and then 4. 
I'm already testing the wallet under Windows with the AIO. Do you know how to config the miner that its using the windows wallet. Where and what to set in the config ?

Thanks you already done a lot, the miner actually is working for 10 hours without any error, always the right block although the wallet says again Block not accepted. (with setting to false). So this workaround is working for me.

I will go through all steps with a new clean JDK and Linux installation. And i will use the branch unstuck-reader. I think it ends all good.

Mining on the pool has never been a problem. Pool Mining was working without any issue very fine and smooth. 

I let you know how i solved the problem. 

You should give whatever you have done with the unstuck-reader brunch to the new CreepMiner Version 1.6.0. For me the brunch is working best and it didn't get so fast stuck when problems with the wallet.

**Comment by Creepsky** [comment]
@BurnMe2 please read [this thread on forums.burst-team.us](http://forums.burst-team.us/topic/4114/keep-your-system-time-in-sync-please).

**Comment by BurnMe2** [comment]
Hi thanks for the link, i already checked the time sync (even on different PC which im using with Linux).  The time sync has always been alright. I'm running another Server program on Linux on another PC,  for this server the time has to in sync too and its working without any time errors since weeks.

But "The Block not accepted" message seems to come on failed time sync. 

So i will check it againg and try ton find a special tool for time sync on linux, perhaps that could be the solution. 

Im testing on and using another Linux thanks for your help and thinking of my problems. Like i read in burstcoin forum it looks like an time error but the time has always been in sync. I used the ntp to update the time each time before i start the wallet 1.2.8. But nevertheless it doesn't work. I could be time issue.

I don't know if it matters but my european time is another than the pool time in USA, i will try to set my sever time to USA time perhaps this helps the wallet to handle the time in the right way.

Now im testing on and let you again know, when i tested the time sync again (only if this is solving my problem)

**Comment by BurnMe2** [comment]
Hi creepsky,

actually i installed a new wallet, downloaded the whole blockchain (new) and configured my ntp settings and config file with new time servers. And i set up a new Linux (Mintlinux KDE). Now i want to test the CreepMiner. I tested the developement version and the version 1.5.2 and again the CreepMiner didn't find any nonces. This issue was solved in the branch unstuck-reader but i cannot find the branch again.

So can you help again, the plot file are recognized and has been read but no nonces are found. Can you fix it so that i am able for more testing. You know in the main im testing for block not accepted error but the Miner doesn't find nonces.

Jminer seems for me to difficult to install, so i will test it in some day if i am able to start in Linux . But first it would be fine that the Creepmienr find nonces. Here you can again the message from the terminal.

01:12:44: last block winner: 
01:12:44: block#             362538
01:12:44: winner-numeric     11071605903816083693
01:12:44: winner-address     8L9F-X5H3-RTVG-BYKBM
01:12:44: winner-name        DigiWarfare
01:12:44: --------------------------------------------------
01:12:45: Dir /mnt/HDD2/plots read (1 files, 2.15 TB total) in 5.672s (~96.96 MB/s)                                        
01:12:59: Dir /mnt/HDD1/plots read (2 files, 6.84 TB total) in 19.259s (~90.86 MB/s)                                       
01:18:16: --------------------------------------------------
01:18:16: block#      362540
01:18:16: scoop#      429
01:18:16: baseTarget# 587966
01:18:16: --------------------------------------------------
01:18:16: --------------------------------------------------
01:18:16: last block winner: 
01:18:16: block#             362539
01:18:16: winner-numeric     3297774512790599656
01:18:16: winner-address     JXZA-GBS5-HTDY-4E2KV
01:18:16: winner-name        Hank1
01:18:16: --------------------------------------------------
01:18:21: Dir /mnt/HDD2/plots read (1 files, 2.15 TB total) in 5.386s (~102.11 MB/s)                                       
01:18:32: Dir /mnt/HDD1/plots read (2 files, 6.84 TB total) in 16.081s (~108.82 MB/s)                                      
01:21:13: --------------------------------------------------
01:21:13: block#      362541
01:21:13: scoop#      248
01:21:13: baseTarget# 593711
01:21:13: --------------------------------------------------
01:21:13: --------------------------------------------------
01:21:13: last block winner: 
01:21:13: block#             362540
01:21:13: winner-numeric     13920149680216353035
01:21:13: winner-address     2CAD-E98T-XX6L-EGLD4
01:21:13: --------------------------------------------------
01:21:18: Dir /mnt/HDD2/plots read (1 files, 2.15 TB total) in 4.936s (~111.41 MB/s)                                       
01:21:30: Dir /mnt/HDD1/plots read (2 files, 6.84 TB total) in 16.806s (~104.13 MB/s)

**Comment by Creepsky** [comment]
Hi,

I merged 'unstuck-reader' into 'development', it should be there. Maybe you have a very low target deadline?
If its not working, please use [unstuck-reader](https://github.com/Creepsky/creepMiner/tree/unstuck-reader) again (I returned it).

**Comment by BurnMe2** [comment]
Hi,

i tried the stable version 1.5.2 and i tried the development version now over hours and no nonce was found. 

The good information is that within the last 7 hours everything runs stable :) but i don't know why. 
Actually im running the Miner under my Linux admin account, has the use of the admin account any effect on the miner? During my last tests im was always using a normal Linux user account. DO the CreepMiner nedd an Linux admin account for running stable ?

I will try the unstuck-reader branch again and post my results.

**Comment by BurnMe2** [comment]
I made some screenshots for you, during make the creepMiner i got some warnings but i don't know how to understand these warnings.
 
Here are the screenshots
![screenshot_20170522_091949](https://cloud.githubusercontent.com/assets/28735005/26296951/2d5eda82-3ed1-11e7-9ba4-d0cb25d9254b.png)
![screenshot_20170522_092339](https://cloud.githubusercontent.com/assets/28735005/26296956/3123c088-3ed1-11e7-8414-f92f74fefffb.png)
![screenshot_20170522_092349](https://cloud.githubusercontent.com/assets/28735005/26296960/33e1144c-3ed1-11e7-834d-4660dfd054a3.png)

Perhaps something goes wrong with the  installation so no nonces are found or submitted. The unstuck-reader doesn't find my noncec too. Now im using it on new linux (Mint 18.1 KDE), i will set up another new Linux and then testing on.

**Comment by Creepsky** [comment]
The warnings are nothing to worry about, I set the warnings to a very high level.
Admin account is not necessary, I always use a normal account without sudo.

Can you please send me your config and your log (with anonymous data)?

**Comment by BurnMe2** [comment]
I switched the Linux to Mintlinux 18.1 mate. Actually im installing a new CreepMiner (version 1.5.2). First tests with unstuck-reader and development Version always made the same thing. They don't find and send nonce even when the config for deadline is set to years.

I don't know why thiss new issue is now happening. Its a bit crazy for me. Now the wallet seems to be stable after reinstalling and downloading a new blockchain and now no nonces are found.

So when i did the new Miner installation i send you the config and the log in this post (after you watched this i will delete them in this post for security reasons. But for me its not so important, this Burstcoin account is just for testing. When everything runs fine i make a new one.

The installation for the poco and the miner takes often 30 minutes and more. Is this normal ?

**Comment by BurnMe2** [comment]
Hi,

here is my config and my logifle . Created with CreepMiner Version 1.5.2. Running as normal user. (Same issue with unstuck-reader and developer).


[creepMiner_20170522_110519.643228.txt](https://github.com/Creepsky/creepMiner/files/1018577/creepMiner_20170522_110519.643228.txt)
[mining.txt](https://github.com/Creepsky/creepMiner/files/1018578/mining.txt)

**Comment by Creepsky** [comment]
Thanks for the files, you can delete them now.
Config and log seems fine.
The miner is reading the plotfiles but there is nothing that shows if it is searching for deadlines :confused: this is really strange.

Because of the long build times. Try to use this `install_poco.sh`:

```
#!/bin/sh
set -ex
wget https://pocoproject.org/releases/poco-1.7.6/poco-1.7.6-all.tar.gz
tar -xzvf poco-1.7.6-all.tar.gz
sudo apt-get install openssl
sudo apt-get install libssl-dev
cd poco-1.7.6-all && ./configure --no-tests --no-samples --omit=Data/ODBC,Data/MySQL && make shared_release && sudo ldconfig && sudo make install
```

Can you please do me a favor and use either `development` or `unstuck-miner` and show me the log file again? These branches have a little bit more log output.

**Comment by BurnMe2** [comment]
I do everything that can help to get it run on Linux. I really would like to mine with Linux and CreepMiner.

So i do some testing with development and unstuck-miner too and post here the log files. I already installed them, so it gets fast.

Thanks for the tips of the install_poco.sh, i will change the install_poco.sh in try  to run it.

So what Linux do you prefer for your CreepMiner. What do you use ?

**Comment by BurnMe2** [comment]
How do i need to stop the CreepMiner the right way, for wallet i hvae to use ctrl + C. Is that the right command for the miner too ?

**Comment by Creepsky** [comment]
I created a gitter chat room for the creepminer: https://gitter.im/creepMiner/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link.
Can you please come there (you can use your github account)? I think there we can solve your problem much faster.

**Comment by BurnMe2** [comment]
Ok i go into the gitter chat room, right now

**Comment by BurnMe2** [comment]
Hi Creepsky,

i did some more testings  and i want to tell you my results so that you can reflect on that issue (nonce not found or submitted). 

1. Putting the HDD with the plotfile to another PC (other Hardware and using Mintlinux LMDE Debian Mate): Nonces are found and submitted

2. When using the exact same setting (of Hardware) like in 1. but using Mintlinux 18.1 Mate: Nonces are not found or submitted)

In conclusion of 1. and 2. i am thinking that it's more an software than hardware issue. I'm still confused about that. The Debian is using Kernel 3.16., The Mintlinux 18.1 uses a newer one, Kernel 4.4 in Mintlinux 18.2 i tried the kernel 4.10 (still the same issue nonces not found).

So now i got a small solution for the nonces not found problem (using the LMDE Mintlinux Debian edition instead of Mintlinux 18.1). 
 
Actually i am testing my original problem (Miner get stuck when Wallet displays "Block not accepted" and Wallet/Miner is far behind the actual block) for the next hours and post here my results for you. I'm using the developer Version for testing. 

Some additoal thoughts for this and for those who are new to burstcoin like me and no developer.

1. 
When starting the wallet the first time after stopping it for a few days or hours i think its normal that the block height isn't the right one because the wallet needs time to get in sync and updating the blockchain. So when starting the wallet with Block behind the actual, its no issue, its normal and just need time to sync.  You have to log in your wallet, there you can see if blockchain still is updating.

2.
In the development Version of the miner, the miner doesn't matter of the block height, it seems that the miner takes all what the wallet transmit to the miner. 

3. Shutting down the wallet with ctrl +c when you want to stop mining and shutdown your PC. I didn't know about this. I think when you don't stop the Wallet with ctrl + c it your blockchain download could get corrupt because its not a clean shutdown and the server shutdown (on solo mining you are hosting your own server)  is not clean too. For me i even got  in trouble with my java on hard shutdown without ctrl + c. This caused my java stuck and didn't quit the process. The java process needed long time to be terminated on hard shudown but with ctrl +c the process immediatly shuts down without any problems.

**Comment by BurnMe2** [comment]
Hi,
here is a new logfile from the development Miner. This time i got an error message from the CreepMiner when it get stuck and the wallet terminal shows Block not accepted. Here it is, so have a look:

[log.txt](https://github.com/Creepsky/creepMiner/files/1030277/log.txt)

25.05.2017 21:00:08 (53, src/MinerServer.cpp, 174, Warning): Could not send the data to the websocket!data: {"address":"6BH8-2UBM-QQQT-BQJLG","name":"ccminer","numeric":10901550065498858982,"type":"lastWinner"}
25.05.2017 21:00:08 (53, src/MinerServer.cpp, 175, Error): I/O error: Broken pipe

what is Broken pipe, and what is the meaning of could not send data to the websocket ? 

👍 BurnMe

**Comment by Creepsky** [comment]
Hi!
If you have a broken websocket pipe it means that the websocket got closed unproperly.
The only websockets the miner is using are the one in the webserver, if you use the webinterface in your webbrowser.
This is not directly related to the error of the wallet, but indicates that you have an issue with your network (firewall, router, switch, antivirus, ...?).
