### ISSUE TITLE
hardware requirements

### ISSUE THREAD

**Issue by ITwrx** [Creepsky/creepMiner#111]
hi,
any chance minimum and recommended hardware requirements (per HDD or a couple rig examples maybe?) could be added to the wiki? i'd like to know what the plotting and mining actually requires from hardware so i can order parts for different situations. Or maybe you could just publish what will be happening with the drives when plotting and mining and we can figure out the ramifications ourselves. are they idling most of the time or working their spindles off? are they passing data as fast as they can or just working to themselves and trickling out results, etc?

For example: what cpu is required for max performance with 9X 8TB 7200 nas HDD's on one MB? what happens if you go below that recommended cpu? negliible reductions or major under performance?  Can an 45watt sempron on an am3 board handle 2 or 4 8TB HDDs? What i read on the burst site sounded to me like cpu/gpu are almost unecessary or mainly just needed for setup and forum posts sound like i need a cray supercomputer or perhaps a quantum falopsoraptor is in order. I want to build the most efficient rig possible with a given budget, but i'm not seeing any solid docs with which to base decisions on. Or maybe i just missed them somewhere?

thanks

**Comment by Creepsky** [comment]
Hi,

I can't say exactly what hardware you need, I can only say:

- CPU: the more cores, the better
- GPU: can compensate and speed up the overall mining process
- RAM: I would say negligible but can speed up the mining process (and is also cheap)
- CPU/GPU/RAM: don't need to be high-end, because the mining process is not very computationally intensive
- HDD: the HDD-interface is the most important part and will be the bottleneck of your whole setup (SATA-III vs USB-3 vs ...)
- SATA-Controller: determines how many HDDs you can use, also the read speed (this is the most important component.. intern controller vs extern?)
- Mainboard Bus: take care that your bus speed can keep up with the speed of the controller (+ GPU)
- don't use things like RAID, don't use SSDs
- Power: negligible.. if you want security, use an USV
- Operating System: negligible, but if your system have to be up all the time (server), I would not rely on Windows

This is what in my opinion is important for Burst mining... but like I said, I don't have a big mining system here and can only assume these things. You should better ask someone with more experience with big mining rigs.

**Comment by Adavan83** [comment]
Hi guys.
@Creepsky good writen. I want add some my notes.
@ITwrx, as @Creepsky wrote important is HDD capacity and speed. It depend on your preferences between USB3.0/3.1 or internal SATA.
Last week i "rebuild" my rig. Mining of burstcoins is for me just relax, hobby activities ;). My rig is builded from scrap of hardware, which i have as unusable. So, basic is old HP DC7800p (C2D E6750, 2GB RAM, onboard vga, ...). PSU are a little weak 350W, but enought for this purpose.
On beginning, i have some old low capacity HDDs. As a "system drive" i used 80GB SATA 3.5". As Creepsky wrote, OS isnt important, but i you planed let this comupter turned on 24/7, Linux is much better like Windows. Linux in this case have some advantages too, for example, lower HW requirements for quick work (low RAM, low space for systems operations, ...) and better stabilities after some mounths of working. I used my favorite distribution Debian x64 (actually Jessie). I create next partitions on this HDD: "/" (root) 8GB, swap 2GB, and other (about 65GB) for "/home" (actually used for TransmissionDaemon purpose). To home i download source code for miner, poco, ... and compile it on this place. Runnig miner in instance of program "screen" and controll this rig throught by SSH daemon from my primary desktop computer (NUC5i5RYH, 16GB RAM, 256GB SSD m.2, Debian too). I start with small plot on 1TB 2.5" HDD (5400rpm, WD CaviarBlue) placed in NUC. After some times i obtain few 1TBs and 500GB HDDs (all 2.5"). I buy internal case for it (6x 2.5" HDD in 1x 5.25" -> https://www.aliexpress.com/item/6-Bays-Mobile-Rack-Backplane-Support-2-5-SATA-HDD-SSD-Hard-Drive-with-Cooling-Fan/32791168648.html) and additional controller card (https://www.aliexpress.com/item/8-Port-Internal-SATA-3-0-Support-1-5Gb-3Gb-6Gb-PCIe-PCI-Express-Expansion-Card/32366596666.html) placed to 1x PCI-E 16x. This controller working with Debian out of box, so no aditional steps needed.
This rig computer not have enought speed for effective ploting, so i plot my HDDs in NUC throught USB3 (https://www.aliexpress.com/item/Beautiful-Gift-New-55cm-Super-Speed-USB-3-0-To-SATA-22-Pin-2-5-Inch/32739597252.html). 1TB plot NUC create after about 14hours, and HP after 44hours ;).
About power consuption: NUC have in full load about 50W, and HP about 120W. Plotting on NUC is in my case more effective, like let it plotting on this old HP desktop.
So, when i reach "new HDD", i plot it on NUC, add it UUID to HPs fstab and mount to correct folder. When i have it, turn of HP, install plotted disk and turn it on. Easy ;). Of course, for miner i add new path for new plot to configuration. I dont want wrote all details on this place, main purpose is support Creepskys miner, not mining rigs.
Actually have 10 HDDs (2x 3.5", 8x 2.5"), power consuption in idle is 70W, when mining process start (miner check plots), power consuption rise to 105W for 10-15s. After this jump back to idle and waiting until next block arrived to pool.
No redudancy is needed. If electric power kick it down, no problem, just start it. I only lost blocks, when this rig was down. When some drive go to heaven, no problem, in fstab i place flag "nofail", when OS loading, it inteligent skip it and miner too. Miner just wrote about missing plot file. When burnout anything else, no problem, i have another identical machine (now i target to PSU, MB, ...)
@ITwrx if i can guide you, start with your some old previous computer with one HDD (SSD) connected to SATA as system and one HDD (noSSD) for one plot. After several solved problems you obtain valuable experience in your exact environment and should prepared for build bigger rig with more capacity and more HDDs ;).
As Creepsky wrote too, it depend on your actually situation. I build this rig from scraps with little investments. Maybe you should be prepared build it from some old storage system (NetApp, EMC, ...).
Next step for me is obtain big tower case from my parents and from another old computer as a housing for new rig. Some old similar MB i have whith similar CPU and rebuild it again to another form. But this topic i absolutte out of this Creepskys miner theme ;).
If you have another questions and i am sure, that you should have it :), you can ask me directly on adavan@burstcoin.sk . You are welcome to our pool at www.burstcoin.sk.

**Comment by ITwrx** [comment]
Thanks to both of you. i'm currently plotting on 2TB 7200 HDD i had here already using the regular [mdcct().](https://github.com/Mirkic7/mdcct) Mining on this HDD should give me a basic idea on resource usage. I plan to use Arch Linux for mining, as I do for everything else.  :)

Do either of you have any experience with longer term profitability? I noticed somewhere that burst mining rewards are reduced 5% each month. How is that not a problem for miners long term? IOW, what am i missing? 
Thanks
