### ISSUE TITLE
Verifying if forwarding works

### ISSUE THREAD

**Issue by hacklab01** [Creepsky/creepMiner#120]
Hello!

After setting up multiple miners and pointing them all to a main forwarder, the main miner's web UI doesn't show total plotsize.

Is there any way to make sure my miners are actually working through the main miner / forwarder?

Thank you!

**Comment by Creepsky** [comment]
Hi,

you are right, the web UI only shows the local capacity.
I will add this to the 1.6.0 release.

Meanwhile, you can check if it is working by either 

a) looking at your capacity on the pool ui (it should show the combined capacity) or
b) looking in the terminal. If one of your non forwarding miner sends a deadline, the forwarding miner will show it in his terminal, as if he found the deadline. Then on both sides (forwarder and worker) a confirmation will be shown.

Have in mind that only connected miners that found a deadline in the last 30 rounds will be added to the total capacity.

**Comment by N8Thrasher** [comment]
what i did, I rename or put each plot files on a specific folder for each PC that is forwarding to the main so that I can see if its working from the console of the main miner PC.
Miner A- d:\A\"plotfile"
Miner B- d:\B\"plotfile"
and so on...

It will show on the main miner when it accepts and transmit the found deadline.

**Comment by thcao** [comment]
Hi Creepsky,

Do you implement web ui for pool (show the combined capacity) ?
I'm using 1.7.1 version, but didn't see pool ui

Thanks!

**Comment by Creepsky** [comment]
Hi,
I just implemented the webinterface for creepMiner.
What pool ui are you looking for?

**Comment by thcao** [comment]
Hi,

Function forward, your comment above
a) looking at your capacity on the pool ui (it should show the combined capacity) or

I only saw plotsize in local system

How about view all plotsize in system, if I forward 4 miners to 1 miner 

Thanks!

**Comment by Creepsky** [comment]
It shows the combined capacity of all miners.
Look at this https://github.com/Creepsky/creepMiner/wiki/Setting-up-the-miner#cumulateplotsizes, and this https://github.com/Creepsky/creepMiner/wiki/Forwarding#combined-capacity.

**Comment by thcao** [comment]
Yes, I configured, but I still saw only plotsize in main server
"webserver" : {
        "cumulatePlotsizes" : true,
        "forwardMinerNames" : true,
...

**Comment by Creepsky** [comment]
>Only connected miners that did a submission in the last 10 rounds are counted into the total sum of capacity.

How big is the total plot size of the miner connected to the forwarder?

**Comment by thcao** [comment]
I tested with 1 master 8T and 1 forward 3T

**Comment by thcao** [comment]
![befee1e6-51a4-4e63-9c6b-7c1a270ef5cf](https://user-images.githubusercontent.com/7821025/31580229-b8e98722-b173-11e7-9601-ecc23e66ee65.jpeg)

**Comment by Creepsky** [comment]
Is your connected miner submitting nonces? You have a target deadline of `00:05:00`, that is very low considering you have 3 TB.

Whenever your second miner submitted a deadline, it will show the combined capacity on your forwarding miner, like said here:

> Only connected miners that did a submission in the last 10 rounds are counted into the total sum of capacity.

You can test this behaviour by setting your target deadline to a higher value (when 5 hours is not forced by your pool), or disable it (set it to `"00:00:00"` or `0`).

**Comment by oxconan** [comment]
I'm using solo mining... walletlocal in master node.
00:05:00 Is 5 minutes or 5 hours ? I want to set it  5 minutes
Ok I will try to test with 0

**Comment by Creepsky** [comment]
You are right, its 5 minutes not hours.

**Comment by oxconan** [comment]
Ok man, I set 0, it showed total ok.
Can you recommend best value for targetDeadline of forward case.
Question: if master submit Pool ex: pool.burstcoin.ml. Do this pool show total pilotsize all nodes?

**Comment by Creepsky** [comment]
For solo mining use a low value, and yes, the miner will send the total amount (of all nodes that are submitting) of plot sizes.

**Comment by oxconan** [comment]
For Pool mining, is the same ?
