### ISSUE TITLE
Compiling on RH7, CentOS 7, or OEL7

### ISSUE THREAD

**Issue by koalup** [Creepsky/creepMiner#121]
Awesome miner. Any chance of getting this to compile on  RH7, CentOS 7, or OEL7?

I got pico compiled, but when I try compiling creepMiner it gives me:

g++ -O3 -march=native -std=c++14 -Wall -D_REENTRANT -DNDEBUG -Isrc/sphlib -Isrc/nxt -Isrc -IPoco/Net -IPoco/Foundation -IPoco/NetSSL_OpenSSL -IPoco/openssl -IPoco/Crypto -IPoco/Util -IPoco/JSON -c src/sphlib/sph_shabal.cpp -o bin/obj/sphlib/sph_shabal.o
g++: error: unrecognized command line option ‘-std=c++14’
make: *** [bin/obj/sphlib/sph_shabal.o] Error 1

Pretty sure this is due to g++ being < 4.9

$ g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I couldn't find an easy way to update g++ on RH7 clones

Thanks!

**Comment by Creepsky** [comment]
Woops, I accidently assigned the wrong issue number to these commits:
00f2ae27f07ad8fea63c07bc2e21ab14d22986d2
07ca6a36c6bc018c714d33c1197c4bbaced0aa43
de249606b411e50b0c13a77956bc62fb40056cdb
52e2015f8bee4ab0e52dcc0e8c731e99b06b25d3

Hope you can compile it now, try this branch: https://github.com/Creepsky/creepMiner/tree/development.
You need at least a C++-11 compiler, otherwise it wont work.

**Comment by koalup** [comment]
It works! 
```
$ cat /etc/oracle-release
Oracle Linux Server release 7.3
$ ./creepMiner
17:05:25: creepMiner 1.6.0 Unix x64
17:05:25: ----------------------------------------------
17:05:25: Github:   https://github.com/Creepsky/creepMiner
17:05:25: Author:   Creepsky [creepsky@gmail.com]
17:05:25: Burst :   BURST-JBKL-ZUAV-UXMB-2G795
17:05:25: ----------------------------------------------
17:05:25: Based on http://github.com/uraymeiviar/burst-miner
17:05:25: author : uray meiviar [ uraymeiviar@gmail.com ]
17:05:25: please donate to support developments :
17:05:25:  [ Burst   ] BURST-8E8K-WQ2F-ZDZ5-FQWHX
17:05:25:  [ Bitcoin ] 1UrayjqRjSJjuouhJnkczy5AuMqJGRK4b
17:05:25: ----------------------------------------------
17:05:25: using config file mining.conf
...
```
You da man! Thank you!

**Comment by mpenagar** [comment]
I use CentOS 7. It comes with gcc 4.8 (CentOS focuses on stability), but it is quite easy to get newer versions runing using the Software Collections. Here I show how to compile creepMiner starting from a clean minimal CentOS 7 instalation:

```
# update the system & reboot
sudo yum -y update && sudo reboot

#Install Extra Packages for Enterprise Linux
sudo yum -y install epel-release

# install git
sudo yum -y install git

# download creepminer
git clone https://github.com/Creepsky/creepMiner

# install poco libraries
sudo yum -y install poco-*

# install openssl headers
sudo yum -y install openssl-devel

# Here is the trick to get gcc 5.3.1 working

# Install Software Collections (www.softwarecollections.org). It gives you
# the power to build, install, and use multiple versions of software
# on the same system, without affecting system-wide installed packages.
sudo yum -y install centos-release-scl

# Add the Devtoolset-4 collection, which includes gcc 5.3.1
sudo yum -y install devtoolset-4

# to start using software collections, just run
#
# $ scl enable devtoolset-4 bash
#
# and you get a "virtual" environment which includes gcc 5.3.1:
# 
# $ gcc --version
#
# That's all. Type "exit" to exit the environment...

# Compile CreepMiner:
cd creepMiner
echo " make -j 8" | scl enable devtoolset-4 - 
```

**Comment by Creepsky** [comment]
This is perfect, thank you for this!
Maybe we should add it to the wiki.

**Comment by Creepsky** [comment]
@mpenagar I copied your text into this [wiki page](https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation-on-CentOS).
Feel free to edit it like you want it.

**Comment by dugravot6** [comment]
For RHEL, you cannot install scl, but you can activate the repo direclty with : 
`sudo subscription-manager repos --enable=rhel-server-rhscl-7-rpms`
V.
