### ISSUE TITLE
Miner not submitting any nonces to pool on macOS

### ISSUE THREAD

**Issue by k06a** [Creepsky/creepMiner#131]
Captured HTTP traffic and discovered no `submitNonce` requests. I can see only `getMiningInfo` requests and log tells that miner can find several nonces. Any ideas?

**Comment by k06a** [comment]
What can you tell me about this ifdef?
```
#ifdef NDEBUG
    nonceSubmitterManager_->start(new NonceSubmitter{ *this, newDeadline });
#endif
```

**Comment by k06a** [comment]
Fine, fixed with this PR: https://github.com/Creepsky/creepMiner/pull/132

**Comment by Creepsky** [comment]
I added this because in debug mode I did not want to submit nonces.
So nice that you test so much things on macOS, really helps a lot!
