### ISSUE TITLE
Config error

### ISSUE THREAD

**Issue by al-shark** [Creepsky/creepMiner#135]
After start, miner checks config (OK) and starts mining (also deleting "decrypted" field in config and filling other settings : Key, encrypted, etc.) Now, break miner work with Ctrl-C and start filed with error JSON error, invalid characters.

It's also starts good with filled decrypted field in config? and also falling after that.

**Comment by Creepsky** [comment]
Do you use version 1.5.2?

**Comment by al-shark** [comment]
Exactly. Just make from development branch 1.6, no issue, restarting after brake works normal.
