### ISSUE TITLE
Getting no response for wallet request

### ISSUE THREAD

**Issue by rattle99** [Creepsky/creepMiner#136]
I seem to be getting this 
> Got no response for wallet request '/burst?requestType=getBlock&height=371755'

on every block.

**Comment by Creepsky** [comment]
The burst-team wallets are all offline again.
Yesterday I decreased the amount of these error messages in the newest development branch.

If you want just hide them, you can set this in your config file:
```
"logging" : {
    "server" : "off"
}
```
or deactivate the wallet temporary:
```
"mining" : {
   "urls" : {
            "wallet" : ""
   }
}
```

Another alternative would be to use a local wallet.
