### ISSUE TITLE
stackframe error upgrading from 1.5.2 to 1.6.0

### ISSUE THREAD

**Issue by N8Thrasher** [Creepsky/creepMiner#138]
![1 6 0](https://user-images.githubusercontent.com/24593637/27254642-fff54422-5394-11e7-9835-2298bcc37b15.PNG)

heres my config file

{
    "logging" : {
        "config" : "information",
        "general" : "information",
        "miner" : "information",
        "nonceSubmitter" : "information",
        "output" : {
            "dirDone" : true,
            "lastWinner" : false,
            "nonceConfirmed" : true,
            "nonceFound" : true,
            "nonceOnTheWay" : false,
            "nonceSent" : true,
            "plotDone" : false
        },
        "path" : "",
        "plotReader" : "information",
        "plotVerifier" : "information",
        "server" : "fatal",
        "session" : "error",
        "socket" : "off",
        "wallet" : "off"
    },
    "mining" : {
        "intensity" : 3,
        "maxBufferSizeMB" : 128,
        "maxPlotReaders" : 4,
        "passphrase" : {
            "algorithm" : "aes-256-cbc",
            "decrypted" : "",
            "deleteKey" : false,
            "encrypted" : "",
            "iterations" : 0,
            "key" : "",
            "salt" : ""
        },
        "plots" : [
            "D:\\plots",
            "E:\\plots",
            "G:\\plots",
            "H:\\plots"
        ],
        "submissionMaxRetry" : 3,
        "targetDeadline" : "2y",
        "timeout" : 45,
        "urls" : {
            "miningInfo" : "http://pool.burstcoin.ml:8124",
            "submission" : "http://pool.burstcoin.ml:8124",
            "wallet" : ""
        }
    },
    "webserver" : {
        "credentials" : {
            "hashed-pass" : "",
            "hashed-user" : "",
            "plain-pass" : "",
            "plain-user" : ""
        },
        "start" : true,
        "url" : "http://192.168.1.2:8080"
    }
}

**Comment by Creepsky** [comment]
Can you please change in your config file
`logging.server` from `fatal` to `error` and copy what the error message says.

**Comment by N8Thrasher** [comment]
it's gone... maybe server/pool issue
