### ISSUE TITLE
Poco/Platform.h file not found on macOS

### ISSUE THREAD

**Issue by BobbyT** [Creepsky/creepMiner#139]
Hello,

I followed the instruction from wiki for macOS, but when I execute `make`, I get this error:

```
 make
[  4%] Building CXX object CMakeFiles/burst-miner.dir/src/Deadline.cpp.o
In file included from /Users/BobbyT/BurstCoin/creepMiner/src/Deadline.cpp:1:
In file included from /Users/BobbyT/BurstCoin/creepMiner/src/Deadline.hpp:4:
/Users/BobbyT/BurstCoin/creepMiner/src/Declarations.hpp:6:10: fatal error: 'Poco/Platform.h' file not found
#include <Poco/Platform.h>
         ^
1 error generated.
make[2]: *** [CMakeFiles/burst-miner.dir/src/Deadline.cpp.o] Error 1
make[1]: *** [CMakeFiles/burst-miner.dir/all] Error 2
make: *** [all] Error 2
```

Do I have to link it somewhere manually?

**Comment by Creepsky** [comment]
Hi!
You need to install [poco](https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation#poco-on-macos) and [openssl](https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation#openssl-on-macos) first.

**Comment by BobbyT** [comment]
both are installed with brew

**Comment by Creepsky** [comment]
hmm.. the cmake file should link to poco, no need to link it manually.
Oh, what version (branch) do you use?

**Comment by BobbyT** [comment]
development branch

**Comment by Creepsky** [comment]
Ok. I am not very familiar with macOS, but can it be that you installed an older version of Poco?
I fear you have to compile Poco by yourself.

Here is the install script for Linux.. if you kick out the OS specific lines, you should be able to execute it and install Poco automatically:
```
#!/bin/sh
set -ex
wget https://pocoproject.org/releases/poco-1.7.6/poco-1.7.6-all.tar.gz
tar -xzvf poco-1.7.6-all.tar.gz
sudo apt-get install openssl
sudo apt-get install libssl-dev
cd poco-1.7.6-all && ./configure --no-tests --no-samples && make && sudo ldconfig && sudo make install
```

these are the important lines:
```
wget https://pocoproject.org/releases/poco-1.7.6/poco-1.7.6-all.tar.gz
tar -xzvf poco-1.7.6-all.tar.gz
cd poco-1.7.6-all && ./configure --no-tests --no-samples && make && sudo ldconfig && sudo make install
```

Maybe @k06a can help you more.

**Comment by k06a** [comment]
@BobbyT maybe try to relink poco:
```
brew unlink poco && brew link poco
```

Looks like your compiler is unable to discover poco headers.

**Comment by BobbyT** [comment]
@k06a unfortunately it didn't work.
@Creepsky I don't have ldconfig

any idea how to tell make to include an extra path?

**Comment by Creepsky** [comment]
Add it to CMakeLists.txt: 
header-files: `include_directories(/your/path/)`
lib-files: `link_directories(/your/path/)`

**Comment by BobbyT** [comment]
@Creepsky 
`include_directories` is  missing, maybe, thats the reason?

**Comment by Creepsky** [comment]
What did you add?

**Comment by BobbyT** [comment]
I added include_directories (missing) after link_directories (existing)

```
link_directories(/usr/local/lib/)
include_directories(/usr/local/include)
```

But the executable wasn't created in bin/ directory but in the root dir, should I move it?
Because, my web interface isn't working. I'm getting a blank site.

**Comment by k06a** [comment]
@BobbyT you should move it in `bin` subdirectory
