### ISSUE TITLE
Incorrect Height

### ISSUE THREAD

**Issue by raigrace01** [Creepsky/creepMiner#140]
I am currently getting below entry on the log files. And looks like the miner is not showing the last winner and other info.

Got response for wallet request '/burst?requestType=getBlock&height=373147'
{"errorCode":4,"errorDescription":"Incorrect \"height\""}

Here is my mining.conf
{
    "logging" : {
        "config" : "information",
        "general" : "information",
        "miner" : "information",
        "nonceSubmitter" : "information",
        "output" : {
            "dirDone" : true,
            "lastWinner" : true,
            "nonceConfirmed" : true,
            "nonceFound" : true,
            "nonceOnTheWay" : true,
            "nonceSent" : true,
            "plotDone" : false
        },
        "path" : "",
        "plotReader" : "information",
        "plotVerifier" : "information",
        "server" : "fatal",
        "session" : "error",
        "socket" : "off",
        "wallet" : "information"
    },
    "mining" : {
        "intensity" : 3,
        "maxBufferSizeMB" : 128,
        "maxPlotReaders" : 0,
        "passphrase" : {
            "algorithm" : "aes-256-cbc",
            "decrypted" : "",
            "deleteKey" : false,
            "encrypted" : "",
            "iterations" : 0,
            "key" : "",
            "salt" : ""
        },
        "plots" : [
            "G:\\Burst\\plots"
        ],
        "submissionMaxRetry" : 3,
        "targetDeadline" : "0y 0m 20d 15:00:00",
        "timeout" : 45,
        "urls" : {
            "miningInfo" : "http://pool.burstcoin.biz:8124",
            "submission" : "http://pool.burstcoin.biz:8124/",
            "wallet" : "https://wallet.burst-team.us:8128"
        }
    },
    "webserver" : {
        "credentials" : {
            "hashed-pass" : "",
            "hashed-user" : "",
            "plain-pass" : "",
            "plain-user" : ""
        },
        "start" : true,
        "url" : "http://localhost:8899"
    }
}

**Comment by Creepsky** [comment]
The wallet is not fully synced and behind the real blockheight. You have to wait some time, until it catches all the new blocks.
It also can be that it is stuck. Then you have to wait until the admin is resetting it again.
