### ISSUE TITLE
OpenCL support on AMD APU

### ISSUE THREAD

**Issue by Axadiw** [Creepsky/creepMiner#141]
Hi,

I've noticed that you're supporting CUDA acceleration on Nvidia graphic cards.

Is it possible to use hardware acceleration from integrated graphic card from AMD CPUs (so just use OpenCL acceleration, instead of CUDA)?

Cheers

**Comment by Creepsky** [comment]
Hi,
it is not possible yet, but sure, why not. It will take some time to develop, because cuda and opencl has quite different apis.

**Comment by Axadiw** [comment]
Oh, I would really appreciate this acceleration on OpenCL :)

Thanks!

**Comment by Creepsky** [comment]
OpenCL is now implemented.

```
    "mining" : {
        "cpuInstructionSet" : "SSE2",
        "gpuDevice" : 0,
        "gpuPlatform" : 0,
        "processorType" : "CPU",
    },
```

**cpuInstructionSet** can be set to SSE2, SSE4, AVX, AVX2.
**gpuDevice** is the device to use for both, CUDA and OpenCL.
**gpuPlatform** is the context platform to use for OpenCL.
**processorType** can be set to CPU, CUDA, OPENCL.

**Comment by Axadiw** [comment]
Nice! 

I don't have currently access to my miner, but as soon as I'll have it - I'll look definitely at this implementation

**Comment by Axadiw** [comment]
ok, I've got an access to my miner sooner than I think. I've got couple of questions about OpenCL usage:

1. Does it matter which `cpuInstructionSet` i'd use If I'm using **OPENCL** `processorType`?
2. When I've started using *OPENCL* `processorType` I've noticed small performance boost (~10-20%), but I think that my system might perform better (specs below). When `creepminer` is scanning my plotfiles, I've noticed that progressbar is splitted into 2 parts:
- half-transparent one (that I think is corresponding to data read from the disks)
- solid one (plots that have been processed by CPU / GPU).

After incresing miner buffer to couple GB's, `half-transparent` progressbar is filling rather quickly, and `solid` one is filling much slower. Does it mean that my GPU / CPU is a bottleneck there? How could I improve performance of my system?

3. At application launch I've noticed that creepminer is using `AMD Accelerated Parallel Processing, Version: OpenCL 1.2 AMD-APP (1445.5)`. I remember that I've got some problems in the past with installing newer OpenCL versions on my system, but is OpenCL version important in case of performance? Which versions of OpenCL are supported by creepminer?

Specs:

CPU: 4 core AMD Athlon X4 845
RAM: 8GB
GPU: Radeon 280X
System: Ubuntu 16.04
Disks: 12 x 8TB Seagate Backup Plus Hub (USB 3.0 drives directly to the mainboard, without extra USB hubs)

This gives ~87TB of plots that are procesed in 70-85 seconds when isung GPU, and 100+ seconds on CPU

**Comment by Creepsky** [comment]
1. no, `cpuInstructionSet` is only for `processorType` **CPU**
2. you are right with the colors, half-transparent stands for read, solid for processed data from plot files.

You can improve the overall speed by increasing `maxBufferSizeMB`, like you did, but never use a buffer size bigger than your RAM or your GPU memory size.
Also try to increase `intensity`.

The OpenCL implementation is still in development and optimizations will come.

3. supported versions depends on the library you use.
Implementations of OpenCL should have macros included, that show you what version is supported. For me (NVidia implementation) these are the macros `CL_VERSION_1_0`, `CL_VERSION_1_1` and `CL_VERSION_1_2`, that are all defined with `1`, what means, they are all supported.

Every new version brings new features and tweeks, so its always good to hold the system up to date.

**Comment by Axadiw** [comment]
ok, but what do you think might be a bottleneck for me right now?

So far I thought that I need to buy PCI-E USB hub with separate USB controllers (I thought that current USB controller just can't handle more data being transferred from the disks).

Looking at creepminer's progressbar (this half-transparent part that's filling very quickly) I'm not so sure about this.

**Comment by Creepsky** [comment]
The way you describe it it must be your GPU, but it could also be just the algorithm.
What timings do you get when you use [jminer](https://github.com/de-luxe/burstcoin-jminer)?

**Comment by Axadiw** [comment]
~10 seconds lower than when using creepMiner

**Comment by Creepsky** [comment]
hmmm.. I am not experienced with that many TB, but when I think about it: 70-85 seconds for 87TB sounds not too bad.
However, I would also say that the bottleneck is your GPU.

There is one more thing you could do to see the [progress times](https://github.com/Creepsky/creepMiner/wiki/Setting-up-the-miner#progressbar) a bit better:

```
    "logging" : {
        "progressBar" : {
            "fancy" : false,
            "steady" : false
        }
    }
```
