### ISSUE TITLE
JSON error with miner forwarding to master miner

### ISSUE THREAD

**Issue by p0nt** [Creepsky/creepMiner#146]
I get the following errors while trying to run a miner that report its results to my nas which has the webinterface available on thuis.rmerdam.com:8080.

09:45:35: Got invalid json response from server
09:45:35:       URI: /burst?requestType=getBlock&height=374821
09:45:35:       Response: <!DOCTYPE html>
09:45:35: 
09:45:35: 
09:45:35: 
09:45:35:  <html class="no-js" lang="en-US"> 
09:45:35: <head>
09:45:35: <title>DNS resolution error | thuis.rmerdam.com | Cloudflare</title></title>

here is my settings:

09:45:35: Pool Host : http://thuis.rmerdam.com:8080 (77.170.19.106)
09:45:35: Mininginfo URL : http://thuis.rmerdam.com:8080 (77.170.19.106)
09:45:35: Wallet URL : http://thuis.rmerdam.com:8080 (77.170.19.106)
09:45:35: Server URL : http://127.0.0.1:8080 (127.0.0.1)

**Comment by p0nt** [comment]
oh and on the master miner it does show me the directory from the slave:

17:37:58: p0nts: nonce confirmed (10m 27d 21:06:59)
17:37:58:       nonce: 5242583
17:37:58:       in /data/plot/647051911296549233_3801088_1900544_8192
17:37:59: p0nts: nonce confirmed (1m 23d 01:13:43)
17:37:59:       nonce: 5265613
17:37:59:       in /data/plot/647051911296549233_3801088_1900544_8192
17:37:59: [++++++++++++++++++++++++------------------------] 50%

Does this mean I can ignore the JSON error?

**Comment by SamuelNZ** [comment]
> 09:45:35: Got invalid json response from server
> 09:45:35: URI: /burst?requestType=getBlock&height=374821
> 09:45:35: Response: 
> 09:45:35: 
> 09:45:35: 
> 09:45:35: 
> 09:45:35: 
> 09:45:35: 
> 09:45:35: <title>DNS resolution error | thuis.rmerdam.com | Cloudflare</title></title>

This means when the miner is trying to make Wallet calls to the API cloudflare on your server is blocking it.

Wallet URL is actually optional but if this is happening for other things you need to look into that.

**Comment by p0nt** [comment]
Thank you for the response @SamuelNZ

I dont have cloudflare on my server, most likely this is the response from the wallet on my main server which uses cloudflare (http://pool.burstcoin.ro:8080)

so on my main server I dont get this error.

On the second server I can keep wallet empty to solve the issue? Wil the second server still report to the main server about the plots?

**Comment by SamuelNZ** [comment]
I'm not sure whether your deadlines are reaching your main server, I imagine if they weren't you'd be getting a different error.

The error you are getting is from cloudflare, I couldn't say why your DNS isn't being resolved, The problem isn't with your creepMiner setup.

I always leave wallet url empty but i don't use forwarding so i don't know if it will impact your setup.

**Comment by Creepsky** [comment]
There are other people that also reported errors with forwarding in combination with cloudflare.
Like @SamuelNZ said, cloudflare is somehow blocking the forwarded wallet requests. It has no impact on mining, but the error messages can be really annoying. 

As a workaround (if you want the wallet informations also on your slave-miner), you can set the wallet-url of the slave-miner directly to the wallet. Or if you dont care about the infos from the wallet you can like already meantioned leave it empty.

I will look for a fix.

**Comment by p0nt** [comment]
Thank you very much!
