### ISSUE TITLE
in MinerData.cpp, when solo mining, targetDeadline_  does not get initialized?

### ISSUE THREAD

**Issue by Bass2014** [Creepsky/creepMiner#148]
in MinerData.cpp, when solo mining, targetDeadline_  does not get initialized?

On Linux, it seems targetDeadline_  is not initialized when solo mining and ends up being some random number, the effect being that manualTargetDeadline gets ignored in getTargetDealine if targetDeadline_ is randomly set to a value lower than manualTargetDeadline.

**Comment by Creepsky** [comment]
This is fixed in [development](https://github.com/Creepsky/creepMiner/tree/development) with commit f318a63749ab6cfcf2629ade255b4bdca486a39d.

**Comment by Bass2014** [comment]
Great thanks !
