### ISSUE TITLE
Secondary nodes send data to the master port 8080

### ISSUE THREAD

**Issue by p0nt** [Creepsky/creepMiner#150]
Is it possible that the secondary node sends all his info from the webinterface to the master? 

For example the master webinterface should show a sum of the total "Plotsize" all nodes have combined instead of separate for each server communicating with the master.

**Comment by Creepsky** [comment]
Yup, will be in the 1.6.0 release.

**Comment by p0nt** [comment]
Sounds great!

**Comment by nitr8** [comment]
closing as forwarding is implemented :) 

Forwarding now is known as "Multi Miner"

Please see the updated wiki page:
https://github.com/Creepsky/creepMiner/wiki/Multi-miner-setup

I have added a task for myself to enhance this page quite a bit.
