### ISSUE TITLE
Logging in UTC instead of system time

### ISSUE THREAD

**Issue by jant90** [Creepsky/creepMiner#154]
creepMiner is logging using UTC time instead of system time. Is that intentional? Because personally I find my log files easier to read when they're logged in my time (system time).

I compiled from the development branch by the way.

**Comment by theblazehen** [comment]
@jant90 It's the same in the web interface, so I'd assume it is

**Comment by jant90** [comment]
@theblazehen the webinterface actually shows my system time (or maybe it uses the time from the miningInfo url?).

**Comment by Creepsky** [comment]
This is changed in this commit in the development-master branch: 4ba5ce4cef67eb969ab630e97eb2bee0c77e46ab

**Comment by jant90** [comment]
Ah, I see thank you!

Btw, how should I see the various branches? Something like:
Master = release?
Development = beta?
Development-master = alpha?

**Comment by Creepsky** [comment]
Yes, you can see the branches like this.
Development-master is only a temporary branch that is a merge between the webinterface-rework and the development branch.
When work is done, it will be merged back into development, so there will only be master and development again.

**Comment by theblazehen** [comment]
@jant90 Ah, whoops. Time in the container where this is running is set to UTC and not local time
