### ISSUE TITLE
Miner has found nonces but doesn't submit it

### ISSUE THREAD

**Issue by gGerret** [Creepsky/creepMiner#155]
Hi.

I am trying to use creepMiner, but I don't understand why it doesn't work properly. I use it in Ubuntu 16. 
In console I see, what nonces was found, but it doesn't submitted. I am useing pool mining with http://pool.burstcoin.biz:8124

Please tell me what I doing wrong. 

There is my miner log:
[creepMiner_20170703_053950.206921.txt](https://github.com/Creepsky/creepMiner/files/1123627/creepMiner_20170703_053950.206921.txt)

Now I have plote 18TB, but no nonces was submitted

And another one, I can not start miner's internal server. In browser it looks like white screen.

And there is my config file 
[mining.txt](https://github.com/Creepsky/creepMiner/files/1123645/mining.txt)

**Comment by Creepsky** [comment]
Hi,

1) in your config you filled in the passphrase. If it is set, the miner will mine solo. Delete all fields inside the "passphrase" block and try again.

I added a warning message in the newest version that will indiciate when you are mining solo.

2) Copy the public/ folder into the same directory as the executable.

**Comment by gGerret** [comment]
Hi, thank you for you comment.

I was installed web server. It works fine, but nonces stil not submit. 

There is screenshot console and web server page: 
![2017-07-05 22-57-50](https://user-images.githubusercontent.com/5090514/27882779-b882f102-61d6-11e7-96b9-e04e7623b6a3.png)

And there is my config without passphrase 
[mining.txt](https://github.com/Creepsky/creepMiner/files/1125901/mining.txt)

And there is new log file: 
[creepMiner_20170705_195604.746259.txt](https://github.com/Creepsky/creepMiner/files/1125929/creepMiner_20170705_195604.746259.txt)

Thank you very match!

**Comment by gGerret** [comment]
Hi again. 

Sorry for my ignorance. I was build it with old gcc (5.x). Now I was built it with gcc 6. And it's a live! 

Best regards!
