### ISSUE TITLE
Cancel plot read process when new block was found

### ISSUE THREAD

**Issue by michaelmattig** [Creepsky/creepMiner#156]
Hi,

I sometimes run into the problem that a new block was found while the miner is still reading the plot files. As far as I see it, the miner then starts reading the plots for the next block concurrently to the old reading process. This leads to a lot of random I/O leading to a longer time to read in the plots. Now if I am unlucky and the next block is found relatively quickly again, I now have three concurrent reading processes.

I propose to either cancel the reading process once a new block was found (if this is possible), or, to wait until the old reading process is done before starting the next one. This should still be faster than reading two scoops at the same time from a hard disk.

**Comment by Creepsky** [comment]
Hi,

this is fixed in this commit 6e870089c955f38f1c9bca60250e909858b632a1.
On a new block the old read process is stopped.

**Comment by michaelmattig** [comment]
thanks, that's great! What is the difference between the development branch and the development-master branch? Is it safe to check out the development-master?

**Comment by Creepsky** [comment]
development-master is unstable and not for production. You can check it out if you want the newest shit.
