### ISSUE TITLE
Help Nothing Works Permission Denied

### ISSUE THREAD

**Issue by Mishapopkin** [Creepsky/creepMiner#158]
Hi. I'm following these instructions on my raspberry pi:

First Install Poco by using the command ./install-poco.sh with the shell-script in the creepMiner-folder.
After this open the Makefile with a Text Editor and change under CFLAGS -march=native to -march=armv6.
Now you can compile by using make. The Miner will be compiled into the subdirectory /bin.
Then change the run.sh-file to:
#!/bin/sh
export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
./creepMiner

Then use sudo ldconfig to update the library cache.
Now you can cd into creepMiner/bin and start the Miner using ./creepMiner.

If you want, I would be glad if you donate to my Burst-Address: BURST-7F9H-KPAG-543J-6VL86

I'm stuck on the first step. Whenever I run ./install-poco.sh, it says permission denied. I even ran it after logging into SU, and it still says that. Please help.

**Comment by Creepsky** [comment]
Call it with sudo maybe? Don't know, this is not the scripts fault. You need to look at your user permission settings of the OS.

**Comment by theblazehen** [comment]
@Mishapopkin Have you ran `chmod +x install-poco.sh`?

**Comment by Mishapopkin** [comment]
That's exactly what I did theblazehen and it seems to have worked. It's still downloading now, it's been 2 hours...
Thank you.

**Comment by Mishapopkin** [comment]
oh hey it just finished. nvm.

**Comment by Mishapopkin** [comment]
Guys, I need help again. I'm doing the next step now, where i have to "compile by using make".
I ran make in the creepminer folder, and it gives me this error:

cclplus: error: unrecognized command line option '-std=c++14

**Comment by Mishapopkin** [comment]
Did some research and changed it to -std=c++0x. 
Something's happening!

**Comment by Mishapopkin** [comment]
nope didn't work. Different error.

**Comment by Creepsky** [comment]
Your compiler does not have the c++14 standard.
What branch did you download and install?

**Comment by Mishapopkin** [comment]
Branch? Sorry I don't know much about this.

**Comment by ITwrx** [comment]
and what version/release of rasbian are you using? sounds like your rasbian and it's gcc are too old to me.

**Comment by Mishapopkin** [comment]
That's probably what it is. 
gcc: gcc (debian 4.6.3- 14+rpil) 4.6.3

That's old I think. I ran a sudo command to install gcc again, but it says that it's the latest version.


I ran a cat command to find the os version. Looks like it's raspbian os 7.

**Comment by Creepsky** [comment]
gcc is indeed a bit old. It only supports c++0x what means, it supports only parts of c++11.
What link did you use to download the creepMiner?

**Comment by Mishapopkin** [comment]
https://github.com/Creepsky/creepMiner I used this link.
Thank you for taking you time to help me.
I'm currently looking at this page: https://stackoverflow.com/questions/25147363/how-to-install-g-4-9-on-debian-wheezy-armel 
And following the instructions in the first reply.

**Comment by ITwrx** [comment]
i would skip trying to upgrade pieces of your really old rasbian(if i'm understanding debian/rasbian versioning. see links below. ) and download the latest rasbian and write that image to your sd card and then download the miner, etc. 

https://www.debian.org/releases/

https://www.raspberrypi.org/downloads/raspbian/

however, i've never owned a rasberi pie so, you know i'm kind of guessing about some things here. :)

**Comment by Mishapopkin** [comment]
Man... That's gonna take a while. You're sure there's no other way? Everything's gonna be erased ): ...
I guess I'll have to do it if there's no other way.

**Comment by Creepsky** [comment]
Before you do something that you will propably regret after a while - what errors exactly do you get when you compile? Can you please copy them?

**Comment by Mishapopkin** [comment]
when I compile with c++0x you mean? I'm gonna run it again and paste the error

**Comment by Mishapopkin** [comment]
Wowser. A bunch of errors, cause that compiler's just too old and incompatible  i guess. Here it is:
pi@raspberrypi ~/Desktop/BurstCoin/creepMiner-master $ make
g++ -O3 -march=armv6 -std=c++0x -Wall -D_REENTRANT -DNDEBUG -Isrc/sphlib -Isrc/nxt -Isrc -IPoco/Net -IPoco/Foundation -IPoco/NetSSL_OpenSSL -IPoco/openssl -IPoco/Crypto -IPoco/Util -IPoco/JSON -c src/Account.cpp -o bin/obj/Account.o
In file included from src/Deadline.hpp:4:0,
                 from src/Account.hpp:3,
                 from src/Account.cpp:1:
src/Declarations.hpp:24:15: error: field ‘literal’ has incomplete type
src/Declarations.hpp:31:15: error: field ‘name’ has incomplete type
src/Declarations.hpp:34:15: error: field ‘nameAndVersion’ has incomplete type
src/Declarations.hpp:35:15: error: field ‘nameAndVersionAndOs’ has incomplete type
src/Declarations.hpp:71:2: error: expected unqualified-id before ‘using’
src/Declarations.hpp:72:8: error: expected nested-name-specifier before ‘ScoopData’
src/Declarations.hpp:72:8: error: ‘ScoopData’ has not been declared
src/Declarations.hpp:72:18: error: expected ‘;’ before ‘=’ token
src/Declarations.hpp:72:18: error: expected unqualified-id before ‘=’ token
src/Declarations.hpp:73:8: error: expected nested-name-specifier before ‘GensigData’
src/Declarations.hpp:73:8: error: ‘GensigData’ has not been declared
src/Declarations.hpp:73:19: error: expected ‘;’ before ‘=’ token
src/Declarations.hpp:73:19: error: expected unqualified-id before ‘=’ token
src/Declarations.hpp:74:8: error: expected nested-name-specifier before ‘HashData’
src/Declarations.hpp:74:8: error: ‘HashData’ has not been declared
src/Declarations.hpp:74:17: error: expected ‘;’ before ‘=’ token
src/Declarations.hpp:74:17: error: expected unqualified-id before ‘=’ token
src/Declarations.hpp:76:8: error: expected nested-name-specifier before ‘AccountId’
src/Declarations.hpp:76:8: error: ‘AccountId’ has not been declared
src/Declarations.hpp:76:18: error: expected ‘;’ before ‘=’ token
src/Declarations.hpp:76:18: error: expected unqualified-id before ‘=’ token
src/Declarations.hpp:77:8: error: expected nested-name-specifier before ‘Nonce’
src/Declarations.hpp:77:8: error: ‘Nonce’ has not been declared
src/Declarations.hpp:77:14: error: expected ‘;’ before ‘=’ token
src/Declarations.hpp:77:14: error: expected unqualified-id before ‘=’ token
In file included from src/Account.hpp:3:0,
                 from src/Account.cpp:1:
src/Deadline.hpp:31:3: error: ‘AccountId’ does not name a type
src/Deadline.hpp:48:27: sorry, unimplemented: non-static data member initializers
src/Deadline.hpp:48:27: error: in-class initialization of static data member ‘plotFile_’ of non-literal type
In file included from src/Account.hpp:3:0,
                 from src/Account.cpp:1:
src/Deadline.hpp:64:16: error: ‘Nonce’ has not been declared
src/Deadline.hpp:65:16: error: ‘Nonce’ has not been declared
src/Deadline.hpp:65:29: error: ‘AccountId’ has not been declared
In file included from src/Account.cpp:1:0:
src/Account.hpp:18:21: error: expected ‘)’ before ‘id’
src/Account.hpp:19:33: error: ‘AccountId’ has not been declared
src/Account.hpp:23:3: error: ‘AccountId’ does not name a type
src/Account.hpp:26:3: error: ‘AccountId’ does not name a type
src/Account.hpp:27:22: error: ‘AccountId’ was not declared in this scope
src/Account.hpp:27:31: error: template argument 1 is invalid
src/Account.hpp:34:3: error: ‘AccountId’ does not name a type
src/Account.hpp:37:3: error: ‘AccountId’ does not name a type
src/Account.hpp:39:18: error: ‘AccountId’ was not declared in this scope
src/Account.hpp:39:27: error: template argument 1 is invalid
src/Account.hpp:42:22: error: ‘AccountId’ was not declared in this scope
src/Account.hpp:42:46: error: template argument 1 is invalid
src/Account.hpp:49:39: error: ‘AccountId’ has not been declared
src/Account.hpp:50:17: error: ‘AccountId’ has not been declared
src/Account.hpp:53:22: error: ‘AccountId’ was not declared in this scope
src/Account.hpp:53:56: error: template argument 1 is invalid
src/Account.hpp:53:56: error: template argument 3 is invalid
src/Account.hpp:53:56: error: template argument 4 is invalid
src/Account.hpp:53:56: error: template argument 5 is invalid
In file included from src/Account.cpp:4:0:
src/Wallet.hpp:32:41: error: ‘AccountId’ has not been declared
src/Wallet.hpp:33:25: error: ‘AccountId’ has not been declared
src/Wallet.hpp:34:36: error: ‘AccountId’ has not been declared
src/Wallet.hpp:34:55: error: ‘AccountId’ has not been declared
src/Wallet.hpp:36:19: error: ‘AccountId’ has not been declared
src/Account.cpp: In constructor ‘Burst::Account::Account()’:
src/Account.cpp:10:4: error: type ‘Burst::Account’ is not a direct base of ‘Burst::Account’
/usr/local/include/Poco/ActiveMethod.h:118:2: error: ‘Poco::ActiveMethod<ResultType, ArgType, OwnerType, StarterType>::ActiveMethod() [with ResultType = std::basic_string<char>, ArgType = bool, OwnerType = Burst::Account, StarterType = Poco::ActiveStarter<Burst::Account>]’ is private
src/Account.cpp:10:14: error: within this context
src/Account.cpp: At global scope:
src/Account.cpp:13:24: error: expected constructor, destructor, or type conversion before ‘(’ token
src/Account.cpp:14:11: error: expected unqualified-id before ‘,’ token
src/Account.cpp:15:11: error: expected constructor, destructor, or type conversion before ‘{’ token
src/Account.cpp:15:20: error: expected unqualified-id before ‘,’ token
src/Account.cpp:16:12: error: expected constructor, destructor, or type conversion before ‘{’ token
src/Account.cpp:16:40: error: expected unqualified-id before ‘,’ token
src/Account.cpp:17:24: error: expected constructor, destructor, or type conversion before ‘{’ token
src/Account.cpp:18:1: error: expected unqualified-id before ‘{’ token
src/Account.cpp:20:47: error: ‘AccountId’ has not been declared
src/Account.cpp: In constructor ‘Burst::Account::Account(const Burst::Wallet&, int, bool)’:
src/Account.cpp:21:4: error: class ‘Burst::Account’ does not have any field named ‘id_’
src/Account.cpp:24:32: error: ‘runGetRewardRecipient’ is not a member of ‘Burst::Account’
src/Account.cpp:24:62: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘int’ in initialization
src/Account.cpp: At global scope:
src/Account.cpp:39:1: error: ‘AccountId’ in namespace ‘Burst’ does not name a type
src/Account.cpp:96:1: error: ‘AccountId’ in namespace ‘Burst’ does not name a type
src/Account.cpp:106:20: error: ‘AccountId’ is not a member of ‘Burst’
src/Account.cpp:106:20: error: ‘AccountId’ is not a member of ‘Burst’
src/Account.cpp:106:36: error: template argument 1 is invalid
src/Account.cpp: In member function ‘int Burst::Account::getRewardRecipientAsync(bool)’:
src/Account.cpp:108:34: error: ‘((Burst::Account*)this)->Burst::Account::getRewardRecipient_’ cannot be used as a function
src/Account.cpp: In member function ‘std::string Burst::Account::getAddress() const’:
src/Account.cpp:113:26: error: ‘getId’ was not declared in this scope
src/Account.cpp: In member function ‘Poco::JSON::Object::Ptr Burst::Account::toJSON() const’:
src/Account.cpp:122:29: error: ‘getId’ was not declared in this scope
src/Account.cpp: In lambda function:
src/Account.cpp:140:36: error: ‘id_’ was not declared in this scope
src/Account.cpp:141:2: error: return-statement with a value, in function returning 'void' [-fpermissive]
src/Account.cpp: At global scope:
src/Account.cpp:144:1: error: ‘AccountId’ in namespace ‘Burst’ does not name a type
src/Account.cpp:155:61: error: ‘std::shared_ptr<Burst::Account> Burst::Accounts::getAccount’ is not a static member of ‘class Burst::Accounts’
src/Account.cpp:155:61: error: ‘AccountId’ was not declared in this scope
src/Account.cpp:155:81: error: expected primary-expression before ‘&’ token
src/Account.cpp:155:83: error: ‘wallet’ was not declared in this scope
src/Account.cpp:155:91: error: expected primary-expression before ‘bool’
src/Account.cpp:156:1: error: expected ‘,’ or ‘;’ before ‘{’ token
In file included from /usr/include/c++/4.6/memory:80:0,
                 from src/Deadline.hpp:3,
                 from src/Account.hpp:3,
                 from src/Account.cpp:1:
/usr/include/c++/4.6/functional: In static member function ‘static _Res std::_Function_handler<_Res(_ArgTypes ...), _Functor>::_M_invoke(const std::_Any_data&, _ArgTypes ...) [with _Res = bool, _Functor = Burst::Account::runGetName(const bool&)::<lambda(std::string&)>, _ArgTypes = {std::basic_string<char>&}]’:
/usr/include/c++/4.6/functional:2148:6:   instantiated from ‘std::function<_Res(_ArgTypes ...)>::function(_Functor, typename std::enable_if<(! std::is_integral<_Functor>::value), std::function<_Res(_ArgTypes ...)>::_Useless>::type) [with _Functor = Burst::Account::runGetName(const bool&)::<lambda(std::string&)>, _Res = bool, _ArgTypes = {std::basic_string<char>&}, typename std::enable_if<(! std::is_integral<_Functor>::value), std::function<_Res(_ArgTypes ...)>::_Useless>::type = std::function<bool(std::basic_string<char>&)>::_Useless]’
src/Account.cpp:141:3:   instantiated from here
/usr/include/c++/4.6/functional:1764:40: error: void value not ignored as it ought to be
src/Account.cpp: In member function ‘std::string Burst::Account::getAddress() const’:
src/Account.cpp:114:1: warning: control reaches end of non-void function [-Wreturn-type]
src/Account.cpp: In member function ‘int Burst::Account::getRewardRecipientAsync(bool)’:
src/Account.cpp:109:1: warning: control reaches end of non-void function [-Wreturn-type]
make: *** [bin/obj/Account.o] Error 1
pi@raspberrypi ~/Desktop/BurstCoin/creepMiner-master $ ^C

[log.txt](https://github.com/Creepsky/creepMiner/files/1129081/log.txt)

**Comment by ITwrx** [comment]
@Mishapopkin what would take a while? what "everything"(not sarcastic quotes, literal ones) will be erased? you have a bunch of stuff running on your rasberry pi already? i must be missing something. 

@Creepsky why would he regret wiping the *old* OS and running a current version of rasbain os?

**Comment by Mishapopkin** [comment]
yeah I might just need to update. I don't really mind. I never use my Raspberry Pi. And when I do, I guess this happens.

**Comment by Mishapopkin** [comment]
Well won't everything on my SD card get wiped? Like all of my files? I don't mind doing it, I'm just wondering if there's another way.

**Comment by Creepsky** [comment]
Ok thats bad, these are things that would take a lot of time to change to non c++11.

@ITwrx well he will not regret the replacement of the old OS, but I am careful telling people to update something, especially the os. You'll never know what will break :)

Not saying that updates are not necessary from time to time and in this case @Mishapopkin doesnt have much choice it seems.

**Comment by Mishapopkin** [comment]
Alright... I'll have to do it. I'm trying one last thing here before though, I'm updating the rpi (framework?) to see if that does anything.

**Comment by Mishapopkin** [comment]
actually one more thing: Do you guys know any other miners for raspberry pi? (debian).
Maybe something else would work with my older version.

**Comment by Creepsky** [comment]
Try this:
https://github.com/guytp/burst-sharp (https://forums.burst-team.us/topic/6627/rpi-arm-cross-platform-architecture-miner-anybody-interested)
or urays miner.

**Comment by ITwrx** [comment]
@Mishapopkin well, yes but you should back up your data first. i'm not suggesting you just delete everything and then see how you feel about that later. :) another way to do what? install software from the future into your ancient rasbian OS? :) maybe, but i doubt it's a viable solution long term. 

@Creepsky oh, yeah. i hear you. @Mishapopkin will want to do his/her own due diligence about compatibility, procedures, whatever or things could go bad. Of course, this is how you learn. These things only seem difficult when you're new to it.

**Comment by Mishapopkin** [comment]
Thank you very much. I'll check it out. But I think I'll just have to update everything. Might be worth it for other stuff

**Comment by ITwrx** [comment]
no prob. good luck.

**Comment by Mishapopkin** [comment]
Yeah of course. I'll make sure to back all the important stuff up. In fact, I could just copy my SD card to this computer. 

Thank you.
