### ISSUE TITLE
no deadlines and no submissions

### ISSUE THREAD

**Issue by blinkin69** [Creepsky/creepMiner#160]
![cree](https://user-images.githubusercontent.com/22307896/27945314-b9d87b96-62ec-11e7-9e36-f11a64565bc8.JPG)
hello,

i installed / compile last day creepminer on ubuntu. it start with no problem, i configured with right poolsettings but i get no deathlines after reading my 25 tb hard disks.

how can i find out where is the problem?

**Comment by Creepsky** [comment]
Please try the development version 1.6.0. 1.5.2 is outdated in will be replaced soon.

**Comment by blinkin69** [comment]
ok i have now 1.6.0 but also no deadline found, on windows 10 i have no problem to find DL

my log: 
[creepMiner_20170707_093409.281551.txt](https://github.com/Creepsky/creepMiner/files/1130605/creepMiner_20170707_093409.281551.txt)

**Comment by blinkin69** [comment]
`07.07.2017 09:35:55 (0, src/Miner.cpp, 200, Notice): --------------------------------------------------
block#      379155
scoop#      2307
baseTarget# 189023
--------------------------------------------------
07.07.2017 09:35:55 (18, src/Wallet.cpp, 163, Debug): Sending wallet request '/burst?requestType=getBlock&height=379154'
07.07.2017 09:35:55 (0, src/MinerServer.cpp, 174, Warning): Could not send the data to the websocket!
	data: {"baseTarget":189023,"bestDeadlines":[],"block":379155,"blocksMined":1,"blocksWon":0,"deadlinesAvg":"00:00:00","deadlinesConfirmed":0,"gensigStr":"9b1253c477e4e2bc3d52ae51c9e4b74c5c0f5c906399320e97603e0637e81986","scoop":2307,"time":"11:35:55","type":"new block"}
07.07.2017 09:35:55 (0, src/MinerServer.cpp, 175, Error): I/O error: Broken pipe
07.07.2017 09:35:55 (0, src/MinerServer.cpp, 174, Warning): Could not send the data to the websocket!
	data: {"baseTarget":189023,"bestDeadlines":[],"block":379155,"blocksMined":1,"blocksWon":0,"deadlinesAvg":"00:00:00","deadlinesConfirmed":0,"gensigStr":"9b1253c477e4e2bc3d52ae51c9e4b74c5c0f5c906399320e97603e0637e81986","scoop":2307,"time":"11:35:55","type":"new block"}
07.07.2017 09:35:55 (0, src/MinerServer.cpp, 175, Error): I/O error: Broken pipe
07.07.2017 09:35:55 (0, src/MinerServer.cpp, 174, Warning): Could not send the data to the websocket!`

**Comment by Creepsky** [comment]
That happens when you close the websocket connection, nothing to worry about.
Yesterday I updated the development branch, this warning is also fixed.
You can try it.

**Comment by jeev20** [comment]
I did not know this feature existed to open a web server in CreepMiner. Tried it today. This is brilliant! Makes monitoring the session easy. Kudos again!
