### ISSUE TITLE
Used Memory rise up and stop client

### ISSUE THREAD

**Issue by blinkin69** [Creepsky/creepMiner#161]
The client dont reset the used memory after each block round and climb to max memory and then virtual ram. if nothing more left, the client crash.

all hdd readings are done in each round. thats not the problem.

i tried different max ram settings but is change only the time when it will be crash.

**Comment by theblazehen** [comment]
I run mine in a lxd container, but even without that, you can limit memory with cgroups

**Comment by blinkin69** [comment]
ok thanks im new to ubuntu but i will try :) should this not do the client?

**Comment by Creepsky** [comment]
Please verify that there is a memory leak by testing it on a different system.

**Comment by blinkin69** [comment]
First Round:
![firstround](https://user-images.githubusercontent.com/22307896/27959277-1319a506-6327-11e7-9af8-0e6e976cbb99.JPG)

Second Round:
![secondround](https://user-images.githubusercontent.com/22307896/27959280-146163d6-6327-11e7-9a14-d465f14a0cb5.JPG)

3. Round:
![3round](https://user-images.githubusercontent.com/22307896/27959284-1588ca42-6327-11e7-9d84-1a805510a3d6.JPG)


i can test it on another pc,  if i know how i can compile this repo on windows 10.

**Comment by blinkin69** [comment]
with follow settings, it works now well. if i get it again i will reply.
thx creepsky for this fine miner. know my read speed are double time faster then on windows 👍 

"intensity" : 2,
        "maxBufferSizeMB" : 4024,
        "maxPlotReaders" : 3,

**Comment by blinkin69** [comment]
@Creepsky my cpu should be my bottleneck, but i found out that if my plotts are search, and the round ends before it finish, then it dont stop the search, and it get slow and eat more ram then i set in config.

**Comment by blinkin69** [comment]
it start with sse2 for G4400 CPU , tomorrow i will check I3 6100 with AX2

**Comment by Creepsky** [comment]
@blinkin69  This is fixed in the newest development branch, please try it with it. (dont forget to pull, cmake, make)

**Comment by blinkin69** [comment]
i did yesterday , git clone and git checkout development and cmake, make, but i have this issue.

**Comment by blinkin69** [comment]
@Creepsky 

i have the same issues with the development branch and avx2 , also i compile with CUDA support but it change nothing, also CPU are at 100% with I3 6100, i have 11 drives about 78 TB

if a round end and the plots are not finish with reading. its slow down and max memory is more and often kill the process. but when i lower the max mem, the whole process is to slow, so i must go over 11 GB RAM. but often hit the limit of my installed 16 GB RAM. 

if i stop the process and start again the read speed is fine, but only when it not overlap with a new block.

**Comment by blinkin69** [comment]
@Creepsky

i fixed it. i have rised my swap to 64 GB from 2 GB. now it works 24h.
