### ISSUE TITLE
Configure HTTP Proxy

### ISSUE THREAD

**Issue by michaelmattig** [Creepsky/creepMiner#162]
Hi,

it would be great if one could configure a HTTP proxy for the miner. Right now I patched the miner myself using this piece of code but  haven't had time to find the correct place or figuring out how to read the config.

```
Poco::Net::HTTPClientSession::ProxyConfig proxyConfig;
proxyConfig.host="proxy.example.com";
proxyConfig.port=1234;
Poco::Net::HTTPClientSession::setGlobalProxyConfig(proxyConfig);
```
If there are others interested in such a feature maybe you could implement it or I try to create a pull request.

**Comment by nitr8** [comment]
and tested - closing
