### ISSUE TITLE
invalid json response from server

### ISSUE THREAD

**Issue by Mishapopkin** [Creepsky/creepMiner#166]
I'm back! I got creepMiner to start on my raspberry pi by updating it from wheezy to jessie. I configured all the settings and ran the miner and i get this message, which repeats every couple minutes:

09:18:32: Got invalid json response from server
09:18:32: 	URI: /burst?requestType=getBlock&height=379863
09:18:32: 	Response: <html>
09:18:32: <head><title>504 Gateway Time-out</title></head>
09:18:32: <body bgcolor="white">
09:18:32: <center><h1>504 Gateway Time-out</h1></center>
09:18:32: <hr><center>nginx/1.4.6 (Ubuntu)</center>
09:18:32: </body>
09:18:32: </html>
09:18:32: 
09:18:32: 	Syntax error: JSON syntax error
09:18:32: Stackframe
09:18:32: Miner::runGetLastWinner (in "src/MinerData.cpp", line 237)
09:18:32: Wallet::getWinnerOfBlock (in "src/Wallet.cpp", line 29)
09:18:32: Wallet::sendWalletRequest (in "src/Wallet.cpp", line 157)
09:18:32: 

Please help me figure out what this means and how to fix it. Thank you.

**Comment by Mishapopkin** [comment]
Ah that's cool the error was written in HTML code so this forum recognized that and styled it accordingly. Here is the complete log.

file:///home/pi/Desktop/log1.txt

**Comment by Creepsky** [comment]
**What it mean**s: https://www.lifewire.com/504-gateway-timeout-error-explained-2622941.
**How to fix**: unfortunately you can not fix it, this problem is on pool side. Please try another pool or wait, till the admin of the pool fixed the problem.

**Comment by Mishapopkin** [comment]
So it's server side? But I'm able to mine just fine on my windows 7 computer using blago on the same pool (pool.burstcoin.space:8124).
Here's my log if it helps.
Thanks.
[log1.txt](https://github.com/Creepsky/creepMiner/files/1133649/log1.txt)

**Comment by theblazehen** [comment]
@Creepsky I had that issue where I couldn't reach the wallet, but the pool was fine, IIRC

**Comment by Creepsky** [comment]
Yep, its not your pool but your wallet.
Change it to a different address, `https://wallet.burst-team.us:8128` is down.

**Comment by Mishapopkin** [comment]
Ahh ok. Do I need to have one for the miner though?

**Comment by Mishapopkin** [comment]
And if I do, which one should i use? I only ever used wallet.burst-team.us so I don't know any other ones.

**Comment by theblazehen** [comment]
@Mishapopkin Nope, you don't need it. You can also just run your own wallet

**Comment by Mishapopkin** [comment]
alright thanks. So in the config file, I can just remove whatever's written in the wallet url line?
