### ISSUE TITLE
creepMiner Server not starting/not found

### ISSUE THREAD

**Issue by Zeereeo** [Creepsky/creepMiner#167]
I wanted to setup forwarding for my miners, either on Linux or Windows. However, for both, the server will not start and no web-GUI shows up(more like not found). 

Here's my config

{
    "maxBufferSizeMB" : 128,
    "maxPlotReaders" : 0,
    "miningInfoUrl" : "http://m.burst4all.com:8124",
    "miningIntensity" : 3,
    "logging" : {
		"path" : "./logs",
        "config" : "information",
        "general" : "information",
        "miner" : "information",
        "nonceSubmitter" : "information",
        "plotReader" : "information",
        "plotVerifier" : "information",
        "server" : "fatal",
        "session" : "error",
        "socket" : "off",
        "wallet" : "fatal"
    },
	"output" : {
        "dirDone" : true,
        "lastWinner" : true,
        "nonceConfirmed" : true,
        "nonceFound" : true,
        "nonceOnTheWay" : true,
        "nonceSent" : true,
        "plotDone" : false
    },
    "passphrase" : {
        "algorithm" : "aes-256-cbc",
        "decrypted" : "",
        "deleteKey" : false,
        "encrypted" : "",
        "iterations" : 0,
        "key" : "",
        "salt" : ""
    },
    "plots" : [
        "xxxxjusttasayxxxx"
    ],
    "poolUrl" : "http://m.burst4all.com:8124",
    "serverUrl" : "http://192.168.0.102:8080",
    "Start Server" : true,
    "submissionMaxRetry" : 3,
    "targetDeadline" : "0y 0m 730d 00:00:00",
    "timeout" : 45,
    "walletUrl" : "https://wallet.burstcoin.ro:8124"
}

Hope yall can help!

**Comment by Creepsky** [comment]
Your config looks like it is from version 1.5.2 or below. What version are you using?

**Comment by Zeereeo** [comment]
Sorry. It seems like I indeed had version 1.5.2. I didn't realise that I had always been downloading the old (Stable) rather than the updated version(Dev). Only realised it later in the forums. Anyways, Thanks!

However, it seems like the server takes up quite a lot of cpu power to keep it running in the background. Is there any way to slow the refresh rate or optimise to use less resources?

**Comment by Creepsky** [comment]
Webserver is using almost no resources.
Try the newest version.
