### ISSUE TITLE
GUI problem and deadlines/submissions just stop after about 2 hours

### ISSUE THREAD

**Issue by dxiri** [Creepsky/creepMiner#169]
I installed/configured creepminer on Centos 7, compiled using these instructions: https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation-on-CentOS. I have a 537GB plot. Everything seems to be working fine except the GUI.

I configured the gui to be available on localhost, port 8080, this is a headless server so to connect to the gui for security reasons I do port forwarding using ssh like this:

ssh -L 8081:localhost:8080 root@SERVERIP

Then type localhost:8081 on my browser, which works (displays the page). However, the page comes up with just the blue bar, the creepminer logo and no info at all (every box is blank). Here is a reference screenshot: http://prntscr.com/ft2r7c

To run the miner, I run: "nohup ./run.sh &" that way I can see the output on nohup.out on the same folder I have the creepminer compiled binary in (and creepminer won't exit when I close my shell).

Is there a reason for the lack of data on the gui?

Here is my mining.conf (feel free to make other suggestions as well :D ):

{
    "logging" : {
        "config" : "information",
        "general" : "information",
        "miner" : "information",
        "nonceSubmitter" : "information",
        "output" : {
            "dirDone" : true,
            "lastWinner" : true,
            "nonceConfirmed" : true,
            "nonceFound" : true,
            "nonceOnTheWay" : true,
            "nonceSent" : true,
            "plotDone" : false
        },
        "path" : "/var/log/",
        "plotReader" : "information",
        "plotVerifier" : "information",
        "server" : "fatal",
        "session" : "error",
        "socket" : "off",
        "wallet" : "information"
    },
    "mining" : {
        "intensity" : 3,
        "maxBufferSizeMB" : 700,
        "maxPlotReaders" : 0,
        "passphrase" : {
            "algorithm" : "aes-256-cbc",
            "decrypted" : "",
            "deleteKey" : false,
            "encrypted" : "",
            "iterations" : 0,
            "key" : "",
            "salt" : ""
        },
        "plots" : [
            "/burst/plots"
        ],
        "submissionMaxRetry" : 3,
        "targetDeadline" : "0",
        "timeout" : 45,
        "urls" : {
            "miningInfo" : "http://pool.burstcoin.ml:8124",
            "submission" : "http://pool.burstcoin.ml:8124",
            "wallet" : "http://localhost:8125"
        }
    },
    "webserver" : {
        "credentials" : {
            "hashed-pass" : "",
            "hashed-user" : "",
            "plain-pass" : "",
            "plain-user" : ""
        },
        "start" : true,
        "url" : "http://localhost:8080"
    }

**Another thing I just noticed:**
for some reason after ~1:45 hours of the miner running, It just stops sending nonces and only shows this output:

01:16:42: Dir /burst/plots read (1 files, 500.39 GB total) in 9.187s (~13.62 MB/s)
01:17:43: --------------------------------------------------
01:17:43: block#      379480
01:17:43: scoop#      1061
01:17:43: baseTarget# 219645
01:17:43: --------------------------------------------------
01:17:43: --------------------------------------------------
01:17:43: last block winner:
01:17:43: block#             379479
01:17:43: winner-numeric     11057109464612582920
01:17:43: winner-address     HFJA-H8EF-ESC5-BYPWL
01:17:43: --------------------------------------------------
01:17:52: Dir /burst/plots read (1 files, 500.39 GB total) in 8.893s (~14.07 MB/s)
01:17:59: --------------------------------------------------
01:17:59: block#      379481
01:17:59: scoop#      2485
01:17:59: baseTarget# 191737
01:17:59: --------------------------------------------------
01:17:59: --------------------------------------------------
01:17:59: last block winner:
01:17:59: block#             379480
01:17:59: winner-numeric     10276640676891941155
01:17:59: winner-address     LQB5-9XM9-9WGY-AQH9X
01:17:59: winner-name        Kanzas
01:17:59: --------------------------------------------------
01:18:08: Dir /burst/plots read (1 files, 500.39 GB total) in 9.565s (~13.08 MB/s)
Software info:

[root@siacr01 bin]# head -100 /var/log/creepMiner_20170707_205158.157623.log
07.07.2017 20:51:58 (0, src/main.cpp, 47, Information): creepMiner 1.5.2 Unix x64
07.07.2017 20:51:58 (0, src/main.cpp, 48, Information): ----------------------------------------------
07.07.2017 20:51:58 (0, src/main.cpp, 49, Information): Github:   https://github.com/Creepsky/creepMiner
07.07.2017 20:51:58 (0, src/main.cpp, 50, Information): Author:   Creepsky [creepsky@gmail.com]
07.07.2017 20:51:58 (0, src/main.cpp, 51, Information): Burst :   BURST-JBKL-ZUAV-UXMB-2G795
07.07.2017 20:51:58 (0, src/main.cpp, 52, Information): ----------------------------------------------
07.07.2017 20:51:58 (0, src/main.cpp, 53, Information): Based on http://github.com/uraymeiviar/burst-miner
07.07.2017 20:51:58 (0, src/main.cpp, 54, Information): author : uray meiviar [ uraymeiviar@gmail.com ]
07.07.2017 20:51:58 (0, src/main.cpp, 55, Information): please donate to support developments :
07.07.2017 20:51:58 (0, src/main.cpp, 56, Information):  [ Burst   ] BURST-8E8K-WQ2F-ZDZ5-FQWHX
07.07.2017 20:51:58 (0, src/main.cpp, 57, Information):  [ Bitcoin ] 1UrayjqRjSJjuouhJnkczy5AuMqJGRK4b
07.07.2017 20:51:58 (0, src/main.cpp, 58, Information): ----------------------------------------------
07.07.2017 20:51:58 (0, src/main.cpp, 72, Information): using config file mining.conf
07.07.2017 20:51:59 (0, src/MinerConfig.cpp, 314, Information): Changing path for log file to
	/var/log/creepMiner_20170707_205158.157623.log
07.07.2017 20:52:02 (0, src/MinerConfig.cpp, 597, Debug): Reading passphrase...
07.07.2017 20:52:02 (0, src/Miner.cpp, 51, Information): Total plots size: 500.39 GB
07.07.2017 20:52:02 (0, src/Miner.cpp, 53, Information): Submission Max Retry : 3
07.07.2017 20:52:02 (0, src/Miner.cpp, 55, Information): Buffer Size : 700 MB
07.07.2017 20:52:02 (0, src/Miner.cpp, 58, Information): Pool Host : http://pool.burstcoin.ml:8124 (173.212.236.124)
07.07.2017 20:52:02 (0, src/Miner.cpp, 61, Information): Mininginfo URL : http://pool.burstcoin.ml:8124 (173.212.236.124)
07.07.2017 20:52:02 (0, src/Miner.cpp, 64, Information): Wallet URL : http://localhost:8125 (::1)
07.07.2017 20:52:02 (0, src/Miner.cpp, 67, Information): Server URL : http://192.168.0.23:8080 (186.176.50.117)
07.07.2017 20:52:02 (0, src/Miner.cpp, 70, Information): Mining intensity : 3
07.07.2017 20:52:02 (0, src/Miner.cpp, 71, Information): Max plot readers : 1
07.07.2017 20:52:02 (0, src/Miner.cpp, 73, Information): Log path : /var/log/creepMiner_20170707_205158.157623.log
07.07.2017 20:52:06 (0, src/Miner.cpp, 174, Debug): Verification queue cleared.
07.07.2017 20:52:06 (0, src/Miner.cpp, 194, Notice): --------------------------------------------------
Killing the process (pkill creepMiner) and starting it again solves it, but we all know it sucks having to babysit a process :)

Hope you can look into this!

**Comment by Creepsky** [comment]
Hi!

To solve your first problem just change `"webserver" -> "url" : "http://localhost:8080"` to `"http://<domain/ip>:8080"`.

`<domain/ip>` is either the IP of your computer in your local network, if you just want to use it inside your network, or the public domain (for example my-domain.com), if you want to use it also from outside your network.

You are using version 1.5.2, that is a bit outdated.
In version 1.6.0 there are a lot of features and bugfixes - try the branch `development (git checkout development)`.

You will notice, that there is no makefile anymore - you have to [build it yourself with cmake](https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation-with-CMake).
