### ISSUE TITLE
Harddisk keep alive

### ISSUE THREAD

**Issue by mrandt** [Creepsky/creepMiner#171]
Some of my external USB drives spin down when they have not been accessed for 5 minutes.

Unfortunately, this "power saving but drive killing" logic is implemented in the drive interface hardware and cannot be controlled by operating system.

A bit of googling showed that actually quite a few manufacturers have implemented their own standby functionality in hardware.

On longer blocks, all drives will spin down - only to wake up and resume spinning a few minutes later. Annoying sound and also not a good idea in terms of drive motor lifetime.

Only way to prevent spindown / spinup is to constantly access the drives every other minute. I currently use a shell script + cron to write a file to the drives every minute.

It would be a helpful feature if creepMiner supported a "keep alive" on the disks. Simply read the first few bytes of each plot file in a configurable interval.

**Comment by Creepsky** [comment]
There is a new keep-alive-feature.

```
{
...
    "mining" : {
        "wakeUpTime" : 0,
    },
...
}
```

wakeUpTime is the interval in seconds, when a weak-up-signal is send to the HDDs.
