### ISSUE TITLE
Show cpu AVX or SSE info

### ISSUE THREAD

**Issue by shadowlinyf** [Creepsky/creepMiner#172]
Is there a way for creepminer to show the info if the miner is mining with avx,avx2,sse support?

**Comment by Creepsky** [comment]
Yes, it is written in the first line on start: "creepMiner 1.6.0 Windows x64 AVX".
Also the name of the executable will match the cpu instruction set: "creepMiner-avx" or "creepMiner-cuda-sse4".

**Comment by shadowlinyf** [comment]
Thanks.
I just figure it out.
Mine used to be x64(does that mean use no cpu instruction set?)
BTW:how much faster will avx2 be compare to just x64?

**Comment by Creepsky** [comment]
x64 means you use the 64 bit version.
I dont know the exact times, but it should be faster (Blago said AVX2 is around 30% faster).

You can build your exe with whatever cpu instruction set you need with [cmake](https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation-with-CMake).
Please dont forget to use the latest development version.
