### ISSUE TITLE
development branch Urls in mining.conf mismatch with the miner start info

### ISSUE THREAD

**Issue by shadowlinyf** [Creepsky/creepMiner#173]
here is the urls config in my mining.conf 
       "urls" : {
            "miningInfo" : "http://bibenwei.com:8124",
            "submission" : "http://192.99.252.194:8124",
            "wallet" : "https://wallet.burst-team.us:8128"
        },

below is the miner start info.
Mininginfo URL and Submission URL are mismatched with the ones from config file.

16:31:36: using config file mining.conf
16:31:40: Logfile deactivated
16:31:40: Submission Max Retry : 3
16:31:40: Buffer Size : 8000 MB
**_**16:31:40: Mininginfo URL : http://192.99.252.194:8124
16:31:40: Submission URL : http://bibenwei.com:8124
16:31:40: Wallet URL : https://wallet.burst-team.us:8128
16:31:40: Server URL : http://192.168.0.100:8080
16:31:40: Target deadline : 3d 12:00:00**_**
16:31:40: Total plots size: 115.23 TB
16:31:40: Mining intensity : 16
16:31:40: Max plot readers : 16
16:31:40: got new target deadline
16:31:40:       old target deadline: 00:00:00
16:31:40:       new target deadline: 9d 04:00:00
16:31:40:       lowest target deadline: 3d 12:00:00

I think it is a bug only related to the starting info because the miner works the way it supposed to though. 

PS:Is it ok I use mining info url different from the submission url?because I got a lot getmininginfo failed from the pool I am using so I use a different url to get the block info.

**Comment by Creepsky** [comment]
You are right, it was a display bug ;)
It is ok to use different Urls!
