### ISSUE TITLE
No thread available

### ISSUE THREAD

**Issue by blinkin69** [Creepsky/creepMiner#174]
now i have an AVX2 cpu I3 it works better but now i get after some time 

Error on getting new block-info!                                    
14:52:07: 	No thread available
14:52:07: Stackframe                                                          
14:52:07: main (in "/home/miner1/creepMiner/src/main.cpp", line 54)
14:52:07: Miner::run (in "/home/miner1/creepMiner/src/mining/Miner.cpp", line 66)
14:52:07: Miner::getMiningInfo (in "/home/miner1/creepMiner/src/mining/Miner.cpp", line 340)
14:52:07: 
14:52:10: Error on getting new block-info!                                    
14:52:10: 	No thread available
14:52:10: Stackframe                                                          
14:52:10: main (in "/home/miner1/creepMiner/src/main.cpp", line 54)
14:52:10: Miner::run (in "/home/miner1/creepMiner/src/mining/Miner.cpp", line 66)
14:52:10: Miner::getMiningInfo (in "/home/miner1/creepMiner/src/mining/Miner.cpp", line 340)

i must stop and restart, what that mean?

**Comment by Creepsky** [comment]
How can I reproduce this error?
It means one of your thread pools is running out of available threads.

**Comment by blinkin69** [comment]
@Creepsky 

i think i figure out why it happen. i run at the same time etherium gpu miner which use the gpu up to 100%.  now i dont use the first GPU for ethereum mining and i dont get this error anymore. but i would like to use both.
