### ISSUE TITLE
Is it possible to add a info bar at the bottom ?

### ISSUE THREAD

**Issue by shadowlinyf** [Creepsky/creepMiner#175]
to show percents of plot file read and combined reading speed and other useful info.
current progress bar of dev branch is not always displayed.

**Comment by Creepsky** [comment]
Do you mean like in Blagos miner?

**Comment by shadowlinyf** [comment]
yes. like the blagos miner.

**Comment by rottmann** [comment]
Hope not, i want to use it in linux shell without gui.

**Comment by shadowlinyf** [comment]
@rottmann I meant to add it  in the linux shell just like current progress bar but with more info.

**Comment by Creepsky** [comment]
New progress bar shows 3 kind of infos:
read progress, deadline verification progress and combined read speed.

options that are for progress bar in config:
```
{
    "logging" : {
...
        "progressBar" : {
            "fancy" : true,
            "steady" : true
        },
...
}
```
