### ISSUE TITLE
Web UI plot info is incorrect

### ISSUE THREAD

**Issue by shadowlinyf** [Creepsky/creepMiner#176]
The plot file on my system was:
ls /mnt/nfs/disk_02_1/ -lah
2.0T Jul  1 04:09 3479212793982110872_2110000000000_8192000_8192000

what was shown on web ui:

Account | Start nonce | Nonces | Staggersize | Size
disk | 02 | 1/3479212793982110872 | 2110000000000 | 1.95 TB

**Comment by Creepsky** [comment]
Is already fixed in development.
