### ISSUE TITLE
Miner stops reading Plots

### ISSUE THREAD

**Issue by eiswuerfel** [Creepsky/creepMiner#177]
Iam using Arch and latest dev Version. Miner starts reading a plotfile and stops at a few percent. New blocks will be displayed and sometimes after start it finde one share. 
I have no idea.

17:39:37: creepMiner 1.6.0 Unix x64
17:39:37: ----------------------------------------------
17:39:37: Github:   https://github.com/Creepsky/creepMiner
17:39:37: Author:   Creepsky [creepsky@gmail.com]
17:39:37: Burst :   BURST-JBKL-ZUAV-UXMB-2G795
17:39:37: ----------------------------------------------
17:39:37: using config file mining.conf
17:39:37: Changed logfile path to
17:39:37: 	creepMiner_20170715_153937.512714.log
17:39:37: Submission Max Retry : 5
17:39:37: Buffer Size : 256 MB
17:39:37: Submission URL : http://burst.cryptoguru.org:8124
17:39:37: Mininginfo URL : http://burst.cryptoguru.org:8124
17:39:37: Wallet URL : http://127.0.0.1:8125
17:39:37: Server URL : http://localhost:8080
17:39:37: Target deadline : 1m 0d 00:00:00
17:39:37: Log path : creepMiner_20170715_153937.512714.log
17:39:37: Total plots size: 18.19 TB
17:39:37: Mining intensity : 3
17:39:37: Max plot readers : 2
17:39:37: --------------------------------------------------
17:39:37: block#     	382104
17:39:37: scoop#     	3515
17:39:37: baseTarget#	232522
17:39:37: gensig     	1e1bb8b9a97c48d682524178591c6b43
17:39:37:               e5abaadfa3b0c711fc373aad57ed2a9f
17:39:37: --------------------------------------------------
17:39:37: --------------------------------------------------
17:39:37: last block winner: 
17:39:37: block#             382103
17:39:37: winner-numeric     1490060754095201482
17:39:37: winner-address     JR8C-DKUT-673M-34GDB
17:39:37: winner-name        HDD_Farmer
17:39:37: --------------------------------------------------

[log.txt](https://github.com/Creepsky/creepMiner/files/1150456/log.txt)

**Comment by Creepsky** [comment]
I have no idea either.
Can you please attach this file `creepMiner_20170715_153937.512714.log` and remove the log from here? Its not really readable.

Also I need some more informations about your problem.
- How did you compile it?
- What are the cmake parameters you used?
- What exactly do you mean with "sometimes after start it finde one share"?
- How many are exactly "a few percent"?
- Does it get stuck at exactly the same percentage every round?
- Do you get messages like `Dir .... read (in .... sec.) .....`?

**Comment by eiswuerfel** [comment]
Im updated the log on the first post.  
Compiled using this:

pacman -S poco
git clone -b development https://github.com/Creepsky/creepMiner.git
cd creepMiner
cmake CMakeLists.txt -DCMAKE_BUILD_TYPE=RELEASE
make

I tried building with latest poco too, but no difference. 

Scannig freeze between 8%-14%. 
On most but not all starts I get this one time:
15.07.2017 18:23:54 (6, /home/admin/Desktop/creepMiner/src/plots/PlotReader.cpp, 257, Information): /mnt/b1/burst/9431759562995605153_110000000_7454720_7454720 (1.78 TB) read in 2.825s (~161.01 MB/s)

If in this File a valid share it will be sent to the pool. 
I have 2 drives with 5 files like this on each, but it only search on this file. 

thanks

**Comment by doiron99** [comment]
I complied last night, have the same problem with pool mining. 

cmake CMakeLists.txt -DCMAKE_BUILD_TYPE=RELEASE -b ./ -DCPU_INSTRUCTION_SET=AVX2 -DGPU_ACCELERATION=None -DLOG_OUTPUT=Terminal -DOVERWRITE_MINING_CONF=OFF

Solo mining it just won't scan drives sometimes.  New blocks come in, but no reading starts.

Seems to only happen on host computer (small, 3 computer network, 2 communicating to 1 host).

**Comment by Creepsky** [comment]
Thanks @eiswuerfel @doiron99 for the infos.
Could you both please compile a version of the miner with the cmake flag: `-DLOG_OUTPUT=SERVICE`?
I have the feeling that somewhere while logging is a deadlock.

**Comment by doiron99** [comment]
Rebuilt.  I'll check back in half an hour to see if it's chugging along.

**Comment by doiron99** [comment]
Ok, it's still dropping.  I turned the web server on and off, same thing.  Still only affecting 1/3 computers (the host).

**Comment by eiswuerfel** [comment]
I see no difference.
[log.txt](https://github.com/Creepsky/creepMiner/files/1150509/log.txt)

**Comment by Creepsky** [comment]
Do you have discord? https://discord.gg/tXmCz6
It would make things a lot easier. You can use it without register.

**Comment by dotkat** [comment]
Me also having the same issue:
10:24:14: Target deadline : 10d 00:00:00
10:24:14: Total plots size: 9.60 TB
10:24:14: Mining intensity : 10
10:24:14: Max plot readers : 1
10:24:14: Get mining info interval : 3 seconds
10:24:14: Looking for mining info...
10:24:14: got new target deadline from pool
10:24:14:       old pool target deadline: 00:00:00
10:24:14:       new pool target deadline: 10d 00:00:00
10:24:14:       target deadline from config: 10d 00:00:00
10:24:14:       lowest target deadline: 10d 00:00:00
10:24:14: --------------------------------------------------
10:24:14: block#        385805
10:24:14: scoop#        1267
10:24:14: baseTarget#   246932
10:24:14: gensig        a82d89d24d51c1789024b2727fc5aea4
10:24:14:               38e008af53cbecc5cf7364fa7655428c
10:24:14: --------------------------------------------------
10:24:14: --------------------------------------------------
10:24:14: last block winner:
10:24:14: block#             385804
10:24:14: winner-numeric     6008331258436716275
10:24:14: winner-address     Y3RM-GARZ-RAHY-73HS8
10:24:14: winner-name        Siraj Ali
10:24:14: --------------------------------------------------
10:24:30: [+++++-------------------------------------------] 11%

Plot reader is stuck between 6-26%

**Comment by Creepsky** [comment]
@dotkat your log does not show anything that could be helpful for me.

**Comment by de7and** [comment]
I'm using ubuntu 17.4 and had a problem same problem with reading the plots... When it starts hit one dl with first plot and stop at 17% . Then in the next block no plots loaded... It loads only small HDDs.

**Comment by blinkin69** [comment]
your buffersize setting with 256mb didnt work for in any versions, i set it to my max available mb RAM. but it depends on the drives i have. now i have 16 drives and i must set it to 30 GB buffersize otherwise its so slow or in the new version it stuck. sry i have no technial background, must it also run with 256 mb buffer?

**Comment by gGerret** [comment]
Hi. I have same problem. Somtimes miner halts on reading plot files. It's web server halts too. And sometimes it stops with segmentation fault error. 

Here is my log files:
[creepMiner_20170806_100520.052158.txt](https://github.com/Creepsky/creepMiner/files/1204097/creepMiner_20170806_100520.052158.txt)
[creepMiner_20170806_173837.311420.txt](https://github.com/Creepsky/creepMiner/files/1204098/creepMiner_20170806_173837.311420.txt)

**Comment by gGerret** [comment]
I am jast see when it happens. It happens when the new block comes before reading finish for old block.

**Comment by gGerret** [comment]
And here another error:

08.08.2017 14:36:05 (4, /home/gerret/creepMiner/src/wallet/Wallet.cpp, 184, Deb$
08.08.2017 14:36:06 (4, /home/gerret/creepMiner/src/wallet/Wallet.cpp, 197, Deb$
{"unconfirmedBalanceNQT":"93361615985","guaranteedBalanceNQT":"93361615985","un$
08.08.2017 14:36:06 (43, /home/gerret/creepMiner/src/mining/MinerData.cpp, 363,$
last block winner:
block#             390473
winner-numeric     475659089355996197
winner-address     ZZ37-FHRM-GBTU-23H8F
winner-name        lj470
--------------------------------------------------
08.08.2017 14:51:04 (21, /home/gerret/creepMiner/src/webserver/MinerServer.cpp,$
        data: {"type":"progress","value":22.04618,"valueVerification":22.000458}
08.08.2017 14:51:04 (21, /home/gerret/creepMiner/src/webserver/MinerServer.cpp,$
        error-code: 110
        class: N4Poco16TimeoutExceptionE

In console - segmentation fault

**Comment by bkrith** [comment]
try to change in mining.conf bufferSizeMB to 0 and maxPlotReaders to 0 also

**Comment by Creepsky** [comment]
Does this problem still occur with the latest version?

**Comment by doiron99** [comment]
My problem was a hard drive that was failing and sometimes holding up the others in the system.  Haven't had any issues since I removed that drive.

**Comment by gGerret** [comment]
Creepsky, I don't know. I am using old version, that was release 1.6.0 for 1.5 months ago because it more stable. 

Today I will try new version 1.6.0 from releases tab.

**Comment by gGerret** [comment]
And another comment, I use creepMiner on Ubuntu 16 (64 bit)
