### ISSUE TITLE
Unable to make

### ISSUE THREAD

**Issue by Bobpick** [Creepsky/creepMiner#182]
I have the latest Raspbian, and have update and upgraded to today's latest.
I've installed the poco using the script file.
I edited the CFLAGS to =armv6
When I run the make command, this is what I get:

g++ -O3 -march=armv6 -std=c++14 -Wall -D_REENTRANT -DNDEBUG -Isrc/sphlib -Isrc/nxt -Isrc -IPoco/Net -IPoco/Foundation -IPoco/NetSSL_OpenSSL -IPoco/openssl -IPoco/Crypto -IPoco/Util -IPoco/JSON -c src/Url.cpp -o bin/obj/Url.o
In file included from src/Url.cpp:1:0:
src/Url.hpp:4:22: fatal error: Poco/URI.h: No such file or directory
 #include <Poco/URI.h>
                      ^
compilation terminated.
Makefile:41: recipe for target 'bin/obj/Url.o' failed
make: *** [bin/obj/Url.o] Error 1

Any suggestions?

**Comment by Creepsky** [comment]
Poco/URI.h: No such file or directory
you have no poco, or your compiler cant find poco.
did you call sudo ldconfig?
you successfully installed poco?

**Comment by Bobpick** [comment]
Well, crap.
No. I did not do the ldconfig. Trying it all now.

**Comment by Bobpick** [comment]
The instructions say to run Make first, then sudo ldconfig. So that's why i didn't do it yet. I did run the Sudo ldconfig, and then ran make with similar results.

I did notice something while installing poco, and that was Arm7 was displayed a few times. Should this matter?

**Comment by StianCronje** [comment]
I am having the same issue. I followed the instructions for building on raspberry pi, and ran the ldconfig command after installing POCO. It still can't find Poco/URI.h

**Comment by StianCronje** [comment]
@Bobpick I am using a raspberry pi 2. I tried making with march=native and it worked. I used the install-poco.sh from the 1.6 release and all the other files from the current source code.

**Comment by Bobpick** [comment]
I will give it a shot later today. I'm using Raspberry pi 3b. I will let you know

**Comment by Bobpick** [comment]
Stian, would you be so kind as to post your install-poco.sh file?

**Comment by StianCronje** [comment]
@Bobpick heres the code for the install-poco.sh
`
#!/bin/sh
set -ex
wget https://pocoproject.org/releases/poco-1.7.6/poco-1.7.6-all.tar.gz
tar -xzvf poco-1.7.6-all.tar.gz
sudo apt-get install openssl
sudo apt-get install libssl-dev
cd poco-1.7.6-all && ./configure --no-tests --no-samples && make && sudo ldconfig && sudo make install
`

**Comment by StianCronje** [comment]
If march=armv6 does not work, try native. RPi2 (and i think RPi3) is armv7 so native worked for me.

**Comment by Creepsky** [comment]
`install_poco.sh` in master is back to normal.

**Comment by Bobpick** [comment]
While installing Poco, using a fresh install, this happened. It did not happen on the last poco install I did.
** Compiling src/Cipher.cpp (debug, shared)
g++  -Iinclude -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/CppUnit/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/CppUnit/WinTestRunner/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Foundation/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/XML/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/JSON/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Util/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Net/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Crypto/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/NetSSL_OpenSSL/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Data/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Data/SQLite/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Data/ODBC/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Data/MySQL/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/MongoDB/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Zip/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/PageCompiler/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/PageCompiler/File2Page/include -Wall -Wno-sign-compare -DPOCO_BUILD_HOST=Collosus -DPOCO_TARGET_OSNAME=Linux -DPOCO_TARGET_OSARCH=armv7l  -D_XOPEN_SOURCE=500 -D_REENTRANT -D_THREAD_SAFE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DPOCO_HAVE_FD_EPOLL  -g -D_DEBUG -fPIC -c src/Cipher.cpp -o /home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Crypto/obj/Linux/armv7l/debug_shared/Cipher.o
** Compiling src/CipherFactory.cpp (debug, shared)
g++  -Iinclude -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/CppUnit/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/CppUnit/WinTestRunner/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Foundation/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/XML/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/JSON/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Util/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Net/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Crypto/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/NetSSL_OpenSSL/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Data/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Data/SQLite/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Data/ODBC/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Data/MySQL/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/MongoDB/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Zip/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/PageCompiler/include -I/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/PageCompiler/File2Page/include -Wall -Wno-sign-compare -DPOCO_BUILD_HOST=Collosus -DPOCO_TARGET_OSNAME=Linux -DPOCO_TARGET_OSARCH=armv7l  -D_XOPEN_SOURCE=500 -D_REENTRANT -D_THREAD_SAFE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DPOCO_HAVE_FD_EPOLL  -g -D_DEBUG -fPIC -c src/CipherFactory.cpp -o /home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Crypto/obj/Linux/armv7l/debug_shared/CipherFactory.o
In file included from include/Poco/Crypto/CipherKeyImpl.h:24:0,
                 from include/Poco/Crypto/CipherKey.h:24,
                 from src/CipherFactory.cpp:19:
include/Poco/Crypto/OpenSSLInitializer.h:26:28: fatal error: openssl/crypto.h: No such file or directory
 #include <openssl/crypto.h>
                            ^
compilation terminated.
/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/build/rules/compile:53: recipe for target '/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Crypto/obj/Linux/armv7l/debug_shared/CipherFactory.o' failed
make[1]: *** [/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Crypto/obj/Linux/armv7l/debug_shared/CipherFactory.o] Error 1
make[1]: Leaving directory '/home/pi/Downloads/creepMiner-master/poco-1.7.6-all/Crypto'
Makefile:201: recipe for target 'Crypto-libexec' failed
make: *** [Crypto-libexec] Error 2


Any suggestions?

**Comment by StianCronje** [comment]
Try installing the latest version of POCO as well. I believe it is version 1.7.8p3.

**Comment by Creepsky** [comment]
Seems like you are missing OpenSSL dev headers: `libssl-dev`.
On Debian for example you can use
```
sudo apt-get install openssl
sudo apt-get install libssl-dev
```

**Comment by rottmann** [comment]
I don't know what i am doing wrong. One time i could compile it, but after last debian update it will not work.

Debian 9.1
Linux 4.9.0-3-amd64

```
$ apt-get install build-essential cmake

$ echo "deb http://ftp.debian.org/debian jessie-backports main" >> /etc/apt/sources.list.d/jessie-backports.list
$ apt-get update
$ apt-get -t jessie-backports install libssl-dev

$ wget https://www.openssl.org/source/openssl-1.0.2l.tar.gz
$ tar xzvf openssl-1.0.2l.tar.gz
$ cd openssl-1.0.2l
$ ./config --prefix=/usr/local --openssldir=/usr/local/openssl shared
$ make
$ make install

$ cd /usr/src
$ git clone https://github.com/Creepsky/creepMiner.git
$ cd creepMiner

tried with master or development
$ git checkout development

$ ./install-poco.sh
$ cp poco-1.7.6-all/lib/Linux/x86_64/* /usr/local/lib/
```

```
$ cmake CMakeLists.txt -DCMAKE_BUILD_TYPE=RELEASE -DCPU_INSTRUCTION_SET=AVX2 -DGPU_ACCELERATION=None -DLOG_OUTPUT=Service -DOVERWRITE_MINING_CONF=ON -b .
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/src/creepMiner

$ make
[  3%] Building CXX object CMakeFiles/creepMiner.dir/src/logging/channels/ColoredPriorityConsoleChannel.cpp.o
[  6%] Building CXX object CMakeFiles/creepMiner.dir/src/logging/channels/MinerDataChannel.cpp.o
[  9%] Building CXX object CMakeFiles/creepMiner.dir/src/logging/Console.cpp.o
[ 12%] Building CXX object CMakeFiles/creepMiner.dir/src/logging/Message.cpp.o
[ 16%] Building CXX object CMakeFiles/creepMiner.dir/src/logging/MinerLogger.cpp.o
[ 19%] Building CXX object CMakeFiles/creepMiner.dir/src/logging/Output.cpp.o
[ 22%] Building CXX object CMakeFiles/creepMiner.dir/src/logging/ProgressPrinter.cpp.o
[ 25%] Building CXX object CMakeFiles/creepMiner.dir/src/mining/Deadline.cpp.o
[ 29%] Building CXX object CMakeFiles/creepMiner.dir/src/mining/Miner.cpp.o
[ 32%] Building CXX object CMakeFiles/creepMiner.dir/src/mining/MinerConfig.cpp.o
[ 35%] Building CXX object CMakeFiles/creepMiner.dir/src/mining/MinerData.cpp.o
[ 38%] Building CXX object CMakeFiles/creepMiner.dir/src/network/NonceSubmitter.cpp.o
[ 41%] Building CXX object CMakeFiles/creepMiner.dir/src/network/Response.cpp.o
[ 45%] Building CXX object CMakeFiles/creepMiner.dir/src/network/Request.cpp.o
[ 48%] Building CXX object CMakeFiles/creepMiner.dir/src/network/Url.cpp.o
[ 51%] Building CXX object CMakeFiles/creepMiner.dir/src/nxt/nxt_address.cpp.o
[ 54%] Building CXX object CMakeFiles/creepMiner.dir/src/plots/Plot.cpp.o
[ 58%] Building CXX object CMakeFiles/creepMiner.dir/src/plots/PlotReader.cpp.o
[ 61%] Building CXX object CMakeFiles/creepMiner.dir/src/plots/PlotSizes.cpp.o
[ 64%] Building CXX object CMakeFiles/creepMiner.dir/src/plots/PlotVerifier.cpp.o
[ 67%] Building CXX object CMakeFiles/creepMiner.dir/src/wallet/Account.cpp.o
[ 70%] Building CXX object CMakeFiles/creepMiner.dir/src/wallet/Wallet.cpp.o
[ 74%] Building CXX object CMakeFiles/creepMiner.dir/src/shabal/sphlib/sph_shabal.cpp.o
[ 77%] Building CXX object CMakeFiles/creepMiner.dir/src/webserver/MinerServer.cpp.o
[ 80%] Building CXX object CMakeFiles/creepMiner.dir/src/webserver/RequestHandler.cpp.o
[ 83%] Building CXX object CMakeFiles/creepMiner.dir/src/Declarations.cpp.o
[ 87%] Building CXX object CMakeFiles/creepMiner.dir/src/main.cpp.o
[ 90%] Building CXX object CMakeFiles/creepMiner.dir/src/MinerUtil.cpp.o
[ 93%] Building CXX object CMakeFiles/creepMiner.dir/src/logging/Performance.cpp.o
[ 96%] Building CXX object CMakeFiles/creepMiner.dir/src/shabal/mshabal/mshabal_avx2.cpp.o
[100%] Linking CXX executable bin/creepMiner-avx2
/usr/local/lib/libPocoCrypto.so: undefined reference to `EVP_CIPHER_CTX_cleanup'
/usr/local/lib/libPocoCrypto.so: undefined reference to `EVP_MD_CTX_cleanup'
/usr/local/lib/libPocoNetSSL.so: undefined reference to `SSLv23_client_method'
/usr/local/lib/libPocoCrypto.so: undefined reference to `CRYPTO_set_dynlock_destroy_callback'
/usr/local/lib/libPocoCrypto.so: undefined reference to `CRYPTO_set_dynlock_lock_callback'
/usr/local/lib/libPocoCrypto.so: undefined reference to `ERR_free_strings'
/usr/local/lib/libPocoCrypto.so: undefined reference to `SSL_load_error_strings'
/usr/local/lib/libPocoCrypto.so: undefined reference to `SSL_library_init'
/usr/local/lib/libPocoCrypto.so: undefined reference to `OPENSSL_add_all_algorithms_noconf'
/usr/local/lib/libPocoCrypto.so: undefined reference to `EVP_cleanup'
/usr/local/lib/libPocoCrypto.so: undefined reference to `EVP_MD_CTX_destroy'
/usr/local/lib/libPocoCrypto.so: undefined reference to `CRYPTO_set_id_callback'
/usr/local/lib/libPocoCrypto.so: undefined reference to `CRYPTO_set_dynlock_create_callback'
/usr/local/lib/libPocoNetSSL.so: undefined reference to `SSLv23_server_method'
/usr/local/lib/libPocoCrypto.so: undefined reference to `CONF_modules_free'
/usr/local/lib/libPocoCrypto.so: undefined reference to `sk_num'
/usr/local/lib/libPocoCrypto.so: undefined reference to `CRYPTO_set_locking_callback'
/usr/local/lib/libPocoCrypto.so: undefined reference to `sk_value'
/usr/local/lib/libPocoCrypto.so: undefined reference to `EVP_MD_CTX_create'
/usr/local/lib/libPocoCrypto.so: undefined reference to `CRYPTO_num_locks'
collect2: error: ld returned 1 exit status
CMakeFiles/creepMiner.dir/build.make:848: die Regel für Ziel „bin/creepMiner-avx2“ scheiterte
make[2]: *** [bin/creepMiner-avx2] Fehler 1
CMakeFiles/Makefile2:67: die Regel für Ziel „CMakeFiles/creepMiner.dir/all“ scheiterte
make[1]: *** [CMakeFiles/creepMiner.dir/all] Fehler 2
Makefile:127: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
```

poco compiled, /usr/local/lib/libPocoCrypto.so exists
any idea?

**Comment by Creepsky** [comment]
All these errors are from missing OpenSSL lib:
```
/usr/local/lib/libPocoCrypto.so: undefined reference to `EVP_CIPHER_CTX_cleanup'
/usr/local/lib/libPocoCrypto.so: undefined reference to `EVP_MD_CTX_cleanup'
/usr/local/lib/libPocoNetSSL.so: undefined reference to `SSLv23_client_method'
/usr/local/lib/libPocoCrypto.so: undefined reference to `CRYPTO_set_dynlock_destroy_callback'
/usr/local/lib/libPocoCrypto.so: undefined reference to `CRYPTO_set_dynlock_lock_callback'
/usr/local/lib/libPocoCrypto.so: undefined reference to `ERR_free_strings'
/usr/local/lib/libPocoCrypto.so: undefined reference to `SSL_load_error_strings'
/usr/local/lib/libPocoCrypto.so: undefined reference to `SSL_library_init'
/usr/local/lib/libPocoCrypto.so: undefined reference to `OPENSSL_add_all_algorithms_noconf'
/usr/local/lib/libPocoCrypto.so: undefined reference to `EVP_cleanup'
/usr/local/lib/libPocoCrypto.so: undefined reference to `EVP_MD_CTX_destroy'
/usr/local/lib/libPocoCrypto.so: undefined reference to `CRYPTO_set_id_callback'
/usr/local/lib/libPocoCrypto.so: undefined reference to `CRYPTO_set_dynlock_create_callback'
/usr/local/lib/libPocoNetSSL.so: undefined reference to `SSLv23_server_method'
/usr/local/lib/libPocoCrypto.so: undefined reference to `CONF_modules_free'
/usr/local/lib/libPocoCrypto.so: undefined reference to `sk_num'
/usr/local/lib/libPocoCrypto.so: undefined reference to `CRYPTO_set_locking_callback'
/usr/local/lib/libPocoCrypto.so: undefined reference to `sk_value'
/usr/local/lib/libPocoCrypto.so: undefined reference to `EVP_MD_CTX_create'
/usr/local/lib/libPocoCrypto.so: undefined reference to `CRYPTO_num_locks'
```

Your setup looks good, maybe just a simple `sudo ldconfig` is missing?

**Comment by rottmann** [comment]
it will not use the self compiles openssl. try now poco 1.7.8

**Comment by neonettech** [comment]
Hi,
I am trying to compile the miner and I am also getting the URI.h not found

=======================
admin@Burst-server-01:$ sudo make
g++ -O3 -march=native -std=c++14 -Wall -D_REENTRANT -DNDEBUG -Isrc/sphlib -Isrc/nxt -Isrc -IPoco/Net -IPoco/Foundation -IPoco/NetSSL_OpenSSL -IPoco/openssl -IPoco/Crypto -IPoco/Util -IPoco/JSON -c src/Url.cpp -o bin/obj/Url.o
In file included from src/Url.cpp:1:0:
src/Url.hpp:4:22: fatal error: Poco/URI.h: No such file or directory
 #include <Poco/URI.h>
                      ^
compilation terminated.
make: *** [Makefile:41: bin/obj/Url.o] Error 1
================================

I already manually installed the latest version of Poco - all the libraries are found under /usr/local/include/Poco - in the various sub folders.
I ran sudo ldconfig, I rebooted the system after installing poco.
I also just for kicks renamed the poco-1.7.8-all folder in the creepminer directory to Poco - thinking that it might find the paths to these files - because the Url.cpp and Url.hpp reference "Poco/include/..." in the include lines.
Also tried to change the path to /usr/local/include/Poco/include" in these files - but I get then I get that it can't find the foundation.h and a few other files.
So I am somewhat stuck here. Is there a step that I am missing?
Thank you for your help in advance! :)

**Comment by neonettech** [comment]
Anyone having luck compiling creepminer without errors? What am I missing?

**Comment by rottmann** [comment]
no i give up and use now jminer

**Comment by rottmann** [comment]
Found this today, package for debian:

`wget -q -O - http://package.cryptoguru.org/debian/init.sh8 | bash && apt-get install creepminer`

**Comment by Creepsky** [comment]
Hope it will help someone: https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation-on-Debian-Linux

**Comment by misovan** [comment]
Hi I have a 1.6.0 version running on pi3. I tried to upgrade to 1.6.3 so I tried to compile it. However, after running make get an error:

`burstcoin@pi:~/Miner/creep_miner/creepMiner-2.6.3 $ make
Scanning dependencies of target creepMiner
[  3%] Building CXX object CMakeFiles/creepMiner.dir/src/logging/channels/ColoredPriorityConsoleChannel.cpp.o
*** Error in `/usr/bin/c++': double free or corruption (top): 0x00d6c418 ***
CMakeFiles/creepMiner.dir/build.make:62: recipe for target 'CMakeFiles/creepMiner.dir/src/logging/channels/ColoredPriorityConsoleChannel.cpp.o' failed
make[2]: *** [CMakeFiles/creepMiner.dir/src/logging/channels/ColoredPriorityConsoleChannel.cpp.o] Aborted
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/creepMiner.dir/all' failed
make[1]: *** [CMakeFiles/creepMiner.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`
Am I missing something or 1.6.3 is not supporting arm chipset anymore?
Thanks Michal

**Comment by DJoeDt** [comment]
I am facing a similar problem when I try to compile on a Banana Pi M2 Berry (has SATA!). 
At the end of the make process I get:

[100%] Linking CXX executable bin/creepMiner
/usr/bin/ld: CMakeFiles/creepMiner.dir/src/nxt/nxt_address.cpp.o: undefined reference to symbol 'sprintf@@GLIBC_2.4'
//lib/arm-linux-gnueabihf/libc.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/creepMiner.dir/build.make:822: recipe for target 'bin/creepMiner' failed
make[2]: *** [bin/creepMiner] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/creepMiner.dir/all' failed
make[1]: *** [CMakeFiles/creepMiner.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

I looked into nxt_address.cpp but couldn't figure out any meaning, sorry.
Does anyone have a clue how to fix this?

**Comment by Creepsky** [comment]
ARM is still supported, I successfully compiled it on a Banana Pro today.

- update your system (`apt-get update` `apt-get upgrade`)
- use the development version (`git checkout development`)
- delete the cmake cache (CMakeCache.txt)
- execute `cmake -DMINIMAL_BUILD=ON`
- execute `make`

What `gcc --version` do you have? Did you successfully compile Poco library before (`sh ./install-poco.sh`)?

Here is a [tutorial for Debian](https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation-on-Debian-Linux), it should be almost the same for Raspbian.

**Comment by rottmann** [comment]
used the latest creepminer soruces 

gcc -v 
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18)
```

poco installs without any problem

```
[ 83%] Building CXX object CMakeFiles/creepMiner.dir/src/main.cpp.o
[ 86%] Building CXX object CMakeFiles/creepMiner.dir/src/MinerUtil.cpp.o
[ 88%] Linking CXX executable bin/creepMiner
/usr/local/lib/libPocoCrypto.so: undefined reference to `EVP_CIPHER_CTX_cleanup'
/usr/local/lib/libPocoCrypto.so: undefined reference to `EVP_MD_CTX_cleanup'
/usr/local/lib/libPocoNetSSL.so: undefined reference to `SSLv23_client_method'
/usr/local/lib/libPocoCrypto.so: undefined reference to `CRYPTO_set_dynlock_destroy_callback'
/usr/local/lib/libPocoCrypto.so: undefined reference to `CRYPTO_set_dynlock_lock_callback'
/usr/local/lib/libPocoCrypto.so: undefined reference to `ERR_free_strings'
/usr/local/lib/libPocoCrypto.so: undefined reference to `SSL_load_error_strings'
/usr/local/lib/libPocoCrypto.so: undefined reference to `SSL_library_init'
/usr/local/lib/libPocoCrypto.so: undefined reference to `OPENSSL_add_all_algorithms_noconf'
/usr/local/lib/libPocoCrypto.so: undefined reference to `EVP_cleanup'
/usr/local/lib/libPocoCrypto.so: undefined reference to `EVP_MD_CTX_destroy'
/usr/local/lib/libPocoCrypto.so: undefined reference to `CRYPTO_set_id_callback'
/usr/local/lib/libPocoCrypto.so: undefined reference to `CRYPTO_set_dynlock_create_callback'
/usr/local/lib/libPocoNetSSL.so: undefined reference to `SSLv23_server_method'
/usr/local/lib/libPocoCrypto.so: undefined reference to `CONF_modules_free'
/usr/local/lib/libPocoCrypto.so: undefined reference to `sk_num'
/usr/local/lib/libPocoCrypto.so: undefined reference to `CRYPTO_set_locking_callback'
/usr/local/lib/libPocoCrypto.so: undefined reference to `sk_value'
/usr/local/lib/libPocoCrypto.so: undefined reference to `EVP_MD_CTX_create'
/usr/local/lib/libPocoCrypto.so: undefined reference to `CRYPTO_num_locks'
collect2: error: ld returned 1 exit status
CMakeFiles/creepMiner.dir/build.make:952: die Regel für Ziel „bin/creepMiner“ scheiterte
make[2]: *** [bin/creepMiner] Fehler 1
CMakeFiles/Makefile2:67: die Regel für Ziel „CMakeFiles/creepMiner.dir/all“ scheiterte
make[1]: *** [CMakeFiles/creepMiner.dir/all] Fehler 2
Makefile:116: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
```

**Comment by Creepsky** [comment]
The file `/usr/local/lib/libPocoCrypto.so` is missing `EVP_CIPHER_CTX_cleanup`.
`EVP_CIPHER_CTX_cleanup` is part of the OpenSSL library: https://www.openssl.org/docs/man1.0.2/crypto/EVP_CIPHER_CTX_cleanup.html.

**Comment by blub0hr** [comment]
@Creepsky 
I keep getting the following error when trying to compile the development branch on my odroid.

	odroid@odroid:~/creepMiner$ cmake CMakeLists.txt -DMINIMAL_BUILD=ON
	CMake Error at CMakeLists.txt:47 (include):
	  include could not find load file:

		conanbuildinfo.cmake


	CMake Error at CMakeLists.txt:50 (conan_basic_setup):
	  Unknown CMake command "conan_basic_setup".


	-- Configuring incomplete, errors occurred!
	See also "/home/odroid/creepMiner/CMakeFiles/CMakeOutput.log".

I thought I needed to run instructions to install conan, but then another error occurs:

	odroid@odroid:~/creepMiner$ conan install -s compiler.libcxx=libstdc++11 --build=missing
	usage: conan install [-h] [-g GENERATOR] [-if INSTALL_FOLDER] [-m [MANIFESTS]]
						 [-mi [MANIFESTS_INTERACTIVE]] [-v [VERIFY]]
						 [--no-imports] [-u] [-pr PROFILE] [-r REMOTE]
						 [-o OPTIONS] [-s SETTINGS] [-e ENV]
						 [-b [BUILD [BUILD ...]]]
						 path
	conan install: error: too few arguments
	ERROR: Exiting with code: 2
