### ISSUE TITLE
Stop a work on the previous block if have already received a new one block

### ISSUE THREAD

**Issue by llybin** [Creepsky/creepMiner#183]
Sometimes the miner does not have time to read all plots to the end. A new block arrives, and the reading on the previous block continues. There is no sense in reading the previous one.

**Comment by michaelmattig** [comment]
This is already solved: https://github.com/Creepsky/creepMiner/issues/156

**Comment by blinkin69** [comment]
i have also the same issues. the solution not work. 

my SMR drives are getting very slow if new block there before the reading of current block is end.

**Comment by Creepsky** [comment]
New commit online, maybe it will fix it for you b0bcfdbbf897f171a357900698d817a01da98787

**Comment by blinkin69** [comment]
@creepsky 

thx for finding a solution but it dont work, its the same and now when you hit the buffer size limit(conf) it stuck. this could the problem which this users have? -> https://github.com/Creepsky/creepMiner/issues/177

**Comment by llybin** [comment]
Looks like it works great for me now. Thanks.

**Comment by Creepsky** [comment]
@blinkin69 do you still have the problem with newest commit?

**Comment by blinkin69** [comment]
when you mean your last commit post, i think it is not the problem by stopping last read search, its problem that the ram not cleared, and it stuck when it reach the max memory.

also when a round is scanned fully, there is the half RAM used left. 

now i run jminer and with this i have not the memory problems, after each round it clears the memory. 

with jminer i need arround 6 GB, ith creepminer, i need more then 30 GB RAM

if you need more information, let me know
