### ISSUE TITLE
Feature request: Proxy node gathering plot file information from "slave" nodes

### ISSUE THREAD

**Issue by feinom** [Creepsky/creepMiner#184]
Hi!

It would be great to have a feature where the "client/slave" nodes could report in information about the plot files and directories to the master/proxy node. That way you could get a centralized overview of the different plots from the web GUI on the proxy node.

Also, it would be cool if the submitted nonces overview on the proxy node could display which host submitted the nonce.

**Comment by hheexx** [comment]
Great feature!
I would like that also.

**Comment by nitr8** [comment]
adding #320 

```
When a miner forward requests to a master node, it would be useful to append the miner's name.

On the master node -
RequestHandler.cpp, 605, Information): Got nonce forward request (m d T)
```

**Comment by nitr8** [comment]
all working like designed now.
