### ISSUE TITLE
No DL being submited

### ISSUE THREAD

**Issue by davidwillis** [Creepsky/creepMiner#187]
Is there any way to see if any dl,s are found?  I have been running creepMiner for a day, and have not seen any dl's.
I am afraid it may not be working, but maybe my luck is just not very good right now.   I would just really like to know if it is finding dl, and not sending them because they are too high, or if it is not even finding any.

I like how jminer shows all the found dl's but then shows it was not submitted because it was too large, or shows it was submitted, then accepted.  With Creepminer, I just see the new block information, the old block winner, and the files scanned.  I don't know if I am supposed to see when I submit, or not.

Thanks!

**Comment by davidwillis** [comment]
I just had one go through.  So I guess it just doesn't show anything until you get one that is low enough.  It would be nice to be able to see that it is finding dl's that are just too long.

**Comment by damccull** [comment]
@davidwillis you can see ALL the deadlines it can find right now by setting targetDeadline to 0 in your config, but it will then also SEND all the deadlines to the pool, rather that just the ones under a certain time frame.

**Comment by davidwillis** [comment]
Hi,
Thanks for the reply.  I set the targetDeadline to 0, but it did not show any deadlines. 
![screenshot_2017-07-31_00-14-49](https://user-images.githubusercontent.com/30534849/28764927-510fba60-7585-11e7-82a0-a64b4752e1fd.png)

**Comment by Creepsky** [comment]
In commit a8c1f8ae1e4bfdbe19f8a83c4404ebc620e42554 there is the new option `nonceFoundTooHigh` under `logging` -> `output`.
Default value is set to false, but if you set it to true, you will see every found nonce, even when higher than target deadline.

Why you dont see deadlines even with `targetDeadline : 0` - target deadline is a hybrid value, that is the min between pool target deadline and your target deadline from config. So I guess your pool has a very low target deadline.
In newer version you should see something like this:
```
10:03:47: got new target deadline from pool
10:03:47:       old pool target deadline: 00:00:00
10:03:47:       new pool target deadline: 6m 2d 14:54:23
10:03:47:       target deadline from config: 6m 0d 00:00:00
10:03:47:       lowest target deadline: 6m 0d 00:00:00
```
