### ISSUE TITLE
Makefile for 1.6 prerelease?

### ISSUE THREAD

**Issue by damccull** [Creepsky/creepMiner#188]
1.6.0 doesn't seem to have a Makefile present in the repo. I tried pulling the one from 1.5 since it seemed generic enough, but it doesn't work (finishing with an error about a recipe not being right for bin/creepMiner). The code base itself for 1.6 doesn't seem to actually have a Makefile.

**OS**: Ubuntu 17.04
**APP-VERSION**: 1.6.0
**APP-BRANCH**: development
**EXECUTABLE**: self compiled
**CMAKE-SETTINGS**: defaults

**Comment by Creepsky** [comment]
Hi!
In version 1.6.0 there are different options you have to set before you can make the project.
Take a look at https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation-with-CMake.
Basically the project became too complex for just one makefile :)
