### ISSUE TITLE
Randomly getting errors when mining...

### ISSUE THREAD

**Issue by Akito13** [Creepsky/creepMiner#189]
I get every couple of blocks the following error:
```
05:23:39: Error on getting new block-info!
05:23:39:       Syntax error: JSON syntax error
05:23:39:       Full response:
05:23:39:       <html>
05:23:39: <head><title>502 Bad Gateway</title></head>
05:23:39: <body bgcolor="white">
05:23:39: <center><h1>502 Bad Gateway</h1></center>
05:23:39: <hr><center>nginx/1.10.3 (Ubuntu)</center>
05:23:39: </body>
05:23:39: </html>
05:23:39:
05:23:39: Stackframe
05:23:39: main (in "src/main.cpp", line 41)
05:23:39: Miner::run (in "src/Miner.cpp", line 36)
05:23:39: Miner::getMiningInfo (in "src/Miner.cpp", line 357)
```
It happens randomly. Sometimes the miner gets block infos, sometimes not. The pool's website seems fine in the browser. Does it really have to do with the *502 Bad Gateway* error? Because it seems strange to me that the website works in the browser but the miner works on and off, randomly on each block...

NOTE! The miner worked for perfectly for many weeks before this happened... I didn't change ANYTHING in the config file, etc...

Running on 32-bit mini-Debian stable.

**Comment by bkrith** [comment]
Im not expert.. 
but this error means that your pool server send html code than json format data back to miner and miner accept a html page with message bad gateway.
im using it in pool.burstcoin.ro where we have cloudflare.. when the pool server is down, or restart, or accept attack, or overload, the cloudflare send to miner bad gateway html like yours but more reach content! 
Its the pool which send those "wrong" data!

**Comment by Akito13** [comment]
Yes, I know, you're right. But I mirrored this issue here, just to be sure.

**Comment by Creepsky** [comment]
Pool error like @bkrith said.
