### ISSUE TITLE
Proxy node unstable after applying commits as of  Jul 31, 2017

### ISSUE THREAD

**Issue by feinom** [Creepsky/creepMiner#190]
After applying the latest commits, my proxy node will randomly "hang" after random periods of time. It's working fine for a while, and then silently starts refusing connections. No errors are shown in the console output, but it stops getting information about new blocks, and the web GUI becomes unreachable.

This only seems to apply to the proxy node. This node isn't doing any mining itself. It just forwards nonces for two other miners I have running.

What can I do to help debug this?

**Comment by Creepsky** [comment]
Please use the latest version on all miners (slave + master).

**Comment by feinom** [comment]
Seems to be stable after upgrading all nodes to the latest revision.

**Comment by Creepsky** [comment]
Can you please activate the logfile (`"logging"."logfile" : true`) and attach the logfile(s) here?
