### ISSUE TITLE
Error: The deadline for your nonce is too long

### ISSUE THREAD

**Issue by llybin** [Creepsky/creepMiner#191]
The last dev version. Is it can be problem of miner? I began to notice this on a last weeks. Miner says one deadline, pool another, sometimes. I've tried on burstmining and romania pool. Engine of pools is different, if I not mistake.

22:42:20: ***********************: nonce found (1d 15:33:27)                                                                                                                                                          
22:42:20:       nonce: 574087050
22:42:20:       in:    /mnt/WD-PURPLE-4TB-WCC7K5YELRJ4/plots/820256820168033388_30507008_15253504_15253504
22:42:20: ***********************: nonce submitted (1d 15:33:27)                                                                                                                                                      
22:42:20:       nonce: 574087050
22:42:20:       in:    /mnt/WD-PURPLE-4TB-WCC7K5YELRJ4/plots/820256820168033388_30507008_15253504_15253504
22:42:21: Error: The deadline for your nonce (574087050) is too long: 1286517 years, 10 months, 26 days, 10 hours, 15 mins, 28 secs (40571628315328). Our max deadline is 172800                                   
22:42:21: ***********************: error on submitting nonce! (1d 15:33:27)

**Comment by Creepsky** [comment]
It can be a fast block, when you submit your deadline at the end of the block and the new block begins.
What version exactly are you using? (1. line on miner startup)

**Comment by llybin** [comment]
No, it's not fast blocks. It was many times for this night. I use last development branch. I will try stable version and will check. I'm sure that it's new problem for me.

```
13:53:24: --------------------------------------------------                                                                                                                                                       
13:53:24: block#        388975
13:53:24: scoop#        2218
13:53:24: baseTarget#   156884
13:53:24: gensig        ddfc90dfcb3932e85f913148879729ae
13:53:24:               54f3c3a49c2005f81712b6247f1dd5f3
13:53:24: --------------------------------------------------
13:53:26: Dir /mnt/WD-500GB-MYPASSPORT/plots read in 2.427s (~47.57 MB/s)                                                                                                                                          
13:53:26:       1 file (462.00 GB)
13:53:29: Dir /mnt/HITACHI-500G-171KAP7E/plots read in 4.587s (~25.18 MB/s)                                                                                                                                        
13:53:29:       1 file (462.00 GB)
13:53:36: ***********************: nonce found (17:27:25)                                                                                                                                                             
13:53:36:       nonce: 538922126
13:53:36:       in:    /mnt/SEAGATE-4TB-WDH1X22Z/plots/820256820168033388_0_15253504_15253504
13:53:36: ***********************: nonce submitted (17:27:25)                                                                                                                                                         
13:53:36:       nonce: 538922126
13:53:36:       in:    /mnt/SEAGATE-4TB-WDH1X22Z/plots/820256820168033388_0_15253504_15253504
13:53:37: Error: The deadline for your nonce (538922126) is too long: 1693584 years, 1 month, 11 days, 14 hours, 35 mins, 3 secs (53408868618903). Our max deadline is 172800                                      
13:53:37: ***********************: error on submitting nonce! (17:27:25)                                                                                                                                              
13:53:42: Dir /mnt/SEAGATE-4TB-WDH1X22Z/plots + /mnt/SEAGATE-4TB-WDH1X0HN/plots read in 18.350s (~101.47 MB/s)                                                                                                     
13:53:42:       2 files (7.27 TB)
13:53:43: Dir /mnt/WD-PURPLE-4TB-WCC7K6TDUD12/plots + /mnt/WD-PURPLE-4TB-WCC7K4FE38HP/plots read in 18.544s (~100.41 MB/s)                                                                                         
13:53:43:       2 files (7.27 TB)
13:53:43: Dir /mnt/WD-PURPLE-4TB-WCC7K5YELRJ4/plots + /mnt/WD-PURPLE-4TB-WCC7K5LJ7HNA/plots read in 18.585s (~100.19 MB/s)                                                                                         
13:53:43:       2 files (7.27 TB)
13:54:23: --------------------------------------------------                                                                                                                                                       
13:54:23: block#        388976
13:54:23: scoop#        1412
13:54:23: baseTarget#   152050
13:54:23: gensig        b6a2fc9a3e88b112cbf9850a4f025cf5
13:54:23:               171836d58dac2ace24c361282e703ed4
```

**Comment by jant90** [comment]
Same here, I updated creepMiner last night and all my deadlines are faulty now.

Copied from the webinterface:

> The pool calculated a different deadline for your nonce than your miner has!
> Pools deadline: 3,452,365y 6m 24d 23:20:59
> Your deadline: 3m 1d 00:03:09
> XXXX: nonce submitted (3m 1d 00:03:09)

From the log file:
```
04.08.2017 10:20:48 (25, /opt/creepMiner/src/webserver/RequestHandler.cpp, 470, Information): Got nonce forward request (2m 19d 00:39:48)
	nonce: 415297560
	account: XXXXX
	in: /home/PLT/08/9565542119917022670_364904448_5701632_5701632
04.08.2017 10:20:48 (5, /opt/creepMiner/src/mining/Miner.cpp, 350, Information): XXXXX: nonce found (2m 19d 00:39:48)
	nonce: 415297560
	in:    /home/PLT/08/9565542119917022670_364904448_5701632_5701632
04.08.2017 10:20:48 (5, /opt/creepMiner/src/network/NonceSubmitter.cpp, 87, Debug): Submit-loop 1 (2m 19d 00:39:48)
04.08.2017 10:20:48 (5, /opt/creepMiner/src/network/NonceSubmitter.cpp, 109, Information): XXXX: nonce submitted (2m 19d 00:39:48)
	nonce: 415297560
	in:    /home/PLT/08/9565542119917022670_364904448_5701632_5701632
04.08.2017 10:20:48 (1, /opt/creepMiner/src/webserver/MinerServer.cpp, 267, Debug): Request: /burst?requestType=getMiningInfo
04.08.2017 10:20:48 (8, /opt/creepMiner/src/webserver/MinerServer.cpp, 267, Debug): Request: /burst?requestType=getMiningInfo
04.08.2017 10:20:49 (5, /opt/creepMiner/src/network/NonceSubmitter.cpp, 124, Debug): JSON confirmation (2m 19d 00:39:48)
	{"result":"success","requestProcessingTime":106,"deadline":37102299337285}
04.08.2017 10:20:49 (5, /opt/creepMiner/src/network/NonceSubmitter.cpp, 160, Error): The pool calculated a different deadline for your nonce than your miner has!
	Pools deadline: 1,192,846y 6m 20d 20:21:25
	Your deadline: 2m 19d 00:39:48
```

**Comment by Creepsky** [comment]
Again: what exactly is your version? Latest dev version could be anything. I need to new the exact version string.
Also: can you please provide a full log? Just upload it here or in private and tell me the link. Otherwise I cant help.

**Comment by llybin** [comment]
Problem exists on this commit: a27b7ee12683bf554cadd2f9d1087924027cb78b
I moved on: 5abade96c3914997827ef0ab6d160223574f1d8c all ok

**Comment by Creepsky** [comment]
Please check the latest commit and report, if it works like intended.

**Comment by llybin** [comment]
@Creepsky Thank you, problem is not produced anymore.

**Comment by oxconan** [comment]
Hi,
I used latest 1.7.3 version, sometimes,  I saw in log:

The pool calculated a different deadline for your nonce than your miner has!
Oct 17 09:13:27 master01 creepMiner[954]: 09:13:27:         Pools deadline: 1,569,092y 0m 11d 16:28:58
Oct 17 09:13:27 master01 creepMiner[954]: 09:13:27:         Your deadline: 3m 12d 18:39:47
Oct 17 09:13:27 master01 creepMiner[954]: 09:13:27: Block 415,352 ended in 00:00:2

I don't understand why that ?

**Comment by Creepsky** [comment]
It happens sometimes. As long as it not on every nonce submission, you dont have to worry.
