### ISSUE TITLE
help conf setting plot grouping

### ISSUE THREAD

**Issue by N8Thrasher** [Creepsky/creepMiner#193]
Im trying to follow this [#86](https://github.com/Creepsky/creepMiner/issues/86) but I keep getting syntax error and this [#67](https://github.com/Creepsky/creepMiner/issues/67) but those drive enclosed in "[  "D:\\Plots", "E:\\Plots" ]," is not been read or skipped.
`{  
    "plots":[  
        [  
            "D:\\Plots",
            "E:\\Plots"
        ],
        "G:\\Plots"
    ]
}`

D: and E: on single HDD with two partition
G: on single HDD
H: to M: on cloud drive

**Comment by Creepsky** [comment]
```
"plots": [
  {
    "path": [
      "D:\\Plots",
      "E:\\Plots"
    ],
    "type": "sequential"
  },
  "G:\\Plots",
  {
    "path": [
      "H:\\.....",
      "I:\\.....",
      "J:\\.....",
      "....."
    ],
    "type": "parallel"
  }
]
```

**Comment by N8Thrasher** [comment]
Thanks it's working now on my other PC... but this one still giving syntax error.
`        },
"plots": [
      {
      "path": ["D:\\PosA","D:\\Plots"],
      "type": "sequential"
      },
      {
      "path": ["E:\\PosA","G:\\PosA"],
      "type": "sequential"
      },
         ],`

**Comment by Creepsky** [comment]
Check it here https://jsonformatter.curiousconcept.com/
