### ISSUE TITLE
cant seem to solo mine

### ISSUE THREAD

**Issue by g10rgio** [Creepsky/creepMiner#194]
I put my decrypted pass phrase into the mining.conf on 1.5.2 and the miner runs but the key and maybe even the salt have invalid characters in them (the key does for sure).

Part of the key shown below, the first character is causing an error when running the miner a second time:
 "key" : "▒N5cLa9

20:20:05: using config file mining.conf
20:20:06: There is an error in the config file!
20:20:06: JSON Exception: Bad character.
20:20:06: Stackframe
20:20:06: main (in "src/main.cpp", line 41)
20:20:06: readConfigFile (in "src/MinerConfig.cpp", line 222)
20:20:06:
20:20:06: Aborting program due to invalid configuration

With v1.6.0 the pass phrase isn't removed from the conf file at all, and the other sections (key and salt) aren't filled in.

**OS**: ubuntu 16.04
**APP-VERSION**: 1.5.2 x64 and 1.6.0 x64
**APP-BRANCH**: release and development
**EXECUTABLE**: self compiled
**CMAKE-SETTINGS**: cmake

**Comment by Creepsky** [comment]
Please use the latest version on master branch.

Use the following settings for the passphrase:

```
            "algorithm" : "aes-256-cbc",
            "decrypted" : "{your passphrase here}",
            "deleteKey" : true,
            "encrypted" : "",
            "iterations" : 1000,
            "key" : "",
            "salt" : ""
```
