### ISSUE TITLE
Unable to make - Poco/URI.h: No such file or directory

### ISSUE THREAD

**Issue by neonettech** [Creepsky/creepMiner#195]
Hi,
I am trying to compile the miner and I am also getting the URI.h not found

admin@Burst-server-01:$ sudo make
g++ -O3 -march=native -std=c++14 -Wall -D_REENTRANT -DNDEBUG -Isrc/sphlib -Isrc/nxt -Isrc -IPoco/Net -IPoco/Foundation -IPoco/NetSSL_OpenSSL -IPoco/openssl -IPoco/Crypto -IPoco/Util -IPoco/JSON -c src/Url.cpp -o bin/obj/Url.o
In file included from src/Url.cpp:1:0:
src/Url.hpp:4:22: fatal error: Poco/URI.h: No such file or directory
#include <Poco/URI.h>
^
compilation terminated.
make: *** [Makefile:41: bin/obj/Url.o] Error 1

I already manually installed the latest version of Poco - all the libraries are found under /usr/local/include/Poco - in the various sub folders.
I ran sudo ldconfig, I rebooted the system after installing poco.
I also just for kicks renamed the poco-1.7.8-all folder in the creepminer directory to Poco - thinking that it might find the paths to these files - because the Url.cpp and Url.hpp reference "Poco/include/..." in the include lines.
Also tried to change the path to /usr/local/include/Poco/include" in these files - but then I get that it can't find the foundation.h and a few other files.
So I am somewhat stuck here. Is there a step that I am missing?
Thank you for your help in advance! :)

===============
OS: Linux 3.10.102 (x86_64 GNU/Linux synology_bromolow_rs3614xs) - on Synology NAS

**Comment by NeO0727** [comment]
Make sure you have sudo installed, it is not always by default and then the Poco install fails...
apt-get install sudo
Run the Poco install again, then the make, should compile fine then.

**Comment by neonettech** [comment]
Hi,
thank you for the reply. Sudo was installed - but I downloaded and installed sudo again, then ran the poco install which goes through without an error. But when I run the make it gives the same error about URI.h missing.
Any other thoughts?
Thank you,
Frank

**Comment by Creepsky** [comment]
Hi, please download and compile from the latest source code. Do you then still get the error?
