### ISSUE TITLE
32bit Linux version doesn't work

### ISSUE THREAD

**Issue by burstking** [Creepsky/creepMiner#196]
Hi team,

I have built 2 environment, 1) 32-bit Linux Mint 18.2 XFCE and 2) 64-bit Linux Mint 18.2 XFCE.

They have the same Linux setup, and mining.conf, plots. Then I let them mining in the same block at the same time. And I also ensure they have complete the scanning of all plots before next block start. 

The creepMiner running on 32-bit Linux didn't find any nonce (not expected).
The creepMiner running on 64-bit Linux did find some nonce (expected).

Any idea why? I guess some deadline calculation result has been truncated due to 64 bit to 32 bit cast?

I have a old PC in 32-bit, and I want to utilize it to do the mining. Hope someone could shed me some lights.

Please help.

Regards,
Burst King.

### Before you submit your issue, please make sure that

- [ ] you use the latest version of your branch (master/development/...; dont forget to git pull and cmake + make again)
- [ ] your issue is reproducable OR you know exactly what was wrong

If you have just a questions or want to talk about the application, please consider posting on https://67.ip-145-239-77.eu.
You can log in with your **github.com** account.

### When you submit your issue, please make sure to add the following informations

- [ ] what operation system are you using?
- [ ] what version of the application are you using?
- [ ] what branch of the application are you using?
- [ ] what executable of the application are you using? (from releases, self compiled, dockerfile, ...)
- [ ] if you compiled the application by yourself, what cmake settings did you use?

Please tell exactly what was wrong, how often it is or was wrong, how it normally works and what you changed.
Also it would be really helpful to get a log file and your configuration file that you can attach by simply drag and drop it into the issue window.

Thank you very much!

You can use the following template and fill in your data (simply delete the rest of the issue template):

**OS**: Linux Mint 18.2
**APP-VERSION**: 1.6.0
**APP-BRANCH**: development
**EXECUTABLE**: self compiled
**CMAKE-SETTINGS**: cmake -DCMAKE_BUILD_TYPE=RELEASE -DCPU_INSTRUCTION_SET=AVX

**Comment by bkrith** [comment]
why you want to use pc with 32bit? ubuntu(and mint is ubuntu-based) will stop very soon 32bit distros!
anyway try to compile with only cmake command without those parameters.. maybe it works!
but bro, you will have soon problem with other 32bit applications/utils/programs!

**Comment by burstking** [comment]
Thanks for replying.

I am setting up a 32bit box because my CPU is on 32bit.

By the way, I have setup a 64bit ubuntu to compile and run creepMiner. Do
you have any idea why the confirm count and mined count always return a
random number as if the counter variable hasnt been initialized properly?
This only happen in linux version, but it works well in windows system

cheers

On 26 Aug 2017 01:46, "Vassilis" <kitmsg03@gmail.com> wrote:

why you want to use pc with 32bit? ubuntu(and mint is ubuntu-based) will
stop very soon 32bit distros!
anyway try to compile with only cmake command without those parameters..
maybe it works!
but bro, you will have soon problem with other 32bit
applications/utils/programs!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Creepsky/creepMiner/issues/196#issuecomment-324990676>,
or mute the thread

**Comment by Creepsky** [comment]
Try the master branch with the following cmake option: ```cmake ... -DCPU_ARCH=X32 ...```

**Comment by burstking** [comment]
It works even without that switch! Thanks a lot! The new version UInis
awesome!
