### ISSUE TITLE
Using creepMiner-cuda 1.6.0 without AVX ?

### ISSUE THREAD

**Issue by Ambiolix** [Creepsky/creepMiner#198]
I have been running creepMiner-cuda 1.5.6 on a Pentium G4560 with an Nvidia GT1030 scanning 36TB USB drives in less then 15 secs with very little power :-)

Now I was very excited to see the new 1.6.0 version, but it will not run on my system since it requires the CPU to be able to understand AVX, which the G4560 cannot :-( best it can do is SSE4.1/4.2.

Is it possible to make a cuda version that does not require a CPU that knows AVX ?

Thanks.

**Comment by Creepsky** [comment]
I will change the prebuild Windows CUDA version it to SSE2.

**Comment by Ambiolix** [comment]
Thanks a lot :-)

**Comment by Creepsky** [comment]
Here is the new zip: https://github.com/Creepsky/creepMiner/releases/download/2.6.0/creepMiner-win64-1.6.0.zip

**Comment by Ambiolix** [comment]
Thanks for the quick update.

I did a test run, but something seems not right.

The new 1.6.0 version required about 90 sec to scan with 100% load on the GPU, while version 1.5.6 only needed 22 sec on the same block to scan all drives with a 65% GPU load...

**Comment by Creepsky** [comment]
What scan times do you get with the equivalent CPU versions (1.5.2 vs 1.6.0)?

**Comment by Ambiolix** [comment]
Thanks, I appreciate that you take the time to look into this.

I took the following screenshots from the different versions together with the CPU & GPU usage graphs from NZXT Cam

New Cuda version
![creepminer-cuda 1 6 0](https://user-images.githubusercontent.com/31508706/29935265-6d5cb544-8e7e-11e7-971f-90e2e7325f42.PNG)

Old Cuda version
![creepminer-cuda 1 5 2](https://user-images.githubusercontent.com/31508706/29935224-54da6ff2-8e7e-11e7-951a-6209707a9c52.PNG)

New CPU version
![creepminer-sse4 1 6 0](https://user-images.githubusercontent.com/31508706/29935294-85b3e90a-8e7e-11e7-920f-b027aa2b4bdb.PNG)

Old CPU version, please note that the CPU usage was so high that NZXT CAM did not update the graph...
![creepminer 1 5 2](https://user-images.githubusercontent.com/31508706/29935281-7b0672d4-8e7e-11e7-9610-3bb5fe9baf97.PNG)

Let me know in case you need anything else.

**Comment by Creepsky** [comment]
Thanks for all the screenshots!

One thing I see is that you have different buffer sizes for the different versions.
What times do you get when you use the same buffer size and also what times do you get when you set ```maxBufferSizeMB : 0``` in 1.6.0 (CUDA and CPU)?

**Comment by Ambiolix** [comment]
When I set the old version to buffer 1024, like I used in the new version, then the program becomes unresponsive, same with buffer 0, so I ended killing the task in both cases.

When I set buffer 0 in the new version, then the cuda version gets memory errors and the cpu version uses all the available ram and even pages on my C drive which is an SSD.

Old cuda version using Buffer 8192
![creepminer-cuda 1 5 2 buffer 8192](https://user-images.githubusercontent.com/31508706/29944139-8de472de-8e9c-11e7-808e-524112979e51.PNG)

New cuda version using buffer 0
![creepminer-cuda 1 6 0 buffer 0](https://user-images.githubusercontent.com/31508706/29944157-a3a50ad4-8e9c-11e7-9304-736b681ae600.PNG)

New cpu version using buffer 0
![creepminer-sse4 1 6 0 buffer 0](https://user-images.githubusercontent.com/31508706/29944172-b5409fba-8e9c-11e7-8897-4c0622e0551d.PNG)

**Comment by Creepsky** [comment]
You forgot to test the new CUDA version with 8GB buffer size.

buffer size 0 will auto set it to ~9GB (this is the optimal size for all your plot files), therefore the paged memory on your SSD.

**Comment by Ambiolix** [comment]
I had tested it with 8GB all in the start and got memory errors, its first when I go all the way down to 1024 that it will work, see screenshots:

New version with buffer 8192
![creepminer-cuda 1 6 0 buffer 8192](https://user-images.githubusercontent.com/31508706/29958730-8179b1d2-8ef4-11e7-95af-1cb513958a79.PNG)

New version with buffer 1536
![creepminer-cuda 1 6 0 buffer 1536](https://user-images.githubusercontent.com/31508706/29958745-9380ac8c-8ef4-11e7-9a3e-5a29030777db.PNG)

New version with buffer 1152
![creepminer-cuda 1 6 0 buffer 1152](https://user-images.githubusercontent.com/31508706/29959123-2da9f614-8ef6-11e7-89bf-8ae8980fbcb8.PNG)

New version with buffer 1024
![creepminer-cuda 1 6 0 buffer 1024](https://user-images.githubusercontent.com/31508706/29959143-44c20cb0-8ef6-11e7-86a5-29cef54473d2.PNG)

**Comment by Ambiolix** [comment]
I did some more test with my Gaming machine, which has an i5-5675C, 16GB Ram and a Nvidia GTX 1070 and no matter which buffer size I use, I get GPU memory errors, see screenshoots.

New cuda version with buffer 0
![1070 buffer 0](https://user-images.githubusercontent.com/31508706/29983884-1b7e685a-8f58-11e7-83c3-945fe048c2ad.PNG)

New cuda version with buffer 1024
![1070 buffer 1024](https://user-images.githubusercontent.com/31508706/29983901-294004ee-8f58-11e7-8024-ccf24a846c2f.PNG)

Old cuda version with buffer 8192
![old 1070 buffer 8192](https://user-images.githubusercontent.com/31508706/29983929-4b16c652-8f58-11e7-84e2-42fcc4db2a1e.PNG)

So something is wrong with the new Cuda version, hope it can be fixed....

**Comment by Creepsky** [comment]
Optimized the cuda algorithm.
@Ambiolix  please check this version: [creepMiner-cuda-1.6.4.zip](https://github.com/Creepsky/creepMiner/files/1280289/creepMiner-cuda-1.6.4.zip)

**Comment by Ambiolix** [comment]
Thanks for the new version :-)

I did a few test runs with different buffer sizes, and the max buffer size I could use with the GT 1030 was 2560. Its also still about 25% slower then the 1.5.6 cuda version...

creepMiner-cuda 1.6.4 buffer 0
![creepminer-cuda 1 6 4 buffer 0](https://user-images.githubusercontent.com/31508706/30105329-8a4e3d2a-92f8-11e7-8d15-dfd2c8de40ad.PNG)

creepMiner-cuda 1.6.4 buffer 1024
![creepminer-cuda 1 6 4 buffer 1024](https://user-images.githubusercontent.com/31508706/30105343-937a95ec-92f8-11e7-84cb-d8e9245b9766.PNG)

creepMiner-cuda 1.6.4 buffer 1536
![creepminer-cuda 1 6 4 buffer 1536](https://user-images.githubusercontent.com/31508706/30105357-9d6b00a0-92f8-11e7-83f8-186780ce40fd.PNG)

creepMiner-cuda 1.6.4 buffer 2048
![creepminer-cuda 1 6 4 buffer 2048](https://user-images.githubusercontent.com/31508706/30105363-a4d92b46-92f8-11e7-8ea2-8535b7c8a2a2.PNG)

creepMiner-cuda 1.6.4 buffer 2560
![creepminer-cuda 1 6 4 buffer 2560](https://user-images.githubusercontent.com/31508706/30105370-aae0d6ba-92f8-11e7-9b8e-64934c8235aa.PNG)

**Comment by Ambiolix** [comment]
I just noticed that the new mining config file also has a

"bufferChunkCount" : 8,

entry. What does it do and should I maybe change that as well ?

**Comment by Creepsky** [comment]
Your GPU has 2GB RAM, so set it to 0 < max buffer size < 2048.

bufferChunkCount is the amount of chunks in which the buffer will be split.
For example when you have buffer = 128, and chunk count = 128, your plotfiles will be read in 1 MB buffer chunks.
8 is the default value, you can try other values. Use values that are power of 2 and <= max buffer size.

Also try different maxPlotReaders (start with 0) and intensity (start with 1).

In [creepMiner-cuda-1.6.3.zip](https://github.com/Creepsky/creepMiner/files/1280997/creepMiner-cuda-1.6.3.zip) you will find:
- creepMiner-cuda-old.exe (1.6.3 with the old read algorithm from 1.5.2)
- creepMiner-cuda-benchmark.exe

Try these too.
The benchmark version will create you a file named benchmark.csv every minute. It would be very nice when you gather these benchmark files for different settings in a zip and upload them here.

**Comment by Ambiolix** [comment]
Thanks for the explanation and all your effort :-)

I am aware of that the GT1030 only has 2GB of memory, thats why I was surprised it did not crash when I set the buffer to 2560...

I will do some testing later this evening / tomorrow and post my results back here.

**Comment by Ambiolix** [comment]
Sorry for the delay, today I finally had some time for the testing...

The creepMiner-cuda-old version was promising, since it showed the same CPU/GPU pattern as the 1.5.2 version. The only problem is, that it always stalls at 73.78%, see screenshot
![creepminer-cuda-old](https://user-images.githubusercontent.com/31508706/30292398-457ea68e-9736-11e7-8bb5-45ccd0041626.PNG)

creepMiner-cuda-benchmark is not like the creepMiner-cuda-old version, as it shows the same CPU/GPU usage pattern as version 1.6.4

Anyway, I was able to run a few benchmarks, but the max buffer size I could use was 1280, otherwise I get cuda memory errors.

Let me know in case there is anything else I should test.

[Benchmarks.zip](https://github.com/Creepsky/creepMiner/files/1293744/Benchmarks.zip)

**Comment by nitr8** [comment]
closing to old
