### ISSUE TITLE
Can't make on Debian 9.0

### ISSUE THREAD

**Issue by Seveley** [Creepsky/creepMiner#200]
I'm getting this error message:

src/CipherImpl.cpp:80:21: error: field ‘_ctx’ has incomplete type ‘EVP_CIPHER_CTX {aka evp_cipher_ctx_st}’
   EVP_CIPHER_CTX    _ctx;
                     ^~~~
In file included from /usr/include/openssl/crypto.h:31:0,
                 from include/Poco/Crypto/OpenSSLInitializer.h:26,
                 from include/Poco/Crypto/CipherKeyImpl.h:24,
                 from include/Poco/Crypto/CipherKey.h:24,
                 from include/Poco/Crypto/CipherImpl.h:25,
                 from src/CipherImpl.cpp:17:
/usr/include/openssl/ossl_typ.h:90:16: note: forward declaration of ‘EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}’
 typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
                ^~~~~~~~~~~~~~~~~
/creepMiner/poco-1.7.6-all/build/rules/compile:53: recipe for target '/creepMiner/poco-1.7.6-all/Crypto/obj/Linux/x
86_64/debug_shared/CipherImpl.o' failed
make[1]: *** [/creepMiner/poco-1.7.6-all/Crypto/obj/Linux/x86_64/debug_shared/CipherImpl.o] Error 1
make[1]: Leaving directory '/creepMiner/poco-1.7.6-all/Crypto'
Makefile:201: recipe for target 'Crypto-libexec' failed
make: *** [Crypto-libexec] Error 2

Any Idea ??

**Comment by Creepsky** [comment]
I changed the POCO version in install_poco.sh from 1.7.6 to 1.7.8p3.

Successfully compiled on Debian 9 in Virtual Box.

Change to root-mode:
```
su
<type in password...>
```

Update packages:
```
apt-get update
apt-get upgrade
```

Install basic build tools:
```
apt-get install build-essential
```

Install git:
```
apt-get install git
```

Install OpenSSL and SSL library development headers:
```
apt-get install openssl
apt-get install libssl-dev
```

Install sudo (this step is optional, you can also remove all `sudo` commands from install_poco.sh and just execute it with `su` instead):
```
apt-get install sudo
```

Install cmake:
```
apt-get install cmake
```

Clone the repository:
```
git clone https://github.com/Creepsky/creepMiner
```

Change the directory:
```
cd creepMiner
```

Run the POCO install script (it will download and install POCO for you):
```
sh ./install_poco.sh
```

Create your makefile using cmake (use this [build with cmake documentation](https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation-with-CMake)):
```
cmake -DCMAKE_BUILD_TYPE=RELEASE -DCPU_INSTRUCTION_SET=AVX2
or
cmake -DCMAKE_BUILD_TYPE=RELEASE -DCPU_INSTRUCTION_SET=AVX
or
cmake -DCMAKE_BUILD_TYPE=RELEASE -DCPU_INSTRUCTION_SET=SSE4
or
cmake -DCMAKE_BUILD_TYPE=RELEASE -DCPU_INSTRUCTION_SET=SSE2
or
cmake -DCMAKE_BUILD_TYPE=RELEASE
```

Make the miner:
```
make
```

The binary file will be in `./bin`

**Comment by Seveley** [comment]
Sweet it worked perfectly !! :)
