### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by agrus** [Creepsky/creepMiner#201]
creepMiner 1.6.2 Unix x64
Release mode

In console

14:21:43: Could not get mining infos 2/5 times...
14:21:50: Could not get mining infos 1/5 times...
14:22:38: Could not get mining infos 2/5 times...
14:22:56: Plot-read-queue: 0, verification-queue: 0
14:22:56: Allocated memory: 0.0 MB
Floating point exception (core dumped)

In log file
[log on pastebin](https://pastebin.com/mYXkjEzd)

GDB output of
(gdb) bt
(gdb) bt full
(gdb) info threads
(gdb) thread apply all bt
(gdb) thread apply all bt full
[gdb output on pastbin](https://pastebin.com/Xe22Jf28)

**Comment by Creepsky** [comment]
Thanks for the full gdb output!
Fixed in 1.6.3 on master.

**Comment by agrus** [comment]
Now it work!
