### ISSUE TITLE
miner.js:149 Uncaught TypeError: Cannot read property 'miner' of null

### ISSUE THREAD

**Issue by agrus** [Creepsky/creepMiner#202]
When you open miner stat first time and there are no data in Local Store, rising error:

miner.js:149 Uncaught TypeError: Cannot read property 'miner' of null
    at localInitLogSettings (miner.js:149)
    at initBlock (miner.js:714)
    at window.onload (miner.js:768)

Function localGet makes temp = null
function localInitLogSettings() {
	var temp = localGet('logSettings');

	if (temp['miner']) $("#cmb_miner").val(temp['miner'])

After change log Settings, and Settings appear in Local Store, еrror gone

**Comment by nitr8** [comment]
closing - fixed, verified with the mistro :)
