### ISSUE TITLE
Segmentation fault during plot scan

### ISSUE THREAD

**Issue by mitchelp** [Creepsky/creepMiner#203]
My creepMiner seems to crash on a plot scan.
Never had this issue before, it seems to be related to the latest version 1.6.3 before it never was the case. Not sure if it's related to the latest version.

I have some logging.

**Console output:**
`22:30:48: /storage/plots/small_plots/14330018276167855832_41369602_409600_409600 (100.00 GB) read in 0.743s (~33.63 MB/s)
22:30:48: /storage/plots/small_plots/14330018276167855832_41779202_409600_409600 (100.00 GB) read in 0.857s (~29.16 MB/s)
22:30:48: ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒▒▒▒░░▌  83.58%Segmentation fault`

And the last lines from the logfile:
`05.09.2017 22:30:48 (10, /opt/creepMiner/src/plots/PlotReader.cpp, 268, Information): /storage/plots/small_plots/14330018276167855832_41369602_409600_409600 (100.00 GB) read in 0.743s (~33.63 MB/s)
05.09.2017 22:30:48 (9, /opt/creepMiner/src/plots/PlotReader.cpp, 268, Information): /storage/plots/small_plots/14330018276167855832_41779202_409600_409600 (100.00 GB) read in 0.857s (~29.16 MB/s)
05.09.2017 22:39:30 (16, /opt/creepMiner/src/webserver/MinerServer.cpp, 239, Warning): Could not send the data to the websocket!
        data: {"type":"progress","value":97.76119,"valueVerification":69.402985}
05.09.2017 22:39:30 (16, /opt/creepMiner/src/webserver/MinerServer.cpp, 240, Error): Exception occured: Timeout
        error-code: 110
        class: N4Poco16TimeoutExceptionE`

Could you please take a look? Thanks.

**Comment by Creepsky** [comment]
Can you give me an instruction to reproduce it, please? I assume it occurs every time you start it?

**Comment by mitchelp** [comment]
No, unfortunately not.. Yesterday it occurred two times, one time after about 3 or 4 hours.
The second time again after 3 or 4 hours.
I can't point out where or what is happening exactly.

**Comment by mitchelp** [comment]
Alright, I recompiled the hole thing. Removed everything and started over. (except the plots)
Was using git for updates. But maybe this broke something.

So far so good, will report me back if everything stays in a working state. And if not ofcourse :)

**Comment by mitchelp** [comment]
It's running for almost 24 hours now without any problems, considder this one closed. Will come back if it crashes anyway.

Thanks Creepsky!
