### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by Axadiw** [Creepsky/creepMiner#204]
Hi,

When I've tried to use newest cuda version of creepminer (1.6.3) using compiled version from https://github.com/Creepsky/creepMiner/releases/download/2.6.3/creepMiner-win64-1.6.3.zip

I'm receiving following error:

```
10:04:55:       Error: CUDA driver version is insufficient for CUDA runtime version
10:04:55: Error while verifying a plot file!
10:04:55:       Error: CUDA driver version is insufficient for CUDA runtime version
10:04:55: Error on cuda_free_memory(memory)
10:04:55: Error on cuda_free_memory(memory)
10:04:55: Error on cuda_free_memory(memory)
10:04:55: Error on cuda_free_memory(memory)
10:04:55: Error on cuda_free_memory(memory)
10:04:55: Error on cuda_free_memory(memory)
```

I've installed newest CUDA toolkit that's available: Patch 2 (Released Jun 26, 2017) from https://developer.nvidia.com/cuda-downloads

How can I get rid of this error?

System: Windows 10
GPU: Nvidia GeForce 980Ti

**Comment by Creepsky** [comment]
Hi,

you need the latest driver for your Nvidia Gefore 980Ti, then it will work.
I have a GTX 1060 and for me driver 385.41 works.

You can check your version for example with this tool: http://cuda-z.sourceforge.net.
![image](https://user-images.githubusercontent.com/8005422/30366639-06e2ef84-986c-11e7-9a11-17260acf9d6d.png)
(it must show minimum version 9)
