### ISSUE TITLE
Still Can't Link on macOS

### ISSUE THREAD

**Issue by bsom** [Creepsky/creepMiner#205]
I've been trying to compile this for a week.  I cannot get it to link on macOS.  I always get:

```
[  3%] Linking CXX executable bin/creepMiner-avx2
Undefined symbols for architecture x86_64:
  "_ASN1_STRING_data", referenced from:
      Poco::Crypto::X509Certificate::extractNames(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) const in libPocoCrypto.a(X509Certificate.cpp.o)
```

Followed by a BUNCH more linking errors.  I'm at a loss.  I can't figure out what I am missing.  Does anyone have a macOS binary that actually works?

**Comment by Creepsky** [comment]
Looks like some Poco error to me.
Did you try to follow this tutorial: https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation-on-macOS?

**Comment by bsom** [comment]
Yes, that is the tutorial I followed.

**Comment by bsom** [comment]
I removed Homebrew and all of its libraries and started from scratch following the macOS instructions.  Two things:
1. It says to install Poco and then openSSL.  Installing Poco through Homebrew installs openSSL automatically as it is a dependency.
2. It starts to link properly, but complains about NEW stuff :-) as seen below:

[100%] Linking CXX executable bin/creepMiner
Undefined symbols for architecture x86_64:
  "Burst::Settings::HashSize", referenced from:
      Burst::PlotVerifierAlgorithm_cpu<Burst::Shabal256_Shell<Burst::Mshabal_sse4_Impl>, Burst::PlotVerifierOperations_4<Burst::Shabal256_Shell<Burst::Mshabal_sse4_Impl> > >::run(std::__1::vector<std::__1::array<unsigned char, 64ul>, std::__1::allocator<std::__1::array<unsigned char, 64ul> > >&, unsigned long, unsigned long, unsigned long, std::__1::array<unsigned char, 32ul> const&, std::__1::function<bool ()>, void*) in Miner.cpp.o
      Burst::PlotVerifierAlgorithm_cpu<Burst::Shabal256_Shell<Burst::Mshabal_avx_Impl>, Burst::PlotVerifierOperations_4<Burst::Shabal256_Shell<Burst::Mshabal_avx_Impl> > >::run(std::__1::vector<std::__1::array<unsigned char, 64ul>, std::__1::allocator<std::__1::array<unsigned char, 64ul> > >&, unsigned long, unsigned long, unsigned long, std::__1::array<unsigned char, 32ul> const&, std::__1::function<bool ()>, void*) in Miner.cpp.o
      Burst::PlotVerifierAlgorithm_cpu<Burst::Shabal256_Shell<Burst::Mshabal_avx2_Impl>, Burst::PlotVerifierOperations_8<Burst::Shabal256_Shell<Burst::Mshabal_avx2_Impl> > >::run(std::__1::vector<std::__1::array<unsigned char, 64ul>, std::__1::allocator<std::__1::array<unsigned char, 64ul> > >&, unsigned long, unsigned long, unsigned long, std::__1::array<unsigned char, 32ul> const&, std::__1::function<bool ()>, void*) in Miner.cpp.o
      Burst::PlotVerifierAlgorithm_cpu<Burst::Shabal256_Shell<Burst::Sphlib_Impl>, Burst::PlotVerifierOperations_1<Burst::Shabal256_Shell<Burst::Sphlib_Impl> > >::run(std::__1::vector<std::__1::array<unsigned char, 64ul>, std::__1::allocator<std::__1::array<unsigned char, 64ul> > >&, unsigned long, unsigned long, unsigned long, std::__1::array<unsigned char, 32ul> const&, std::__1::function<bool ()>, void*) in Miner.cpp.o
      Burst::PlotGenerator::generateAndCheck(unsigned long, unsigned long, Burst::Miner const&) in PlotGenerator.cpp.o
  "Burst::Settings::ScoopSize", referenced from:
      Burst::PlotVerifierAlgorithm_cpu<Burst::Shabal256_Shell<Burst::Mshabal_sse4_Impl>, Burst::PlotVerifierOperations_4<Burst::Shabal256_Shell<Burst::Mshabal_sse4_Impl> > >::verify(Burst::Shabal256_Shell<Burst::Mshabal_sse4_Impl> const&, std::__1::vector<std::__1::array<unsigned char, 64ul>, std::__1::allocator<std::__1::array<unsigned char, 64ul> > >&, unsigned long, unsigned long, unsigned long, unsigned long) in Miner.cpp.o
      Burst::PlotVerifierAlgorithm_cpu<Burst::Shabal256_Shell<Burst::Mshabal_avx_Impl>, Burst::PlotVerifierOperations_4<Burst::Shabal256_Shell<Burst::Mshabal_avx_Impl> > >::verify(Burst::Shabal256_Shell<Burst::Mshabal_avx_Impl> const&, std::__1::vector<std::__1::array<unsigned char, 64ul>, std::__1::allocator<std::__1::array<unsigned char, 64ul> > >&, unsigned long, unsigned long, unsigned long, unsigned long) in Miner.cpp.o
      Burst::PlotVerifierAlgorithm_cpu<Burst::Shabal256_Shell<Burst::Mshabal_avx2_Impl>, Burst::PlotVerifierOperations_8<Burst::Shabal256_Shell<Burst::Mshabal_avx2_Impl> > >::verify(Burst::Shabal256_Shell<Burst::Mshabal_avx2_Impl> const&, std::__1::vector<std::__1::array<unsigned char, 64ul>, std::__1::allocator<std::__1::array<unsigned char, 64ul> > >&, unsigned long, unsigned long, unsigned long, unsigned long) in Miner.cpp.o
      Burst::PlotVerifierAlgorithm_cpu<Burst::Shabal256_Shell<Burst::Sphlib_Impl>, Burst::PlotVerifierOperations_1<Burst::Shabal256_Shell<Burst::Sphlib_Impl> > >::run(std::__1::vector<std::__1::array<unsigned char, 64ul>, std::__1::allocator<std::__1::array<unsigned char, 64ul> > >&, unsigned long, unsigned long, unsigned long, std::__1::array<unsigned char, 32ul> const&, std::__1::function<bool ()>, void*) in Miner.cpp.o
      Burst::PlotGenerator::generateAndCheck(unsigned long, unsigned long, Burst::Miner const&) in PlotGenerator.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/creepMiner] Error 1
make[1]: *** [CMakeFiles/creepMiner.dir/all] Error 2
make: *** [all] Error 2

**Comment by Creepsky** [comment]
Ok, what is your `gcc --version`, what version is the miner (`root/version.id`) and what are the parameters that you used building the makefile?

**Comment by bsom** [comment]
GCC version information:
`Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

Version ID:
`version:1.7.1`

CMAKE command line:
`cmake -DCMAKE_BUILD_TYPE=RELEASE -DNO_GPU=ON`

**Comment by Creepsky** [comment]
Please try compilation on development branch again, I changed some things that should fix your problem.

**Comment by bsom** [comment]
Yup, the development branch compiles correctly now.  I'm running it now and it appears to be working.
