### ISSUE TITLE
Webinterface not displaying Data via ReverseProxy

### ISSUE THREAD

**Issue by cuthulino** [Creepsky/creepMiner#206]
I use creepminer on an local computer and got a server running my apache for different websites.
I changed the config in creepminer to the external wanted domain and configured a apache reverse proxy, so creepminer gets displayed when I enter the external url.

When i enter the external url, the frontend gets displayed but no data. (see Screenshot)

https://i.imgur.com/HbIHt4y.png

**Comment by Doncode** [comment]
Fixed
https://github.com/Creepsky/creepMiner/pull/214

**Comment by cuthulino** [comment]
Tryed the new Master and the Webinterface can not be loaded completely now.
No Matter if reverse-proxy or local.

Firefox and Chrome loading circles are turning all the time and no more than the screenshot from the first post is displayed.

**Comment by Creepsky** [comment]
> Tryed the new Master and the Webinterface

What version did you use before? What was the config you used before?
What are the differences in the new config you use now?
How did you install the new version?

> can not be loaded completely now.
> No Matter if reverse-proxy or local.
>
> Firefox and Chrome loading circles are turning all the time and no more than the screenshot from the first post is displayed.

Normally, your webbrowser should show you a html code after a while, when there is an error. Did you change the settings for your browser, so it does not?
What is written in your webbrowser debug console?

> Tryed the new Master and the Webinterface is extremly slow now.
Was much faster before.
> I now have to wait 1-2 minutes until the login screen is displayed.

So it is working now, but you have to wait for the page a long time? What did you change so it is working now?

**Comment by cuthulino** [comment]
ok, while i was answering all your questions, i found out why.
I changed the config value "activeConnections"  to one. Because i thougth, there is max. myself watching.
After changing it to a higher value it is working now.

But if i try to connect from my domain (changed config to the domain url) i get the following error in the firefox console (i know you are german):
`Firefox kann keine Verbindung zu dem Server unter ws://meine.domain.de/ aufbauen.  general.js:26:14`

My plotfiles and sizes are displayed correct, but no reading progress, block data or nonce submission is displayed.
Mainscreen looks like the screenshot from my first post.
