### ISSUE TITLE
1.7.0.1 install: cmake error Specify CUDA_TOOLKIT_ROOT_DIR

### ISSUE THREAD

**Issue by mike0074** [Creepsky/creepMiner#207]
CMake Error at /usr/share/cmake-3.5/Modules/FindCUDA.cmake:617 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  CMakeLists.txt:46 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/mb/creepMiner-1.7.0.1/CMakeFiles/CMakeOutput.log".

[CMakeOutput.log](https://github.com/Creepsky/creepMiner/files/1333140/CMakeOutput.log)

**Comment by Creepsky** [comment]
cmake -DUSE_GPU=OFF

**Comment by mike0074** [comment]
~/creepMiner-1.7.0.1$ sudo cmake CMakeLists.txt -DCMAKE_BUILD_TYPE=RELEASE -DUSE_GPU=OFF
[sudo] Passwort für mb: 
CMake Error at /usr/share/cmake-3.5/Modules/FindCUDA.cmake:617 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR

~/creepMiner-1.7.0.1$ sudo cmake CMakeLists.txt -DCMAKE_BUILD_TYPE=RELEASE -DGPU_ACCELERATION=None
CMake Error at /usr/share/cmake-3.5/Modules/FindCUDA.cmake:617 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR

**Comment by Creepsky** [comment]
cmake -DNO_GPU=ON

**Comment by mike0074** [comment]
cmake CMakeLists.txt -DCMAKE_BUILD_TYPE=RELEASE -DNO_GPU=ON
-- Build files have been written to: /home/mb/creepMiner-1.7.0.1
you nailed it!
little detail from the make:
/home/mb/creepMiner-1.7.0.1/src/plots/PlotGenerator.cpp: In static member function ‘static Poco::UInt64 Burst::PlotGenerator::generateAndCheck(Poco::UInt64, Poco::UInt64, const Burst::Miner&)’:
/home/mb/creepMiner-1.7.0.1/src/plots/PlotGenerator.cpp:61:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (auto i = 0; i < Settings::PlotSize; i++)
                     ^
but the miner is up! thanks
