### ISSUE TITLE
error on submitting nonce! to v2 pool 

### ISSUE THREAD

**Issue by amtx** [Creepsky/creepMiner#208]
can't submit nonces to v2 pool  (http://pool.burstcoin.ml/) any more.
was working till 3:00 am 09-29-2017
creepminer version:1.6.3 built on linux
log: 
29.09.2017 20:39:59 (8, /mnt/2TB/tmp/creepMiner/src/mining/Miner.cpp, 369, Information): 88Z5-83AG-6G2Z-D9RCY: nonce found (6d 15:20:56)
	nonce: 31372011
	in:    /mnt/8TB/plots/13775076604967590883_28244288_4096000_4096
29.09.2017 20:39:59 (4, /mnt/2TB/tmp/creepMiner/src/wallet/Wallet.cpp, 184, Debug): Sending wallet request '/burst?requestType=getAccount&account=13775076604967590883'
29.09.2017 20:39:59 (5, /mnt/2TB/tmp/creepMiner/src/network/NonceSubmitter.cpp, 87, Debug): Submit-loop 1 (6d 15:20:56)
29.09.2017 20:39:59 (4, /mnt/2TB/tmp/creepMiner/src/wallet/Wallet.cpp, 197, Debug): Got response for wallet request '/burst?requestType=getAccount&account=13775076604967590883'
{"unconfirmedBalanceNQT":"79163460052","guaranteedBalanceNQT":"79163460052","unconfirmedAssetBalances":[{"unconfirmedBalanceQNT":"400","asset":"6896197830923766736"},{"unconfirmedBalanceQNT":"100","asset":"10071080214837377826"},{"unconfirmedBalanceQNT":"66","asset":"5255893438014874161"}],"effectiveBalanceNXT":79163460052,"accountRS":"BURST-88Z5-83AG-6G2Z-D9RCY","forgedBalanceNQT":"0","balanceNQT":"79163460052","publicKey":"1a88f8fceda49bd71151a72b54cbd928890d950ca28becd770d3df7ccc13f516","requestProcessingTime":1,"assetBalances":[{"balanceQNT":"400","asset":"6896197830923766736"},{"balanceQNT":"100","asset":"10071080214837377826"},{"balanceQNT":"66","asset":"5255893438014874161"}],"account":"13775076604967590883"}
29.09.2017 20:39:59 (5, /mnt/2TB/tmp/creepMiner/src/network/NonceSubmitter.cpp, 109, Information): 88Z5-83AG-6G2Z-D9RCY: nonce submitted (6d 15:20:56)
	nonce: 31372011
	in:    /mnt/8TB/plots/13775076604967590883_28244288_4096000_4096
29.09.2017 20:39:59 (4, /mnt/2TB/tmp/creepMiner/src/wallet/Wallet.cpp, 184, Debug): Sending wallet request '/burst?requestType=getAccount&account=13775076604967590883'
29.09.2017 20:39:59 (4, /mnt/2TB/tmp/creepMiner/src/wallet/Wallet.cpp, 197, Debug): Got response for wallet request '/burst?requestType=getAccount&account=13775076604967590883'
{"unconfirmedBalanceNQT":"79163460052","guaranteedBalanceNQT":"79163460052","unconfirmedAssetBalances":[{"unconfirmedBalanceQNT":"400","asset":"6896197830923766736"},{"unconfirmedBalanceQNT":"100","asset":"10071080214837377826"},{"unconfirmedBalanceQNT":"66","asset":"5255893438014874161"}],"effectiveBalanceNXT":79163460052,"accountRS":"BURST-88Z5-83AG-6G2Z-D9RCY","forgedBalanceNQT":"0","balanceNQT":"79163460052","publicKey":"1a88f8fceda49bd71151a72b54cbd928890d950ca28becd770d3df7ccc13f516","requestProcessingTime":0,"assetBalances":[{"balanceQNT":"400","asset":"6896197830923766736"},{"balanceQNT":"100","asset":"10071080214837377826"},{"balanceQNT":"66","asset":"5255893438014874161"}],"account":"13775076604967590883"}
29.09.2017 20:39:59 (5, /mnt/2TB/tmp/creepMiner/src/network/Response.cpp, 148, Error): Error while waiting for confirmation!
Syntax error: JSON syntax error
29.09.2017 20:39:59 (5, /mnt/2TB/tmp/creepMiner/src/network/Response.cpp, 150, Error): Stackframe
NonceResponse::getConfirmation (in "/mnt/2TB/tmp/creepMiner/src/network/Response.cpp", line 107)

29.09.2017 20:39:59 (5, /mnt/2TB/tmp/creepMiner/src/network/NonceSubmitter.cpp, 124, Debug): JSON confirmation (6d 15:20:56)
	
29.09.2017 20:39:59 (5, /mnt/2TB/tmp/creepMiner/src/network/NonceSubmitter.cpp, 197, Warning): 88Z5-83AG-6G2Z-D9RCY: error on submitting nonce! (6d 15:20:56)

**Comment by Creepsky** [comment]
Did the owner of the pool changed something?
Maybe the pool is just temporary under heavy load?

**Comment by amtx** [comment]
Oh sorry - yes they switched off port 80 for nonce submission. I changed creepminer config to use port 8080 - now everything is OK. Thank you!
