### ISSUE TITLE
Wrong CPU Instruction set

### ISSUE THREAD

**Issue by N8Thrasher** [Creepsky/creepMiner#209]
Using [Intel I5-2400 (Instruction Set Extensions
SSE4.1/4.2, AVX)](https://ark.intel.com/products/52207/Intel-Core-i5-2400-Processor-6M-Cache-up-to-3_40-GHz)

Miner reports error
![image](https://user-images.githubusercontent.com/24593637/31047577-225e2078-a616-11e7-9de3-15a1e4f424a1.png)

**Comment by yEinFallsLos** [comment]
how did you compile it?

**Comment by N8Thrasher** [comment]
i did not.. just download the pre compiled one

**Comment by Creepsky** [comment]
use "cpuInstructionSet" : "SSE4" instead of "sse4" (case sensitive)

**Comment by N8Thrasher** [comment]
Yeah I did it.. it works now.
