### ISSUE TITLE
creepMiner-sse4[8510]: segfault at 25 ip 00005644ee2383b1 [..cut..]

### ISSUE THREAD

**Issue by mitchelp** [Creepsky/creepMiner#211]
I got creepMiner segfaulting on me.
Is there any known issue that could cause this to happen:
`[Fri Sep 29 14:32:16 2017] creepMiner-sse4[8510]: segfault at 25 ip 00005644ee2383b1 sp 00007ffcbe58f420 error 4 in creepMiner-sse4[5644ee19a000+f5000]`

Version is: v1.6.3
Running on:
~# cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by Creepsky** [comment]
This is a very old issue - did you try the latest release? Is it still happening?
Segfaults a very vague errors that can be caused by many things.
