### ISSUE TITLE
OpenCL on macOS

### ISSUE THREAD

**Issue by bsom** [Creepsky/creepMiner#216]
In MinerCL.hpp:
`#include <CL/cl.h>` doesn't work on macOS.
The line should be `<OpenCL/cl.h>` for macOS.

**Comment by Creepsky** [comment]
Isnt it `<OpenCL/opencl.h>`? Changed it in new commit..

**Comment by bsom** [comment]
I just compiled using `<OpenCL/cl.h> `and it worked great.  I'm on High Sierra.

**Comment by Creepsky** [comment]
Ok, changed to `<OpenCL/cl.h>` in master 👍
