### ISSUE TITLE
OpenCL kernel_args error

### ISSUE THREAD

**Issue by PsyDafke** [Creepsky/creepMiner#218]
Hi Creepsky,

I'm trying to get OpenCL working, since my current mining rig is lacking AVX2, and the amount of disks/plot size is becoming too large for AVX (certainly on short rounds).
I was temporarily running creepMiner successfully on a dual socket Xeon (12 cores/32 threads) AVX2, and loved it! But that server is way overkill to keep using it as a miner ;)

Connected the JBOD back to the intended machine, but I keep getting:
`16.10.2017 12:05:12 (36, F:\dev\C++\creepMiner\src\gpu/algorithm/gpu_algorithm_atomic.hpp, 77, Error): Error while verifying a plot file!
	Error: CL_INVALID_KERNEL_ARGS`

Even if I lower intensity and buffersize.

This is on version 1.7.1 with a Radeon RX 480 8GB, on Windows 2016 DC, 32GB RAM.
jMiner runs without issues on the same system, but I'd prefer to have creepMiner running on it, since then higher DLs then already submitted are skipped (which is beneficial for pool performance)!

`2017-10-16 12:06:54.825  INFO 1564 --- [           main] b.jminer.core.checker.util.OCLChecker    : List of system openCL platforms and devices (* = used for mining)
2017-10-16 12:06:54.825  INFO 1564 --- [           main] b.jminer.core.checker.util.OCLChecker    :
2017-10-16 12:06:54.825  INFO 1564 --- [           main] b.jminer.core.checker.util.OCLChecker    :  * PLATFORM-[0] AMD Accelerated Parallel Processing - (OpenCL 2.0 AMD-APP (2442.8))
2017-10-16 12:06:54.840  INFO 1564 --- [           main] b.jminer.core.checker.util.OCLChecker    :  *   DEVICE-[0] Ellesmere (8GB) - Advanced Micro Devices, Inc. (OpenCL 2.0 AMD-APP (2442.8) | '2442.8')
2017-10-16 12:06:54.840  INFO 1564 --- [           main] b.jminer.core.checker.util.OCLChecker    :  *          [0] work group size: '256', computing units: '36', available 'true'
2017-10-16 12:06:54.840  INFO 1564 --- [           main] b.jminer.core.checker.util.OCLChecker    :      DEVICE-[1] AMD FX(tm)-8320 Eight-Core Processor (34GB) - AuthenticAMD (OpenCL 1.2 AMD-APP (2442.8) | '2442.8 (sse2,avx,fma4)')
2017-10-16 12:06:54.840  INFO 1564 --- [           main] b.jminer.core.checker.util.OCLChecker    :             [1] work group size: '1024', computing units: '8', available 'true'
2017-10-16 12:06:56.121  INFO 1564 --- [           main] b.jminer.core.checker.util.OCLChecker    :
2017-10-16 12:06:56.121  INFO 1564 --- [           main] b.jminer.core.checker.util.OCLChecker    : (*) openCL context successfully started! (platformId: 0, deviceId: 0)` 

If there is any extra info I can provide or if you want me to test something else, please let me know.

Thanks,

David

**Comment by Creepsky** [comment]
Hello David,

the error you get `CL_INVALID_KERNEL_ARGS` indicates, that the OpenCL kernel was started with the wrong amount or wrong types of parameters.

Maybe you somehow mixed up the OpenCL kernel file `mining.cl` and the matching version of the miner?
Try to download the latest release again and test it with a fresh installation.

The next thing I would test is to use different OpenCL devices by changing `gpuDevice` and `gpuPlatform` in the config file. Do you get different results from it?

**Comment by PsyDafke** [comment]
Hi, I’ll try to freshly download 1.7.1 and try again (and also freshly adapt the config from default).
I’m very certain of the platformID and deviceID though, as I use them successfully with jMiner and GPUPlotGenerator,
also the logfile indicates that the RX 480 is being used.

**Comment by PsyDafke** [comment]
Nope, redownloaded, adapted the mining config from zero, and verified.
Lowered the intensity, lowered the buffer to 256M... still got the 'crashing'/error.
How is the relation to the buffersize/itensity/plotreaders in opencl?
I ask as I caught this:
`16.10.2017 18:06:32 (36, F:\dev\C++\creepMiner\src\gpu/algorithm/gpu_algorithm_atomic.hpp, 77, Error): Error while verifying a plot file!
	Error: CL_MEM_OBJECT_ALLOCATION_FAILURE`
Which I haven't seen while using AVX2 with much higher numbers on the dual-Xeon...

**Comment by PsyDafke** [comment]
Follow up:
I replaced the 1.7.1 mining.cl with the one from the sources (https://github.com/Creepsky/creepMiner/blob/master/src/shabal/opencl/mining.cl), since I saw you did a commit (https://github.com/Creepsky/creepMiner/commit/07dad9a1aab7410fc10d3a57b74b551652acc10d)
 concerning a OpenCL 2.0 bug.
That seems to mitigate the errors, and now I should go hunting to where the performance difference between creepMiner and jMiner is... since I can't seem to manage to get a better result than double the time per round as jMiner needs.
So any insight into the difference between the 2 would be awesome!

**Comment by Creepsky** [comment]
This can help to optimize the performance:
https://github.com/Creepsky/creepMiner/wiki/The-mining-process-and-otimizations

Here you can see all settings:
https://github.com/Creepsky/creepMiner/wiki/Setting-up-the-miner

**Comment by PsyDafke** [comment]
I'm well aware of those pages, and have tried to find optimized settings (but failed until now to match the jMiner performance).
Currently have the RX480 (which has 36 CUs), and 28 plotpaths (soon to be expanded to 60! as I have a SAS3 connected toploader with 9600MB/s max bandwidth).
I expect the RX Vega (with 64 CUs) to arrive this week, and already 4 extra 10TB HGSTs to test those.
Think I might need to dive in the code to see how I can find the right parameters, so I fully understand the required mem allocation per parameter, and to use those system rescources at full, as scan times are becoming more and more important.
