### ISSUE TITLE
Miners stops reading plots after a few days of running

### ISSUE THREAD

**Issue by yuzi-co** [Creepsky/creepMiner#219]
Miner was running fine for a few days and suddenly stopped reading plots
Forwarding nonces continues to work fine

After miner restart, everything works fine.
creepMiner 1.7.1 Windows x64 is running in Windows 10, using AVX2
Config file:
[mining.zip](https://github.com/Creepsky/creepMiner/files/1387215/mining.zip)

Log file attached (last rotated part of the full log)
last plot "read in" message in log is from 16.10.2017 09:36:08
and no reads for the next 4 hours
[creepMiner_20171013_121847.693625.zip](https://github.com/Creepsky/creepMiner/files/1387205/creepMiner_20171013_121847.693625.zip)

**Comment by yuzi-co** [comment]
another example
[creepMiner_20171022_154106.474097.log.0.gz](https://github.com/Creepsky/creepMiner/files/1414687/creepMiner_20171022_154106.474097.log.0.gz)

I believe that it happened due to a memory hungry process that was running at the same time.
Possibly the miner failed to allocate a memory buffer and stopped trying after that

**Comment by Creepsky** [comment]
Hi and thanks for the attached files.
Hard to tell what exactly happened, the log just says that the plot readers stop their work after a while.
It may be, that they could not allocate enough memory.

I wrapped the plot reader into a security bubble to fetch and output errors inside it, also there is some more debug info on a new block.

[creepMiner-win64-1.7.4.zip](https://github.com/Creepsky/creepMiner/files/1422549/creepMiner-win64-1.7.4.zip)

**Comment by yuzi-co** [comment]
Thanks, I'll try to reproduce with this version
