### ISSUE TITLE
cpuInstructionSet in arm64

### ISSUE THREAD

**Issue by oxconan** [Creepsky/creepMiner#221]
Hi,

I compile it with -DNO_GPU=ON  -DMINIMAL_BUILD=ON.. 
I'm running in arm64 system, with config:
"processorType" : "CPU"
"cpuInstructionSet" : "SSE2",

I see it no issue.. Do I configure right or wrong ?

**Comment by Creepsky** [comment]
Looks good 👍

**Comment by oxconan** [comment]
I read your source, sse2 use Shabal256_SSE2 = Shabal256_Shell<Sphlib_Impl>;

**Comment by oxconan** [comment]
I was running solo mining 3 weeks in arm64. But never win blocks :-(
Do you think about that ?

**Comment by Creepsky** [comment]
Depends on the size of your plotted space.
The difficulty is super high and very weird in last times.

**Comment by oxconan** [comment]
Hi Creepsky,

Should use one account or two account BURT in burning system (had 4 PC) ?

**Comment by Creepsky** [comment]
Hi,
you can use forwarding for one account on different computers. I hope your system is not physically burning.
