### ISSUE TITLE
Function Forward in pool

### ISSUE THREAD

**Issue by oxconan** [Creepsky/creepMiner#222]
I ran 3 nodes with forward function, but I see in pool
![image](https://user-images.githubusercontent.com/7821025/32369053-6216533e-c0ba-11e7-8819-c5dab103e1f7.png)
![image](https://user-images.githubusercontent.com/7821025/32369057-674f59ae-c0ba-11e7-9abe-9823e4922e7d.png)

**Comment by Creepsky** [comment]
Fixed in commit 41abf49fd4b248840e7aef9584589f7be53bb34a and online in the master branch.

**Comment by oxconan** [comment]
I’m running 1.7.7, see full size in pool.

Thanks!
