### ISSUE TITLE
cmake issue

### ISSUE THREAD

**Issue by Seveley** [Creepsky/creepMiner#223]
having following error on debian 9 

burstcoin1@instance-1:/creepMiner$ sudo cmake -DCMAKE_BUILD_TYPE=RELEASE -DNO_GPU=OFF
CMake Error at /usr/share/cmake-3.7/Modules/FindCUDA.cmake:642 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  CMakeLists.txt:46 (find_package)

-- Configuring incomplete, errors occurred!
See also "/creepMiner/CMakeFiles/CMakeOutput.log".
See also "/creepMiner/CMakeFiles/CMakeError.log".

burstcoin1@instance-1:/creepMiner$ sudo cmake -DCMAKE_BUILD_TYPE=RELEASE -DNO_GPU=ON
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OpenCL_LIBRARY
    linked by target "creepMiner" in directory /creepMiner

-- Configuring incomplete, errors occurred!
See also "/creepMiner/CMakeFiles/CMakeOutput.log".
See also "/creepMiner/CMakeFiles/CMakeError.log".

I Tryed to install opencl but can't find how same for CUDA. (running in virtual box so no GPU)

**Comment by Creepsky** [comment]
Before changing your cmake settings you have to delete the following files and folders
```
CMakeCache.txt
CMakeFiles/*
```
Then you can run your cmake command.

**Comment by oxconan** [comment]
You try to make with DNO_GPU=ON -DMINIMAL_BUILD=ON

**Comment by Seveley** [comment]
the -DMINIMAL_BUILD=ON feature looks to do the job right now

But... as long as i'm plotting drive i can't make will let you know when done

**Comment by oxconan** [comment]
You can doing plot and compile parallel... :-)

**Comment by Seveley** [comment]
don't have enough memory in VM make crash lol

**Comment by Seveley** [comment]
Good ploting has finished and make went perfectly ty guys
