### ISSUE TITLE
GeForce GT 330M - CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by ohsweetgod987** [Creepsky/creepMiner#225]
I have an Nvidia GeForce GT 330M and am trying to run EWBF's Zcash CUDA miner 0.3.4b. I know it's old and not the most powerful GPU for mining, but I have an old laptop that I figured I'd try to get some use out of. I get the error "CUDA driver version is insufficient for CUDA runtime version" and have tried updating to the most recent drivers for the graphics card itself and CUDA separately but nothing works. Any help is appreciated!
![image](https://user-images.githubusercontent.com/34191295/33517341-b6a08850-d750-11e7-8b3d-fbb02676736a.png)

**Comment by Creepsky** [comment]
Hello,
the most recent CUDA version is 9.1, did you try it?
