### ISSUE TITLE
Ready-to-install packages for releases

### ISSUE THREAD

**Issue by Kristian-Popov** [Creepsky/creepMiner#226]
Hello!
This miner is mature enough for easy-to-install packages for different OS (e.g. InstallShield, Chocolatey or 0Install for Windows, deb package for Debian/Ubuntu/Mint). I wouldn't mind if it won't use shared libraries in OS like it is usually done on Linux (i.e. can be compiled in a fully static build so it's larger but it's probably easier), but it would be way easier to install and use. Plus automatic creating of these packages by continuous integration system will enable a possibility for automatic upgrades (at least on Linux).
Since I plan to use this miner soon and I have an appropriate background, I will try to contribute some time on this myself, but I can't give any ETA.

Regards,
Kristian Popov

**Comment by Beddhist** [comment]
PoCC already have an old version in their repo: https://forums.getburst.net/t/the-pocc-has-started-a-linux-package-repository-for-burst/399

It would be nice to have that updated to a newer version and the install script modified to accept Ubuntu derivatives, like the popular Mint.

**Comment by Creepsky** [comment]
Done for Debian + Windows
