### ISSUE TITLE
Feature request: Configurable miner name in mining.conf, transmit in HTTP header as "X-Minername" or similar

### ISSUE THREAD

**Issue by solfolango** [Creepsky/creepMiner#229]
I am currently developing a node app that acts as a forward proxy and collects some statistical information about the miners forwarding to this proxy. I tried using creepminer for this, but for some reason it segfaults after a couple of hours on my proxy VM, and I thought decoupling this feature would be a good idea (github link will follow when it is in a usable state).

To identify the miner that forwarded the nonce, one can use the x-plotshash, but this value is changed whenever a plot is added to the miner, therefore it is not really identifying a computer, but a collection of plots - which can change. I am currently plotting and constantly adding new plots, so this value will change randomly. To be able to set a miner name in the config would resolve this problem (at least for me).

Just as the hashing of plain username/password the first time they are set, the miner name could be randomly choosen on the first run if the value is empty. I am really bad at C++, therefore I won't submit working code, sorry about that.

**Comment by deanhloop** [comment]
What about displaying the IP address that a deadline came from? The Blago miner does this. Additionally, maybe a section could be added to the mining.conf file that would allow one to create a "friendly" name for IP addresses. This name could be displayed in parentheses after the IP address in the console output.

**Comment by nitr8** [comment]
please use the new "ServerName" in the web config
