### ISSUE TITLE
Test mode, don't send on a pool deadlines

### ISSUE THREAD

**Issue by llybin** [Creepsky/creepMiner#231]
Why I need this. When I configure a system for mining, I trying changes some parameters for increasing speed of mining. I'd like to disable send deadlines to pool because pools have fine for duplicates of deadlines on one block.

**Comment by Creepsky** [comment]
There is a new setup mode in the new development version (not finished yet), that can also find the best setting for your miner. I think that is what you are looking for :)

**Comment by Creepsky** [comment]
It is still in development state, but please consider using version [1.8.0](https://github.com/Creepsky/creepMiner/tree/2.8.0).

Start the setup mode with `./creepMiner -setup` on Linux, and `creepMiner.exe /setup` on Windows.

**Comment by llybin** [comment]
I couldn't build, Linux.

```
cmake CMakeLists-Original.txt                                                                                                                            
CMake Error: The source directory "/home/lybin/bin/creepMiner-2.8.0/CMakeLists-Original.txt" is a file, not a directory.
Specify --help for usage, or press the help button on the CMake GUI.
```
```
cmake CMakeLists.txt                                                                                                                                       
CMake Error at CMakeLists.txt:25 (include):
  include could not find load file:

    conanbuildinfo.cmake

CMake Error at CMakeLists.txt:26 (conan_basic_setup):
  Unknown CMake command "conan_basic_setup".

-- Configuring incomplete, errors occurred!
```

Conan version 0.30.3

**Comment by Creepsky** [comment]
Oh, if you want to use the old cmakelists, you have to rename it to `CMakeLists.txt` (sorry, CMake is a bit.. strange sometimes).

`Unknown CMake command "conan_basic_setup".` indicates you have not properly let conan setup the dependencies for you (or had errors).

Did you call `conan install` inside the creepMiner project dir? If this is not working, try `conan install --build=missing -s compiler.libcxx=libstdc++11`.

**Comment by llybin** [comment]
I couldn't build with conan, Archlinux, Poco is already installed in my system, but building with conan try to build poco and he couldn't built.

I renamed CMakeLists-Original.txt  -> CMakeLists.txt
cmake . -DNO_GPU=ON
make

CMakeFiles/creepMiner.dir/src/main.cpp.o: In function `main':
main.cpp:(.text.startup+0xa94): undefined reference to `Burst::Setup::setup(Burst::MinerConfig&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/creepMiner.dir/build.make:1031: bin/creepMiner] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/creepMiner.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by Creepsky** [comment]
I added the missing source file to cmakelists-original, please try it again.
You dont need to rename it: `cmake CMakeLists-Original.txt -DNO_GPU=ON`

**Comment by llybin** [comment]
development branch

Sorry, I can't build: CMake Error: The source directory "creepMiner/CMakeLists-Original.txt" is a file, not a directory.

If rename CMakeLists-Original.txt to CMakeLists.txt get error: 

CMake Error: File creepMiner/bin/mining.conf does not exist.
CMake Error at CMakeLists.txt:181 (configure_file):
  configure_file Problem configuring file

Copying mining.conf

cmake . -DNO_GPU=ON
OK

make:
[  2%] Building CXX object CMakeFiles/creepMiner.dir/src/Declarations.cpp.o
/home/lybin/sources/creepMiner/src/Declarations.cpp:31:17: error: ‘VERSION_MAJOR’ was not declared in this scope
  Burst::Version(VERSION_MAJOR, VERSION_MINOR, VERSION_BUILD, 0));
                 ^~~~~~~~~~~~~
/home/lybin/sources/creepMiner/src/Declarations.cpp:31:32: error: ‘VERSION_MINOR’ was not declared in this scope
  Burst::Version(VERSION_MAJOR, VERSION_MINOR, VERSION_BUILD, 0));
                                ^~~~~~~~~~~~~
/home/lybin/sources/creepMiner/src/Declarations.cpp:31:47: error: ‘VERSION_BUILD’ was not declared in this scope
  Burst::Version(VERSION_MAJOR, VERSION_MINOR, VERSION_BUILD, 0));
                                               ^~~~~~~~~~~~~
make[2]: *** [CMakeFiles/creepMiner.dir/build.make:63: CMakeFiles/creepMiner.dir/src/Declarations.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/creepMiner.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by nitr8** [comment]
@llybin 

Please check out the new instructions - https://github.com/Creepsky/creepMiner/wiki/Compiling-from-source if you running on *nix or macOS hit me up on discord I can provide you with precompiled binaries.

**Comment by llybin** [comment]
Great, thank you, I built successfully.

But feature looks like a doesn't works. If to remove -setup - a miner starts a work.

./creepMiner --config=/home/lybin/.creepMiner/1.7.16/mining.conf -setup                                                                               
usage: creepMiner <options>
Burstcoin cryptocurrency CPU and GPU miner.

-h, --help             Display help information
-cpath, --config=path  Path to the config file

Copyright (C)  2016-2018 Creepsky (creepsky@gmail.com)

**Comment by nitr8** [comment]
Thanks for the heads up -setup was removed, I tried find out where you got this info from to remove it.

Please would you be so kind as to letting me know where you found that so it can be reworked :)

**Comment by llybin** [comment]
in description of this issue :)

**Comment by nitr8** [comment]
cheers - will get this resolved, closing case as you up and running thanks so much for the input.
