### ISSUE TITLE
Crash when using Linux every couple of hours

### ISSUE THREAD

**Issue by rpseng** [Creepsky/creepMiner#232]
I have creepMiner (latest from the repository) running on a 64bit Ubuntu Linux 17.10. Every couple of hours it crashes because of a timeout exception. The last lines of the log read:

22.12.2017 21:06:02 (0, /home/rafael/git/creepMiner/src/webserver/MinerServer.cpp, 241, Error): Exception occured: Timeout
	error-code: 110
	class: N4Poco16TimeoutExceptionE

It is probably a bug with some unhandled exception.

**Comment by Beddhist** [comment]
By latest, do you mean 2.7.6, flagged as "latest release" or 2.8, flagged "pre-release"? I found 2.7.6 very unstable on Linux. Switched to 2.7.13, problem solved.

**Comment by rpseng** [comment]
Thanks for the reply. I meant the master head code from github. Just downloaded the 2.7.13 and will let it running.

**Comment by wouterpol93** [comment]
I have this issue using 2.7.13, any updates on it?

**Comment by Creepsky** [comment]
Try the latest release 1.7.16.
Re-open if you still get this issue.
