### ISSUE TITLE
Unable to complit Creepminer on Ubuntu 17.10 with NVIDIA

### ISSUE THREAD

**Issue by MrClayPole** [Creepsky/creepMiner#235]
Hi I'm unable to get creepminer to compile on Ubuntu 17.10. Below is what I get

burst@cn-srv-ubunt-01:~/creepMiner$ cmake -DCMAKE_BUILD_TYPE=RELEASE
-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 5.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr (found version "8.0") 
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - found
-- Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found version "2.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/burst/creepMiner
burst@cn-srv-ubunt-01:~/creepMiner$ make clean
burst@cn-srv-ubunt-01:~/creepMiner$ make
[  2%] Building NVCC (Device) object CMakeFiles/creepMiner.dir/src/shabal/cuda/creepMiner_generated_Shabal.cu.o
Scanning dependencies of target creepMiner
[  5%] Building CXX object CMakeFiles/creepMiner.dir/src/gpu/impl/gpu_cuda_impl.cpp.o
In file included from /home/burst/creepMiner/src/gpu/impl/gpu_cuda_impl.hpp:6:0,
                 from /home/burst/creepMiner/src/gpu/impl/gpu_cuda_impl.cpp:22:
/home/burst/creepMiner/src/mining/MinerData.hpp:27:30: fatal error: Poco/JSON/Object.h: No such file or directory
compilation terminated.
CMakeFiles/creepMiner.dir/build.make:69: recipe for target 'CMakeFiles/creepMiner.dir/src/gpu/impl/gpu_cuda_impl.cpp.o' failed
make[2]: *** [CMakeFiles/creepMiner.dir/src/gpu/impl/gpu_cuda_impl.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/creepMiner.dir/all' failed
make[1]: *** [CMakeFiles/creepMiner.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Below is the NVIDIA GPU and CUDA versions I have installed.

burst@cn-srv-ubunt-01:~/creepMiner$ nvidia-smi 
Wed Dec 27 18:13:39 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 680     Off  | 00000000:01:00.0 N/A |                  N/A |
| 34%   24C    P0    N/A /  N/A |      0MiB /  1999MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+
burst@cn-srv-ubunt-01:~/creepMiner$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

Not sure what the issues is?

**Comment by Creepsky** [comment]
Hi!
The error message is:  `fatal error: Poco/JSON/Object.h: No such file or directory`.
Did you install Poco? There is an install script for poco in the root directory: install-poco.sh.
Any reason why you dont use the latest release?

**Comment by MrClayPole** [comment]
When Install Poco using ./install-poco.sh I get the following error.

+ cd poco-1.7.8p3-all
+ ./configure --no-tests --no-samples --omit=Data/ODBC,Data/MySQL
Configured for Linux
+ make
make -C /home/burst/creepMiner/poco-1.7.8p3-all/Foundation
make[1]: Entering directory '/home/burst/creepMiner/poco-1.7.8p3-all/Foundation'
** Compiling src/ArchiveStrategy.cpp (debug, shared)
g++  -Iinclude -I/home/burst/creepMiner/poco-1.7.8p3-all/CppUnit/include -I/home/burst/creepMiner/poco-1.7.8p3-all/CppUnit/WinTestRunner/include -I/home/burst/creepMiner/poco-1.7.8p3-all/Foundation/include -I/home/burst/creepMiner/poco-1.7.8p3-all/XML/include -I/home/burst/creepMiner/poco-1.7.8p3-all/JSON/include -I/home/burst/creepMiner/poco-1.7.8p3-all/Util/include -I/home/burst/creepMiner/poco-1.7.8p3-all/Net/include -I/home/burst/creepMiner/poco-1.7.8p3-all/Crypto/include -I/home/burst/creepMiner/poco-1.7.8p3-all/NetSSL_OpenSSL/include -I/home/burst/creepMiner/poco-1.7.8p3-all/Data/include -I/home/burst/creepMiner/poco-1.7.8p3-all/Data/SQLite/include -I/home/burst/creepMiner/poco-1.7.8p3-all/Data/ODBC/include -I/home/burst/creepMiner/poco-1.7.8p3-all/Data/MySQL/include -I/home/burst/creepMiner/poco-1.7.8p3-all/MongoDB/include -I/home/burst/creepMiner/poco-1.7.8p3-all/Zip/include -I/home/burst/creepMiner/poco-1.7.8p3-all/PageCompiler/include -I/home/burst/creepMiner/poco-1.7.8p3-all/PageCompiler/File2Page/include -Wall -Wno-sign-compare -DPOCO_BUILD_HOST='"'cn-srv-ubunt-01'"' -DPOCO_TARGET_OSNAME='"'Linux'"' -DPOCO_TARGET_OSARCH='"'x86_64'"'  -D_XOPEN_SOURCE=600 -D_REENTRANT -D_THREAD_SAFE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DPOCO_HAVE_FD_EPOLL  -g -D_DEBUG -fPIC -c src/ArchiveStrategy.cpp -o /home/burst/creepMiner/poco-1.7.8p3-all/Foundation/obj/Linux/x86_64/debug_shared/ArchiveStrategy.o
In file included from include/Poco/FPEnvironment.h:33:0,
                 from include/Poco/NumericString.h:25,
                 from include/Poco/NumberFormatter.h:24,
                 from include/Poco/ArchiveStrategy.h:27,
                 from src/ArchiveStrategy.cpp:17:
include/Poco/FPEnvironment_C99.h: In static member function ‘static bool Poco::FPEnvironmentImpl::isInfiniteImpl(float)’:
include/Poco/FPEnvironment_C99.h:78:9: error: ‘__builtin_isinf_sign’ is not a member of ‘std’
  return std::isinf(value) != 0;
         ^
include/Poco/FPEnvironment_C99.h:78:9: note: suggested alternative:
<built-in>: note:   ‘__builtin_isinf_sign’
include/Poco/FPEnvironment_C99.h: In static member function ‘static bool Poco::FPEnvironmentImpl::isInfiniteImpl(double)’:
include/Poco/FPEnvironment_C99.h:84:9: error: ‘__builtin_isinf_sign’ is not a member of ‘std’
  return std::isinf(value) != 0;
         ^
include/Poco/FPEnvironment_C99.h:84:9: note: suggested alternative:
<built-in>: note:   ‘__builtin_isinf_sign’
include/Poco/FPEnvironment_C99.h: In static member function ‘static bool Poco::FPEnvironmentImpl::isInfiniteImpl(long double)’:
include/Poco/FPEnvironment_C99.h:90:9: error: ‘__builtin_isinf_sign’ is not a member of ‘std’
  return std::isinf((double) value) != 0;
         ^
include/Poco/FPEnvironment_C99.h:90:9: note: suggested alternative:
<built-in>: note:   ‘__builtin_isinf_sign’
include/Poco/FPEnvironment_C99.h: In static member function ‘static bool Poco::FPEnvironmentImpl::isNaNImpl(float)’:
include/Poco/FPEnvironment_C99.h:96:9: error: ‘__builtin_isnan’ is not a member of ‘std’
  return std::isnan(value) != 0;
         ^
include/Poco/FPEnvironment_C99.h:96:9: note: suggested alternative:
<built-in>: note:   ‘__builtin_isnan’
include/Poco/FPEnvironment_C99.h: In static member function ‘static bool Poco::FPEnvironmentImpl::isNaNImpl(double)’:
include/Poco/FPEnvironment_C99.h:102:9: error: ‘__builtin_isnan’ is not a member of ‘std’
  return std::isnan(value) != 0;
         ^
include/Poco/FPEnvironment_C99.h:102:9: note: suggested alternative:
<built-in>: note:   ‘__builtin_isnan’
include/Poco/FPEnvironment_C99.h: In static member function ‘static bool Poco::FPEnvironmentImpl::isNaNImpl(long double)’:
include/Poco/FPEnvironment_C99.h:108:9: error: ‘__builtin_isnan’ is not a member of ‘std’
  return std::isnan((double) value) != 0;
         ^
include/Poco/FPEnvironment_C99.h:108:9: note: suggested alternative:
<built-in>: note:   ‘__builtin_isnan’
/home/burst/creepMiner/poco-1.7.8p3-all/build/rules/compile:53: recipe for target '/home/burst/creepMiner/poco-1.7.8p3-all/Foundation/obj/Linux/x86_64/debug_shared/ArchiveStrategy.o' failed
make[1]: *** [/home/burst/creepMiner/poco-1.7.8p3-all/Foundation/obj/Linux/x86_64/debug_shared/ArchiveStrategy.o] Error 1
make[1]: Leaving directory '/home/burst/creepMiner/poco-1.7.8p3-all/Foundation'
Makefile:131: recipe for target 'Foundation-libexec' failed
make: *** [Foundation-libexec] Error 2

so I used the ubuntu package libpoco-dev/artful,now 1.7.8+dfsg1-2 amd64

**Comment by MrClayPole** [comment]
I've been able to get ./install_poco.sh to work. I was using "ln -s" to make the default gcc and g++ map to version 5 rather than version 7. I've removed the soft links and removed and reinstall gcc5 and g++5. I now get the following error when I attempt to compile creepminer.

mat@cn-srv-ubunt-01:/home/burst/creepMiner$ sudo make
[  2%] Building CXX object CMakeFiles/creepMiner.dir/src/gpu/impl/gpu_cuda_impl.cpp.o
In file included from /usr/local/include/Poco/FPEnvironment.h:33:0,
                 from /usr/local/include/Poco/NumericString.h:25,
                 from /usr/local/include/Poco/NumberFormatter.h:24,
                 from /usr/local/include/Poco/Dynamic/VarHolder.h:24,
                 from /usr/local/include/Poco/Dynamic/Var.h:26,
                 from /usr/local/include/Poco/JSON/Array.h:25,
                 from /usr/local/include/Poco/JSON/Object.h:24,
                 from /home/burst/creepMiner/src/mining/MinerData.hpp:27,
                 from /home/burst/creepMiner/src/gpu/impl/gpu_cuda_impl.hpp:6,
                 from /home/burst/creepMiner/src/gpu/impl/gpu_cuda_impl.cpp:22:
/usr/local/include/Poco/FPEnvironment_C99.h: In static member function ‘static bool Poco::FPEnvironmentImpl::isInfiniteImpl(float)’:
/usr/local/include/Poco/FPEnvironment_C99.h:78:9: error: ‘__builtin_isinf_sign’ is not a member of ‘std’
  return std::isinf(value) != 0;
         ^
/usr/local/include/Poco/FPEnvironment_C99.h:78:9: note: suggested alternative:
<built-in>: note:   ‘__builtin_isinf_sign’
/usr/local/include/Poco/FPEnvironment_C99.h: In static member function ‘static bool Poco::FPEnvironmentImpl::isInfiniteImpl(double)’:
/usr/local/include/Poco/FPEnvironment_C99.h:84:9: error: ‘__builtin_isinf_sign’ is not a member of ‘std’
  return std::isinf(value) != 0;
         ^
/usr/local/include/Poco/FPEnvironment_C99.h:84:9: note: suggested alternative:
<built-in>: note:   ‘__builtin_isinf_sign’
/usr/local/include/Poco/FPEnvironment_C99.h: In static member function ‘static bool Poco::FPEnvironmentImpl::isInfiniteImpl(long double)’:
/usr/local/include/Poco/FPEnvironment_C99.h:90:9: error: ‘__builtin_isinf_sign’ is not a member of ‘std’
  return std::isinf((double) value) != 0;
         ^
/usr/local/include/Poco/FPEnvironment_C99.h:90:9: note: suggested alternative:
<built-in>: note:   ‘__builtin_isinf_sign’
/usr/local/include/Poco/FPEnvironment_C99.h: In static member function ‘static bool Poco::FPEnvironmentImpl::isNaNImpl(float)’:
/usr/local/include/Poco/FPEnvironment_C99.h:96:9: error: ‘__builtin_isnan’ is not a member of ‘std’
  return std::isnan(value) != 0;
         ^
/usr/local/include/Poco/FPEnvironment_C99.h:96:9: note: suggested alternative:
<built-in>: note:   ‘__builtin_isnan’
/usr/local/include/Poco/FPEnvironment_C99.h: In static member function ‘static bool Poco::FPEnvironmentImpl::isNaNImpl(double)’:
/usr/local/include/Poco/FPEnvironment_C99.h:102:9: error: ‘__builtin_isnan’ is not a member of ‘std’
  return std::isnan(value) != 0;
         ^
/usr/local/include/Poco/FPEnvironment_C99.h:102:9: note: suggested alternative:
<built-in>: note:   ‘__builtin_isnan’
/usr/local/include/Poco/FPEnvironment_C99.h: In static member function ‘static bool Poco::FPEnvironmentImpl::isNaNImpl(long double)’:
/usr/local/include/Poco/FPEnvironment_C99.h:108:9: error: ‘__builtin_isnan’ is not a member of ‘std’
  return std::isnan((double) value) != 0;
         ^
/usr/local/include/Poco/FPEnvironment_C99.h:108:9: note: suggested alternative:
<built-in>: note:   ‘__builtin_isnan’
CMakeFiles/creepMiner.dir/build.make:707: recipe for target 'CMakeFiles/creepMiner.dir/src/gpu/impl/gpu_cuda_impl.cpp.o' failed
make[2]: *** [CMakeFiles/creepMiner.dir/src/gpu/impl/gpu_cuda_impl.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/creepMiner.dir/all' failed
make[1]: *** [CMakeFiles/creepMiner.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jrejrdco** [comment]
I am getting a similar error, can you help me please? :

85%] Building CXX object CMakeFiles/creepMiner.dir/src/main.cpp.o
[ 88%] Building CXX object CMakeFiles/creepMiner.dir/src/MinerUtil.cpp.o
[ 91%] Linking CXX executable bin/creepMiner
/usr/local/lib/libPocoCrypto.so: undefined reference to `EVP_CIPHER_CTX_reset'
/usr/local/lib/libPocoCrypto.so: undefined reference to `OPENSSL_init_crypto'
/usr/local/lib/libPocoCrypto.so: undefined reference to `EVP_MD_CTX_new'
/usr/local/lib/libPocoCrypto.so: undefined reference to `EVP_MD_CTX_free'
/usr/local/lib/libPocoNetSSL.so: undefined reference to `SSL_CTX_set_options'
/usr/local/lib/libPocoNetSSL.so: undefined reference to `DH_set_length'
/usr/local/lib/libPocoCrypto.so: undefined reference to `OPENSSL_init_ssl'
/usr/local/lib/libPocoNetSSL.so: undefined reference to `SSL_session_reused'
/usr/local/lib/libPocoCrypto.so: undefined reference to `X509_getm_notBefore'
/usr/local/lib/libPocoCrypto.so: undefined reference to `OPENSSL_sk_num'
/usr/local/lib/libPocoNetSSL.so: undefined reference to `TLS_server_method'
/usr/local/lib/libPocoCrypto.so: undefined reference to `RSA_get0_key'
/usr/local/lib/libPocoNetSSL.so: undefined reference to `DH_set0_pqg'
/usr/local/lib/libPocoCrypto.so: undefined reference to `OPENSSL_sk_value'
/usr/local/lib/libPocoNetSSL.so: undefined reference to `TLS_client_method'
/usr/local/lib/libPocoCrypto.so: undefined reference to `X509_up_ref'
/usr/local/lib/libPocoCrypto.so: undefined reference to `X509_getm_notAfter'
collect2: error: ld returned 1 exit status
CMakeFiles/creepMiner.dir/build.make:953: recipe for target 'bin/creepMiner' failed
make[2]: *** [bin/creepMiner] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/creepMiner.dir/all' failed
make[1]: *** [CMakeFiles/creepMiner.dir/all] Error 2
Makefile:129: recipe for target 'all' failed

**Comment by jrejrdco** [comment]
I am having a similar problem, failing at 100% ?

[ 94%] Building CXX object CMakeFiles/creepMiner.dir/src/shabal/mshabal/mshabal_avx1.cpp.o
[ 97%] Building CXX object CMakeFiles/creepMiner.dir/src/shabal/mshabal/mshabal_avx2.cpp.o
[100%] Linking CXX executable bin/creepMiner
/usr/local/lib/libPocoCrypto.so: undefined reference to `EVP_CIPHER_CTX_reset'
/usr/local/lib/libPocoCrypto.so: undefined reference to `OPENSSL_init_crypto'
/usr/local/lib/libPocoCrypto.so: undefined reference to `EVP_MD_CTX_new'
/usr/local/lib/libPocoCrypto.so: undefined reference to `EVP_MD_CTX_free'
/usr/local/lib/libPocoNetSSL.so: undefined reference to `SSL_CTX_set_options'
/usr/local/lib/libPocoNetSSL.so: undefined reference to `DH_set_length'
/usr/local/lib/libPocoCrypto.so: undefined reference to `OPENSSL_init_ssl'
/usr/local/lib/libPocoNetSSL.so: undefined reference to `SSL_session_reused'
/usr/local/lib/libPocoCrypto.so: undefined reference to `X509_getm_notBefore'
/usr/local/lib/libPocoCrypto.so: undefined reference to `OPENSSL_sk_num'
/usr/local/lib/libPocoNetSSL.so: undefined reference to `TLS_server_method'
/usr/local/lib/libPocoCrypto.so: undefined reference to `RSA_get0_key'
/usr/local/lib/libPocoNetSSL.so: undefined reference to `DH_set0_pqg'
/usr/local/lib/libPocoCrypto.so: undefined reference to `OPENSSL_sk_value'
/usr/local/lib/libPocoNetSSL.so: undefined reference to `TLS_client_method'
/usr/local/lib/libPocoCrypto.so: undefined reference to `X509_up_ref'
/usr/local/lib/libPocoCrypto.so: undefined reference to `X509_getm_notAfter'
collect2: error: ld returned 1 exit status
CMakeFiles/creepMiner.dir/build.make:1030: recipe for target 'bin/creepMiner' failed
make[2]: *** [bin/creepMiner] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/creepMiner.dir/all' failed
make[1]: *** [CMakeFiles/creepMiner.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Hodgegoblin** [comment]
I have Dev up and running in 17.10. Conan worked, fine to install Poco other libs. You have to install gcc and g++ 5 then use update-alternatives to change to gcc-5, setting CC or CXX variables didn't work.

Only hangup was after build run.sh wasn't seeing libPoco until I ran 'sudo ldconfig'

**Comment by Creepsky** [comment]
Thank you @Hodgegoblin.
