### ISSUE TITLE
new release and raspberry Pi 3

### ISSUE THREAD

**Issue by Kneval** [Creepsky/creepMiner#236]
Hi guys,

first of all I have to say that I tested the creepminer last June successfully at my raspberry Pi 3. Unfortunately I deleted the creepminer after testing and I do not know which version it was.

Nevertheless I want to restart the project brust mining and downloaded the latest version of the creepminer.
After installing poco (without failure message) I missed the makefile which I have to fix as described at the wiki.
Ok. I installed cmake and tried it (cmake -DCMAKE_BUILD_TYPE=RELEASE). First I got a failure message that cuda is missing. So I added -DUSE_CUDA=OFF. Next I get a failure message about opencl, so I added -DUSE_OPENCL=OFF. Now cmake do not show any message and I receive a makefile.
But when I try to make it, it interrups at 2 % and shows a failure regading opencl.

Is there anybody how installed the latest version of the creepminer at a raspberry and can help me? Or someone else who have an idea what I have to change, that it works?

Thanks in advance
Kneval

**Comment by Osa1989** [comment]
I got it compiled using
cmake CMakeLists.txt -DCMAKE_BUILD_TYPE=RELEASE -DNO_GPU=ON -DMINIMAL_BUILD=ON
in the CMakeLists.txt I left -march=native

Giive it a try.
