### ISSUE TITLE
Expected output while mining

### ISSUE THREAD

**Issue by zkdzegede** [Creepsky/creepMiner#238]
I'm not exactly sure what I should be seeing while mining so could someone tell me if this output is actually doing anything?

I've seen some screenshots online and usually it says things like "Confirmed DL" or "Sent DL", but I just get this....

```
07:00:23: Dir /media/burst-4t/mine read in 0.000s (~309.15 GB/s)
07:00:23:        1 file (305.18 GB)
07:01:15: Block 442,341 ended in 00:00:51
07:01:15: --------------------------------------------------
07:01:15: block#         442,342
07:01:15: scoop#         2351
07:01:15: baseTarget#    113,328
07:01:15: gensig         aee5f18804fbbb26b947486d7e58977a
07:01:15:               1efce842b634fa489d637d5a532a124e
07:01:15: difficulty     161,700 (+3,184)
07:01:15: --------------------------------------------------
07:01:15: Dir /media/burst-4t/mine read in 0.000s (~284.37 GB/s)
07:01:15:        1 file (305.18 GB)
07:01:41: Block 442,342 ended in 00:00:25
07:01:41: --------------------------------------------------
07:01:41: block#         442,343
07:01:41: scoop#         473
07:01:41: baseTarget#    97,485
07:01:41: gensig         7ca29f1c748f09f3a619c252d02c9c3b
07:01:41:               65996912ce2b22dd536978fff5ad552a
07:01:41: difficulty     187,979 (+26,279)
07:01:41: --------------------------------------------------
07:01:41: Dir /media/burst-4t/mine read in 0.000s (~274.93 GB/s)
07:01:41:        1 file (305.18 GB)
07:07:22: Block 442,343 ended in 00:05:41
07:07:22: --------------------------------------------------
07:07:22: block#         442,344
07:07:22: scoop#         3153
07:07:22: baseTarget#    98,025
07:07:22: gensig         cba646f38ecccaa2ac766632c937f4c7
07:07:22:               44000bd371e35d5301e3f3f939225511
07:07:22: difficulty     186,944 (-1,035)
07:07:22: --------------------------------------------------
07:07:22: Dir /media/burst-4t/mine read in 0.000s (~251.71 GB/s)
07:07:22:        1 file (305.18 GB)
```

I'm setting my up first 4TB drive in 256GB sections.  I'm mining while plotting the second section, but expected I would at least get positive results with my first plot.  It seems like nothing is happening.

**Comment by zkdzegede** [comment]
Config file I just copied the file from https://github.com/Creepsky/creepMiner/wiki/Setting-up-the-miner

and changed these lines

```
"nonceFoundTooHigh" : true,
"plots" : [
     "/media/burst-4t/mine"
],
"targetDeadline" : "1y 1m 3d 01:20:00",
"urls" : {
    "miningInfo" : "http://fastpool.info:8080",
    "submission" : "http://fastpool.info:8080",
    "wallet" : "https://wallet3.burstnation.com:8125"
},
```

**Comment by Beddhist** [comment]
Your plot is very small by today's standards. It reads the plot file ok, but hasn't found any valid nonces yet.

You will need to be very patient.

**Comment by zkdzegede** [comment]
@Beddhist  Thanks for the reply.

I'll be patient and add some more plots a bit at a time.  

Would you say 4TB is ok by today's standards?  I plan on adding more but starting with 4TB for now

**Comment by Beddhist** [comment]
It depends on how much you want to earn. You can check it here:
http://explore.burstcoin.ro/calculators
​

**Comment by zkdzegede** [comment]
@Beddhist  
If there is no info in the list to the right here does that mean there's something wrong?
Is there anything else to check to make sure I will actually eventually find a deadline?  I haven't even submitted anything let alone a confirmation.

![screenshot 2018-01-02 22 44 18_preview](https://user-images.githubusercontent.com/2668400/34485543-9322218c-f00e-11e7-810b-491a23069d04.png)

**Comment by Beddhist** [comment]
You need to click on the blue bar to make the file names appear.

Copy the last 5 chars of your address, go to the pool page and press Ctrl-F, then paste. Can you find your address in the list?

**Comment by zkdzegede** [comment]
> You need to click on the blue bar to make the file names appear.

Thank you.  Is this sort of info written anywhere here?  I couldn't find it.

![screenshot 2018-01-03 18 14 37_preview](https://user-images.githubusercontent.com/2668400/34514770-49de98ee-f0b2-11e7-836a-60f270470f3f.png)

> Copy the last 5 chars of your address

Nothing shows up and this is the second miner I've tried
Fastpool and now pool.burst.ro

![screenshot 2018-01-03 18 14 54_preview](https://user-images.githubusercontent.com/2668400/34514777-5205b854-f0b2-11e7-94d5-c3f27eedcac6.png)

**Comment by Beddhist** [comment]
I don't think the plot files info is documented anywhere, but if you have several it becomes self-explanatory.

One thing I find strange: it seems the miner is reading your files too fast, almost as if it wasn't reading them at all. Have you plotted as root, but run the miner as a user? Permissions problem on the plot files? I would have thought creep would throw an error, but maybe it doesn't?

**Comment by zkdzegede** [comment]
You were correct.  I plotted as root and ran as user .... 👎 

However now my output doesn't have any plots marked as read...

and just as i was typing this I found a nonce!

```
05:39:15: Block 443,392 ended in 00:03:04
05:39:15: --------------------------------------------------
05:39:15: block#         443,393
05:39:15: scoop#         2854
05:39:15: baseTarget#    86,971
05:39:15: gensig         f6c4cf022850bea27a005adc8b0c888a
05:39:15:               c0c98b2435646358d4eccc913c6144b5
05:39:15: difficulty     210,704 (-3,295)
05:39:15: --------------------------------------------------
05:48:51: VJ5R-QURP-B99P-2Y6HC: nonce found (23y 8m 7d 05:55:41)                                                                                                                                                           
05:48:51:        nonce: 2,741,184
05:48:51:        in:    /media/burst-4t/mine/377350976255672439_2500000_1250000_1250000
05:48:51: ▐▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▌   6.99 % ▌ 0.03 MB/s
```

**Comment by Beddhist** [comment]
Well, yeay! 23 years.

At least now you know it's reading the files, albeit extremely slowly. How is the disk connected?

**Comment by zkdzegede** [comment]
Connected via SATA.

i am plotting and mining at the same time is that an issue?

Current setup

```
Celeron
20GB ram (16 and 4)
Total: 5 GPUs
XMR mining: 4 GPUs
Plotting: 1 GPU using gpuPlotGenerator
Mining: creepMiner --nogpu build 
SSD: 16GB connected via SATA. Holds ethoOS and no plots
HDD: 4TB connect via SATA.  Holds 900GB of plots, while plotting another 300GB
```

**Comment by zkdzegede** [comment]
> Buffer Size : 128 (128 MB)
Is this too small?

**Comment by zkdzegede** [comment]
I tried setting it to zero and it became 229MB

```
06:16:41: Logfile deactivated
06:16:41: Submission Max Retry : 5 seconds
06:16:41: Buffer Size : 0 (229 MB)
06:16:41: Submission URL : http://pool.burstcoin.ro:8080
06:16:41: Mininginfo URL : http://pool.burstcoin.ro:8080
06:16:41: Wallet URL : https://wallet.burstcoin.ro:443
06:16:41: Server URL : http://192.168.86.162:9080
06:16:41: Target deadline : 1y 1m 3d 01:20:00
06:16:41: Total plots size: 915.53 GB
06:16:41: Mining intensity : 3
06:16:41: Max plot readers : 3
06:16:41: Get mining info interval : 3 seconds
06:16:41: Processor type : CPU
06:16:41: CPU instruction set : SSE2
```

**Comment by Beddhist** [comment]
Well, of course, if the plotter writes at the same time as the miner reads... But you don't really have another option.

Creepsky suggested not setting the buffer to 128. Apparently that number has a problem. Mine is at 256 (with only 2 GB RAM. With 0 it takes what it needs, which in your case is probably good.

Does your CPU not have avx or avx2 instruction sets?

Great that it is now working! :)

**Comment by zkdzegede** [comment]
I don't know.  I'll check on the other instruction sets.  I was just trying so hard to get the default settings to work :-D 

Thanks for all the help!

**Comment by zkdzegede** [comment]
It seems my other miner has avx2 (i3), but this miner (celeron)does not.

Maybe I'll move it over to the other miner when this current plot is done. 🥇

**Comment by zkdzegede** [comment]
Workes better on the i3 with avx2 set

Thank you so much!

```
09:19:41: VJ5R-QURP-B99P-2Y6HC: nonce submitted (1m 22d 04:20:34)                                                                                                                                  
09:19:41: 	nonce: 51,188
09:19:41: 	in:    /media/burst-4t/mine/377350976255672439_0_1250000_1250000
09:19:42: VJ5R-QURP-B99P-2Y6HC: nonce confirmed (1m 22d 04:20:34)                                                                                                                                  
09:19:42: 	nonce: 51,188
09:19:42: 	in:    /media/burst-4t/mine/377350976255672439_0_1250000_1250000
~``
