### ISSUE TITLE
Server redirects to login and then "page cannot be found"

### ISSUE THREAD

**Issue by zkdzegede** [Creepsky/creepMiner#239]
CreepMiner v1.7 and v1.8

I set the server address to the IP of my rig on my local network

```
192.168.86.162:9080
```

I go to this address in chrome and it redirects to login

```
http://192.168.86.162:9080/login
```

But then I just get a page that says
```
This 192.168.86.162 page can’t be found
No webpage was found for the web address: http://192.168.86.162:9080/login
Search Google for 192 168 162 9080 log
HTTP ERROR 404
```

**Comment by loppefaaret** [comment]
make sure that the ./public/ folder in ur creepminer folder is populated correctly

**Comment by zkdzegede** [comment]
dumb mistake I didn't realize I had to run the command from the same directory as the public directory parent.  I was using a detached screen so I wasn't running the command manually anymore.

```
screen -S burst-miner -d -m /home/ethos/creepMiner/bin/creepMiner --config=/home/ethos/creepMiner.conf
```
vs
```
screen -S burst-miner -dm bash -c 'cd /home/ethos/creepMiner/bin/; ./creepMiner --config=/home/ethos/creepMiner.conf'
```

Is there a way to set the public directory in the config?
