### ISSUE TITLE
Can't read plot files

### ISSUE THREAD

**Issue by siffreinsg** [Creepsky/creepMiner#240]
Hi,
I config the miner to read in the dir D:\plots
But when I enter that in the config file :
`"plots" : [
    "D:\plots"
],`
The miner don't want to start.
So I enter that 
`"plots" : [
    "D:\\plots"
],`
And here the miner run but it detects no plots files...

Why ?

**Comment by Beddhist** [comment]
Find a site where you can check the syntax of json files. Paste your entire config file in for checking.
