### ISSUE TITLE
2.8.0: cmake throws error

### ISSUE THREAD

**Issue by Beddhist** [Creepsky/creepMiner#244]
peter@minty ~/creepMiner-2.8.0 $ cmake CMakeLists.txt -DMINIMAL_BUILD=ON
CMake Error at CMakeLists.txt:25 (include):
  include could not find load file:

    conanbuildinfo.cmake

CMake Error at CMakeLists.txt:26 (conan_basic_setup):
  Unknown CMake command "conan_basic_setup".

-- Configuring incomplete, errors occurred!
See also "/home/peter/creepMiner-2.8.0/CMakeFiles/CMakeOutput.log".

I have tried running the two install commands from https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation-with-Conan, but they, too give errors.

Reverting to 2.7.13.

**Comment by BugRoger** [comment]
Are you sure you ran both install commands? 

```
pip install conan
conan install --build=missing
```

The second command will create the missing file.

**Comment by Beddhist** [comment]
Thank you Roger.

I forgot to add: Linux Mint, 64 bit, 2 GB RAM, freshly installed. Python & Python 3 already present.

Yes, I'm sure I tried both conan commands and neither gave success. I have just re-run the one you suggested and it says that it installed the missing file. Now running make.

**Comment by Beddhist** [comment]
I got hundreds, if not thousands of warnings about comparing signed and unsigned integers. Seemed to compile ok, though, but the linking failed.
[make-error.txt](https://github.com/Creepsky/creepMiner/files/1609200/make-error.txt)

**Comment by Creepsky** [comment]
Dont worry about the warnings, they came with the new poco version. You can hide them by searching and removing `-Wall` in the CMakeLists.txt.
Use `conan install --build=missing -s compiler.libcxx=libstdc++11` and then cmake + make again.

**Comment by Beddhist** [comment]
Thanks guys! It worked. I don't know why it didn't work the first time around.

Took at least 2 hours on my low-end and busy mining machine.
