### ISSUE TITLE
Debian Documentation

### ISSUE THREAD

**Issue by ChrOst** [Creepsky/creepMiner#245]
If you use debian stretch you can just do 

```sudo apt install libpoco-dev```

to install poco.
This will install it in a clean and removeable way, without the mess the script does on a clean system.

Could you please update the Documentation? :-)
Full way to success on stretch:

```
# Execute Package installations as root using sudo
sudo apt update
sudo apt upgrade
sudo apt install build-essential git openssl libssl-dev cmake libpoco-dev
# if nvidia-cuda support is needed
apt install nvidia-cuda-toolkit

# Install miner as user
cd ~
mkdir sources
cd sources
git clone https://github.com/Creepsky/creepMiner
cd creepMiner
# for CPU + GPU:
cmake CMakeLists.txt
# for CPU only:
cmake CMakeLists.txt -DNO_GPU=ON
# for SSE2 only:
cmake CMakeLists.txt -DMINIMAL_BUILD=ON

make
```

**Comment by Creepsky** [comment]
Thanks for the clarification, I will change the wiki pages.
However the new version is using the [Conan](https://conan.io/) package manager, that is also a clean way to install the third party libs (and also works on almost every OS).

**Comment by timgkeller** [comment]
Unfortunately I can't get it working on debian stretch using this procedure. My integrated GPU supports OpenGL but not CUDA.

`# cmake CMakeLists.txt -DUSE_CUDA=OFF
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - found
-- Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found version "2.0")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tim/repos/creepMiner

# make
Scanning dependencies of target creepMiner
[  2%] Building CXX object CMakeFiles/creepMiner.dir/src/gpu/impl/gpu_cuda_impl.cpp.o
In file included from /home/user/repos/creepMiner/src/gpu/impl/gpu_cuda_impl.hpp:6:0,
                 from /home/user/repos/creepMiner/src/gpu/impl/gpu_cuda_impl.cpp:22:
/home/user/repos/creepMiner/src/mining/MinerData.hpp:27:30: fatal error: Poco/JSON/Object.h: No such file or directory
 #include <Poco/JSON/Object.h>
                              ^
compilation terminated.
CMakeFiles/creepMiner.dir/build.make:62: recipe for target 'CMakeFiles/creepMiner.dir/src/gpu/impl/gpu_cuda_impl.cpp.o' failed
make[2]: *** [CMakeFiles/creepMiner.dir/src/gpu/impl/gpu_cuda_impl.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/creepMiner.dir/all' failed
make[1]: *** [CMakeFiles/creepMiner.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by Creepsky** [comment]
Change the wiki for old releases:

Either install POCO with your package manager:
```
apt-get install libpoco-dev
```

Or if you want the latest release of POCO, run the POCO install script (it will download and install POCO for you):
```
sh ./install-poco.sh
```
