### ISSUE TITLE
Critical Crash + Config file error

### ISSUE THREAD

**Issue by Tahx** [Creepsky/creepMiner#246]
I'm trying to setup CreepMiner on my Windows Server 2016. Since I don't want the headache of compiling. I downloaded the latest windows release version.

Here is the log error file

> 05.01.2018 17:51:07 (0, E:\dev\C++\creepMiner\src\main.cpp, 121, Information): creepMiner 1.8.0 Windows x64
05.01.2018 17:51:07 (0, E:\dev\C++\creepMiner\src\main.cpp, 122, Information): Release mode -CUDA +OpenCL +SSE4 +AVX +AVX2
05.01.2018 17:51:07 (0, E:\dev\C++\creepMiner\src\main.cpp, 123, Information): ----------------------------------------------
05.01.2018 17:51:07 (0, E:\dev\C++\creepMiner\src\main.cpp, 124, Information): Github:   https://github.com/Creepsky/creepMiner
05.01.2018 17:51:07 (0, E:\dev\C++\creepMiner\src\main.cpp, 125, Information): Author:   Creepsky [creepsky@gmail.com]
05.01.2018 17:51:07 (0, E:\dev\C++\creepMiner\src\main.cpp, 126, Information): Burst :   BURST-JBKL-ZUAV-UXMB-2G795
05.01.2018 17:51:07 (0, E:\dev\C++\creepMiner\src\main.cpp, 127, Information): ----------------------------------------------
05.01.2018 17:51:07 (0, E:\dev\C++\creepMiner\src\network\Request.cpp, 67, Error): Error on sending request: SSL Exception: Failed to acquire Schannel credentials: The Local Security Authority cannot be contacted
05.01.2018 17:51:07 (0, E:\dev\C++\creepMiner\src\network\Request.cpp, 68, Error): Stackframe
main (in "E:\dev\C++\creepMiner\src\main.cpp", line 82)
Request::send(Poco::Net::HTTPRequest&) (in "E:\dev\C++\creepMiner\src\network\Request.cpp", line 56)
05.01.2018 17:51:07 (0, E:\dev\C++\creepMiner\src\main.cpp, 225, Error): Aborting program due to invalid configuration

The invalid configuration is said to be inside the plots path string which looks like this : 

`        "plots" : [
			"D:\plots\xxxxxxx"
        ],`

CreepMiner doesn't crash when the plots file isn't set.

Howewer, windows crash everytime I start creepminer.exe throwing no specific error beside "Windows has encountered a problem and will be restarted in one min"

Hope someone can help !

**Comment by Tahx** [comment]
So, well, creepMiner is crashing with the Powershell but not with the cmd.exe

I guess that's easily reproducible.

**Comment by Creepsky** [comment]
I can't reproduce it with powershell.
This is strange:
```
 05.01.2018 17:51:07 (0, E:\dev\C++\creepMiner\src\network\Request.cpp, 67, Error): Error on sending request: SSL Exception: Failed to acquire Schannel credentials: The Local Security Authority cannot be contacted
```

You need to escape the plot dirs like this: `"plots" : [ "D:\\plots\\xxxxxxx" ],` or use the Linux form: `"plots" : [ "D:/plots/xxxxxxx" ],`

I think it has something to do with the SSL error. Maybe you need to open ports or change some other security settings so the miner can communicate properly?

**Comment by Tahx** [comment]
Well now that I got creepminer working with the cmd I'll just keep using the cmd.

I'm closing this issue since it is solved.
