### ISSUE TITLE
how to start creepminer on ubuntu/linux

### ISSUE THREAD

**Issue by Oius** [Creepsky/creepMiner#251]
Hey,

Total newbie on the linux platform. 2 questions.

Where is the configuration file?
How do i start the miner?

i seemingly have it compiled and installed. [after multiple issues fixed it ran the compilation and make without problems] but with my bare knowledge about linux i dont realy know where to go from here.

any help is greatly appreciated.

**Comment by Creepsky** [comment]
Hi,
the config file is inside `bin`.
[Setting up the miner](https://github.com/Creepsky/creepMiner/wiki/Setting-up-the-miner) should help you.
Start the miner with the shell script `bin/run.sh`.

**Comment by dbeuchler** [comment]
Added some help for beginners in #254

**Comment by Oius** [comment]
hope i can add to this with just 1 more question.
where would i need to mount the plotted drives and how would i put the path in the config?
i dont quite get this part of the settings: 

> On Linux, this can get a problem, because the file tree looks different, here the partitions become the top directory of the path (/media, ~/, ...).

it's probably something stupid i missed but i keep getting these kinds of errors:

`        "plots" : [/ <-- error somewhere hereMedia,~/
        ],
`

Currently i have created the folder Media with in it the mounted hdd. this "Media" folder sits next to the creepminer folder in my user folder. if that makes any sense?

Please help.

**Comment by Creepsky** [comment]
If you are using 1.8.* please use the setup function (creepMiner - setup). It will guide you trough.
If you want to set your paths manually, put every path in `"" `, split by an `, `.

**Comment by Oius** [comment]
not currently running the development branch, so i would have to set them manualy.
where does creepminer consider to be the root directory?

**Comment by Oius** [comment]
okay, sorry for being such a noob. i seem to have finally found the plotfile. 
but now crashes on start. not really getting any info from the logfile either.
it only does this when i point it at the plotfile.

terminal says:

> timslaa@BurstMiner1:~/creepMiner/bin$ sudo sh ./run.sh
00:39:59: creepMiner 1.7.13 Unix x64
00:39:59: Release mode -CUDA -OpenCL +SSE4 +AVX +AVX2
00:39:59: ----------------------------------------------
00:39:59: Github:   https://github.com/Creepsky/creepMiner
00:39:59: Author:   Creepsky [creepsky@gmail.com]
00:39:59: Burst :   BURST-JBKL-ZUAV-UXMB-2G795
00:39:59: ----------------------------------------------
00:40:00: Logfile deactivated
00:40:00: You are running the webserver without protecting it with an username and/or password!
00:40:00: Every person with access to the webserver has FULL admin rights!
00:40:00: Submission Max Retry : 3 seconds
00:40:00: Buffer Size : 0 (466 MB)
00:40:00: Submission URL : http://burstpool.net:8124
00:40:00: Mininginfo URL : http://burstpool.net:8124
00:40:00: Wallet URL : https://wallet.burst.cryptoguru.org:8125
00:40:00: Server URL : http://192.168.0.101:8080
00:40:00: Target deadline : 15d 00:00:00
00:40:00: Total plots size: 1.82 TB
00:40:00: Mining intensity : 1
00:40:00: Max plot readers : 1
00:40:00: Get mining info interval : 3 seconds
00:40:00: Processor type : CPU
00:40:00: CPU instruction set : AUTO
00:40:00: Looking for mining info...
00:40:00: got new target deadline from pool
00:40:00:       old pool target deadline:    00:00:00
00:40:00:       new pool target deadline:    15d 00:00:00
00:40:00:       target deadline from config: 15d 00:00:00
00:40:00:       lowest target deadline:      15d 00:00:00
Segmentation fault (core dumped)

and the log says:

> 10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/main.cpp, 182, Information): creepMiner 1.7.13 Unix x64
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/main.cpp, 183, Information): Release mode -CUDA -OpenCL +SSE4 +AVX +AVX2
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/main.cpp, 184, Information): ----------------------------------------------
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/main.cpp, 185, Information): Github:   https://github.com/Creepsky/creepMiner
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/main.cpp, 186, Information): Author:   Creepsky [creepsky@gmail.com]
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/main.cpp, 187, Information): Burst :   BURST-JBKL-ZUAV-UXMB-2G795
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/main.cpp, 188, Information): ----------------------------------------------
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/mining/MinerConfig.cpp, 1510, Information): Changed logfile path to
        creepMiner_20180109_233754.834812.log
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/mining/MinerConfig.cpp, 632, Debug): Reading passphrase...
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/mining/MinerConfig.cpp, 796, Warning): You are running the webserver without protecting it with an user$
Every person with access to the webserver has FULL admin rights!
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/mining/MinerConfig.cpp, 80, Information): Submission Max Retry : 3 seconds
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/mining/MinerConfig.cpp, 139, Information): Buffer Size : 0 (466 MB)
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/mining/MinerConfig.cpp, 132, Information): Submission URL : http://burstpool.net:8124
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/mining/MinerConfig.cpp, 132, Information): Mininginfo URL : http://burstpool.net:8124
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/mining/MinerConfig.cpp, 132, Information): Wallet URL : https://wallet.burst.cryptoguru.org:8125
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/mining/MinerConfig.cpp, 132, Information): Server URL : http://192.168.0.101:8080
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/mining/MinerConfig.cpp, 1222, Information): Target deadline : 15d 00:00:00
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/mining/MinerConfig.cpp, 92, Information): Log path : creepMiner_20180109_233754.834812.log
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/mining/MinerConfig.cpp, 110, Information): Total plots size: 1.82 TB
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/mining/MinerConfig.cpp, 111, Information): Mining intensity : 1
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/mining/MinerConfig.cpp, 112, Information): Max plot readers : 1
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/mining/MinerConfig.cpp, 96, Information): Get mining info interval : 3 seconds
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/mining/MinerConfig.cpp, 98, Information): Processor type : CPU
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/mining/MinerConfig.cpp, 101, Information): CPU instruction set : AUTO
10.01.2018 00:37:54 (0, /home/timslaa/creepMiner/src/mining/Miner.cpp, 147, Information): Looking for mining info...
10.01.2018 00:37:55 (0, /home/timslaa/creepMiner/src/mining/Miner.cpp, 537, Information): got new target deadline from pool
        old pool target deadline:    00:00:00
        new pool target deadline:    15d 00:00:00
        target deadline from config: 15d 00:00:00
        lowest target deadline:      15d 00:00:00

**Comment by Beddhist** [comment]
Check your CPU's capabilities:

cat /proc/cpuinfo

If you have avx, but not avx2 try changing "cpuInstructionSet" from AUTO to avx.

If you have neither, try sse4 and sse2.

**Comment by Oius** [comment]
that did it. thanks. aparantly it crashes when trying the avx instruction set. now mining with sse4.

thanks for all the help.

**Comment by Creepsky** [comment]
I reopened the issue, because such error should not happen with the setting "auto".

**Comment by Oius** [comment]
what can i do to help?
i read a bit into the "core dump" i would have to enable to actualy be dumped. would this help?

current version: 1.7.13
running on intel nuc BOXNUC6CAYH [https://www.newegg.com/global/nl/Product/Product.aspx?Item=N82E16856102183](url)
OS: ubuntu-16.04.3-server-amd64

**Comment by PatNarciso** [comment]
CreepSuggestion: the 'quick **start** guide' should include how to **start** the miner.

**Comment by PatNarciso** [comment]
CreepSuggestion: the 'quick **start** guide' should include how to **start** the miner.
