### ISSUE TITLE
1.8.0 Problems running OpenCL under local system account

### ISSUE THREAD

**Issue by jasoncouture** [Creepsky/creepMiner#260]
I had CreepMiner configured as a windows service running as NT AUTHORITY\LOCAL SYSTEM
When CPU Mining, everything was fine. Switching to OpenCL caused the miner to have OpenCL errors and not find deadlines.
While troubleshooting the issue, I changed the windows service to use Administrator instead, and the errors go away.

Screenshots:
OpenCL Errors: 
https://cdn.discordapp.com/attachments/324092664813191170/400768256358744064/unknown.png

Service Login Configuration:
https://cdn.discordapp.com/attachments/324092664813191170/400768849521278976/unknown.png

**Comment by jasoncouture** [comment]
The issue reoccured even with the account set to Administrator
Ran in foreground, same issue.
It doesn't happen 100% of the time, it's quite random in fact.

**Comment by Beddhist** [comment]
I think this is a feature of Windows, not a bug. I just installed boinc on Windows 10 and during the install it gives you the option to run as a service under an un-privileged a/c, saying this will prevent any GPU apps from running.

This does not explain your errors in interactive mode, though.

**Comment by jasoncouture** [comment]
Yes, for a windows service to use the GPU it must use the feature "Allow service to interact with the desktop" or run as a user account so windows can allocate a user desktop. If you do this, you can use the GPU, boinc does not do this.
This is further evidenced by the fact that I can run it as a service, and make use of the GPU.

In short: As long as the service can allocate a user desktop, or local system is set to allow interaction with the desktop, you can use the GPU. The local system option is a legacy option, and is not recommended.

**Comment by nitr8** [comment]
creepMiner 1.8.0  was pulled, please use a supported version in the downloads section or if you need to be on the bleeding edge wait for 1.7.17 or build from source:

https://github.com/Creepsky/creepMiner/wiki/Compiling-from-source
