### ISSUE TITLE
Master node does not see data from slave node

### ISSUE THREAD

**Issue by kurakin-oleksandr** [Creepsky/creepMiner#261]
I use v 1.8.3 and master node does see data from slave node (no plot or nonce info). How can I check that slave node is connected correctly?

**Comment by deanhloop** [comment]
I had opened a similar issue the other day thinking it wasn't working. I ended up determining that it was, in fact, working by seeing some of my Linux mounts (slave node) showing up in the submitted nonces on my primary machine.

My understanding is that while the master node responds to the slave node each time confirming their deadlines, it only displays better-than-current-best in the console on the master node. Little difficult to see if things are actually working.

**Comment by Creepsky** [comment]
You can activate debug output and see what messages you get.
