### ISSUE TITLE
cant make 2.8.0

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [Creepsky/creepMiner#263]
CMake Error at CMakeLists.txt:25 (include):
  include could not find load file:

    conanbuildinfo.cmake

CMake Error at CMakeLists.txt:26 (conan_basic_setup):
  Unknown CMake command "conan_basic_setup".

**Comment by MrGrote** [comment]
Did you install conan before running cmake?

**Comment by vitaliy-kuzmich** [comment]
I just noticed that, it was not mentioned anywhere, I did not know what the conan is..
