### ISSUE TITLE
Linux mining

### ISSUE THREAD

**Issue by weeder** [Creepsky/creepMiner#264]
Hi all
I just want to tell my story about creepminer.
I cant get it compiled on ubuntu x64 14.04, despite all effort to install different kind of make, libpoco, or conan.
Few days ago appeared here on github a precompiled 1.8.3 creepminer.
I downloaded that and started to find out is it works or not.
Few days later i found out what makes it working.

I installed newer gcc version, bcs creepminer doesnt find a correct version of some librarie from older version:

sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-4.9 g++-4.9

Then i installed the libpoco:

sudo apt-get install libpoco-dev

After that it needed to add library path like this:

export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"

And there was no mining.conf file, so i copied there a mining.conf file from some source package.
Just writing here to show some other miners how to get it work eventually.
It is not an issue.Just few steps what needed to make it work on Ubuntu 14.04
Hope i not forget something :)
GL to all miners

**Comment by Beddhist** [comment]
Thanks for taking the time to write all this up.

Where exactly did you find the pre-compiled 1.8.3? I cannot find it.

**Comment by weeder** [comment]
It is disappeared from git.
Here is the link
https://www.dropbox.com/s/8p8x6jfzsf4vnlb/creepMiner-1.8.3-Linux.tar?dl=0

**Comment by Beddhist** [comment]
Thanks for that!
​

**Comment by lthiery** [comment]
do you get drastically decreased read speeds in Linux? I'm getting the following:
```
21:41:33: Dir /burst/burst1/6830838705850140717_14378042_7192576_7192576 read in 1.184s (~370.52 MB/s)                                               
21:41:33: 	1 file (1.71 TB)
21:41:37: Dir /burst/burst1/6830838705850140717_21567063_7192576_7192576 read in 4.988s (~88.01 MB/s)                                                
21:41:37: 	1 file (1.71 TB)
21:41:37: Dir /burst/burst2/6830838705850140717_50323147_7192576_7192576 read in 5.051s (~86.91 MB/s)                                                
21:41:37: 	1 file (1.71 TB)
21:41:38: Dir /burst/burst2/6830838705850140717_43134126_7192576_7192576 read in 5.784s (~75.89 MB/s)                                                
21:41:38: 	1 file (1.71 TB)
21:42:06: Dir /burst/burst2/6830838705850140717_28756084_7192576_7192576 read in 34.124s (~12.86 MB/s)                                               
21:42:06: 	1 file (1.71 TB)
21:42:06: Dir /burst/burst2/6830838705850140717_35945105_7192576_7192576 read in 34.181s (~12.84 MB/s)                                               
21:42:06: 	1 file (1.71 TB)
21:42:15: Dir /burst/burst1/6830838705850140717_0_7192576_7192576 read in 42.510s (~10.33 MB/s)                                                      
21:42:15: 	1 file (1.71 TB)
21:42:15: Dir /burst/burst1/6830838705850140717_7189021_7192576_7192576 read in 43.115s (~10.18 MB/s)  ```

**Comment by weeder** [comment]
Mine works normally 
06.02.2018 07:41:53  /plots/ read in 5.424s (~78.16 MB/s)	1 file (1.66 TB)
sometime it is weird
06.02.2018 08:04:03  /plots/ read in 0.153s (~2.69 GB/s) 	1 file (1.66 TB)
