### ISSUE TITLE
Linking CXX executable bin/creepMiner error 

### ISSUE THREAD

**Issue by zezaocapoeira** [Creepsky/creepMiner#265]
Hello.

(sorry bad english)

I'm testing the development branch, in Slackware64-14.2.

The command line I had to use this way:

In the instructions it says:
`$ conan install -s compiler.libcxx=libstdc++11 --build=missing`

To work here:

`$ conan install . -s compiler.libcxx=libstdc++11 --build=missing`

After this step:

`$ cmake CMakeLists.txt -DNO_GPU=ON`

Concludes the process normally

The problem is that it does not finish compiling the binary:

$ `make`

I'll attach the log.
[make-creepminer-dev.log](https://github.com/Creepsky/creepMiner/files/1636435/make-creepminer-dev.log)

Thanks for listening.

**Comment by Creepsky** [comment]
Hi,

please test with the latest release (1.7.16).
Try `conan install . --build=missing` instead if its still failing. Read the conan docs, there are a lot of flags and switches you can customize to make it work on your system: http://docs.conan.io/en/latest/getting_started.html#building-with-other-configurations.
Reopen this issue if needed.
