### ISSUE TITLE
Cannot compile since 1.8.0 on Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-78-generic i686)

### ISSUE THREAD

**Issue by HiFish8472** [Creepsky/creepMiner#266]
Following the Debian / Linux unstructions leaves me stuck after
cmake CMakeLists.txt -DNO_GPU=ON

with the following error:
CMake Error at CMakeLists.txt:47 (include):
  include could not find load file:

    conanbuildinfo.cmake

CMake Error at CMakeLists.txt:50 (conan_basic_setup):
  Unknown CMake command "conan_basic_setup".

i googled a bit to figure out what "conan" is, but could not figure out a package that might install it on my system. Am i doing something wrong or is 32bit environment just not supported? 

I am currently running Version 1.7.13 which compiled succesfully without asking for any barbarians...

**Comment by Beddhist** [comment]
Get your barbarian here: https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation-with-Conan

**Comment by HiFish8472** [comment]
Thank you! I got a bit farther, the Barbarians are still elusive. The basic install of conan is working, but i get the following when running 
`conan install --build=missing -s compiler.libcxx=libstdc++11 `
conan install: error: too few arguments
ERROR: Exiting with code: 2

after this i get the original error witth cmake. I tried this on my i686 system and on a  bannana pi runing ubuntu mate 16.04, witht the same result. Maybe there is a typo in the command?

**Comment by HiFish8472** [comment]
PS: i got the notice `You are using pip version 8.1.1, however version 9.0.1 is available.`
so i tried with both versions with same result.

**Comment by Beddhist** [comment]
I couldn't upgrade pip, it went around in circles. Sorry, can't help you further, the conan install worked for me the 2nd time round. Perhaps just try again?

**Comment by HiFish8472** [comment]
I did, so far no luck. Maybe i will set up a different box with regular fresh x64 Ubuntu to see if its working there. To clarify: The `error: too few arguments` happens regardless of pip-version (bananpi had 7.x, x86 PC had 8.1.1, updated both to 9.0.1). I guess i did not get the Barbarian i was looking for...

**Comment by PatNarciso** [comment]
*following* 
I saw this thread in my email, I wanted to jump on board and provide swift feedback.

I too am unable to compile from a fresh x64 ubuntu install.  also Ubuntu related -- the last time I checked, 'apt-get remove' 'apt-get purge' failed.  from what I recall, it had issue with the db_ remove section.  This was important when I was trying to troubleshoot my setup, and wanted a full 'purge'. 

(I get apt-get is not a compile... I was trying many options in attempts to get this working, including other linux flavors.  Important note if this is your first time: run from a desktop cli, not a base-install non-desktop cli).

**Comment by Creepsky** [comment]
Conan got an update, the syntax now is: `conan . install --build=missing -s compiler.libcxx=libstdc++11`

**Comment by HiFish8472** [comment]
Thank you for the reply. This leads to `ERROR: Unknown command '.'`  Maybe the github-formating breaks the syntax? I cant see a difference to the command above besides the dot before `install`.

**Comment by Creepsky** [comment]
Im sorry, it's `conan install . --build=missing -s compiler.libcxx=libstdc++11`, my fault.

**Comment by HiFish8472** [comment]
Thank you, it worked!
