### ISSUE TITLE
1.8.0 incorrect log levels

### ISSUE THREAD

**Issue by Beddhist** [Creepsky/creepMiner#267]
Some excerpts from my log:

18.01.2018 16:06:38 (0, /home/peter/creepMiner-2.8.0/src/main.cpp, 127, Information): ----------------------------------------------
18.01.2018 16:06:39 (0, /home/peter/creepMiner-2.8.0/src/mining/MinerConfig.cpp, 1500, Information): Changed logfile path to
        /home/peter/creepMiner_20180118_030638.879076.log
18.01.2018 16:06:39 (0, /home/peter/creepMiner-2.8.0/src/mining/MinerConfig.cpp, 646, Debug): Reading passphrase...

18.01.2018 16:06:40 (0, /home/peter/creepMiner-2.8.0/src/wallet/Account.cpp, 239, Debug): Cached accounts: 1
18.01.2018 16:06:40 (25, /home/peter/creepMiner-2.8.0/src/wallet/Wallet.cpp, 227, Debug): Sending wallet request '/burst?requestType=getAccount&account=180

18.01.2018 16:06:41 (2, /home/peter/creepMiner-2.8.0/src/webserver/MinerServer.cpp, 276, Debug): Request: /
18.01.2018 16:06:41 (2, /home/peter/creepMiner-2.8.0/src/webserver/MinerServer.cpp, 277, Information): Request: /

18.01.2018 16:06:43 (5, /home/peter/creepMiner-2.8.0/src/network/NonceSubmitter.cpp, 124, Debug): JSON confirmation (2m 5d 01:32:39)
        { "result" : "success", "deadline" : 5621559, "deadlineText" : "2m 5d 01:32:39" }

Please note that all log levels are set to Notice or higher, Yet I keep getting lots of Information and Debug. The web server, in particular, fills the log with debug junk.

Question: what values can I put in here:

"outputType" : "terminal"

**Comment by Creepsky** [comment]
The log level for the **logfile** is always **trace**.
The log levels for the **miner** are the settings from your **config file**.
The log levels for the **webinterface** are the settings from the webinterface (bottom right on the main page).

"outputType" can be "terminal" or "service".

**Comment by Beddhist** [comment]
Ok, I'm running it as a service, so no console. Here is my .conf:

----------------------------------------------------------------
{
    "logging" : {
        "config" : "notice",
        "general" : "notice",
        "logfile" : true,
        "miner" : "notice",
        "nonceSubmitter" : "notice",
        "output" : {
            "dirDone" : true,
            "lastWinner" : false,
            "nonceConfirmed" : true,
            "nonceFound" : true,
            "nonceFoundTooHigh" : false,
            "nonceSent" : true,
            "plotDone" : false
        },
        "outputType" : "terminal",
        "path" : "/home/peter",
        "plotReader" : "notice",
        "plotVerifier" : "notice",
        "progressBar" : {
            "fancy" : false,
            "steady" : false
        },
        "server" : "warning",
        "session" : "warning",
        "socket" : "error",
        "useColors" : true,
        "wallet" : "error"
    },
---------------------------------------------------
And this is from the web server:
![image](https://user-images.githubusercontent.com/11470181/35165469-4940ac7a-fdb3-11e7-98fb-cb04e8ff6c63.png)

Is the output what you expect from the config?
Is there any way to quieten the log file, because it's quite unreadable.

Thanks for your time.

**Comment by Creepsky** [comment]
The logfile looks ok. Can't say if it's okay for the miner and webinterface.
If this is still true: `The web server, in particular, fills the log with debug junk.`, there is a bug in the webinterface and I have to fix it (please give me exact informations on how to reproduce the issue).

You can disable the logfile in the config file. Actually it was never meant for the user, it is mainly there to make my life easier. What exactly are you searching for in the logfile, maybe I can help.

**Comment by Beddhist** [comment]
I'm not searching for anything in particular, but since I don't have a
console I would like to be able to check and see what it's doing, in case I
suspect something is not working right. I guess it's more a peace-of-mind
thing. Normally, I rely on the web i/f.

This is the "debug junk":

----------------------------------------------------
​18.01.2018 16:06:41 (2,
/home/peter/creepMiner-2.8.0/src/webserver/MinerServer.cpp, 276, Debug):
Request: /
18.01.2018 16:06:41 (2,
/home/peter/creepMiner-2.8.0/src/webserver/MinerServer.cpp, 277,
Information): Request: /
Ip: 192.168.1.136:55560
Method: GET
Host:minty:8080
Connection:keep-alive
Cache-Control:max-age=0
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Upgrade-Insecure-Requests:1
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
DNT:1
Referer:http://minty:8080/plotfiles
Accept-Encoding:gzip, deflate
Accept-Language:en-GB,en;q=0.9,en-US;q=0.8,de;q=0.7,fr;q=0.6

18.01.2018 16:06:41 (6, /home/peter/creepMiner-2.8.0/src/mining/Miner.cpp,
423, Information): ZFNS-3W9J-V5SG-HSKYP: nonce found (28y 0m 6d 05:28:40)
        nonce: 4,445,083
        in:    /mnt/WD4TB/plots/18084828890988000920_4400000_1600000_6400
18.01.2018 16:06:41 (2,
/home/peter/creepMiner-2.8.0/src/webserver/MinerServer.cpp, 276, Debug):
Request: /css/cerulean.min.css
18.01.2018 16:06:41 (2,
/home/peter/creepMiner-2.8.0/src/webserver/MinerServer.cpp, 277,
Information): Request: /css/cerulean.min.css
Ip: 192.168.1.136:55560
Method: GET
Host:minty:8080
Connection:keep-alive
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Accept:text/css,*/*;q=0.1
DNT:1
Referer:http://minty:8080/
Accept-Encoding:gzip, deflate
Accept-Language:en-GB,en;q=0.9,en-US;q=0.8,de;q=0.7,fr;q=0.6

18.01.2018 16:06:41 (3,
/home/peter/creepMiner-2.8.0/src/webserver/MinerServer.cpp, 276, Debug):
Request: /css/creepMiner.css
18.01.2018 16:06:41 (3,
/home/peter/creepMiner-2.8.0/src/webserver/MinerServer.cpp, 277,
Information): Request: /css/creepMiner.css
Ip: 192.168.1.136:55561
Method: GET
Host:minty:8080
Connection:keep-alive
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Accept:text/css,*/*;q=0.1
DNT:1
Referer:http://minty:8080/
Accept-Encoding:gzip, deflate
Accept-Language:en-GB,en;q=0.9,en-US;q=0.8,de;q=0.7,fr;q=0.6

**Comment by nitr8** [comment]
logging is trace - there is an enhancment request #320 & #316 I only use logfile as I dont use the interface either.  

I will write a article on how to use frontail with creep - check it out in the meantime https://github.com/mthenw/frontail

<img width="1442" alt="frontail" src="https://user-images.githubusercontent.com/541890/37255104-eb8bfe24-2547-11e8-97c4-25c8cbfed7e9.png">

 Here is a json for syntax for highlighting creep specific:

```
{
    "words": {
        "ERROR": "color: #E88D67;",
        "Error": "color: #E88D67;",
        "WARN": "color: yellow;",
        "INFO": "color: #99C5B5;",
        "Node is DEAD": "color: #E88D67;",
        "Nonce forward request": "color: yellow;",
        "Got nonce forward request": "color: yellow;",
        "nonce forward request from remote miner": "color: yellow;",
        "success": "font-weight: bold;color: green;",
        "deadlineText": "font-weight: bold;color: green;",
        "ended in": "font-weight: bold;color:#70389c;",
        "Sending wallet request": "color: yellow;",
        "Processed block": "color: yellow;color: #99C5B5;",
        "Ip": "color: yellow;color: #99C5B5;",
        "in:    ": "color: #2fa4e7;",
        "Submit-loop 1": "color: #468847;",
        "Submit-loop 2": "color: #468847;",
        "Submit-loop ": "color: yellow;",
        "ItemStateChangedEvent": "font-weight: bold;"
    },
    "lines": {
        "ERROR": "font-weight: bold;",
        "Error": "font-weight: bold;",
        "block#": "color: #99C5B5;",
        "scoop#": "color: #99C5B5;",
        "baseTarget#": "color: #99C5B5;",
        "nonce: ": "color: #2fa4e7;",
        "nonce found": "color: #73a839;",
        "nonce submitted": "color: #468847;",
        "JSON confirmation": "color: #468847;",
        "nonce confirmed": "color: green;font-weight: bold;",
        "requestType=getMiningInfo": "color: black;"
    }
}
```
