### ISSUE TITLE
Documentation: run as a service under Linux

### ISSUE THREAD

**Issue by Beddhist** [Creepsky/creepMiner#268]
This applies to Ubuntu, Mint and possibly Debian, using systemd.

As root create the file

/etc/systemd/system/creepminer.service

---------------- Contents: -------------------
[Unit]
Description=CreepMiner
After=network.target

[Service]
Type=simple
User=<your linux username>
ExecStart=<path to your creepminer executable>
WorkingDirectory=<path to your creepminer>
Restart=on-abort

[Install]
WantedBy=multi-user.target
---------------------- EoF -----------------------

after creating that file enter on the command line:
systemctl enable creepminer
systemctl start creepminer

I can't remember where I found this, but it works for me. Creep now starts on boot and with either systemctl or service commands you can control it.

@Creepsky: can you add that to the wiki?

Thanks for a great program.

**Comment by Creepsky** [comment]
Added: https://github.com/Creepsky/creepMiner/wiki/Run-as-a-service-under-Linux
Thank you for this tutorial :)
