### ISSUE TITLE
cannot compile on Banana Pi M2 Berry with ubuntu 16.04.03 LTS (mate) , Raspbian 8 (jessie) or ubuntu 16.04.04 (server)

### ISSUE THREAD

**Issue by HiFish8472** [Creepsky/creepMiner#271]
I was following the Guides for Debian and Raspberry Pi. Using the newest OS-Image i found for the Banana-Pi and the creepminer availble from GIT (1.7.3?) 
System Version:
`LSB Version:	core-9.20160110ubuntu0.2-armhf:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-armhf:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial`

i used  cmake `CMakeLists.txt -DMINIMAL_BUILD=ON` after editing march=native as requested in the guide. Everything runs smooth till the end of make:
`[ 94%] Building CXX object CMakeFiles/creepMiner.dir/src/MinerUtil.cpp.o
[ 97%] Building CXX object CMakeFiles/creepMiner.dir/src/logging/Performance.cpp.o
[100%] Linking CXX executable bin/creepMiner
/usr/bin/ld: CMakeFiles/creepMiner.dir/src/logging/channels/ColoredPriorityConsoleChannel.cpp.o: undefined reference to symbol '__stack_chk_fail@@GLIBC_2.4'
//lib/arm-linux-gnueabihf/libc.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/creepMiner.dir/build.make:952: recipe for target 'bin/creepMiner' failed
make[2]: *** [bin/creepMiner] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/creepMiner.dir/all' failed
make[1]: *** [CMakeFiles/creepMiner.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`
Everything is working fine on an old first generation banana pi running raspian 8.0 "jessie".
I am thankful for any advice on how to proceed. I am hesitant to clone the OS from the old Banana Pi, because this will most like turn into a headache (f.e. the old one doesn't have wifi).

**Comment by HiFish8472** [comment]
I did a comple reinstall with a different image "Raspbian 8 (jessie)". After following all the steps i get a similar error:
`[100%] Linking CXX executable bin/creepMiner
/usr/bin/ld: CMakeFiles/creepMiner.dir/src/nxt/nxt_address.cpp.o: undefined reference to symbol 'sprintf@@GLIBC_2.4'
//lib/arm-linux-gnueabihf/libc.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/creepMiner.dir/build.make:952: recipe for target 'bin/creepMiner' failed
make[2]: *** [bin/creepMiner] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/creepMiner.dir/all' failed
make[1]: *** [CMakeFiles/creepMiner.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`
could this be something specific to the m2 berry with glibc?

**Comment by darbs** [comment]
Not sure this would help you or not but i successfully have creepMiner running on ubuntu mate following the debian instructions. I did not follow the gpu section nor did i change the native flag.

**Comment by HiFish8472** [comment]
Sadly not. I had no trouble running it on a Raspberry Pi 1 or a Banana Pi 1.
Today i started from scratch wit the image 
`2018-01-15-ubuntu-16.04-server-v1.0-bpi-m2u-sd-emmc.img`
I switched to develompement branch as suggested in an other issue and used the conan-installation. Everything works find till the end, were i end up again with a slightly different glibc-error:
`undefined reference to symbol 'fflush@@GLIBC_2.4 //lib/arm-linux-gnuabihf/libc.so.6: error adding symbols: DSO missing from command line collect2: error: ld returned 1 exit status`
this is on Linux Version 3.10.108-BPI-M2U-Kernel (root@bpi-iot-ros-ai) (gcc version 5.4.0 20160609 ...)
I am hopefull for some suggestion at what to try next...

**Comment by darbs** [comment]
Have you tried ubuntu mate instead of ubuntu server? Its build specifically for raspberry pi 3, also im building off master not develop so there may be some changes that arent quite working

**Comment by HiFish8472** [comment]
I tried Mate, Server and Raspian, and all with both the development and master branch. It always ends with a (slightly varied) error in GLIBC_2.4 after compiling (make) to 100%. I had no issues on a raspberry v1 or bananapi v1.

**Comment by Creepsky** [comment]
If you want help with your compilation, contact me on discord (I won't do this for free, because it can take some hours).
