### ISSUE TITLE
The plotfile is incomplete!

### ISSUE THREAD

**Issue by utmuk** [Creepsky/creepMiner#272]
CreepMiner gives me this error and skips the plot. BlagoMiner doesn't show any error on that plot.

**Comment by utmuk** [comment]
I also recreated it. Everything should be fine, but...

**Comment by Creepsky** [comment]
What is your creepminer version, os, plotting application, hard drive type, ..........? Please give me something can work with :)

**Comment by utmuk** [comment]
Sure :) It's creepMiner-win64-1.8.0 for Windows from here - https://github.com/Creepsky/creepMiner/releases. Plotting application is latest Xplotter from QBundle. Hard drive is a usual drive 500 GB. I started creepminer and closed it and took the fresh log. Here it is - https://yadi.sk/d/1yBW3jDz3RcaRy

**Comment by Creepsky** [comment]
Quick and dirty fix: use `"mining": { "useInsecurePlotfiles": true, ... }`

**Comment by utmuk** [comment]
Ok, the error message gone. But is the plot OK ?

**Comment by Creepsky** [comment]
You can validate your plotfile with the Burst PlotsChecker tool.

**Comment by utmuk** [comment]
It says all files are OK. I am not sure how it checks though)

**Comment by Creepsky** [comment]
I will close this issue now. 
You may want to switch to 1.7.16 (I removed 1.8).
