### ISSUE TITLE
creepMiner 2.8.3 / 1.8.3 Unix x32 - Setup behavior

### ISSUE THREAD

**Issue by HiFish8472** [Creepsky/creepMiner#273]
After successfully compiling the new version i wanted to test the new setup feature, i ran into some unexpected behavior which may be a bug or user error:
- on  Option "Everything" everything seems to be fine until i am asked to enter the URI. This always gives me a "no connection"-Error, no matter what i enter. I could not figure out how to skip this step, only way out seemed to be STRG+C, which breaks of the setup without writing the changes as far as i noticed.
- on all the indivudal option the miner starts mining after the option was set
- on the options 4 (buffer size) and 5 (Plotreader/verifier) it imideatly skips to running the miner without the possibility to enter any further selection. Those steps work when running "everything".

Besides that, everything is running fine after i manually edited the mining.conf to add the URL.

**Comment by Creepsky** [comment]
Thank you for the feedback. 1.8.* (development-branch) is still in development and not for production use. Please use the master branch instead.
