### ISSUE TITLE
Update Wiki Forwarding section

### ISSUE THREAD

**Issue by Have-a-question-about-this-project** [Creepsky/creepMiner#274]
It refers to what appears to be old setting names, e.g. "poolUrl" which I assume has been replaced by "submission".
No example of usage of forwardUrls.

**Comment by Creepsky** [comment]
https://github.com/Creepsky/creepMiner/wiki/Forwarding :white_check_mark:
https://github.com/Creepsky/creepMiner/wiki/Setting-up-the-miner#forwardurls :white_check_mark:
