### ISSUE TITLE
web interface doesn't list plot files

### ISSUE THREAD

**Issue by Have-a-question-about-this-project** [Creepsky/creepMiner#275]
Running on windows 10.
My plots are on CIFS/samba share paths - this may be causing it to not work.
E.g.  \\nuc\e\Burstcoin
![image](https://user-images.githubusercontent.com/35617009/35178751-415339c0-fd85-11e7-8bad-3edc4259f3ba.png)

**Comment by Creepsky** [comment]
For the future-me: https://github.com/Creepsky/creepMiner/blob/master/bin/public/js/plotfiles.js#L91

**Comment by Have-a-question-about-this-project** [comment]
I've just realised that if I select a dir on the left it does show the files, but just for that dir.
I was expecting it to show a list of all plot files found on all dirs when no dir is selected.
