### ISSUE TITLE
Forwarding when DNS resolves to ipv6 address

### ISSUE THREAD

**Issue by Have-a-question-about-this-project** [Creepsky/creepMiner#279]
creepMiner 1.8.0 Windows x64

Windows 10 has ipv6 enabled on interfaces by default.
If I set the pool + submission URLs to a hostname on my local network for forwarding, e.g. http://host:8080, it fails to connect.
If I ping the hostname I see it pinging after resolving to an ipv6 address.

If I disable ipv6 on my network interfaces pinging the hostname resolves to an ipv4 address and creepMiner forwarding starts working.

**Comment by nitr8** [comment]
This is down to OS, nothing to do with miner.

Going ahead and closing this case: workaround "disable IPv6"
