### ISSUE TITLE
missed rounds

### ISSUE THREAD

**Issue by loppefaaret** [Creepsky/creepMiner#281]
would it be possible to add a line under the highscores that shows how many rounds you've not had a confirmed DL in ?

**Comment by GoodbyeWorld** [comment]
that sounds like a nice feature!  In addition, I'd love to see the number of rounds where the round ends before I finish reading all my plots.  

When the round ends before your plots are all read, I assume you are missing out on submitting DLs to your pool.

**Comment by nitr8** [comment]
closing, the new multi-setup requirements will make this obsolete
