### ISSUE TITLE
Issue during setup step "How to set the plotreader/-verifier?"

### ISSUE THREAD

**Issue by timgkeller** [Creepsky/creepMiner#282]
Version: 2.8.0
OS: Debian 9
Processor: Intel Celeron J1900
Error message:

18:43:10: Your CPU has 4 cores
18:43:10: How to set the plotreader/-verifier?
18:43:10: [      1]: Auto <--
18:43:10: [      2]: Manual
18:43:10: [ Escape]: Exit
18:43:10: [  Enter]: Use the default value (Auto)
18:43:10: Your choice: Auto
18:43:17: Performing tests, please wait...
18:43:23: Dir /plots/disk_1/plots read in 6.261s (~46.88 MB/s)
18:43:23:       1 file (1.15 TB)
18:43:40: 1 reader, 1 verifier, time: 23.448570s
18:43:44: Dir /plots/disk_1/plots read in 3.409s (~86.09 MB/s)
18:43:44:       1 file (1.15 TB)
18:44:01: 1 reader, 2 verifier, time: 20.294045s
Beignet: "CL object 0x7f4480001410, call destroy with a reference -1"
creepMiner: ../../intel/intel_bufmgr_gem.c:1431: drm_intel_gem_bo_unreference: Assertion `atomic_read(&bo_gem->refcount) > 0' failed.
creepMiner: /build/beignet-1.3.0/src/cl_base_object.c:42: cl_object_destroy_base: Assertion `0' failed.
Aborted

**Comment by Creepsky** [comment]
Use Manual and set the verifier to 1. Your integrated GPU can't run more than 1 instance.
