### ISSUE TITLE
got no confirmation from server! busy?

### ISSUE THREAD

**Issue by timgkeller** [Creepsky/creepMiner#283]
Version: 2.8.0
OS: Debian 9

19:29:14: Dir /plots/disk_1 read in 4.016s (~73.08 MB/s)
19:29:14:       1 file (1.15 TB)
19:29:17: Wallet: nonce found (1m 18d 00:53:26)
19:29:17:       nonce: 4,254,360
19:29:17:       in:    /plots/disk_1/12374030639820508813_0_4809000_4809000
19:29:17: Processed block 450,646
19:29:17:       round time:     6.817s
19:29:17:       best deadline:  1m 18d 00:53:26
19:29:17: Wallet: nonce submitted (1m 18d 00:53:26)
19:29:17:       nonce: 4,254,360
19:29:17:       in:    /plots/disk_1/12374030639820508813_0_4809000_4809000
19:29:45: Wallet: got no confirmation from server! busy? (1m 18d 00:53:26)

This is happening with all my deadlines. This is the config I am using:

"urls" : {
  "miningInfo" : "http://50-50-pool.burst.cryptoguru.org:8124",
  "submission" : "http://50-50-pool.burst.cryptoguru.org:8124",
  "wallet" : "https://wallet.burstcoin.ro"
}

Any suggestion how to debug this issue?

**Comment by Creepsky** [comment]
Are you sure you have the right mining info and submission url?

**Comment by timgkeller** [comment]
Pretty sure: https://50-50-pool.burst.cryptoguru.org/ under Info tab

> Download and run miner
> Download miner creepMiner
> Edit mining.conf: set poolUrl and miningInfoUrl to 50-50-pool.burst.cryptoguru.org:8124
> Run miner

**Comment by timgkeller** [comment]
When I configure the connection using the -s option, I also get an error:

20:12:33: Mininginfo
20:12:33: URI: 50-50-pool.burst.cryptoguru.org:8124
20:12:48: Testing the connection...
20:12:48: http://50-50-pool.burst.cryptoguru.org:8124: ok
20:12:48: Submission
20:12:48: Testing the connection...
20:12:48: No connection!

I can ping 50-50-pool.burst.cryptoguru.org just fine:

$ ping 50-50-pool.burst.cryptoguru.org
PING 50-50-pool.burst.cryptoguru.org (78.46.172.170) 56(84) bytes of data.
64 bytes from burst.cryptoguru.org (78.46.172.170): icmp_seq=1 ttl=49 time=26.6 ms
64 bytes from burst.cryptoguru.org (78.46.172.170): icmp_seq=2 ttl=49 time=27.8 ms
64 bytes from burst.cryptoguru.org (78.46.172.170): icmp_seq=3 ttl=49 time=24.1 ms

**Comment by timgkeller** [comment]
Could this issue be due to a defective plot? I now changed the pool url of miner A to another miner B  running creepMiner (as a forwarder) and now the deadlines of miner A are confirmed. But once miner B submits those deadlines to 50-50-pool.burst.cryptoguru.org the same issue occurs. The deadlines found by miner B however, are confirmed just fine.

**Comment by timgkeller** [comment]
Ok, must have been due to a defective plot. I replotted and it works now.
