### ISSUE TITLE
c++: error: unrecognized command line option ‘-std=c++14’

### ISSUE THREAD

**Issue by aotto1968** [Creepsky/creepMiner#284]
What next ??

> ~/burst/creepMiner> cmake CMakeLists.txt -DCMAKE_BUILD_TYPE=RELEASE -DMINIMAL_BUILD=ON
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: XXX/burst/creepMiner

> ~/burst/creepMiner> make
Scanning dependencies of target creepMiner
[  2%] Building CXX object CMakeFiles/creepMiner.dir/src/gpu/impl/gpu_cuda_impl.cpp.o
c++: error: unrecognized command line option ‘-std=c++14’
CMakeFiles/creepMiner.dir/build.make:62: recipe for target 'CMakeFiles/creepMiner.dir/src/gpu/impl/gpu_cuda_impl.cpp.o' failed
make[2]: *** [CMakeFiles/creepMiner.dir/src/gpu/impl/gpu_cuda_impl.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/creepMiner.dir/all' failed
make[1]: *** [CMakeFiles/creepMiner.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Creepsky** [comment]
update your gcc

**Comment by aotto1968** [comment]
not so fast…

cmake CMakeLists.txt -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_BUILD_TYPE=RELEASE -DMINIMAL_BUILD=ON...

works, but…

1) why ccmake does not check the compiler to be… the right one… (g++-5…) ?

**Comment by Creepsky** [comment]
Good question, you can ask them here: https://gitlab.kitware.com/cmake/cmake/issues.
