### ISSUE TITLE
I have no glue how to use this SW

### ISSUE THREAD

**Issue by aotto1968** [Creepsky/creepMiner#285]
1) where I can setup a mining-pool URL ?
 → any mining-pool to recommend ?
2) where I can setup my wallet-adress für solo mining ?
 → any online-wallet to recommend ?
3) I have 3 empty shares 2x100G 1x500G… how to setup the "pools"

just some question … as introduction :-)

**Comment by Creepsky** [comment]
As this is only the page for the miner I can't give you recommendations regards the pool and wallet you have to choose.
But there are several forums and other Burst related pages that can give you useful informations about these topics, https://www.burst-coin.org for example to just call one.

2. please don't use online wallets for solo mining - download the wallet and run it locally on your machine.
3. not sure if I understood your question, but you have to plot your drives before you can "feed" them to your miner.

Again: this is only the miner page - I think the informations you seek are on different places :)
