### ISSUE TITLE
CreepMiner hangs with error

### ISSUE THREAD

**Issue by similar75** [Creepsky/creepMiner#286]
Sometimes CreepMiner hangs during plot reads.
The error  (in console):

Could not send the data to the websocket!
data: {"type":"progress","value":92.37652,"valueVerification":84.55619}

Values are different. If i not use web interface it works for weeks.
I think that CreepMiner is not notified for 'logoff' event and this error must be non-fatal.

This happens with master branch (1.7.x) and with dev (1.8.x) version.

**Comment by Creepsky** [comment]
Please check the latest release 1.7.16.
Re-open the issue if it still fails.
