### ISSUE TITLE
Allow to query webinterface for more information on miner

### ISSUE THREAD

**Issue by jboadas** [Creepsky/creepMiner#289]
You can use:
`http://192.168.0.1:8080/burst?requestType=getMiningInfo`
and get info about.
baseTarget
generationSignature
height
targetDeadline

But you cannot get information about:
Plotsize
Buffersize
Won blocks
Mined blocks
etc.

**Comment by Creepsky** [comment]
You can alternatively connect a websocket to the webserver and listen for a "config" message, like done [here](https://github.com/Creepsky/creepMiner/blob/master/bin/public/js/block.js#L628) and [here](https://github.com/Creepsky/creepMiner/blob/master/bin/public/js/block.js#L422).

But I like the idea and will probably add something like `GET /api?type=settings`. That will return a JSON representation of the current settings.

**Comment by jboadas** [comment]
Nice thanks

**Comment by nitr8** [comment]
all done - check it out in 1.8.0

**Comment by jboadas** [comment]
Hello have any documentation about the api ?

Thanks.
