### ISSUE TITLE
cannot get miner to install on Ubuntu 16.04.3 

### ISSUE THREAD

**Issue by roadh0use** [Creepsky/creepMiner#295]
Hello,
Ive tried installing the .deb and it says successful and its installed. however it does not appear in home directory.
Tried following building from source but when I get to the last step with make i get this:

~/creepMiner# make
[  2%] Building NVCC (Device) object CMakeFiles/creepMiner.dir/src/shabal/cuda/creepMiner_generated_Shabal.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_60'
CMake Error at creepMiner_generated_Shabal.cu.o.cmake:209 (message):
  Error generating
  /root/creepMiner/CMakeFiles/creepMiner.dir/src/shabal/cuda/./creepMiner_generated_Shabal.cu.o

CMakeFiles/creepMiner.dir/build.make:63: recipe for target 'CMakeFiles/creepMiner.dir/src/shabal/cuda/creepMiner_generated_Shabal.cu.o' failed
make[2]: *** [CMakeFiles/creepMiner.dir/src/shabal/cuda/creepMiner_generated_Shabal.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/creepMiner.dir/all' failed
make[1]: *** [CMakeFiles/creepMiner.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

any ideas?

**Comment by Creepsky** [comment]
It is in /opt/creepMiner-{version}
