### ISSUE TITLE
Miner hangs after some hours

### ISSUE THREAD

**Issue by timgkeller** [Creepsky/creepMiner#296]
Version: creepMiner-2.8.0
OS: Debian 9
CPU: Intel(R) Atom(TM) CPU N2800 (Minimal Build)

I am having an issue that the miner just hangs after some hours. The timeframe is always different but it hasn't run continuously for more than 24h at a time.

The process doesn't stop when this happens, so unfortunately I can't restart it in such cases. The webserver is just not responding anymore and no deadlines are submitted. The clients that are submitting to this instance get no response either, when they try to reach the server.

The logs (default loglevel) do not offer any insights into why this is happening. Do you have any suggestion what I could do to debug this issue?

FYI, this is my _mining.conf_:
{
	"logging" : {
		"config" : "information",
		"general" : "information",
		"logfile" : true,
		"miner" : "information",
		"nonceSubmitter" : "information",
		"output" : {
			"dirDone" : true,
			"lastWinner" : true,
			"nonceConfirmed" : true,
			"nonceFound" : true,
			"nonceFoundTooHigh" : false,
			"nonceSent" : true,
			"plotDone" : false
		},
		"outputType" : "service",
		"path" : "/home/user/creepMiner-2.8.0/log/",
		"plotReader" : "information",
		"plotVerifier" : "information",
		"progressBar" : {
			"fancy" : false,
			"steady" : false
		},
		"server" : "fatal",
		"session" : "error",
		"socket" : "off",
		"useColors" : true,
		"wallet" : "fatal"
	},
	"mining" : {
		"benchmark" : {
			"active" : false,
			"interval" : 60
		},
		"bufferChunkCount" : 8,
		"cpuInstructionSet" : "SSE2",
		"getMiningInfoInterval" : 3,
		"gpuDevice" : 0,
		"gpuPlatform" : 0,
		"intensity" : 2,
		"maxBufferSizeMB" : 408,
		"maxPlotReaders" : 1,
		"passphrase" : {
			"algorithm" : "aes-256-cbc",
			"decrypted" : "",
			"deleteKey" : false,
			"encrypted" : "",
			"iterations" : 1000,
			"key" : "",
			"salt" : ""
		},
		"plots" : [
			"/data/plots"
		],
		"processorType" : "CPU",
		"rescanEveryBlock" : false,
		"submissionMaxRetry" : 3,
		"targetDeadline" : "1y 0m 5d 00:00:00",
		"timeout" : 30,
		"urls" : {
			"miningInfo" : "http://50-50-pool.burst.cryptoguru.org:8124",
			"submission" : "http://50-50-pool.burst.cryptoguru.org:8124",
			"wallet" : "https://wallet.burstcoin.ro"
		},
		"useInsecurePlotfiles" : false,
		"wakeUpTime" : 0,
		"walletRequestRetryWaitTime" : 3,
		"walletRequestTries" : 5
	},
	"webserver" : {
		"activeConnections" : 8,
		"calculateEveryDeadline" : false,
		"connectionQueue" : 64,
		"credentials" : {
			"pass" : "user",
			"user" : "password"
		},
		"cumulatePlotsizes" : true,
		"forwardMinerNames" : true,
		"forwardUrls" : [
			"*"
		],
		"start" : true,
		"url" : "http://burst.domain.com:8080"
	}
}

**Comment by Creepsky** [comment]
Please test with the latest release 1.7.16 (1.8 has been withdrawn).
Reopen this issue if you will still have this issue.
