### ISSUE TITLE
CreepMiner Freezed

### ISSUE THREAD

**Issue by a7lan** [Creepsky/creepMiner#297]
Creepminer freezed, if i reload web pages (web server) when creepminer rescanning plot-dirs.

**Comment by Creepsky** [comment]
Read https://github.com/Creepsky/creepMiner/blob/master/ISSUE_TEMPLATE.md.
If you are done, change your issue please.
Then re-open it.

**Comment by a7lan** [comment]
version: 1.7.13
OS: Ubuntu 16.04.3 LTS
5 hard drive WD RED 4TB. 
plotter: mdcct. last git version
When freesed looks like

14:01:21: ▐▓▓▓▓▓▓▓▓▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▌  18.51 % ▌ 123.66 MB/s

What i'm doing:
1. start creepminer
2. whait when creepminer starting rescan plots dir
3. when rescan start, reload page. 
4. Creepminer freezed. Rescan stoped

**Comment by Creepsky** [comment]
Thank you.
Please test with version 1.7.16 and check if it's still freezing.

**Comment by a7lan** [comment]
Thx! now everything is fine
