### ISSUE TITLE
Error when finalizing compilation and setting the program version ( Linux )

### ISSUE THREAD

**Issue by zezaocapoeira** [Creepsky/creepMiner#298]
Hello.

(sorry bad english)

I have tested the master branch 2ba1a47 here:

And the error occurs when defining the program version:

`$ conan install . -s compiler.libcxx=libstdc++11 --build=missing`

[creepMiner-conan.log](https://github.com/Creepsky/creepMiner/files/1695990/creepMiner-conan.log)

`$ cmake CMakeLists.txt -DNO_GPU=ON`

[creepMiner-cmake.log](https://github.com/Creepsky/creepMiner/files/1695991/creepMiner-cmake.log)

`$ make -j5`

[creepMiner-make.log](https://github.com/Creepsky/creepMiner/files/1695992/creepMiner-make.log)

Thanks for listening.

**Comment by Creepsky** [comment]
This has nothing to do with the version. Please don't open a new issue for every compilation.
Look what I wrote for your last issue: https://github.com/Creepsky/creepMiner/issues/298.

**Comment by zezaocapoeira** [comment]
Hello.

( sorry bad english )

Sorry for the duplicate post.

I've tested your suggestion to use only:

`$ conan install . --build=missing`

[creepMiner-make.log](https://github.com/Creepsky/creepMiner/files/1696701/creepMiner-make.log)
[creepMiner-conan.log](https://github.com/Creepsky/creepMiner/files/1696702/creepMiner-conan.log)
[creepMiner-cmake.log](https://github.com/Creepsky/creepMiner/files/1696703/creepMiner-cmake.log)

And it worked :)

Congratulations on your work.

Thanks for listening.
