### ISSUE TITLE
1.8.0 x 1.7.6 ?

### ISSUE THREAD

**Issue by NightOwlCoder** [Creepsky/creepMiner#302]
Hey there,
nice little program you have here.

But can you help me understand the version history?
https://github.com/Creepsky/creepMiner/commit/2a42ce6185001ba2ccc30a87402169dd77cf8394

I had 1.8.0 and looks like the new version is a lower number?

Thanks,
NightOwl

**Comment by Creepsky** [comment]
Hi,

I use this sort of versioning: 1.x.y, where x = minor and y = patch.
Every time I implement a new featute, I increased x. If x is increased, y is set to 0.

1.8.0 was a pre-release (1.7.x + new features), based on the development-branch. After a while, I decided to remove the features  of 1.8 (they need too much time to implement), so it got 1.7.16 again.
I hope this makes it clear.

**Comment by NightOwlCoder** [comment]
Sure, thanks, I just wanted to be sure I was on the right version, as I had 1.8.0.

**Comment by nitr8** [comment]
yes - there is - jump onto discord if you want it.

**Comment by Creepsky** [comment]
We have cookies.
