### ISSUE TITLE
run.sh/screen.sh not being installed

### ISSUE THREAD

**Issue by kazamatzuri** [Creepsky/creepMiner#303]
I ran through the install:

Install Python
Install Conan: pip install conan
Install Poco: conan install . -s compiler.libcxx=libstdc++11 --build=missing (inside the creepMiner root dir)
cmake CMakeLists.txt -DNO_GPU=ON
make

however, it seems the run.sh and screen.sh files are not being copied to the bin directory, 

make install throws stuff into /usr/local/ directly

**Comment by Creepsky** [comment]
https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation-with-CMake-1.7.*#cmake_install_prefix

**Comment by Beddhist** [comment]
make install doesn't work for me:

6$ make install
[100%] Built target creepMiner
Install the project...
-- Install configuration: "RELEASE"
-- Installing: /usr/local/./mining.cl
CMake Error at cmake_install.cmake:36 (file):
  file INSTALL cannot copy file
  "/mnt/usbdrive/creepminer/creepMiner-2.7.16/src/shabal/opencl/mining.cl" to
  "/usr/local/./mining.cl".


Makefile:104: recipe for target 'install' failed
make: *** [install] Error 1

Looks like it would need to be run as root, which I'm reluctant to do, esp. seeing there is a /./ in the path.

**Comment by Beddhist** [comment]
It looks like the shell script must be run from the releases dir, or the web server can't find its files and you get a blank page.

**Comment by Creepsky** [comment]
Use this flag to change the install dir: https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation-with-CMake-1.7.*#cmake_install_prefix.
See the CMakeScript: https://github.com/Creepsky/creepMiner/blob/master/CMakeLists.txt#L203
If you have a better idea how the CMakeLists should look, feel free to change it and please make a pull request.

>esp. seeing there is a /./ in the path

I'm 100% sure you know what `.` means in the Linux filesystem :)

> need to be run as root

no, except if you want to https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html:

> This variable defaults to /usr/local on UNIX and c:/Program Files on Windows.

**Comment by nitr8** [comment]
Hi,

Please just copy run.sh and screen.sh  if you wish to use them, but I would recommend running the miner as a service.  Don't wast your time with run.sh and screen.sh  

I will be recommending to creepSky to remove this for linux for 1.7.8

Please see https://github.com/Creepsky/creepMiner/wiki/Running-as-a-service

I am closing this as there are multiple workarounds, and the recommended way is to run it as a service and not under screen
