### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_60'

### ISSUE THREAD

**Issue by ciscler** [Creepsky/creepMiner#304]
Hi all,
I have a Nvidia Geforce GT 1030 and I would like to mine with creepminer.
Creepminer is running on Ubuntu 16.04.

While doing "make" I got the following issue

`~/creepMiner-2.7.3$ make
[  2%] Building NVCC (Device) object CMakeFiles/creepMiner.dir/src/shabal/cuda/creepMiner_generated_Shabal.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_60'
CMake Error at creepMiner_generated_Shabal.cu.o.cmake:209 (message):
  Error generating
  /home/dirk/creepMiner-2.7.3/CMakeFiles/creepMiner.dir/src/shabal/cuda/./creepMiner_generated_Shabal.cu.o

CMakeFiles/creepMiner.dir/build.make:63: recipe for target 'CMakeFiles/creepMiner.dir/src/shabal/cuda/creepMiner_generated_Shabal.cu.o' failed
make[2]: *** [CMakeFiles/creepMiner.dir/src/shabal/cuda/creepMiner_generated_Shabal.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/creepMiner.dir/all' failed
make[1]: *** [CMakeFiles/creepMiner.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by Leozolt** [comment]
cuda 7.5 doesn't support pascal gpu's / compute_60

**Comment by justSomeoneThatsHere** [comment]
so there is no way to cuda mine? Ive tried opencl as well and have gotten the same error even trying that.

**Comment by Leozolt** [comment]
cuda 8 or 9 supports pascal gpu's / compute_60. I had some trouble installing cuda 9 so i stopped trying.

**Comment by Creepsky** [comment]
- Remove the following lines in your CMakeLists.txt at this position https://github.com/Creepsky/creepMiner/blob/master/CMakeLists.txt#L79:
```
-gencode=arch=compute_60,code=sm_60
-gencode=arch=compute_61,code=sm_61
-gencode=arch=compute_62,code=sm_62
```


- Set `GPU_CUDA_ARCH` to the architecture of your own gpu
- Remove all CMakeCache files and dirs
- Run your cmake command
- Make

**Comment by nitr8** [comment]
Please use the latest pre-compiled build with GPU support in. If you need access to it, join us on discord till its public
