### ISSUE TITLE
Windows installation does not contain mining.conf file

### ISSUE THREAD

**Issue by mtarca** [Creepsky/creepMiner#306]
Instructions require the user to edit "mining.conf" but that file does not exist in windows installations.

**Comment by Creepsky** [comment]
Copy a config of an older release or simply start the miner.. it will create you a fresh config.

**Comment by Beddhist** [comment]
ditto on Linux when compiling from source.

**Comment by nitr8** [comment]
Please see this: https://github.com/Creepsky/creepMiner/wiki/Setting-up-the-miner

By default the miner will store the config in the following location for windows:
`C:\Users\UserName\.creepMiner\{version}`
