### ISSUE TITLE
Floating Point Exception (Core Dumped)

### ISSUE THREAD

**Issue by WiggidyW** [Creepsky/creepMiner#307]
Getting this error when I attempt to mine with CUDA using my GTX 560 Ti. Using Ubuntu 16.04. Using creepMiner 1.7.16. Using CUDA 9.1. I do not get this error when mining with CPU.

LOG:
[creepMiner_20180213_163412.075858.log](https://github.com/Creepsky/creepMiner/files/1720770/creepMiner_20180213_163412.075858.log)

CONFIG:
[mining.conf.txt](https://github.com/Creepsky/creepMiner/files/1720773/mining.conf.txt)

EDIT: Interestingly enough, after updating my CUDA drivers it now reads for a second or 2 at the start before crashing with the same error, whereas before it would crash instantly.

**Comment by nitr8** [comment]
@WiggidyW - please could you try the development branch. If this is still an issue let us know, else we will close this case in a week or so.

**Comment by WiggidyW** [comment]
Yes, still having the same issue.

**Comment by nitr8** [comment]
You will need to wait for the 1.8.0 release which will have GPU support. There have been to many changes to support old versions, also I think its fair to say, that when there is pre-built binaries with GPU/CPU support there is no need for people to compile it themselves. 

Hang tight and wait for 1.8 release
