### ISSUE TITLE
CreepMiner Mining using Intel OpenCL

### ISSUE THREAD

**Issue by jretropie** [Creepsky/creepMiner#310]
I am trying to use Intel UHD internal graphic to do the mining.  So the CPU can free up I can do some other stuff with it.

Using creepMiner 1.8.0 Windows x64 works but it seems only use half of the GPU.  Is there way to fully use the GPU?

**Available OpenCL platforms:
Platform[0]: Intel(R) OpenCL, Version: OpenCL 2.1 
Platform[1]: Intel(R) OpenCL, Version: OpenCL 2.1 
Using platform[0]
Available OpenCL devices on platform[0]:
Device[0]: Intel(R) UHD Graphics 630
Device[1]: Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
Available OpenCL platforms:
Platform[0]: Intel(R) OpenCL, Version: OpenCL 2.1 
Platform[1]: Intel(R) OpenCL, Version: OpenCL 2.1 
Using platform[0]
Available OpenCL devices on platform[0]:
Device[0]: Intel(R) UHD Graphics 630
Device[1]: Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz**

**Comment by loppefaaret** [comment]
isnt it just that when using the GPU - you  dont have hyperthreading

**Comment by jretropie** [comment]
It seems like the internal graphic separate to two GPU.  When I use other programs to do plotting.  It shows GPU0 and GPU1.  This plotting program can select both GPU and fully use the GPU.
Is there way for CreepMiner to use 2 GPU?

![capture](https://user-images.githubusercontent.com/36509096/36264074-c8940cfc-1239-11e8-96eb-073c20813e2f.JPG)

**Comment by Creepsky** [comment]
Yeah like @loppefaaret said, no GPU multithreading yet. Maybe in the future.

**Comment by loppefaaret** [comment]
im guessing here, but im convinced you dont have 2 GPU in your CPU... perhaps under the install of some drivers, a secondary reference was made to access OpenCL devices...

**Comment by jretropie** [comment]
Ok.  Thanks guys!
