### ISSUE TITLE
quotes on value of targetDeadline

### ISSUE THREAD

**Issue by loppefaaret** [Creepsky/creepMiner#312]
when setting targetDeadline in the mining.conf, and using YMD, you enclose the value in ""
but when setting it in pure seconds 45987267, it will not accept ""
if you "45987267" rather than 45987267 - it will ignore the local targetDeadline, and use 0 instead, or whatever it gets from the pool over mininginfo

**Comment by Creepsky** [comment]
Like described here https://github.com/Creepsky/creepMiner/wiki/Setting-up-the-miner#targetdeadline.
Numbers and strings are different things in JSON, read here: https://stackoverflow.com/questions/15368231/can-json-numbers-be-quoted.

**Comment by loppefaaret** [comment]
lesson learned, thank you
