### ISSUE TITLE
Problem "making" on a Raspberry Pi 3

### ISSUE THREAD

**Issue by Emilex108** [Creepsky/creepMiner#313]
pi@raspberrypi:~/cm $ make
Scanning dependencies of target creepMiner
[  2%] Building CXX object CMakeFiles/creepMiner.dir/src/MinerUtil.cpp.o
/home/pi/cm/src/MinerUtil.cpp:855:29: error: ‘size_t Burst::getMemorySize()’ should have been declared inside ‘Burst’
 size_t Burst::getMemorySize()
                             ^
/home/pi/cm/src/MinerUtil.cpp:935:37: error: ‘void Burst::setStdInEcho(bool)’ should have been declared inside ‘Burst’
 void Burst::setStdInEcho(bool enable)
                                     ^
CMakeFiles/creepMiner.dir/build.make:830: recipe for target 'CMakeFiles/creepMiner.dir/src/MinerUtil.cpp.o' failed
make[2]: *** [CMakeFiles/creepMiner.dir/src/MinerUtil.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/creepMiner.dir/all' failed
make[1]: *** [CMakeFiles/creepMiner.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

I am trying to install it on a pi as you can see, and I keep encountering this issue when trying to "make" in the "cm" folder.

**Comment by Creepsky** [comment]
What version do you compile?
