### ISSUE TITLE
Feature Request - Ability to Secure Web Server with SSL Certificate

### ISSUE THREAD

**Issue by metalingusman** [Creepsky/creepMiner#321]
I would like to request a feature for the ability to apply a certificate to the web server to enable SSL/TLS connections.

**Comment by Creepsky** [comment]
Only pkcs12 certificates are supported.
To convert your current certificate, use `openssl pkcs12 -export -out domain.name.pfx -inkey domain.name.key -in domain.name.crt`.

New config settings:
```
"webserver": {
    "certificate": {
        "path": "<path_to_certificate>",
        "pass": "<password_in_plaintext>"
    }
}
```

The websockets will also be secured with that certificate.
Password is currently saved in plain text; I will change this maybe later on.

Just for the record: `openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout privatekey.key -out certificate.crt`.

**Comment by nitr8** [comment]
implemented - tested - documenting soon

**Comment by modislaszlox2** [comment]
I didn't wan to open open a new issue but this doesn't seem to be working correctly.
I created a valid .pfx file(managed to install it as windows certificate without errors) and when I try to use it I get the following error:

02:38:10: Error while creating local http server on port 8000!
02:38:10: Exception occured: Bad data format: PKCS #12 certificate file too large: certificate.pfx
02:38:10:       error-code: 0
02:38:10:       class: class Poco::DataFormatException

Le me know what log settings I have to set for more logs.
