### ISSUE TITLE
Compile problem for Master version - How to resolve

### ISSUE THREAD

**Issue by Dealazer** [Creepsky/creepMiner#322]
Need to change:
in conanfile.txt: Poco to 1.8.0
[requires]
Poco/1.8.1@pocoproject/stable

**Comment by nitr8** [comment]
If you using the master branch please use the precompiled versions supplied. 

If you wish to use the dev branch for development purposes then take a look at https://github.com/Creepsky/creepMiner/wiki/Compiling-from-source
