### ISSUE TITLE
The version ('90000') of the host compiler ('Apple clang') is not supported

### ISSUE THREAD

**Issue by wrumble** [Creepsky/creepMiner#330]
wazza  ~/Desktop/Burst/creepMiner   master  make -j$(nproc)
zsh: command not found: nproc
[  2%] Building NVCC (Device) object CMakeFiles/creepMiner.dir/src/shabal/cuda/creepMiner_generated_Shabal.cu.o
nvcc fatal   : The version ('90000') of the host compiler ('Apple clang') is not supported
CMake Error at creepMiner_generated_Shabal.cu.o.RELEASE.cmake:221 (message):
  Error generating
  /Users/waynerumble/Desktop/Burst/creepMiner/CMakeFiles/creepMiner.dir/src/shabal/cuda/./creepMiner_generated_Shabal.cu.o

make[2]: *** [CMakeFiles/creepMiner.dir/src/shabal/cuda/creepMiner_generated_Shabal.cu.o] Error 1
make[1]: *** [CMakeFiles/creepMiner.dir/all] Error 2
make: *** [all] Error 2

I keep getting this error on the final step of the intrcuctions on the readme, can anyone help? Ive tried so many options like here https://github.com/fireice-uk/xmr-stak/issues/623#issuecomment-355598337 but nothing is working

**Comment by nitr8** [comment]
before your make

```
cmake CMakeLists.txt -DCMAKE_BUILD_TYPE=RELEASE -DNO_GPU=ON 
make -j$(nproc)
```

then make - you trying to compile and do not have the CUDA or NVIDA SDK installed.

**Comment by nitr8** [comment]
wrumble,

any news on this?

**Comment by MrGrote** [comment]
Nvidias CUDA doesn't support version of clang.
Use -DCUDA_HOST_COMPILER=/path/to/compatiblecompiler
The Compilers compatible with your version of CUDA can be found in the docs by nvidia.

**Comment by wrumble** [comment]
Hi sorry, i managed to get it to work by installing an old verision of CUDA, i then had to re do the steps building up to the step that got this error and it worked. My only issue now is that i have done all the install steps nothing works when i call sh ./run.sh in the root directory or bin directory

**Comment by nitr8** [comment]
cd bin &./creepMiner

**Comment by nitr8** [comment]
@wrumble - please can you confirm if this has resolved your issue, if we have not heard back from you in a week, ill assume its fixed and close the case.

**Comment by nitr8** [comment]
I cann verify clang 90000 does work - 910000 does not - but thats beta.

Going ahead and closing.
