### ISSUE TITLE
./run.sh does nothing

### ISSUE THREAD

**Issue by wrumble** [Creepsky/creepMiner#331]
I have succesfully installed using the instructions for a mac found here: https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation-on-macOS this created a bin folder within the creepMiner root directory. When running ./run.sh from the root directory it says it cant find it, i fi run it from resources when run.sh is its says it cant find creepMiner so if i point that script to creepMiner in bin folder it then says it cant find the image.

Any help/ideas would be great

**Comment by nitr8** [comment]
hiya,

cd bin && chmod 755 creepMiner && ./creepMiner

**Comment by nitr8** [comment]
Closing this case as there are clear instructions now provided
