### ISSUE TITLE
./creepMiner does not appear in home folder after .deb installation

### ISSUE THREAD

**Issue by justSomeoneThatsHere** [Creepsky/creepMiner#335]
Hardware:
gtx 1060
fx 8350
16gb ram
Ubuntu 16.04 64bit
Nvidia binary driver version 384.111

Before I start, yes I know its a hidden folder. After installing the deb with my package manager everything appears to go fine. However ./creepMiner never appears in my home folder. What am I missing?

**Comment by loppefaaret** [comment]
no, it usually lands in /opt/creepMiner - atleast on debian

**Comment by justSomeoneThatsHere** [comment]
ah cool found it. now this is my issue when trying to run it

g@xxxxxxx:/opt/creepMiner-1.7.16$ ls
creepMiner  lib  mining.cl  mining.conf  public  run.sh  screen.sh
g@xxxxxxx:/opt/creepMiner-1.7.16$ sudo chmod +x creepMiner 
g@xxxxxxx/opt/creepMiner-1.7.16$ sudo chmod +x run.sh
g@xxxxxxx:/opt/creepMiner-1.7.16$ ./creepMiner 
./creepMiner: symbol lookup error: ./creepMiner: undefined symbol: _ZN4Poco3Net11HTTPRequest8HTTP_GETE
g@xxxxxxx:/opt/creepMiner-1.7.16$ ./run.sh 
./creepMiner: symbol lookup error: ./creepMiner: undefined symbol: _ZN4Poco3Net11HTTPRequest8HTTP_GETE

**Comment by loppefaaret** [comment]
try apt update && apt upgrade - if it still dont work, await other help

**Comment by amiller2k17** [comment]
I havent used the deb install but when I didn't the manual way, I had to install poco.   Maybe you need to do that?  

apt-get install libpoco-dev
sh ./install-poco.sh  (on mine the script was in the creepminer folder)

**Comment by nitr8** [comment]
closing - not an issue - miner setup / not reading wiki issue :)
