### ISSUE TITLE
Admin page does not load

### ISSUE THREAD

**Issue by Integrative** [Creepsky/creepMiner#341]
Admin page does not load on FireFox (Latest) running on Ubuntu 17(latest).

>    "webserver" : {
>         "activeConnections" : 32,
>         "calculateEveryDeadline" : false,
>         "certificate" : {
>             "pass" : "",
>             "path" : ""
>         },
>         "connectionQueue" : 64,
>         "credentials" : {
>             "pass" : "pass",
>             "user" : "admin"
>         },
>         "cumulatePlotsizes" : true,
>         "forwardMinerNames" : true,
>         "forwardUrls" : [
> 
>         ],
>         "start" : true,
>         "url" : "http://192.168.32.12:8080"
>     }
> }

**Comment by nitr8** [comment]
@Integrative i have just tested this on my 16.04.4 and 17.19 builds and it works a dream.

The only difference is i use 0.0.0.0 please try that, restart miner.

Also have you tried from another browser and another pc?

**Comment by Integrative** [comment]
Tried

**Comment by Integrative** [comment]
Sorry, thick fingers.. tried 

"start" : true, 
"url" : "http://0.0.0.0:8080" 


Same result, blank page redirected to /login 

Also tried another PC/Server, windoze IE and Chrome. 

Something is off.

**Comment by Integrative** [comment]
get this in logs

```
> 12.03.2018 14:08:02 (3, /opt/creepMiner/src/webserver/RequestHandler.cpp, 194, Error): Could not open public/index.html!
> 12.03.2018 14:08:02 (3, /opt/creepMiner/src/webserver/RequestHandler.cpp, 195, Error): Exception occured: File not found: public/index.html
> 	error-code: 2
> 	class: N4Poco21FileNotFoundExceptionE
```

**Comment by nitr8** [comment]
ahh easy fix :)

could you copy the `public` folder into the same directory as where you launch creepMiner from please.

Then restart and you should be sorted. Please let us know how it goes.

**Comment by Integrative** [comment]
That seems to work. thanks!

**Comment by nitr8** [comment]
Thanks for the heads up, going ahead and closing this case :)
