### ISSUE TITLE
TargetDeadline on pool which have no target deadline

### ISSUE THREAD

**Issue by ludovicscribe** [Creepsky/creepMiner#342]
Hi,

I mine on BTFG and I want to put a target deadline on my miner to optimyze my historical share but the pool has 0 as target deadline so the miner doesn't take care of my custom target deadline (`"targetDeadline" : "20099707"` in the config file).

I think you have to add an option to override pool target deadline, even if it is higher than user configured target deadline.

Thanks and congratulation for developping this verry good miner ;)

Ludovic

**Comment by nitr8** [comment]
@ludovicscribe 

If you wish to use the target deadline, you need to follow the config which does not handle seconds see https://github.com/Creepsky/creepMiner/wiki/Setting-up-the-miner 

If you wish to use 20099707 simply google "20099707 seconds to days" then in your config for  use the following format:

"targetDeadline" : "0y 7m 0d 00:00:00",

**Comment by ludovicscribe** [comment]
@nitr8 

On this page it's written `The target deadline can be given as a number (for example "targetDeadline" : 12345), which represents the total seconds of the deadline, or as a formatted string (for example "targetDeadline" : "1y 2d 12:34:56").`, it's obselete ?

On an other page I read that CreepMiner take the pool target deadline if it is higher than the configured target deadline. In my case, the pool target deadline is 0 (no target deadline). So, I think CreepMiner take 0 instead of 20099707. Am I right ?

Thanks for your answer

**Comment by Creepsky** [comment]
Hi,

you are right, you can enter it as number (in seconds; don't forget to remove the `"`) or as formatted string.

If the pool target deadline is `0`, the miner will use your manual target deadline, as seen here:
https://github.com/Creepsky/creepMiner/blob/master/src/mining/MinerConfig.cpp#L936

So just set it to a value > 0, and the miner will respect it.

**Comment by nitr8** [comment]
My bad folks :)

**Comment by ludovicscribe** [comment]
@Creepsky in my config file (`~/.creepMiner/1.7.16/mining.conf`) I've changed `"targetDeadline" : "00:00:00"` to `"targetDeadline" : "20099707"` and I've restarted the miner from the web interface but CreepMiner continue to send deadlines with target > 20099707 :

![capture](https://user-images.githubusercontent.com/17702669/37330561-ce12e0c8-26a1-11e8-8d28-ed2c556ae858.PNG)

**Comment by Creepsky** [comment]
As I wrote, dont forget to remove the `"` ;)
`"20099707"`: text with the content `20099707` -> creepMiner doesn't understand this, and faults to `0`
`20099707`: number 20099707 -> creepMiner parses this as 20099707 seconds

**Comment by ludovicscribe** [comment]
Sorry, I read your answer too quickly. My target deadline works now.

Thanks for your help and congratulation for your work !
