### ISSUE TITLE
Phassphrase does not match  / wrong, old Burst address

### ISSUE THREAD

**Issue by Integrative** [Creepsky/creepMiner#343]
When switching wallet accounts, reconfiguring the miner for local mining, chaning the passphrases etc.
I get 'error on submitting nonce' , pass-phrase does not match reward receipt.

Paraphrase is correct. 

Is there some cache that needs clearing?

**Comment by nitr8** [comment]
Hi @Integrative 

could you verify your mining section looks something like this?

```
        "passphrase" : {
            "algorithm" : "aes-256-cbc",
            "decrypted" : "",
            "deleteKey" : true,
            "encrypted" : "",
            "iterations" : 1000,
            "key" : "",
            "salt" : ""
        },
```

**Comment by Integrative** [comment]
Yes, but think the issue is with the plot files :** they are still for the old account of course..

**Comment by nitr8** [comment]
oh well - then you answered your own question no? if so please close this case, else let us know and we can look @ it.

**Comment by nitr8** [comment]
@Integrative - could we get an update please?  If no update in the next week, I assume this is resolved and will close the case

**Comment by Integrative** [comment]
Yes sorry, reinstalled, and all was fine again, thanks

**Comment by nitr8** [comment]
thanks for the heads up @Integrative
