### ISSUE TITLE
getMiningInfoInterval = 0 spams pools

### ISSUE THREAD

**Issue by Nalindar** [Creepsky/creepMiner#349]
getMiningInfoInterval should default to 3 if a user enters anything less than 3.

---------------------------------------------
y0ureAtowel[94tb] - Today at 9:57 PM
pool down?

pYl - Today at 9:57 PM
nopes

Valareos - Today at 9:57 PM
whats your ip

y0ureAtowel[94tb] - Today at 9:58 PM
im on a vpn but --removed--

Valareos - Today at 9:58 PM
Ill unban you but you need to check your config settings.
What miner you use

Nalindar - Today at 9:58 PM
lol biggest culprit
😁1

y0ureAtowel[94tb] - Today at 9:58 PM
creep
oh man what am i doing wrong

mining.conf
3.28 KB
thats my config

Valareos - Today at 9:59 PM
you hit the rate limiter a huge amount of time

y0ureAtowel[94tb] - Today at 9:59 PM
sorry

pYl - Today at 9:59 PM
not just hitting the limiter... ur the topscore thru a DDoS attack :D
😂2

y0ureAtowel[94tb] - Today at 9:59 PM
not trying to be malicious
but i dunno what im doing as far as making it do that
i just run creep

pYl - Today at 10:01 PM
"getMiningInfoInterval" : 0,
please set to 3
pretty plz

**Comment by nitr8** [comment]
@Nalindar - This is an operator issue. I will make a note in the wiki about it, but it should not be a change like you suggest. If i want to sep getMiningInfoInterval to 1 i want it to get info from my miner every second. I use a multi miner setup for example and its my decision not the codes.

Added a note to this: https://github.com/Creepsky/creepMiner/wiki/Setting-up-the-miner so going ahead and closing, thanks for reporting this :)
