### ISSUE TITLE
Previously working miner no longer working

### ISSUE THREAD

**Issue by zkdzegede** [Creepsky/creepMiner#353]
My miner was working 1 month ago and I had to shut down everything when I moved to a new house.

I finally got my hardware running again, having made no changes, and it now gets stuck at this part

```
Looking for mining info...
```

I am mining to pool.burstcoin.ro and noticed they  have something about v2.0 on their  page now.
Did something change, and how can I fix this issue?

**Comment by zkdzegede** [comment]
after a little bit of time it prints

```
Could not get block infos!
```

**Comment by nitr8** [comment]
@zkzegede please provide the necessary information when opening a case.

```
issue
Pronunciation /ˈɪʃuː/ /ˈɪsjuː/
An important topic or problem for debate or discussion.
```

Please use the **search** function! Maybe your issue is already created by someone else. Also read the [**wiki pages**](https://github.com/Creepsky/creepMiner/wiki).

If you have a **question** about the miner:
- please post only miner related questions
- be precise (questions like 'Dude, it is slow for me, why?' will be closed)

- use the [**latest release**](https://github.com/Creepsky/creepMiner/releases/latest), your issue may be solved already
- describe the problem as accurately as possible
- describe all steps to get to your problem so it can be traced - otherwise it is nearly impossible to fix it!
- provide additional information like the name of your **OS**, the miner **version**, your **gcc version**, ...
- attach **log files**, **screenshots** and your **config-file**

**Comment by MircoBlitz** [comment]
I think I can add to that. I have the same problem with http://pool.burstcoin.ro 

Mining System: Ubuntu 16.04 (latest updates as of this post)
I have tried with 
downloaded version of creepMiner-1.7.16
and build my own from latest soures. The problem occurs at both builds.

creepminer seems not to reach the wallet of burstpool.ro or does not compute.
I can ping the wallet address from this system and I can curl the wallet page with success.

I use this config, which worked until 6 days ago (with the downloaded version of the miner.
`{
    "logging" : {
        "config" : "information",
        "general" : "debug",
        "logfile" : true,
        "miner" : "debug",
        "nonceSubmitter" : "information",
        "output" : {
            "dirDone" : true,
            "lastWinner" : true,
            "nonceConfirmed" : true,
            "nonceFound" : true,
            "nonceFoundTooHigh" : false,
            "nonceSent" : true,
            "plotDone" : false
        },
        "outputType" : "terminal",
        "path" : "",
        "plotReader" : "information",
        "plotVerifier" : "information",
        "progressBar" : {
            "fancy" : true,
            "steady" : true
        },
        "server" : "fatal",
        "session" : "error",
        "socket" : "off",
        "useColors" : true,
        "wallet" : "fatal"
    },
    "mining" : {
        "benchmark" : {
            "active" : false,
            "interval" : 60
        },
        "bufferChunkCount" : 128,
        "cpuInstructionSet" : "SSE2",
        "getMiningInfoInterval" : 5,
        "gpuDevice" : 0,
        "gpuPlatform" : 0,
        "intensity" : 4,
        "maxBufferSizeMB" : 8192,
        "maxPlotReaders" : 6,
        "passphrase" : {
            "algorithm" : "aes-256-cbc",
            "decrypted" : "",
            "deleteKey" : false,
            "encrypted" : "",
            "iterations" : 1000,
            "key" : "",
            "salt" : ""
        },
        "plots" : [
            "/plots/a",
            "/plots/b",
            "/plots/c",
            "/plots/d",
            "/plots/e",
            "/plots/f",
            "/plots/g",
            "/plots/h",
            "/plots/i",
            "/plots/j",
            "/plots/k",
            "/plots/l",
            "/plots/m",
            "/plots/n",
            "/plots/o"
        ],
        "processorType" : "CPU",
        "rescanEveryBlock" : false,
        "submissionMaxRetry" : 5,
        "targetDeadline" : "0y 2m 0d 00:00:00",
        "timeout" : 30,
        "urls" : {
            "miningInfo" : "http://pool.burstcoin.ro:8080",
            "submission" : "http://pool.burstcoin.ro:8080",
            "wallet" : "https://wallet.burstcoin.ro"
        },
        "useInsecurePlotfiles" : false,
        "wakeUpTime" : 1,
        "walletRequestRetryWaitTime" : 5,
        "walletRequestTries" : 10
    },
    "webserver" : {
        "activeConnections" : 8,
        "calculateEveryDeadline" : false,
        "connectionQueue" : 64,
        "credentials" : {
            "pass" : "",
            "user" : ""
        },
        "cumulatePlotsizes" : true,
        "forwardMinerNames" : true,
        "forwardUrls" : [

        ],
        "start" : false,
        "url" : "http://192.168.0.101:8080"
    }
}`

This is the log of a run
` 2018-03-29 00:41:38 ⌚  drachenhort in ~/mining/burst/creepMiner-1.7.16-Linux/opt/creepMiner-1.7.16
○ → ./run.sh 
00:41:39: creepMiner 1.7.16 Unix x64
00:41:39: Release mode -CUDA -OpenCL +SSE4 +AVX +AVX2
00:41:39: ----------------------------------------------
00:41:39: Github:   https://github.com/Creepsky/creepMiner
00:41:39: Author:   Creepsky [creepsky@gmail.com]
00:41:39: Burst :   BURST-JBKL-ZUAV-UXMB-2G795
00:41:39: ----------------------------------------------
00:41:40: Changed logfile path to
00:41:40:       creepMiner_20180328_224139.661059.log
00:41:40: Config file loaded: mining.conf
00:41:40: Submission Max Retry : 5 seconds
00:41:40: Buffer Size : 8192 (8 GB)
00:41:40: Submission URL : http://pool.burstcoin.ro:8080
00:41:40: Mininginfo URL : http://pool.burstcoin.ro:8080
00:41:40: Wallet URL : https://wallet.burstcoin.ro:443
00:41:40: Server URL : http://192.168.0.101:8080
00:41:40: Target deadline : 2m 0d 00:00:00
00:41:40: Log path : creepMiner_20180328_224139.661059.log
00:41:40: Total plots size: 27.55 TB
00:41:40: Mining intensity : 4
00:41:40: Max plot readers : 6
00:41:40: Get mining info interval : 5 seconds
00:41:40: Processor type : CPU
00:41:40: CPU instruction set : SSE2
00:41:40: Looking for mining info...
00:42:10: Could not get mining infos 1/5 times...
00:42:45: Could not get mining infos 2/5 times...
`

**Comment by zkdzegede** [comment]
Fixed when disabling ipv6.  thank you @MircoBlitz 

Sorry for the lack of information.

**Comment by nitr8** [comment]
Added this to https://github.com/Creepsky/creepMiner/wiki/FAQ
