### ISSUE TITLE
Fwding from other miners doesn't report correct capacity to pool

### ISSUE THREAD

**Issue by Have-a-question-about-this-project** [Creepsky/creepMiner#357]
Machine A: 15 TB creepMiner-1.7.16-win64 -> pool
Machine B: 55TB jminer-0.4.11-SNAPSHOT -> creep miner
Pool reports my capacity as 15TB. Creepminer is ignoring the size from the jminer machine fwded to it.

I'm only using jminer becasue its current release supports opencl and creepminrer is currently built without it.

**Comment by nitr8** [comment]
Hi @Have-a-question-about-this-project 

Please could you provide us your config file as well as a copy of your log file.

Also you could try this on the main miner:

```
"cumulatePlotsizes" : true,
"forwardMinerNames" : false,
```

**Comment by Have-a-question-about-this-project** [comment]
I previously had:
```
"cumulatePlotsizes" : true,
"forwardMinerNames" : true,
```
I changed forwardMinerNames to false as you suggested and it made no difference.
[creepMiner_20180405_233554.982275.log](https://github.com/Creepsky/creepMiner/files/1882194/creepMiner_20180405_233554.982275.log)
[creepminer_console.txt](https://github.com/Creepsky/creepMiner/files/1882195/creepminer_console.txt)
[jminer.txt](https://github.com/Creepsky/creepMiner/files/1882196/jminer.txt)

**Comment by Herscht** [comment]
Well it is just a visual issue, your rewards should be unaffected by this. But yes, would be nice if the capacity would be cumulated across miners at some point ... have you tried setting it up the other way around? creep->jminer->pool

**Comment by Creepsky** [comment]
Changed in 1.8.0+.
Remote plot sizes are now cumulated by IP not by an unique hash.
