### ISSUE TITLE
Feature-Request: History/Graphs persist through restarts

### ISSUE THREAD

**Issue by TOoSmOotH** [Creepsky/creepMiner#359]
As someone who is constantly adding disk it would be nice if it was possible to maintain the history/graphs through restart. Maybe having an option to to reset the data or a file to delete would probably be helpful.

**Comment by nitr8** [comment]
Hiya,

There is already a case someware opened by me for this exact thing. After this release it is planned to use some sort of a lightweight db.

I'll go ahead and mark this as an enhancements, will probably link to too am existing one and close if cool with you?

**Comment by nitr8** [comment]
@TOoSmOotH 

This is now implemented - there is a sqllite DB as part of the new 1.8.0 which saves stats to db

you can use databasePath under mining to set the path of the db else it will got to .creepMiner/VER/.
