### ISSUE TITLE
got no confirmation from server! Busy ?

### ISSUE THREAD

**Issue by Nikolay899** [Creepsky/creepMiner#361]
Hi i have one problem and read some psot but i dont now how to fix it....Creepminer no accept my DL
My config si 

{
    "logging" : {
        "config" : "information",
        "general" : "information",
        "logfile" : false,
        "miner" : "information",
        "nonceSubmitter" : "information",
        "output" : {
            "dirDone" : true,
            "lastWinner" : true,
            "nonceConfirmed" : true,
            "nonceFound" : true,
            "nonceFoundTooHigh" : false,
            "nonceSent" : true,
            "plotDone" : false
        },
        "outputType" : "terminal",
        "path" : "",
        "plotReader" : "information",
        "plotVerifier" : "information",
        "progressBar" : {
            "fancy" : true,
            "steady" : true
        },
        "server" : "fatal",
        "session" : "error",
        "socket" : "off",
        "useColors" : true,
        "wallet" : "fatal"
    },
    "mining" : {
        "benchmark" : {
            "active" : false,
            "interval" : 60
        },
        "bufferChunkCount" : 8,
        "cpuInstructionSet" : "SSE2",
        "getMiningInfoInterval" : 3,
        "gpuDevice" : 0,
        "gpuPlatform" : 0,
        "intensity" : 1,
        "maxBufferSizeMB" : 0,
        "maxPlotReaders" : 0,
        "passphrase" : {
            "algorithm" : "aes-256-cbc",
            "decrypted" : "",
            "deleteKey" : false,
            "encrypted" : "",
            "iterations" : 1000,
            "key" : "",
            "salt" : ""
        },
        "plots" : [
            "D://Plots",
            "D://Plots2",
            "E://",
            "H://Plots",
            "I://Plots",
            "J://",
            "G://Plots"
        ],
        "processorType" : "OPENCL",
        "rescanEveryBlock" : false,
        "submissionMaxRetry" : 3,
        "targetDeadline" : "0y 9m 0d 00:00:00",
        "timeout" : 45,
        "urls" : {
            "miningInfo" : "http://burst.btfg.space:8124",
            "submission" : "http://burst.btfg.space:8124",
            "wallet" : "https://wallet.burstcoin.ro"
        },
        "useInsecurePlotfiles" : false,
        "wakeUpTime" : 0,
        "walletRequestRetryWaitTime" : 3,
        "walletRequestTries" : 5
    },
    "webserver" : {
        "activeConnections" : 8,
        "calculateEveryDeadline" : false,
        "connectionQueue" : 64,
        "credentials" : {
            "pass" : "",
            "user" : ""
        },
        "cumulatePlotsizes" : true,
        "forwardMinerNames" : true,
        "forwardUrls" : [

        ],
        "start" : true,
        "url" : "http://192.168.0.101:8080"
    }
}

**Comment by nitr8** [comment]
@Nikolay899 

Please open a case with the right information next time - like described when opening a case.

1) Use latest creepMiner build - https://github.com/Creepsky/creepMiner/releases
2) Set submitProbability to 0 if you want to use targetDeadline 

However its pointless using the targetDeadline if you have the new dynamic target dedalines
