### ISSUE TITLE
Including new plotfiles while mining

### ISSUE THREAD

**Issue by ohager** [Creepsky/creepMiner#365]
Hi Creepsky.

while running a test plot yesterday, I discovered that newly generated plotfiles weren't considered once the miner was started. 

_Scenario_
- I have a plotter (burst-autoplotter, i.e. XPlotter) running that creates several plot files under `C:\burst\plots`
- I added `C:\burst\plots` as plot path in the `miner.conf` and start the miner
- The plotter finishes a plot file (and automatically goes over to the next plot)

_Result_
The miner does not recognize the plot generated, while it's up. I needed to restart the miner, such that the plot is going to recognized.

_Request_
Would be awesome, if new plots (as long as the base plot path is configured) could be detected and considered dynamically while mining, like hot plugging.

**Comment by Creepsky** [comment]
Hi,

I think the setting you are looking for is [rescanEveryBlock](https://github.com/Creepsky/creepMiner/wiki/Setting-up-the-miner#rescaneveryblock).
When set to `true`, it will automatically add new plot files.

**Comment by ohager** [comment]
Oh, cool... a typical case of RTFM.
