### ISSUE TITLE
1.8.0 updated doesn't run on Win 10

### ISSUE THREAD

**Issue by Beddhist** [Creepsky/creepMiner#366]
I have 1.7.16 running on Win 10 Pro. When trying to run the updated 1.8.0 with the existing config file it gets to loading the config, then sits there for about 20 secs, then Windows shuts it down. In Event Viewer I have these entries:

Fault bucket 1990513222425287468, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 1735205920945272033

Problem signature:
P1: creepMiner.exe
P2: 0.0.0.0
P3: 5ad1bbbe
P4: creepMiner.exe
P5: 0.0.0.0
P6: 5ad1bbbe
P7: c0000005
P8: 000000000006f690
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREEA.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER14C8.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1505.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1525.tmp.txt
\\?\C:\Users\Dell\AppData\Local\Temp\WER22D3.tmp.appcompat.txt
\\?\C:\Users\Dell\AppData\Local\Temp\WER2341.tmp.WERDataCollectionStatus.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_creepMiner.exe_948796589149d0124142cf4babc1ba5f89f073_ca20f596_cab_360838e8

Analysis symbol: 
Rechecking for solution: 0
Report Id: 02ee3715-9792-453d-b9e2-c17601e3d39e
Report Status: 268435464
Hashed bucket: 0e5640e4daac9e732b9fb93ac7609b2c

------------------------------------------------------------------------------------------------

Faulting application name: creepMiner.exe, version: 0.0.0.0, time stamp: 0x5ad1bbbe
Faulting module name: creepMiner.exe, version: 0.0.0.0, time stamp: 0x5ad1bbbe
Exception code: 0xc0000005
Fault offset: 0x000000000006f690
Faulting process id: 0xb40
Faulting application start time: 0x01d3d4af67b6c316
Faulting application path: C:\Program Files\creepMiner 1.8.0\creepMiner.exe
Faulting module path: C:\Program Files\creepMiner 1.8.0\creepMiner.exe
Report Id: 02ee3715-9792-453d-b9e2-c17601e3d39e
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Beddhist** [comment]
[Report.zip](https://github.com/Creepsky/creepMiner/files/1912485/Report.zip)

**Comment by nitr8** [comment]
User used zip insted of installer and that fixed the issue
