### ISSUE TITLE
config

### ISSUE THREAD

**Issue by brentyosy007** [Creepsky/creepMiner#367]
Hey im having some troubles in understanding how to make the plotfile could someone show me theirs?
am i just supposed to write H:\\New folder

**Comment by nitr8** [comment]
Hi.

It is all documented in the wiki - https://github.com/Creepsky/creepMiner/wiki/Setting-up-the-miner

**Comment by nitr8** [comment]
See the plots section.

**Comment by nitr8** [comment]
Please see the plots section.
