### ISSUE TITLE
Raspberry Pi 3 - Segmentation Fault

### ISSUE THREAD

**Issue by XternA** [Creepsky/creepMiner#371]
I am constantly getting a ``Segmentation fault`` thrown everytime I try to run the miner with a plot file specified. If I remove plots from the config files the miner runs fine but obviously doesn't proceed further due to no plots available.

The compilation worked without errors and as instructed as per wiki instructions.

Details of the environment:
![details](https://user-images.githubusercontent.com/9136075/38951994-22275e0c-4342-11e8-8e0f-6770dec32b1a.JPG)

Steps taken to get the miner compiled after cloning (Cloned from release branch):
```
conan install . --build=missing -s compiler.libcxx=libstdc++11
cmake CMakeLists.txt -DCMAKE_BUILD_TYPE=RELEASE -DMINIMAL_BUILD=ON
make
```

Tried also the following options but the compilation will fail:
```
conan install . --build=missing -s compiler.libcxx=libstdc++11
cmake CMakeLists.txt -DCMAKE_BUILD_TYPE=RELEASE -DMINIMAL_BUILD=ON
make -j$(nproc)
```

After compilation and running the miner this is the outputs:

Without plots specified in config file.
![miner](https://user-images.githubusercontent.com/9136075/38952375-5029a818-4343-11e8-9538-f95511cfbc59.png)

With plot specified.
![miner](https://user-images.githubusercontent.com/9136075/38952456-a629b7b2-4343-11e8-9fe0-0ff9428da36b.png)

Any ideas how to resolve this? Seems to be memory address accessing problem. Have tried all compilation options/configuration settings etc and still results back to this issue. 

Many thanks.

**Comment by chrulri** [comment]
> CPU instruction set : AVX2

RPi does not support AVX(2).

**Comment by XternA** [comment]
Works like a charm. Looks the the instruction set was SSE2 instead. Many thanks.
