### ISSUE TITLE
Segmentation fault with wrong values in ProcessorType

### ISSUE THREAD

**Issue by rico666** [Creepsky/creepMiner#374]
In my first experiments with instruction sets, I wrongly entered "SSE4" as value for processortype

This caused both creepMiner 1.7.16 as well as 1.8.0 (pre-release) prebuilt binaries to crash with a segmentation fault.

In general, even /dev/urandom output as config file should not cause an application to SEGV.
Maybe add some fuzzy testing.

**Comment by brmmm3** [comment]
Should be fixed now with PR #413
