### ISSUE TITLE
Cannot use HTTPS with the miner

### ISSUE THREAD

**Issue by modislaszlo** [Creepsky/creepMiner#375]
issue: Created a pfx file but whenever I try to start the miner with using the certificates the webserver is not starting.

I get the following error:

02:38:10: Error while creating local http server on port 8000!
02:38:10: Exception occured: Bad data format: PKCS #12 certificate file too large: certificate.pfx
02:38:10:       error-code: 0
02:38:10:       class: class Poco::DataFormatException

The certificate should be correct because Windows installed it properly(Left Click -> Install). Running 1.8.0 on Windows 10. If you need more logs let me know what logs settings should I use for it.

**Comment by nitr8** [comment]
This means there is an issue with your pfx 

Attached is a cert for localhost - you may use this to test with
[localhost.pfx.zip](https://github.com/Creepsky/creepMiner/files/1942865/localhost.pfx.zip)

This is working on windows only right now - *nix support will follow shortly

**Comment by modislaszlox2** [comment]
@nitr8 your pfx is working but I don't think mine is incorrect. I created it from a valid Let's encrypt certificate(by running the command from #321). The same certificate works correctly for the wallet. I'm not sure if it matters but I want to use ssl over the internet not for localhost.

**Comment by modislaszlo** [comment]
@nitr8 your pfx is working but I don't think mine is incorrect. I created it from a valid [Let's encrypt](https://letsencrypt.org/) certificate(by running the command from #321). The same certificate works correctly for the wallet. I'm not sure if it matters but I want to use ssl over the internet not for localhost.

**Comment by nitr8** [comment]
@modislaszlo 

See this - 
https://blog.nfye.com/create-your-own-self-signed-certificate-with-subject-alternative-names-using-openssl/

however - Its not a miner issue but how you creating your cert.  So i would suggest googling that all we will have to do.

**Comment by modislaszlo** [comment]
I'm running the exact command from the #321 (openssl pkcs12 -export -out domain.name.pfx -inkey domain.name.key -in domain.name.crt with the correct file names). There is no way I fucked it up because I did it like 10 times and I said the certificate works perfectly for burst wallet(and to create *.jks file for burst is 10 times harder). Did you try the miner with a certificate issued by a valid authority? Maybe only the localhost one works.

**Comment by nitr8** [comment]
please watch your language in here - Mine is working externally with my cert no problem - i gave you a localhost one to show you its got nothing to do with the miner. 

Yes i have a valid wildcard cert for 2 domains that im using it on - i don't use lets encrypt 

<img width="430" alt="image" src="https://user-images.githubusercontent.com/541890/39236554-635bd7a4-4879-11e8-951b-0d656c292a98.png">

is auth valid enough for you?

**Comment by Creepsky** [comment]
Should also work for Linux and Mac now (dev branch).

I used this command to create a self signed certificate: `openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout creepMiner.key -out creepMiner.crt`

Be sure to use the same name for the key and cert file! Otherwise it will not work.

Enter the path of the cert file in the config like this:

```
    "webserver" : {
        "certificate" : {
            "pass" : "",
            "path" : "creepMiner.crt"
        },
    }
```

http giving me an error:
![grafik](https://user-images.githubusercontent.com/8005422/39526518-423ef92e-4e1f-11e8-8b97-751268bed308.png)

https is working (the warning sign is because it is a self signed certificate):
![grafik](https://user-images.githubusercontent.com/8005422/39526548-6465a96c-4e1f-11e8-9828-1abb3d27c445.png)

However I cant test if the websocket is working, because Firefox don't let me because of security reasons.

**Comment by nitr8** [comment]
using Let's Encrypt cert it works perfect

See attached image:
![image](https://user-images.githubusercontent.com/541890/39589130-9ba48270-4efd-11e8-9791-90bc21f36939.png)

Going ahead and closing - tested on windows miner / linux / macOS

**Comment by modislaszlo** [comment]
I don't understand how it's working for you but for me it's not working:
Valid certificate:
![screenshot from 2018-05-11 19-43-17](https://user-images.githubusercontent.com/1011545/39936158-47173e02-5554-11e8-8e83-98db18ebe0ae.png)
CreepMiner config:
![screenshot from 2018-05-11 19-45-57](https://user-images.githubusercontent.com/1011545/39936179-508ef164-5554-11e8-8023-8335393554e3.png)
Error:
![screenshot from 2018-05-11 19-45-57](https://user-images.githubusercontent.com/1011545/39936267-982dc856-5554-11e8-993c-10dd814b0e6b.png)
