### ISSUE TITLE
creepMiner 1.8.0 fails to start on MacOS

### ISSUE THREAD

**Issue by ciclopez** [Creepsky/creepMiner#378]
creepMiner version: **1.8.0**
OS name: **MacOS**
OS version: reproduced in **10.12.6** and **10.13.4**

**Steps to reproduce:**
1. `git clone https://github.com/Creepsky/creepMiner`
2. `cd creepMiner`
3. `conan install . --build=missing`
4. `cmake CMakeLists.txt -DCMAKE_BUILD_TYPE=RELEASE -DNO_GPU=ON`
5. `make -j$(nproc)`
6. copy files from "resources" to "bin"
7. create mining.conf in "bin" and set relevant values
8. `chmod +x bin/run.sh`
9. `bin/run.sh`

**Error:**
Aborting program due to exceptional state: collate_byname<char>::collate_byname failed to construct for

![screen shot 2018-04-24 at 14 06 25](https://user-images.githubusercontent.com/16405677/39186456-c169584e-47ca-11e8-8e30-43a1292e0f4d.png)

**These same steps works perfectly with previous versions of CreepMiner**

[creepMiner_20180424_120427.559257.log](https://github.com/Creepsky/creepMiner/files/1942686/creepMiner_20180424_120427.559257.log)
[mining.conf.txt](https://github.com/Creepsky/creepMiner/files/1942687/mining.conf.txt)

**Comment by nitr8** [comment]
@ciclopez - please follow wiki steps :)
dont use run 
1. `git clone https://github.com/Creepsky/creepMiner`
2. `cd creepMiner`
3. `conan install . --build=missing`
4. `cmake CMakeLists.txt -DCMAKE_BUILD_TYPE=RELEASE -DNO_GPU=ON`
5. `make -j$(nproc)`
6. cp resources\public bin\
7. create mining.conf in "bin" and set relevant values
8. `cd bin`
9. `./creepMiner`

**Comment by ciclopez** [comment]
I see you updated the Wiki, it works now thanks! and sorry to post an issue for this, I asked in Discord but nobody answered.
Closing it.

**Comment by nitr8** [comment]
@ciclopez - sorry i missed it in discord 😀 hit me up there should you have any questions please
