### ISSUE TITLE
It is possible define "deadline" value for miner?

### ISSUE THREAD

**Issue by Adavan83** [Creepsky/creepMiner#38]
Hello.
Some others miners have capabilities to define "deadline" to miner side (if deadline for miner is too low, nuances isnt sended).
If not, it is possible add this feature?
Many thanks.

**Comment by Creepsky** [comment]
Hi,
it is not possible to define the target deadline manually, but it is set when fetching mining data from the pool automatically.
I will add this feature and push it (+ how to use).

**Comment by Creepsky** [comment]
Ok I implemented it, please see [the config description](https://github.com/Creepsky/burst-miner#config) under "targetDeadline".
If something is wrong, please post it here.

**Comment by Adavan83** [comment]
Many thanks, i test it and let you know.

**Comment by Adavan83** [comment]
I try to compile and install new dev version, byt without success, see #42.

**Comment by Adavan83** [comment]
Sorry, my fault.

**Comment by Adavan83** [comment]
I attempt define deadline like you describe `"targetDeadline": "1m 2d 12:34:56"`, but without success. Miner drop down with error message:
```
adavan@Debian:~/BurstCoin/Creepsky_150/bin$ ./burst-miner 
18:31:03: Burst miner 1.5.0 Unix
18:31:03: ----------------------------------------------
18:31:03: Github:   https://github.com/Creepsky/burst-miner
18:31:03: Author:   Creepsky [creepsky@gmail.com]
18:31:03: Burst :   BURST-JBKL-ZUAV-UXMB-2G795
18:31:03: ----------------------------------------------
18:31:03: Based on http://github.com/uraymeiviar/burst-miner
18:31:03: author : uray meiviar [ uraymeiviar@gmail.com ]
18:31:03: please donate to support developments :
18:31:03:  [ Burst   ] BURST-8E8K-WQ2F-ZDZ5-FQWHX
18:31:03:  [ Bitcoin ] 1UrayjqRjSJjuouhJnkczy5AuMqJGRK4b
18:31:03: ----------------------------------------------
18:31:03: using config file : mining.conf
18:31:03: there is an error in the config file!
18:31:03: JSON Exception: JSON syntax error
18:31:03: Stackframe

main (in "src/main.cpp", line 38)
readConfigFile (in "src/MinerConfig.cpp", line 48)

18:31:03: Aborting program due to invalid configuration
```
Thank you for fixing this issue.

**Comment by Creepsky** [comment]
Seems like you have a syntax error in the mining.conf.
Copy paste it here https://jsonformatter.curiousconcept.com and click on process.

**Comment by Creepsky** [comment]
Does this error still occur or can I close this issue?
