### ISSUE TITLE
libPoco.60 dependency, scratching my head!

### ISSUE THREAD

**Issue by HayvanOnTech** [Creepsky/creepMiner#383]
I am on brand new Ubuntu 18.04 and it only shows libpoco50. That was enough in creepMiner1.7x but 1.8 .deb has a libpoco60 dependecy, I can't figure out how/where to get that! Of course the .deb is misbehaved, it should list the requirement or, better, be a static build. Anyway, I can't even imagine the Debian version that includes libpoco60!

**Comment by itompkins** [comment]
I am having the same issue. Though i was partially able to get around it by running the run.sh script that is in the folder. Though when I try to run the creepMiner executable  by it self, i get the same error as above. I used to be able to just run the executable with out issue. I am thinking that maybe the new POCO library was moved to a different folder in ubuntu 18.04 and that is why the executable is having issues finding it? I also had the same issue when i tried to install the POCO library from ubuntu 16.04 as well.

**Comment by chrisf4lc0n** [comment]
I only just compiled the creepMiner from source following the Wiki Guide and had no issues.

**Comment by itompkins** [comment]
@chrisf4lc0n - when you did how did you run creep? Did you run the executable ./creep miner or did you use the run.sh screen.sh script?

**Comment by chrisf4lc0n** [comment]
@itompkins I used ./creep.

**Comment by nitr8** [comment]
Hi as explained in opening a issue, this is for bug-tacking and enhancements. Please would you move this discussion to discord.

Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. 
Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. We have a great discord to ask for help here: https://discord.gg/qnjyVQt
- [ ] **DO** include log files.
- [ ] **DO** include the miner config.
- [ ] **DO** describe the operating system for the Server and Client (Windows / Linux). Also, the run-time platform and versions.
