### ISSUE TITLE
config issue

### ISSUE THREAD

**Issue by NagaokaJoe** [Creepsky/creepMiner#388]
Hi i am having this issue after running the miner for the first time:
05:26:57: Server URL : http://127.0.0.1:8080
05:26:57: Aborting program due to exceptional state: collate_byname<char>::collate_byname failed to construct for 
MacMini:bin

Seems like a config issue. Can you give me an idea of what i am doing wrong here? thx

**Comment by nitr8** [comment]
```
- use the [**latest release**](https://github.com/Creepsky/creepMiner/releases/latest), your issue may be solved already
- describe the problem as accurately as possible
- describe all steps to get to your problem so it can be traced - otherwise it is nearly impossible to fix it!
- provide additional information like the name of your **OS**, the miner **version**, your **gcc version**, ...
- attach **log files**, **screenshots** and your **config-fIle**
```

**Comment by Creepsky** [comment]
Should be fixed in dev branch.
Never seen this error message, but i guess it has to do with std::locale.

**Comment by NagaokaJoe** [comment]
nitr8. Thank you so much. You were right. I was not using the right release. Can you share your burst ID? I'd like to make a donation.

**Comment by nitr8** [comment]
hey @NagaokaJoe 

Glad you got it resolved - please check about the about page on the miner UI :) Its new so posting here so others can see too.

![image](https://user-images.githubusercontent.com/541890/39700214-b6d43d0e-51fc-11e8-968d-58ca344f1142.png)

BURST-2ZXJ-NC7Q-PM3W-GFU97

So is this resolved? May I close this issue?

**Comment by NagaokaJoe** [comment]
Yes. Please close it. I am sorry for the inconvenience.

iPhoneから送信

2018/05/07 20:44、nitr8 <notifications@github.com>のメール:
