### ISSUE TITLE
Cant compile creepMiner

### ISSUE THREAD

**Issue by mdawson1977** [Creepsky/creepMiner#389]
Hi all,

I was following this guide below;

update the system & reboot
sudo yum -y update && sudo reboot

Install Extra Packages for Enterprise Linux
sudo yum -y install epel-release

install git
sudo yum -y install git

download creepminer
git clone https://github.com/Creepsky/creepMiner

install poco libraries
sudo yum -y install poco-*

install openssl headers
sudo yum -y install openssl-devel

Here is the trick to get gcc 5.3.1 working

Install Software Collections (www.softwarecollections.org). It gives you
The power to build, install, and use multiple versions of software
on the same system, without affecting system-wide installed packages.
sudo yum -y install centos-release-scl

Add the Devtoolset-4 collection, which includes gcc 5.3.1
sudo yum -y install devtoolset-4

to start using software collections, just run

$ scl enable devtoolset-4 bash

 and you get a "virtual" environment which includes gcc 5.3.1:

$ gcc --version
 That's all. Type "exit" to exit the environment...

 Compile CreepMiner:
cd creepMiner
echo make | scl enable devtoolset-4 - 

at the last step 
 Compile CreepMiner:
cd creepMiner
echo make | scl enable devtoolset-4 - 

gives me the error make: *** No targets specified and no makefile found.  Stop.

Can anyone help with this??

Thanks in advance

**Comment by nitr8** [comment]
Please use the pre compiled binaries or use conan instructions if you have to compile from source https://github.com/Creepsky/creepMiner/wiki/Compiling-from-source

**Comment by mdawson1977** [comment]
Thanks nitr8 ill give that a try.

**Comment by mdawson1977** [comment]
Hi all,

Started compiling from source as nitr8 suggested now when I run;

conan install . --build=missing -s compiler.libcxx=libstdc++11

I get these errors;

[root@Centos7 creepMiner]# conan install . --build=missing -s compiler.libcxx=libstdc++11                              
Auto detecting your dev setup to initialize the default profile (/root/.conan/profiles/default)                        
ERROR: Unable to find a working compiler                                                                               
Default settings                                                                                                       
        os=Linux                                                                                                       
        os_build=Linux                                                                                                 
        arch=x86_64                                                                                                    
        arch_build=x86_64                                                                                              
        build_type=Release                                                                                             
*** You can change them in /root/.conan/profiles/default ***                                                           
*** Or override with -s compiler='other' -s ...s***                                                                    
                                                                                                                       
                                                                                                                       
ERROR: compiler not defined for compiler.libcxx                                                                        
Please define compiler value first too

**Comment by mpenagar** [comment]
Guide at [https://github.com/Creepsky/creepMiner/issues/121#issuecomment-306068541](https://github.com/Creepsky/creepMiner/issues/121#issuecomment-306068541) is obsolete. Here you've got an updated one (could be included in the wiki?):

```
# CentOS 7 - creepminer 1.8.0
# tested on a clean minimal installation:
# http://isoredirect.centos.org/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-1708.iso

# update the system & reboot
sudo yum -y update && sudo reboot

# install Extra Packages for Enterprise Linux
sudo yum -y install epel-release

# install Software Collections (www.softwarecollections.org). It gives you
# the power to build, install, and use multiple versions of software
# on the same system, without affecting system-wide installed packages.
sudo yum -y install centos-release-scl

# add the devtoolset-4 collection, which includes gcc 5.3.1
sudo yum -y install devtoolset-4

# install cmake3, git and pip
sudo yum -y install cmake3 git python-pip

# upgrade pip
sudo pip install --upgrade pip

# install conan
sudo pip install conan

# enable devtoolset-4 software collection
# you get a "virtual" environment which includes gcc 5.3.1:
# $ gcc --version
scl enable devtoolset-4 bash

# download creepminer
git clone https://github.com/Creepsky/creepMiner
cd creepMiner

# configure cmake3 to be used during installation and check.
# NOTE: this is not the correct way to use cmake3, see:
# https://stackoverflow.com/questions/48831131/cmake-on-linux-centos-7-how-to-force-the-system-to-use-cmake3/48842999#48842999
mkdir cmake && ln -s $(which cmake3) cmake/cmake
export PATH=$(pwd)/cmake:$PATH

# check version (should be 3.x)
cmake --version

# compile
# NOTE: "conan install . --build=missing" downloads prebuilt packeges linked to incompatible libs
conan install . --build
cmake CMakeLists.txt -DCMAKE_BUILD_TYPE=RELEASE -DNO_GPU=ON
make

# exit from devtoolset-4 software collection environment
exit
```

**Comment by nitr8** [comment]
@mpenagar - nice one, thanks man - https://github.com/Creepsky/creepMiner/wiki/Compiling-from-source added there.

I will try and make it more aligned to be a reference. Please hit me up any time should you spot a discrepancy :)

**Comment by nitr8** [comment]
@mdawson1977 - please try the guide provided kindly by @mpenagar

**Comment by mpenagar** [comment]
Hi, just a commen,

the recipe includes so many steps that I would include it in a single "source code" block, juts copy and paste it.
