### ISSUE TITLE
Why my speed is not increase?

### ISSUE THREAD

**Issue by babasa** [Creepsky/creepMiner#391]
Hi i want to ask why when i adding drive my speed is not increased? ex: mining drive A, speed mining is 6 MB, and when use mining drive A and drive B , my speed mining still 6 MB

while when i try to use other miner its show that adding more drive also increase my speed mining, is there something i do wrong? thank you

**Comment by nitr8** [comment]
Hi babasa,

- [ ] **AVOID** using the issue tracker for questions or help. 
Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. We have a great discord to ask for help here: https://discord.gg/qnjyVQt
