### ISSUE TITLE
deadline exceeded - with ALL POC2 plots

### ISSUE THREAD

**Issue by kaeptnb** [Creepsky/creepMiner#394]
Hello,

using creepminer-dev branch (from yesterday), i get:

16:08:30: miner1: error on submitting nonce! (20:23:56)                                                                                      
16:08:30:        nonce:        195873657
16:08:30:        in:           /mnt/d9/burst/poc2/burstidnumbercensored_195870721_40960
16:08:30:        from:         m11 (127.0.0.1)
16:08:30:        error-code:   1008
16:08:30:        error-text:   deadline exceeds deadline limit of the pool

for every deadline found in a POC2 Plotfile; even if the deadline (like in this example) is really good (<1day), it gets rejected with 1008, clearly shouldn't ?!

All deadlines found in POC1 Plotfiles are submitted and accepted fine... ?!

Can you tell me what more infos you need to debug this?
Greetings
Tobias

**Comment by rico666** [comment]
If you do it on the MainNet, which is still PoC1 that is the expected behavior.

**Comment by kaeptnb** [comment]
oh sorry, i - wrongly -assumed POC2 support meant (just like you mentioned with jminer) that both is supported; i understand, creepminer will support POC2 files, but only after the hardfork, not before

thanks for the clarification!

Greetings

**Comment by rico666** [comment]
Every miner will support PoC2 files after the PoC2 switch (a little later than the HF itself).

What creepminer will support in addition to that will be "interpreting PoC1 files as PoC2"

What you tried now was "interpreting PoC2 files as PoC1" - this is not supported by creepminer.

**Comment by Rion1337** [comment]
Would it be worth the effort to add support for interpreting PoC2 as PoC1?
