### ISSUE TITLE
Crash on startup if ".plotting" file exists

### ISSUE THREAD

**Issue by brmmm3** [Creepsky/creepMiner#395]
Used creepMiner version 1.9.0.3 on Kubuntu 18.04.

If a plot file exists which is currently plotted and has the extensions ".plotting", then creepMiner crashes on startup.
The crash occurs in getStartNonceFromPlotFile called in isValidPlotFile.
A simple solution is to check at the beginning of isValidPlotFile if a file ends with ".plotting".

	if (0 == filePath.compare(filePath.length() - 9, 9, ".plotting")) {
		return PlotCheckResult::Incomplete;
	}

Best regards,
Martin

**Comment by Creepsky** [comment]
All plot files with extensions will now be seen as invalid.
Implemented in 1.9.0.5.
