### ISSUE TITLE
Could not read mirror for nonce

### ISSUE THREAD

**Issue by 4nt1g0** [Creepsky/creepMiner#396]
Mining against testnet with PoC2 activated I get the following error on every block while mining:

> Could not read mirror for nonce [ERRFMT]+ in /mnt/d/Burst/plots/16598168020165113423_0_409600_409600

for all plot files

Still deadlines are found, submitted and accepted. I even forged blocks.

I used Version : 1.9.0 (DEV. 4) and PoC1 plots

**Comment by Creepsky** [comment]
ERRFMT <- your miner is not using 64 bit integers? Self compiled?
Please try the latest dev version.

**Comment by 4nt1g0** [comment]
Self-compiled miner yes. On the newest dev version I no longer get this error.

**Comment by nitr8** [comment]
Closing false positive
