### ISSUE TITLE
Error make

### ISSUE THREAD

**Issue by testmaster99** [Creepsky/creepMiner#398]
I have the following error when making the make command
![imagen](https://user-images.githubusercontent.com/30342657/40725124-e8359068-6422-11e8-9f5f-ce7fcb72d42e.png)

**Comment by nitr8** [comment]
Hi please open a VSE with the relevant request information. It seems you trying to bull on a rpi. That's not for the faint heartened hit me up on discord I can give to pe built binary it get them from pool.creepminwe.net
