### ISSUE TITLE
1.8.1 Windows: Web monitoring stopped updating.

### ISSUE THREAD

**Issue by Beddhist** [Creepsky/creepMiner#406]
My miner has functioned without problems for about a week. Then suddenly, it has stopped updating the web monitoring page. The current block timer is ticking, but nothing else will update, not the progress bar, nor the current block, nor the Plots page.

I tried rebooting (Windows installed updates) and restarting the miner.

### Your environment
* version of creepMiner. - 1.8.1
* version of OS. - Win 10 Pro 64 bit
* which browser and its version. - Chrome and Firefox, both latest.

### Steps to reproduce
Happens all the time now.

### Expected behavior
Current block should update, progress bar should move.

[creepMiner_20180613_222343.844504.log](https://github.com/Creepsky/creepMiner/files/2101369/creepMiner_20180613_222343.844504.log)

[mining.conf.txt](https://github.com/Creepsky/creepMiner/files/2101374/mining.conf.txt)

**Comment by Beddhist** [comment]
I now have 1.8.1 running on Linux Mint and this one does not have the problem, yet. The Windows miner is still not updating.

**Comment by nitr8** [comment]
@Beddhist - delete your db file - restart miner also - could you try 1.9.0.15

**Comment by Beddhist** [comment]
Tried deleting the db and restarting, didn't work.
I can't find the binaries for 1.9, so I am now running 1.7.18.  It is working so far.
Thank you.

**Comment by nitr8** [comment]
@Beddhist 

- cool hit me up on discord if you wanna play with 1.9 ill organise you something
