### ISSUE TITLE
1.8.2 - When creepminer works through the creepminer proxy, the deadline is incorrectly considered.

### ISSUE THREAD

**Issue by Monstreek** [Creepsky/creepMiner#409]
When creepminer works through the creepminer proxy, the deadline is incorrectly considered.
When working directly with the pool, there is no problem.

* 1.8.2.0.
* Ubuntu 16.04.3 LTS

The pool calculated a different deadline for your nonce than your miner has!
12:22:44:       Plot file: /mnt/b1/5955708417007022062_1201000000000_3559920_3559920
12:22:44:       Pools deadline: 2334255y 3m 1d 10:02:50
12:22:44:       Your deadline: 3m 27d 00:28:51

**Comment by blaqone** [comment]
I do have exactly the same problem!

**Comment by Marko-Miner** [comment]
in 1.7.19.0 was the solution :
 "calculateEveryDeadline" : false,
for me was this the  solution
now my miner run good. and forwarding go
but before i have the same Problem

**Comment by blaqone** [comment]
Yes, this seems to solve the problem.

**Comment by jboadas** [comment]
I have this same problem but I am not using a proxy, i am submitting directly to the wallet
