### ISSUE TITLE
Embed bootswatch themes

### ISSUE THREAD

**Issue by damccull** [Creepsky/creepMiner#424]
Occasionally I will have a problem with creepminer where it refuses to load the theme because the bootswatch.com website either has a certificate problem, or my computer can't otherwise access that website. This leads to an unusable UI. I would like to request that in the next version of creepminer, download and embed the theme files directly into the program so it can access them locally. Or, if embedding them isn't easy or possible, at least download them to a local folder dedicated to UI files.

**Comment by Creepsky** [comment]
@COhsrt was so kind to make these changes in #425. Maybe [1.8.3](https://github.com/Creepsky/creepMiner/releases/tag/1.8.3) is what youre looking for.

**Comment by damccull** [comment]
This is what happens when I'm a version behind. Lol.

**Comment by nitr8** [comment]
Closing - this is now resolved - don't like the solution but never the less.
