### ISSUE TITLE
CreepMiner 1.7.9 http rendering in text mode

### ISSUE THREAD

**Issue by sgabay242** [Creepsky/creepMiner#426]
Hello, I'm testing the latest release 1.7.9 and the software unfortunately is not rendering the images

Attached is an image for reference

![image](https://user-images.githubusercontent.com/23418879/42354967-46fbf150-807f-11e8-9d1a-b3be228e4fb1.png)

18:11:27: creepMiner 1.7.19 Windows x64
18:11:27: Release mode -CUDA -OpenCL +SSE4 +AVX +AVX2
18:11:27: ----------------------------------------------
18:11:27: Github:   https://github.com/Creepsky/creepMiner
18:11:27: Author:   Creepsky [creepsky@gmail.com]
18:11:27: Burst :   BURST-JBKL-ZUAV-UXMB-2G795
18:11:27: ----------------------------------------------
18:11:27: There is a new version () on
18:11:27:       https://github.com/Creepsky/creepMiner
18:11:27: You are running the webserver without protecting it with an username and/or password!
18:11:27: Every person with access to the webserver has FULL admin rights!
18:11:33: ║▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓║ 100.00 % ║ 709.70 MB/s

The problem is reproduced on two computers running windows 10 Chrome Latest Version 67.0.3396.99 (Official Build) (64-bit)

Open the browser to the creepminer IP:PORT and there is not graphics but only text

Attempted to remove cookies and clear the cache but no luck

**Comment by davesmith87** [comment]
Getting the same thing with 1.8.1 on Chrome Windows 10 64bit.

**Comment by Creepsky** [comment]
Fixed in #425.
Please copy and overwrite your `public` folder with this version: https://github.com/Creepsky/creepMiner/tree/master/resources/public.

If you want to use 1.9.17, you can use this link to download a zip of the current source code: https://github.com/Creepsky/creepMiner/archive/master.zip. (look for `resources/public`)

I will release a new 1.8 version with the fixed webinterface soon.

**Comment by sgabay242** [comment]
Thank you! It looks like it was resolved, we will continue doing more
testing and let you know otherwise.

Saul

**Comment by sgabay242** [comment]
We noticed these output on the console, not sure if is related or not to
the issue we reported with the web interface

06:55:06: creepMiner 1.8.2 Windows x64
06:55:06: Release mode -CUDA +OpenCL +SSE4 +AVX +AVX2
06:55:06: ----------------------------------------------
06:55:06: Github:   https://github.com/Creepsky/creepMiner
06:55:06: Author:   Creepsky [creepsky@gmail.com]
06:55:06: Burst :   BURST-JBKL-ZUAV-UXMB-2G795
06:55:06: ----------------------------------------------
06:55:06: You are running the webserver without protecting it with an
username and/or password!
06:55:06: Every person with access to the webserver has FULL admin rights!
*06:55:51: Exception occured: Software caused connection abort*
*06:55:51:       error-code: 10053*
*06:55:51:       class: class Poco::Net::ConnectionAbortedException*
*06:55:51: Exception occured: Software caused connection abort*
*06:55:51:       error-code: 10053*
*06:55:51:       class: class Poco::Net::ConnectionAbortedException*

**Comment by nitr8** [comment]
This has now been resolved
