### ISSUE TITLE
Come on Creepsky, one last update to creep Miner?  :-)

### ISSUE THREAD

**Issue by pir8radio** [Creepsky/creepMiner#451]
Come on Creepsky, one last update to creep Miner?  :-)

**Comment by nitr8** [comment]
This is not an issue

**Comment by pir8radio** [comment]
Creepminer doesnt work with todays signum block chain.. so yes it is an issue.   Creepminer needs to be updated to work with the latest signum blockchain..

**Comment by Creepsky** [comment]
Is there some kind of paper or list of what changed and is different between Signum and Burst?
What is the reference miner people use nowadays?

**Comment by pir8radio** [comment]
HEY! the star themselves!   Signum miner is the primary.   I was able to get yours to run and looks awesome, but a bit behind on the network changes.       Today's miner is a fork of scavenger located here: https://github.com/signum-network/signum-miner      Let me know if you are willing to revive creepminer i would love to help any way i can and test.
