### ISSUE TITLE
Popup in deadlines graph on HTTP server

### ISSUE THREAD

**Issue by Creepsky** [Creepsky/creepMiner#51]
A mouseover popup would be nice, if you hover the bullets in the deadlines graph on the HTTP server. It can show for example the blockheight and the deadline.

**Comment by guelz** [comment]
yes, exactly what I thought!-) like the graphs on uray pools...

**Comment by Creepsky** [comment]
Added in 30b38ee
https://github.com/Creepsky/creepMiner/releases/tag/2.3.6.1
