### ISSUE TITLE
bunch of .DLL Missing

### ISSUE THREAD

**Issue by N8Thrasher** [Creepsky/creepMiner#54]
MSVCP140.DLL
VCRUNTIME140.DLL

Downloading the missing file now.

**Comment by Creepsky** [comment]
Wait don't download them separate

**Comment by N8Thrasher** [comment]
there's a lot of dll's missing

downloading them one by one

**Comment by Creepsky** [comment]
If you install the Visual C++ Redistributable from Microsoft this should be fine.

**Comment by N8Thrasher** [comment]
DLL Done thanks
