### ISSUE TITLE
\/

### ISSUE THREAD

**Issue by Pascal66** [Creepsky/creepMiner#79]
Strange but usable modifications of config file :
```
"miningInfo" : "http:\/\/127.0.0.1:8124",
 "submission" : "http:\/\/127.0.0.1:8124",
 "wallet" : "http:\/\/127.0.0.1:8125"

```

**Comment by Creepsky** [comment]
All ok, the / just gets escaped (/ -> \/ // -> \/\/), see [RFC 7159 page 7](https://tools.ietf.org/html/rfc7159).
Escaping the slash is optional and I want to remove it, but it has low priority because it don't break anything.
