### ISSUE TITLE
Please check

### ISSUE THREAD

**Issue by N8Thrasher** [Creepsky/creepMiner#80]
Im not sure what happening, it's just not reading the plot files but it's showing the block winner. I have to restart the miner for it to work again.

![image](https://cloud.githubusercontent.com/assets/24593637/23328802/792540ac-fb3b-11e6-8039-c58213e71466.png)

here's my config file

```
{
    "Start Server" : true,
    "logging" : {
        "config" : "information",
        "general" : "information",
        "miner" : "information",
        "nonceSubmitter" : "information",
        "path" : "",
        "plotReader" : "information",
        "plotVerifier" : "information",
        "server" : "fatal",
        "session" : "error",
        "socket" : "off",
        "wallet" : "information"
    },
    "maxBufferSizeMB" : 128,
    "maxPlotReaders" : 0,
    "miningInfoUrl" : "http:\/\/m.burst4all.com:8124",
    "miningIntensity" : 3,
    "passphrase" : {
        "algorithm" : "aes-256-cbc",
        "decrypted" : "",
        "deleteKey" : false,
        "encrypted" : "",
        "iterations" : 0,
        "key" : "",
        "salt" : ""
    },
    "plots" : [
        "H:\\plots"
    ],
    "poolUrl" : "http:\/\/m.burst4all.com:8124",
    "serverUrl" : "http:\/\/192.168.1.2:8080",
    "submissionMaxRetry" : 3,
    "targetDeadline" : "1y 8m 0d 15:00:00",
    "timeout" : 45,
    "walletUrl" : "https:\/\/wallet.burst-team.us:8127"
}
```

**Comment by Creepsky** [comment]
Pushed a new release with a fix for this: https://github.com/Creepsky/creepMiner/releases/tag/2.4.6.
Please test it.

**Comment by N8Thrasher** [comment]
Thanks. will update if still has some problems

**Comment by N8Thrasher** [comment]
`26.02.2017 06:39:45 (0, src\main.cpp, 45, Information): creepMiner 1.4.4 Windows
26.02.2017 06:39:45 (0, src\main.cpp, 46, Information): ----------------------------------------------
26.02.2017 06:39:45 (0, src\main.cpp, 47, Information): Github:   https://github.com/Creepsky/creepMiner
26.02.2017 06:39:45 (0, src\main.cpp, 48, Information): Author:   Creepsky [creepsky@gmail.com]
26.02.2017 06:39:45 (0, src\main.cpp, 49, Information): Burst :   BURST-JBKL-ZUAV-UXMB-2G795
26.02.2017 06:39:45 (0, src\main.cpp, 50, Information): ----------------------------------------------
26.02.2017 06:39:45 (0, src\main.cpp, 51, Information): Based on http://github.com/uraymeiviar/burst-miner
26.02.2017 06:39:45 (0, src\main.cpp, 52, Information): author : uray meiviar [ uraymeiviar@gmail.com ]
26.02.2017 06:39:45 (0, src\main.cpp, 53, Information): please donate to support developments :
26.02.2017 06:39:45 (0, src\main.cpp, 54, Information):  [ Burst   ] BURST-8E8K-WQ2F-ZDZ5-FQWHX
26.02.2017 06:39:45 (0, src\main.cpp, 55, Information):  [ Bitcoin ] 1UrayjqRjSJjuouhJnkczy5AuMqJGRK4b
26.02.2017 06:39:45 (0, src\main.cpp, 56, Information): ----------------------------------------------
26.02.2017 06:39:45 (0, src\main.cpp, 70, Information): using config file mining.conf
26.02.2017 06:39:45 (0, src\MinerConfig.cpp, 174, Error): Error while reading plot files!
Invalid access: Can not convert empty value.
26.02.2017 06:39:45 (0, src\MinerConfig.cpp, 176, Error): Stackframe
main (in "src\main.cpp", line 39)
readConfigFile (in "src\MinerConfig.cpp", line 51)

26.02.2017 06:39:45 (0, src\Miner.cpp, 46, Critical): Pool/Wallet/MiningInfo are all empty! Miner has nothing to do and shutting down!
`

not working

**Comment by Creepsky** [comment]
There was a problem with the config file.
Fixed it and uploaded to https://github.com/Creepsky/creepMiner/releases/tag/2.4.6.

**Comment by N8Thrasher** [comment]
5 hours running... seems ok now

**Comment by N8Thrasher** [comment]
> 26.02.2017 11:51:04 (4, src\NonceSubmitter.cpp, 72, Information): Yey-Burst: nonce submitted (5m 18d 18:24:04)
	nonce: 11040089
	in H:\plots\10871057679973349262_11004392_409600_409600
26.02.2017 11:51:04 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (5m 0d 20:42:29)
	nonce: 11475870
	in: H:\plots\10871057679973349262_11413992_409600_409600
26.02.2017 11:51:04 (9, src\PlotReader.cpp, 169, Information): H:\plots\10871057679973349262_13052392_409600_409600 done 100.00 GB in 0.408s (~245.08 GB/s)
26.02.2017 11:51:04 (4, src\NonceSubmitter.cpp, 144, Debug): Better deadline in pipeline, stop submitting! (5m 18d 18:24:04)
26.02.2017 11:51:04 (7, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (4m 8d 14:02:10)
	nonce: 11511861
	in: H:\plots\10871057679973349262_11413992_409600_409600
26.02.2017 11:51:04 (5, src\NonceSubmitter.cpp, 48, Information): Yey-Burst: nonce on the way (5m 0d 20:42:29)
26.02.2017 11:51:05 (9, src\PlotReader.cpp, 169, Information): H:\plots\10871057679973349262_13461992_123312_123312 done 30.11 GB in 0.123s (~244.75 GB/s)
26.02.2017 11:51:04 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (1m 28d 16:11:57)
	nonce: 11591850
	in: H:\plots\10871057679973349262_11413992_409600_409600
26.02.2017 11:51:05 (4, src\NonceSubmitter.cpp, 48, Information): Yey-Burst: nonce on the way (4m 8d 14:02:10)
26.02.2017 11:51:05 (5, src\NonceSubmitter.cpp, 144, Debug): Better deadline in pipeline, stop submitting! (5m 0d 20:42:29)
26.02.2017 11:51:05 (107, src\NonceSubmitter.cpp, 48, Information): Yey-Burst: nonce on the way (1m 28d 16:11:57)
26.02.2017 11:51:05 (4, src\NonceSubmitter.cpp, 144, Debug): Better deadline in pipeline, stop submitting! (4m 8d 14:02:10)
26.02.2017 11:51:05 (107, src\NonceSubmitter.cpp, 59, Debug): Submit-loop 1 (1m 28d 16:11:57)
26.02.2017 11:51:05 (107, src\NonceSubmitter.cpp, 72, Information): Yey-Burst: nonce submitted (1m 28d 16:11:57)
	nonce: 11591850
	in H:\plots\10871057679973349262_11413992_409600_409600
26.02.2017 11:51:06 (107, src\NonceSubmitter.cpp, 136, Information): Yey-Burst: nonce confirmed (1m 28d 16:11:57)
	nonce: 11591850
	in H:\plots\10871057679973349262_11413992_409600_409600
26.02.2017 11:53:14 (0, src\Miner.cpp, 179, Debug): Verification queue cleared.
26.02.2017 11:53:14 (0, src\Miner.cpp, 199, Notice): --------------------------------------------------
block#      332342
scoop#      855
baseTarget# 781188
--------------------------------------------------
26.02.2017 11:53:16 (108, src\MinerData.cpp, 236, Information): --------------------------------------------------
last block winner: 
block#             332341
winner-numeric     8568867472463842787
winner-address     QMH5-L5ZT-NK9Z-9VPUF
winner-name        JMGP&JAGS
--------------------------------------------------
26.02.2017 12:13:40 (0, src\Miner.cpp, 179, Debug): Verification queue cleared.
26.02.2017 12:13:40 (0, src\Miner.cpp, 199, Notice): --------------------------------------------------
block#      332343
scoop#      1427
baseTarget# 937425
--------------------------------------------------
26.02.2017 12:20:05 (0, src\Miner.cpp, 179, Debug): Verification queue cleared.
26.02.2017 12:20:05 (0, src\Miner.cpp, 199, Notice): --------------------------------------------------
block#      332344
scoop#      3136
baseTarget# 976783
--------------------------------------------------
26.02.2017 12:20:12 (110, src\MinerData.cpp, 236, Information): --------------------------------------------------
last block winner: 
block#             332343
winner-numeric     13767309312433786497
winner-address     Q5N3-W4EA-5M27-DGU5Y
winner-name        AngryChicken
--------------------------------------------------

**Comment by Creepsky** [comment]
Can you please copy paste the first 26 lines in the log file.

**Comment by Pascal66** [comment]
Work well with the last release.

http://priveyes.freeboxos.fr:82/pool
Pascal

**Comment by N8Thrasher** [comment]
26.02.2017 18:34:10 (0, src\main.cpp, 45, Information): creepMiner 1.4.4 Windows
26.02.2017 18:34:10 (0, src\main.cpp, 46, Information): ----------------------------------------------
26.02.2017 18:34:10 (0, src\main.cpp, 47, Information): Github:   https://github.com/Creepsky/creepMiner
26.02.2017 18:34:10 (0, src\main.cpp, 48, Information): Author:   Creepsky [creepsky@gmail.com]
26.02.2017 18:34:10 (0, src\main.cpp, 49, Information): Burst :   BURST-JBKL-ZUAV-UXMB-2G795
26.02.2017 18:34:10 (0, src\main.cpp, 50, Information): ----------------------------------------------
26.02.2017 18:34:10 (0, src\main.cpp, 51, Information): Based on http://github.com/uraymeiviar/burst-miner
26.02.2017 18:34:10 (0, src\main.cpp, 52, Information): author : uray meiviar [ uraymeiviar@gmail.com ]
26.02.2017 18:34:10 (0, src\main.cpp, 53, Information): please donate to support developments :
26.02.2017 18:34:10 (0, src\main.cpp, 54, Information):  [ Burst   ] BURST-8E8K-WQ2F-ZDZ5-FQWHX
26.02.2017 18:34:10 (0, src\main.cpp, 55, Information):  [ Bitcoin ] 1UrayjqRjSJjuouhJnkczy5AuMqJGRK4b
26.02.2017 18:34:10 (0, src\main.cpp, 56, Information): ----------------------------------------------
26.02.2017 18:34:10 (0, src\main.cpp, 70, Information): using config file mining.conf
26.02.2017 18:34:10 (0, src\MinerConfig.cpp, 263, Debug): Reading passphrase...
26.02.2017 18:34:10 (0, src\Miner.cpp, 50, Information): Total plots size: 930.11 GB
26.02.2017 18:34:10 (0, src\Miner.cpp, 52, Information): Submission Max Retry : 5
26.02.2017 18:34:10 (0, src\Miner.cpp, 55, Information): Buffer Size : 128 MB
26.02.2017 18:34:10 (0, src\Miner.cpp, 58, Information): Pool Host : http://m.burst4all.com:8124 (192.99.181.227)
26.02.2017 18:34:10 (0, src\Miner.cpp, 61, Information): Mininginfo URL : http://m.burst4all.com:8124 (192.99.181.227)
26.02.2017 18:34:11 (0, src\Miner.cpp, 64, Information): Wallet URL : https://wallet.burst-team.us:8127 (216.165.179.44)
26.02.2017 18:34:11 (0, src\Miner.cpp, 67, Information): Server URL : http://192.168.1.2:8080 (fe80::b575:2d05:264e:e215%11)
26.02.2017 18:34:11 (0, src\Miner.cpp, 69, Information): Target deadline : 1y 8m 0d 15:00:00
26.02.2017 18:34:11 (0, src\Miner.cpp, 70, Information): Mining intensity : 1
26.02.2017 18:34:11 (0, src\Miner.cpp, 74, Information): Max plot readers : 1
26.02.2017 18:34:11 (0, src\Miner.cpp, 76, Information): Log path : 
26.02.2017 18:34:11 (0, src\Miner.cpp, 179, Debug): Verification queue cleared.
26.02.2017 18:34:11 (0, src\Miner.cpp, 199, Notice): --------------------------------------------------
block#      332433
scoop#      3689
baseTarget# 1553639
--------------------------------------------------
26.02.2017 18:34:12 (7, src\PlotReader.cpp, 169, Information): H:\plots\10871057679973349262_10185192_409600_409600 done 100.00 GB in 0.529s (~189.03 GB/s)
26.02.2017 18:34:12 (7, src\PlotReader.cpp, 169, Information): H:\plots\10871057679973349262_10594792_409600_409600 done 100.00 GB in 0.280s (~357.12 GB/s)
26.02.2017 18:34:12 (7, src\PlotReader.cpp, 169, Information): H:\plots\10871057679973349262_11004392_409600_409600 done 100.00 GB in 0.287s (~348.41 GB/s)
26.02.2017 18:34:13 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (194,019y 11m 1d 12:42:50)
	nonce: 10185192
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:13 (7, src\PlotReader.cpp, 169, Information): H:\plots\10871057679973349262_11413992_409600_409600 done 100.00 GB in 0.300s (~333.31 GB/s)
26.02.2017 18:34:13 (6, src\Miner.cpp, 316, Debug): Nonce is higher then the target deadline of the pool (1y 8m 0d 15:00:00)
26.02.2017 18:34:13 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (169,218y 6m 15d 18:57:42)
	nonce: 10185195
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:13 (6, src\Miner.cpp, 316, Debug): Nonce is higher then the target deadline of the pool (1y 8m 0d 15:00:00)
26.02.2017 18:34:13 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (17,014y 1m 15d 03:38:44)
	nonce: 10185196
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:13 (6, src\Miner.cpp, 316, Debug): Nonce is higher then the target deadline of the pool (1y 8m 0d 15:00:00)
26.02.2017 18:34:13 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (6,437y 0m 1d 15:48:38)
	nonce: 10185205
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:13 (6, src\Miner.cpp, 316, Debug): Nonce is higher then the target deadline of the pool (1y 8m 0d 15:00:00)
26.02.2017 18:34:13 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (2,820y 3m 3d 10:20:13)
	nonce: 10185271
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:13 (6, src\Miner.cpp, 316, Debug): Nonce is higher then the target deadline of the pool (1y 8m 0d 15:00:00)
26.02.2017 18:34:13 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (1,042y 6m 22d 06:01:08)
	nonce: 10185306
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:13 (6, src\Miner.cpp, 316, Debug): Nonce is higher then the target deadline of the pool (1y 8m 0d 15:00:00)
26.02.2017 18:34:13 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (168y 4m 9d 10:20:08)
	nonce: 10185518
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:13 (6, src\Miner.cpp, 316, Debug): Nonce is higher then the target deadline of the pool (1y 8m 0d 15:00:00)
26.02.2017 18:34:13 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (137y 3m 6d 01:42:36)
	nonce: 10185710
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:13 (6, src\Miner.cpp, 316, Debug): Nonce is higher then the target deadline of the pool (1y 8m 0d 15:00:00)
26.02.2017 18:34:13 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (61y 11m 13d 10:43:52)
	nonce: 10185714
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:13 (6, src\Miner.cpp, 316, Debug): Nonce is higher then the target deadline of the pool (1y 8m 0d 15:00:00)
26.02.2017 18:34:13 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (41y 3m 9d 21:31:16)
	nonce: 10189428
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:13 (6, src\Miner.cpp, 316, Debug): Nonce is higher then the target deadline of the pool (1y 8m 0d 15:00:00)
26.02.2017 18:34:13 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (16y 4m 28d 00:23:40)
	nonce: 10210166
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:13 (6, src\Miner.cpp, 316, Debug): Nonce is higher then the target deadline of the pool (1y 8m 0d 15:00:00)
26.02.2017 18:34:13 (7, src\PlotReader.cpp, 169, Information): H:\plots\10871057679973349262_11823592_409600_409600 done 100.00 GB in 0.651s (~153.60 GB/s)
26.02.2017 18:34:13 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (1y 5m 21d 07:01:54)
	nonce: 10267418
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:13 (4, src\NonceSubmitter.cpp, 48, Information): Yey-Burst: nonce on the way (1y 5m 21d 07:01:54)
26.02.2017 18:34:13 (4, src\NonceSubmitter.cpp, 59, Debug): Submit-loop 1 (1y 5m 21d 07:01:54)
26.02.2017 18:34:13 (8, src\MinerData.cpp, 236, Information): --------------------------------------------------
last block winner: 
block#             332432
winner-numeric     9072823045170977478
winner-address     BQQ8-HPGQ-C443-96BUV
winner-name        shark
--------------------------------------------------
26.02.2017 18:34:14 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (5m 6d 12:56:51)
	nonce: 10486913
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:14 (5, src\NonceSubmitter.cpp, 48, Information): Yey-Burst: nonce on the way (5m 6d 12:56:51)
26.02.2017 18:34:14 (5, src\NonceSubmitter.cpp, 59, Debug): Submit-loop 1 (5m 6d 12:56:51)
26.02.2017 18:34:14 (4, src\NonceSubmitter.cpp, 72, Information): Yey-Burst: nonce submitted (1y 5m 21d 07:01:54)
	nonce: 10267418
	in H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:14 (4, src\NonceSubmitter.cpp, 144, Debug): Better deadline in pipeline, stop submitting! (1y 5m 21d 07:01:54)
26.02.2017 18:34:14 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (2m 17d 23:14:05)
	nonce: 10682570
	in: H:\plots\10871057679973349262_10594792_409600_409600
26.02.2017 18:34:14 (4, src\NonceSubmitter.cpp, 48, Information): Yey-Burst: nonce on the way (2m 17d 23:14:05)
26.02.2017 18:34:14 (4, src\NonceSubmitter.cpp, 59, Debug): Submit-loop 1 (2m 17d 23:14:05)
26.02.2017 18:34:14 (5, src\NonceSubmitter.cpp, 72, Information): Yey-Burst: nonce submitted (5m 6d 12:56:51)
	nonce: 10486913
	in H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:14 (5, src\NonceSubmitter.cpp, 144, Debug): Better deadline in pipeline, stop submitting! (5m 6d 12:56:51)
26.02.2017 18:34:14 (4, src\NonceSubmitter.cpp, 72, Information): Yey-Burst: nonce submitted (2m 17d 23:14:05)
	nonce: 10682570
	in H:\plots\10871057679973349262_10594792_409600_409600
26.02.2017 18:34:15 (4, src\NonceSubmitter.cpp, 136, Information): Yey-Burst: nonce confirmed (2m 17d 23:14:05)
	nonce: 10682570
	in H:\plots\10871057679973349262_10594792_409600_409600
26.02.2017 18:34:16 (7, src\PlotReader.cpp, 169, Information): H:\plots\10871057679973349262_12233192_409600_409600 done 100.00 GB in 2.828s (~35.36 GB/s)
26.02.2017 18:34:18 (0, src\Miner.cpp, 179, Debug): Verification queue cleared.
26.02.2017 18:34:18 (0, src\Miner.cpp, 199, Notice): --------------------------------------------------
block#      332434
scoop#      1672
baseTarget# 1325265
--------------------------------------------------
26.02.2017 18:34:19 (7, src\PlotReader.cpp, 169, Information): H:\plots\10871057679973349262_12642792_409600_409600 done 100.00 GB in 2.537s (~39.41 GB/s)
26.02.2017 18:34:19 (7, src\PlotReader.cpp, 188, Information): Dir H done: 10 files, 930.11 GB total, 7.864s (~118.25 GB/s)
26.02.2017 18:34:19 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (272,570y 0m 24d 16:47:39)
	nonce: 10185192
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:19 (6, src\Miner.cpp, 316, Debug): Nonce is higher then the target deadline of the pool (1y 8m 0d 15:00:00)
26.02.2017 18:34:19 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (64,233y 0m 2d 11:22:58)
	nonce: 10185194
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:19 (6, src\Miner.cpp, 316, Debug): Nonce is higher then the target deadline of the pool (1y 8m 0d 15:00:00)
26.02.2017 18:34:19 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (19,909y 7m 16d 23:54:01)
	nonce: 10185195
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:19 (6, src\Miner.cpp, 316, Debug): Nonce is higher then the target deadline of the pool (1y 8m 0d 15:00:00)
26.02.2017 18:34:19 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (9,960y 4m 5d 12:03:44)
	nonce: 10185207
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:19 (7, src\PlotReader.cpp, 169, Information): H:\plots\10871057679973349262_10185192_409600_409600 done 100.00 GB in 0.273s (~366.28 GB/s)
26.02.2017 18:34:19 (6, src\Miner.cpp, 316, Debug): Nonce is higher then the target deadline of the pool (1y 8m 0d 15:00:00)
26.02.2017 18:34:19 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (9,330y 1m 19d 18:20:34)
	nonce: 10185250
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:19 (6, src\Miner.cpp, 316, Debug): Nonce is higher then the target deadline of the pool (1y 8m 0d 15:00:00)
26.02.2017 18:34:19 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (8,641y 2m 16d 18:07:47)
	nonce: 10185308
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:20 (6, src\Miner.cpp, 316, Debug): Nonce is higher then the target deadline of the pool (1y 8m 0d 15:00:00)
26.02.2017 18:34:20 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (3,136y 4m 1d 15:39:11)
	nonce: 10185309
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:20 (6, src\Miner.cpp, 316, Debug): Nonce is higher then the target deadline of the pool (1y 8m 0d 15:00:00)
26.02.2017 18:34:20 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (6y 9m 27d 12:36:56)
	nonce: 10185321
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:20 (7, src\PlotReader.cpp, 169, Information): H:\plots\10871057679973349262_10594792_409600_409600 done 100.00 GB in 0.260s (~384.59 GB/s)
26.02.2017 18:34:20 (6, src\Miner.cpp, 316, Debug): Nonce is higher then the target deadline of the pool (1y 8m 0d 15:00:00)
26.02.2017 18:34:20 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (2y 11m 1d 20:19:51)
	nonce: 10232260
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:20 (6, src\Miner.cpp, 316, Debug): Nonce is higher then the target deadline of the pool (1y 8m 0d 15:00:00)
26.02.2017 18:34:20 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (2y 0m 15d 18:20:45)
	nonce: 10297337
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:20 (6, src\Miner.cpp, 316, Debug): Nonce is higher then the target deadline of the pool (1y 8m 0d 15:00:00)
26.02.2017 18:34:20 (7, src\PlotReader.cpp, 169, Information): H:\plots\10871057679973349262_11004392_409600_409600 done 100.00 GB in 0.272s (~367.63 GB/s)
26.02.2017 18:34:20 (9, src\MinerData.cpp, 236, Information): --------------------------------------------------
last block winner: 
block#             332433
winner-numeric     17154141772299672229
winner-address     T8P7-3SQB-S6EE-G3Y5W
winner-name        Thanh Dang
--------------------------------------------------
26.02.2017 18:34:20 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (8m 17d 10:06:24)
	nonce: 10385279
	in: H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:20 (4, src\NonceSubmitter.cpp, 48, Information): Yey-Burst: nonce on the way (8m 17d 10:06:24)
26.02.2017 18:34:20 (4, src\NonceSubmitter.cpp, 59, Debug): Submit-loop 1 (8m 17d 10:06:24)
26.02.2017 18:34:20 (7, src\PlotReader.cpp, 169, Information): H:\plots\10871057679973349262_11413992_409600_409600 done 100.00 GB in 0.291s (~343.62 GB/s)
26.02.2017 18:34:20 (4, src\NonceSubmitter.cpp, 72, Information): Yey-Burst: nonce submitted (8m 17d 10:06:24)
	nonce: 10385279
	in H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:21 (7, src\PlotReader.cpp, 169, Information): H:\plots\10871057679973349262_11823592_409600_409600 done 100.00 GB in 0.307s (~325.71 GB/s)
26.02.2017 18:34:21 (4, src\NonceSubmitter.cpp, 136, Information): Yey-Burst: nonce confirmed (8m 17d 10:06:24)
	nonce: 10385279
	in H:\plots\10871057679973349262_10185192_409600_409600
26.02.2017 18:34:21 (7, src\PlotReader.cpp, 169, Information): H:\plots\10871057679973349262_12233192_409600_409600 done 100.00 GB in 0.333s (~300.28 GB/s)
26.02.2017 18:34:21 (7, src\PlotReader.cpp, 169, Information): H:\plots\10871057679973349262_12642792_409600_409600 done 100.00 GB in 0.368s (~271.72 GB/s)
26.02.2017 18:34:22 (7, src\PlotReader.cpp, 169, Information): H:\plots\10871057679973349262_13052392_409600_409600 done 100.00 GB in 0.409s (~244.49 GB/s)
26.02.2017 18:34:22 (7, src\PlotReader.cpp, 169, Information): H:\plots\10871057679973349262_13461992_123312_123312 done 30.11 GB in 0.166s (~181.35 GB/s)
26.02.2017 18:34:22 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (1m 21d 17:33:41)
	nonce: 12456191
	in: H:\plots\10871057679973349262_12233192_409600_409600
26.02.2017 18:34:22 (4, src\NonceSubmitter.cpp, 48, Information): Yey-Burst: nonce on the way (1m 21d 17:33:41)
26.02.2017 18:34:22 (6, src\Miner.cpp, 306, Information): Yey-Burst: nonce found (6d 05:34:31)
	nonce: 12467611
	in: H:\plots\10871057679973349262_12233192_409600_409600
26.02.2017 18:34:22 (4, src\NonceSubmitter.cpp, 144, Debug): Better deadline in pipeline, stop submitting! (1m 21d 17:33:41)
26.02.2017 18:34:22 (5, src\NonceSubmitter.cpp, 48, Information): Yey-Burst: nonce on the way (6d 05:34:31)
26.02.2017 18:34:23 (5, src\NonceSubmitter.cpp, 59, Debug): Submit-loop 1 (6d 05:34:31)
26.02.2017 18:34:23 (5, src\NonceSubmitter.cpp, 72, Information): Yey-Burst: nonce submitted (6d 05:34:31)
	nonce: 12467611
	in H:\plots\10871057679973349262_12233192_409600_409600
26.02.2017 18:34:23 (5, src\NonceSubmitter.cpp, 136, Information): Yey-Burst: nonce confirmed (6d 05:34:31)
	nonce: 12467611
	in H:\plots\10871057679973349262_12233192_409600_409600
26.02.2017 18:35:13 (0, src\Miner.cpp, 179, Debug): Verification queue cleared.
26.02.2017 18:35:13 (0, src\Miner.cpp, 199, Notice): --------------------------------------------------
block#      332435
scoop#      2733
baseTarget# 1291036
--------------------------------------------------
26.02.2017 18:35:16 (10, src\MinerData.cpp, 236, Information): --------------------------------------------------
last block winner: 
block#             332434
winner-numeric     11171938866304733864
winner-address     LNPA-8NF9-AEG6-BMP4Q
winner-name        Padzino
--------------------------------------------------
26.02.2017 18:36:28 (0, src\Miner.cpp, 179, Debug): Verification queue cleared.
26.02.2017 18:36:28 (0, src\Miner.cpp, 199, Notice): --------------------------------------------------
block#      332436
scoop#      2939
baseTarget# 1282642
--------------------------------------------------
26.02.2017 18:38:55 (0, src\Miner.cpp, 179, Debug): Verification queue cleared.
26.02.2017 18:38:55 (0, src\Miner.cpp, 199, Notice): --------------------------------------------------
block#      332437
scoop#      701
baseTarget# 1255552
--------------------------------------------------

**Comment by Creepsky** [comment]
Somehow you use version 1.4.4, fix is in 1.4.6 (https://github.com/Creepsky/creepMiner/releases/tag/2.4.6).

**Comment by Creepsky** [comment]
Any news on this?

**Comment by N8Thrasher** [comment]
you can close it. I think its working fine now.
