### ISSUE TITLE
Stack Frame error

### ISSUE THREAD

**Issue by N8Thrasher** [Creepsky/creepMiner#81]
`27.02.2017 11:47:04 (95, src\MinerData.cpp, 261, Information): --------------------------------------------------
last block winner: 
block#             332691
winner-numeric     15154575530379673774
winner-address     R27G-6W73-YPVK-FYYM6
winner-name        UniBURST Miner 2
--------------------------------------------------
27.02.2017 11:47:05 (5, src\NonceSubmitter.cpp, 72, Information): Yey-Burst: nonce submitted (4m 22d 03:46:24)
	nonce: 11727163
	in H:\plots\10871057679973349262_11413992_409600_409600
27.02.2017 11:47:05 (5, src\NonceSubmitter.cpp, 90, Trace): miner.getBlockheight
27.02.2017 11:47:05 (5, src\NonceSubmitter.cpp, 138, Information): Yey-Burst: nonce confirmed (4m 22d 03:46:24)
	nonce: 11727163
	in H:\plots\10871057679973349262_11413992_409600_409600
27.02.2017 11:47:06 (7, src\Miner.cpp, 295, Information): Yey-Burst: nonce found (9d 06:54:08)
	nonce: 12086671
	in: H:\plots\10871057679973349262_11823592_409600_409600
27.02.2017 11:47:06 (5, src\NonceSubmitter.cpp, 48, Information): Yey-Burst: nonce on the way (9d 06:54:08)
27.02.2017 11:47:06 (5, src\NonceSubmitter.cpp, 59, Debug): Submit-loop 1 (9d 06:54:08)
27.02.2017 11:47:06 (9, src\PlotReader.cpp, 179, Information): H:\plots\10871057679973349262_11823592_409600_409600 (100.00 GB) read in 2.574s (~9.71 MB/s)
27.02.2017 11:47:07 (5, src\NonceSubmitter.cpp, 72, Information): Yey-Burst: nonce submitted (9d 06:54:08)
	nonce: 12086671
	in H:\plots\10871057679973349262_11823592_409600_409600
27.02.2017 11:47:07 (9, src\PlotReader.cpp, 179, Information): H:\plots\10871057679973349262_12233192_409600_409600 (100.00 GB) read in 0.327s (~76.31 MB/s)
27.02.2017 11:47:07 (9, src\PlotReader.cpp, 179, Information): H:\plots\10871057679973349262_12642792_409600_409600 (100.00 GB) read in 0.343s (~72.84 MB/s)
27.02.2017 11:47:07 (5, src\NonceSubmitter.cpp, 90, Trace): miner.getBlockheight
27.02.2017 11:47:07 (5, src\NonceSubmitter.cpp, 138, Information): Yey-Burst: nonce confirmed (9d 06:54:08)
	nonce: 12086671
	in H:\plots\10871057679973349262_11823592_409600_409600
27.02.2017 11:47:07 (9, src\PlotReader.cpp, 179, Information): H:\plots\10871057679973349262_13052392_409600_409600 (100.00 GB) read in 0.390s (~64.10 MB/s)
27.02.2017 11:47:08 (9, src\PlotReader.cpp, 179, Information): H:\plots\10871057679973349262_13461992_123312_123312 (30.11 GB) read in 0.280s (~26.80 MB/s)
27.02.2017 11:47:08 (9, src\PlotReader.cpp, 179, Information): H:\plots\10871057679973349262_9775592_409600_409600 (100.00 GB) read in 0.249s (~100.16 MB/s)
27.02.2017 11:47:08 (9, src\PlotReader.cpp, 207, Information): Dir H read (10 files, 930.11 GB total) in 6.240s (~37.26 MB/s)
27.02.2017 11:48:04 (0, src\Response.cpp, 51, Error): Error on receiving response!
No message received
27.02.2017 11:48:04 (0, src\Response.cpp, 53, Error): Stackframe
main (in "src\main.cpp", line 39)
Miner::run (in "src\Miner.cpp", line 35)
Miner::getMiningInfo (in "src\Miner.cpp", line 322)
Response::receive (in "src\Response.cpp", line 29)

27.02.2017 11:48:04 (0, src\Miner.cpp, 141, Debug): Could not get mining infos 1/5 times...
27.02.2017 11:48:09 (0, src\Request.cpp, 46, Error): Error on sending request: Connection refused
27.02.2017 11:48:09 (0, src\Request.cpp, 47, Error): Stackframe
main (in "src\main.cpp", line 39)
Miner::run (in "src\Miner.cpp", line 35)
Miner::getMiningInfo (in "src\Miner.cpp", line 322)
Request::send(Poco::Net::HTTPRequest&) (in "src\Request.cpp", line 35)

27.02.2017 11:48:09 (0, src\Miner.cpp, 141, Debug): Could not get mining infos 2/5 times...
27.02.2017 11:48:14 (0, src\Request.cpp, 46, Error): Error on sending request: Connection refused
27.02.2017 11:48:14 (0, src\Request.cpp, 47, Error): Stackframe
main (in "src\main.cpp", line 39)
Miner::run (in "src\Miner.cpp", line 35)
Miner::getMiningInfo (in "src\Miner.cpp", line 322)
Request::send(Poco::Net::HTTPRequest&) (in "src\Request.cpp", line 35)

27.02.2017 11:48:14 (0, src\Miner.cpp, 141, Debug): Could not get mining infos 3/5 times...
27.02.2017 11:48:24 (0, src\Request.cpp, 46, Error): Error on sending request: Connection refused
27.02.2017 11:48:24 (0, src\Request.cpp, 47, Error): Stackframe
main (in "src\main.cpp", line 39)
Miner::run (in "src\Miner.cpp", line 35)
Miner::getMiningInfo (in "src\Miner.cpp", line 322)
Request::send(Poco::Net::HTTPRequest&) (in "src\Request.cpp", line 35)

27.02.2017 11:48:24 (0, src\Miner.cpp, 141, Debug): Could not get mining infos 4/5 times...
27.02.2017 11:48:34 (0, src\Request.cpp, 46, Error): Error on sending request: Connection refused
27.02.2017 11:48:34 (0, src\Request.cpp, 47, Error): Stackframe
main (in "src\main.cpp", line 39)
Miner::run (in "src\Miner.cpp", line 35)
Miner::getMiningInfo (in "src\Miner.cpp", line 322)
Request::send(Poco::Net::HTTPRequest&) (in "src\Request.cpp", line 35)

27.02.2017 11:48:34 (0, src\Miner.cpp, 141, Debug): Could not get mining infos 5/5 times...
27.02.2017 11:48:35 (0, src\Miner.cpp, 148, Error): Could not get block infos!
27.02.2017 11:48:39 (0, src\Request.cpp, 46, Error): Error on sending request: Connection refused
27.02.2017 11:48:39 (0, src\Request.cpp, 47, Error): Stackframe
main (in "src\main.cpp", line 39)
Miner::run (in "src\Miner.cpp", line 35)
Miner::getMiningInfo (in "src\Miner.cpp", line 322)
Request::send(Poco::Net::HTTPRequest&) (in "src\Request.cpp", line 35)

27.02.2017 11:48:39 (0, src\Miner.cpp, 141, Debug): Could not get mining infos 1/5 times...
27.02.2017 11:48:50 (0, src\Request.cpp, 46, Error): Error on sending request: Connection refused
27.02.2017 11:48:50 (0, src\Request.cpp, 47, Error): Stackframe
main (in "src\main.cpp", line 39)
Miner::run (in "src\Miner.cpp", line 35)
Miner::getMiningInfo (in "src\Miner.cpp", line 322)
Request::send(Poco::Net::HTTPRequest&) (in "src\Request.cpp", line 35)

27.02.2017 11:48:50 (0, src\Miner.cpp, 141, Debug): Could not get mining infos 2/5 times...
27.02.2017 11:49:00 (0, src\Request.cpp, 46, Error): Error on sending request: Connection refused
27.02.2017 11:49:00 (0, src\Request.cpp, 47, Error): Stackframe
main (in "src\main.cpp", line 39)
Miner::run (in "src\Miner.cpp", line 35)
Miner::getMiningInfo (in "src\Miner.cpp", line 322)
Request::send(Poco::Net::HTTPRequest&) (in "src\Request.cpp", line 35)

27.02.2017 11:49:00 (0, src\Miner.cpp, 141, Debug): Could not get mining infos 3/5 times...
27.02.2017 11:49:10 (0, src\Request.cpp, 46, Error): Error on sending request: Connection refused
27.02.2017 11:49:10 (0, src\Request.cpp, 47, Error): Stackframe
main (in "src\main.cpp", line 39)
Miner::run (in "src\Miner.cpp", line 35)
Miner::getMiningInfo (in "src\Miner.cpp", line 322)
Request::send(Poco::Net::HTTPRequest&) (in "src\Request.cpp", line 35)

27.02.2017 11:49:10 (0, src\Miner.cpp, 141, Debug): Could not get mining infos 4/5 times...
27.02.2017 11:49:20 (0, src\Request.cpp, 46, Error): Error on sending request: Connection refused
27.02.2017 11:49:20 (0, src\Request.cpp, 47, Error): Stackframe
main (in "src\main.cpp", line 39)
Miner::run (in "src\Miner.cpp", line 35)
Miner::getMiningInfo (in "src\Miner.cpp", line 322)
Request::send(Poco::Net::HTTPRequest&) (in "src\Request.cpp", line 35)

27.02.2017 11:49:20 (0, src\Miner.cpp, 141, Debug): Could not get mining infos 5/5 times...
27.02.2017 11:49:21 (0, src\Miner.cpp, 148, Error): Could not get block infos!`

**Comment by N8Thrasher** [comment]
![image](https://cloud.githubusercontent.com/assets/24593637/23360709/f88904f0-fcfd-11e6-8962-3e5a32d2e22a.png)

**Comment by Pascal66** [comment]
Msg are just because the pool code is udpated/crashed
Just wait for this pool back online

**Comment by N8Thrasher** [comment]
on my other pc using blago miner no error or anything.

**Comment by Creepsky** [comment]
Connection refused means, the peer is not online. It is not possible that Blagos miner can talk with a server that is offline ;) maybe he gets the mining info from somewhere else.

If this happens again, the miner will reconnect the session. But even then, the messages would appear again until the server comes online.

Compiled and uploaded: https://github.com/Creepsky/creepMiner/releases/tag/2.4.6.
