### ISSUE TITLE
Mining is stopping after 3-4 hours of runtime

### ISSUE THREAD

**Issue by Axadiw** [Creepsky/creepMiner#82]
Hi,

I've noticed a problem with the creepMiner versions 1.4.3 - 1.4.6:

It looks like after 3-4 hours of mining, creepMiner is stopping minig process. 

Webserver is still working. On the console log I can see even new block winners.  but mining isn't happening.

After reboot of creepMiner everything works fine again (again for 3-4 hours :))

Here's my configuration and log file:

[mining.conf.txt](https://github.com/Creepsky/creepMiner/files/804003/mining.conf.txt)

[creepMiner_20170227_072757.696576.log.txt](https://github.com/Creepsky/creepMiner/files/804004/creepMiner_20170227_072757.696576.log.txt)

Currently I'm pointing miner to wallet at localhost, but I've been experiencing this issue using web wallet as well (https://wallet.burst-team.us:8125).

I've been investingating this shortly issue, and it looks like every time mining hangs logfile containg massive amount of plotVerifier logs like this one:

```8, src/PlotVerifier.cpp, 109, Debug): Plot verifier is done with work, but not for this block!```

What could be a problem here?

I'm running miner on Ubuntu 16.04

**Comment by Creepsky** [comment]
Hi,

the message ```8, src/PlotVerifier.cpp, 109, Debug): Plot verifier is done with work, but not for this block!``` comes, because the plot readers are reading plot files in chunks of max maxBufferSizeMB.

Every chunk gets pushed onto a stack. Now the verifiers take the work from the stack and search for good nonces in it. 

I can't reproduce the bug, so the only thing left for me to do is trace it :) I added some more debug output, made some parts thread-safe and optimized the whole nonce-search-submit-process in the branch *[fix-mining-bug](https://github.com/Creepsky/creepMiner/tree/fix-mining-bug)*.

Please check it out and try again with it.

**Comment by Axadiw** [comment]
Ok than, I've started creepMiner compled from *fix-minig-bug* branch. I'll update with the correct log when it will freeze again

Cheers

**Comment by Axadiw** [comment]
I'm not sure what have you changed in this version from `fix-mining-bug` since 1.4.6 version, but it's working flawlessly since 24 hours :)

Maybe this bug is connected with pool condition? If this problem would happen again, I'll update you in this thread

**Comment by Creepsky** [comment]
Really glad about it, this bug bothered me since 1.4.3 :D
I think it happened when a new block came in while the old one was still mined. Something got stuck, most likely the memory allocation like you said already.

Hope we got finally rid of this bug, thank you for your help here!

**Comment by WebfinityDesign** [comment]
I do have this exact same problem but in version 1.6.0 How to solve this?

**Comment by WebfinityDesign** [comment]
My maxbuffersize is 512MB. Is that to much?

**Comment by Creepsky** [comment]
@WebfinityDesign Please open a new issue and provide some more informations there.
