### ISSUE TITLE
Multiple plot files handling

### ISSUE THREAD

**Issue by Axadiw** [Creepsky/creepMiner#86]
Hi,

I have been experimenting with Burst cloud mining with couple thousands of 5-10GB plot files.
All of them are mounted using FUSE driver under certain directory on my filesystem.

The problem I'm experiencing is very low performance of plots reading processes. I believe that cause of this that plot readers are reading files sequentially (and in my scenario parallel approach is better). 
I have been experimenting with this problem with grouping plot files into separate folders, and place them separately in `mining.conf` file like:

```
"plots": [
        "path_to_directory1",
        "path_to_directory2",
        "path_to_directory3",
        "path_to_directory4",
...
    ],
```

Unfortunately (no matter how many `maxPlotReaders` I have selected) performance was the same as when one all of them were placed in the same folder.

I have been able to increase performance when I have scattered plot files into multiple folders (with ~100 of plot files in single directory), and launched multiple instances of creepMiner on the same machine with different mining configurations like:

```
"plots": [
        "path_to_directory1"
    ],
```

,

```
"plots": [
        "path_to_directory2"
    ],
```

and so on.

With this approach I have been able to increase performance drastically, as well as CPU and RAM :)
I guess that large amount of these resources could be saved if I would use single instance of creepMiner that will spawn multiple plot reading threads that will scan single plot file directory.

I know that creep miner wasn't designed for this kind of usage (generally miners are using couple of plot files instead of thousands of them), but could you implement functionality that will allow scan single plot file directories with multiple reading threads?

Regards

**Comment by Pascal66** [comment]
👍 WIsh you can test that in my pool :)

**Comment by Creepsky** [comment]
Ok, you can find the changes in the branch [plotfile-types](https://github.com/Creepsky/creepMiner/tree/plotfile-types).

You can now declare some more things in the "plots" section in the configuration.

There are 2 types of plot dirs/files: **sequiential** and **parallel**.

All files of a **sequential** one are read one by one, by one plot reader. This is the default type, what is useful if you have a normal HDD.

Files from a **parallel** one are all read together by all plot reader side by side. SSDs or network dirs would benefit from this setting.

You can declare the type of the dir like this

```
"plots" : [
    {
        "path" : "I:\\Plotfiles",
        "type" : "sequential"
    },
    {
        "path" : "J:\\Plotfiles",
        "type" : "paralell"
    },
    "K:\\Plotfiles"
]
```

The old form (that is still valid for backward compatibility)
```
"plots" : [
    "I:\\Plotfiles"
]
```
is equivalent to
```
"plots" : [
    {
        "path" : "I:\\Plotfiles",
        "type" : "sequential"
    }
]
```

Also have a look at #67. You can create related plot dirs, but this is described in the other issue.
