### ISSUE TITLE
CUDA miner for linux

### ISSUE THREAD

**Issue by mpenagar** [Creepsky/creepMiner#89]
Is it posible to compile the CUDA miner in linux?

**Comment by Creepsky** [comment]
Yes, but it is not yet possible with the makefile.

If you want to try it yourself, here are some (hopefully) helpful tips:
- You have to download [CUDA](https://developer.nvidia.com/cuda-downloads)
- These are the compilation command lines for Visual Studio (need to be translated into Linux + change paths):

```

# (Approximate command-line.  Settings inherited from host are not visible below.)
# (Please see the output window after a build for the full command-line)

# Driver API (NVCC Compilation Type is .cubin, .gpu, or .ptx)
set CUDAFE_FLAGS=--sdk_dir "C:\Program Files (x86)\Windows Kits\8.1\"
"F:\dev\C++\Cuda\bin\nvcc.exe" --use-local-env --cl-version 2015 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64"        --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static  -o F:\dev\C++\creepMiner\obj\Release\cuda\%(Filename)%(Extension).obj "%(FullPath)"

# Runtime API (NVCC Compilation Type is hybrid object or .c file)
set CUDAFE_FLAGS=--sdk_dir "C:\Program Files (x86)\Windows Kits\8.1\"
"F:\dev\C++\Cuda\bin\nvcc.exe" --use-local-env --cl-version 2015 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64"        --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static      -Xcompiler "/EHsc  /nologo  /FS /Zi   " -o F:\dev\C++\creepMiner\obj\Release\cuda\%(Filename)%(Extension).obj "%(FullPath)"
```

```
# (Approximate command-line.  Settings inherited from host are not visible below.)
# (Please see the output window after a build for the full command-line)

"F:\dev\C++\Cuda\bin\nvcc.exe" -dlink -o F:\dev\C++\creepMiner\obj\Release\cuda\creepMiner-cuda.device-link.obj -Xcompiler "/EHsc  /nologo  /Zi   "   
```

Sooner or later I will add this to the makefile so it will be easier to compile.

**Comment by mpenagar** [comment]
I managed to compile it manually, i will comment it in github.

Thanks!

Enviado desde Yahoo Mail con Android 
 
  El dom., mar. 5, 2017 a 18:21, Creepsky<notifications@github.com> escribió:   
Yes, but it is not yet possible with the makefile.

If you want to try it yourself, here are some (hopefully) helpful tips:
   
   - You have to download CUDA
   - These are the compilation command lines for Visual Studio (need to be translated into Linux + change paths):

# (Approximate command-line.  Settings inherited from host are not visible below.)
# (Please see the output window after a build for the full command-line)

# Driver API (NVCC Compilation Type is .cubin, .gpu, or .ptx)
set CUDAFE_FLAGS=--sdk_dir "C:\Program Files (x86)\Windows Kits\8.1\"
"F:\dev\C++\Cuda\bin\nvcc.exe" --use-local-env --cl-version 2015 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64"        --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static  -o F:\dev\C++\creepMiner\obj\Release\cuda\%(Filename)%(Extension).obj "%(FullPath)"

# Runtime API (NVCC Compilation Type is hybrid object or .c file)
set CUDAFE_FLAGS=--sdk_dir "C:\Program Files (x86)\Windows Kits\8.1\"
"F:\dev\C++\Cuda\bin\nvcc.exe" --use-local-env --cl-version 2015 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64"        --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static      -Xcompiler "/EHsc  /nologo  /FS /Zi   " -o F:\dev\C++\creepMiner\obj\Release\cuda\%(Filename)%(Extension).obj "%(FullPath)"
# (Approximate command-line.  Settings inherited from host are not visible below.)
# (Please see the output window after a build for the full command-line)

"F:\dev\C++\Cuda\bin\nvcc.exe" -dlink -o F:\dev\C++\creepMiner\obj\Release\cuda\creepMiner-cuda.device-link.obj -Xcompiler "/EHsc  /nologo  /Zi   "   

Sooner or later I will add this to the makefile so it will be easier to compile.

**Comment by mpenagar** [comment]
My knowledge about Makefiles is quite limited, so here you've got the commands used to compile it:

1 - add  -DMINING_CUDA to CFLAGS . Make will fail at last step, when trying to generate the  bin/creepMiner executable, because the cuda source was not compiled

`CUDA_PATH=/usr/local/cuda make CFLAGS="-O3 -march=native -std=c++14 -Wall -D_REENTRANT -DNDEBUG -DMINING_CUDA" `

2 - Compile src/shabal-cuda/Shabal.cu

`/usr/local/cuda/bin/nvcc -c src/shabal-cuda/Shabal.cu -o bin/obj/Shabal.o -Isrc -std=c++11`

3 - Do the last step (added bin/obj/Shabal.o, -L/usr/local/cuda/lib64 and -lcudart, and changed target binary name to bin/creepMiner-cuda)

`/usr/local/cuda/bin/nvcc -c src/shabal-cuda/Shabal.cu -o bin/obj/Shabal.o -Isrc -std=c++11
g++ -O3 -march=native -std=c++14 -Wall -D_REENTRANT -DNDEBUG -DMINING_CUDA -o bin/creepMiner-cuda bin/obj/sphlib/sph_shabal.o bin/obj/nxt/nxt_address.o bin/obj/MinerLogger.o bin/obj/PlotVerifier.o bin/obj/MinerUtil.o bin/obj/MinerServer.o bin/obj/Response.o bin/obj/Socket.o bin/obj/RequestHandler.o bin/obj/Url.o bin/obj/PlotGenerator.o bin/obj/Deadline.o bin/obj/NonceSubmitter.o bin/obj/Wallet.o bin/obj/MinerShabal.o bin/obj/PlotSizes.o bin/obj/Request.o bin/obj/MinerData.o bin/obj/PlotReader.o bin/obj/Declarations.o bin/obj/MinerConfig.o bin/obj/Account.o bin/obj/AccountNames.o bin/obj/main.o bin/obj/Miner.o bin/obj/Shabal.o -L/usr/local/lib -L/usr/local/cuda/lib64 -pthread -lPocoFoundation -lPocoNetSSL -lPocoCrypto -lPocoUtil -lPocoNet -lPocoJSON -lcudart`

I suppose that adding a CUDALIB variable, defining a new target creepMiner-cuda and making small changes to Makefile should be enough to can run:

`make`

to get the cpu miner, and

`CUDALIB=/usr/local/cuda/lib64  make creepMiner-cuda`

to get the GPU miner

Hope it helps.

**Comment by Creepsky** [comment]
Very nice, will add it to the makefile.

**Comment by mikeabrahamsen** [comment]
Tried this out using a 660ti, while it was fast I started getting a lot of errors on submitting nonces.
They looked like this generally:
```
--- nonce on the way (12d 12:42:06)
14:14:43: ---: nonce submitted (12d 12:42:06)                                                                                                                                
14:14:43:       nonce: 287103471                                                                                                                                                              
14:14:43:       in /media/sd/139eb08f-9240-40a9-a8be-ef485iha8ida2/123_280193293_14991360_14991360                                                                             
14:14:49: Error: The deadline for your nonce is too long: 765535 years, 8 months, 20 days, 9 hours, 22 mins, 19 secs (24141934257739).
```

Going to try to debug further but if anyone else was able to fix this let me know. The only part I did differently from @mpenagar was using sm_30 instead of sm_52 to optimize for the 660ti

**Comment by Creepsky** [comment]
Your output looks like from an older version.
Did you try the newest development branch?

**Comment by mikeabrahamsen** [comment]
Gave the new development branch a try, a lot easier to get working for sure. I still have the issue but I've done some debugging and have started to narrow it down some. 

I'm using CUDA 8.0
I've tried 2 different 660 ti cards, both give me incorrect deadline calculations. If I run it with the GPU and the CPU the GPU gives me different deadlines than the CPU.

I tried a GTX 1070 card and that worked fine. The deadlines matched the CPU. I might try using an older driver / cuda version for the 660 ti and see if that makes a difference

**Comment by Creepsky** [comment]
I have tested it only on a GTX 1060 with CUDA 8.0.

When you compare the deadlines on the GPU version with the ones you get on the CPU version, are they the same? For example in the log you attached do you get `12d 12:42:06` in both versions, but only in CPU it gets confirmed?
Or are they completely different for the same blocks?
