### ISSUE TITLE
could not get mining infos

### ISSUE THREAD

**Issue by N8Thrasher** [Creepsky/creepMiner#93]
![capture](https://cloud.githubusercontent.com/assets/24593637/23629751/b484f544-02c9-11e7-9e90-484755b93f2b.PNG)

Running side by side with Blagos miner on separate plot files but on same pool

**Comment by Creepsky** [comment]
Hard to say, but if I should bet all my money on my bank, I would go for a wrong submission/miningInfo-URL 😬 
```
"submission" : "http://m.burst4all.com:8124"
```

What is your config and version?

**Comment by N8Thrasher** [comment]
`{
    "logging" : {
        "config" : "information",
        "general" : "information",
        "miner" : "information",
        "nonceSubmitter" : "information",
        "output" : {
            "dirDone" : true,
            "lastWinner" : true,
            "nonceConfirmed" : true,
            "nonceFound" : true,
            "nonceOnTheWay" : true,
            "nonceSent" : true,
            "plotDone" : false
        },
        "path" : "",
        "plotReader" : "information",
        "plotVerifier" : "information",
        "server" : "fatal",
        "session" : "error",
        "socket" : "information",
        "wallet" : "information"
    },
    "mining" : {
        "intensity" : 3,
        "maxBufferSizeMB" : 512,
        "maxPlotReaders" : 0,
        "passphrase" : {
            "algorithm" : "aes-256-cbc",
            "decrypted" : "",
            "deleteKey" : false,
            "encrypted" : "",
            "iterations" : 0,
            "key" : "",
            "salt" : ""
        },
        "plots" : [
            "H:\\plots"
        ],
        "submissionMaxRetry" : 10,
        "targetDeadline" : "1y 6m 0d 15:00:00",
        "timeout" : 60,
        "urls" : {
            "miningInfo" : "http://m.burst4all.com:8124",
            "submission" : "http://m.burst4all.com:8124",
            "wallet" : "https://wallet.burst-team.us:8127"
        }
    },
    "webserver" : {
        "credentials" : {
            "hashed-pass" : "",
            "hashed-user" : "",
            "plain-pass" : "",
            "plain-user" : ""
        },
        "start" : true,
        "url" : "http://192.168.1.2:8080"
    }
}`

**Comment by N8Thrasher** [comment]
`{
"Mode" : "pool",
"Server" : "m.burst4all.com",
"Port" : 8124,

"UpdaterAddr" : "m.burst4all.com",
"UpdaterPort" : 8124,

"InfoAddr" : "m.burst4all.com",
"InfoPort" : 8124,

"EnableProxy" : true	,
"ProxyPort" : 8126,

"Paths":
[
        "E:\\plots", "F:\\plots"
],
"CacheSize" : 100000,
"ShowMsg" : false,
"ShowUpdates" : false,

"Debug" : false,

"SendBestOnly" : true,
"TargetDeadline": 31556926,

"UseFastRcv" : false,
"SendInterval" : 15,
"UpdateInterval" : 450,

"UseLog" : true,
"ShowWinner" : true,
"UseBoost" : true,

"UseHDDWakeUp" : true,

"WinSizeX" : 80,
"WinSizeY" : 60
}`

**Comment by Creepsky** [comment]
Ok so I lost all my money 😄 
But joke aside, seems like the creepMiner can't connect. Does this happen all the time?
What version do you use?

**Comment by Creepsky** [comment]
Hello @N8Thrasher,

I need some more infos on this please.
Do you still have the log file(s) and can post them somewhere?

On your Blago screenshot the last block began at ```00:02:51```, on the creepMiner screenshot it shows ```00:03:53```. What happened before this time on the creepMiner? Did the error came all the time or did it just appeared suddenly while mining? Did it work properly at later time?
