### ISSUE TITLE
Error after succefull compilation

### ISSUE THREAD

**Issue by Pascal66** [Creepsky/creepMiner#95]
I achieved to compile creepMiner, but I always got this error, what I missing ?

08.03.2017 07:26:47 (0, src\Url.cpp, 68, Warning): Could not send request to host: unknown protocol 'http'!
URI: 127.0.0.1
08.03.2017 07:26:47 (0, src\Url.cpp, 68, Warning): Could not send request to host: unknown protocol 'http'!
URI: 127.0.0.1

**Comment by Creepsky** [comment]
`unknown protocol 'http'` means that there is no handler for http registered.
Did you change something on the code? Especially in main.cpp?

**Comment by Pascal66** [comment]
Removed all references concerning IE Requesthandler & MinerServer as I consider it as an option.
Maybe something usefull was on requestHandler, but I no warning about that.

**Comment by Creepsky** [comment]
Better compile the whole project. You can disable the webserver by changing the setting `webserver.start: false`.

**Comment by Pascal66** [comment]
Allready done that. But Project need reference too SSL, so I removed things about it.

**Comment by Pascal66** [comment]
Same version, without Server part.

**Comment by Creepsky** [comment]
It's hard to say if I can't see what you changed :)
You could make a fork and push your changes there so I can look at it.

**Comment by Pascal66** [comment]
Mean a version without webserver ?

**Comment by Creepsky** [comment]
I mean your version.
The webserver has nothing to do with your issue. It don't even touches it..
You removed parts of the project, most likely the request handler and this causes your problem.

**Comment by Creepsky** [comment]
Pascal if I think about it this whole issue, it is just nonsense.

You have not successfully compiled this project, you made changes and than compiled your personal project out of it.

If every user would make changes to a project and then open an issue with the question "why is my version not working??", I would have a really bad time. :)

First you should understand what you really did. Read the code, understand it FULLY, then make changes.

**Comment by Pascal66** [comment]
Resolved, i've commented too quickly the HTTPSessionInstantiator::registerInstantiator(); in main.
And I've just removed your wonderfull addon i've not modified the code wich i read and read ;) TY
