### ISSUE TITLE
Forwarding miners causes segfault

### ISSUE THREAD

**Issue by Axadiw** [Creepsky/creepMiner#96]
Hi,

I have access to couple of mining machines (that have plot files generated for the same account). In order to send nonces from them from single machine (called "hub"), I'd like to use forwarding feature from creepminer.

According to the documentation I have used this configuration on miners:

```
...
        "timeout" : 45,
        "urls" : {
            "miningInfo" : "<address_to_hub>",
            "submission" : "<address_to_hub>",
            "wallet" : "https://wallet4.burstnation.com:8125"
        }
    },
    "webserver" : {
        "credentials" : {
            "hashed-pass" : "",
            "hashed-user" : "",
            "plain-pass" : "",
            "plain-user" : ""
        },
        "start" : false,
        "url" : "http://192.168.0.100:8080"
    }
```

and on hub:

```
...
        "urls" : {
            "miningInfo" : "<pool_address>",
            "submission" : "<pool_address>",
            "wallet" : "https://wallet4.burstnation.com:8125"
        }
    },
    "webserver" : {
        "credentials" : {
            "hashed-pass" : "",
            "hashed-user" : "",
            "plain-pass" : "",
            "plain-user" : ""
        },
        "start" : true,
        "url" : "http://0.0.0.0"
    }
```

The problem occurs when one of the miners submits nonce to the hub. 
Hub crashes with 

```Segmentation fault (core dumped)```

where last line form log file on hub is just:

```09.03.2017 21:02:14 (8, src/MinerServer.cpp, 192, Debug): Request: /burst?requestType=submitNonce&nonce=2694042348&accountId=<account_id>```

Am I doing anything wrong, or is it a problem with creepminer?

**Comment by mpenagar** [comment]
I think that on hub, webserver URL is not correct:

`"url" : "http://0.0.0.0"`

It should be (port 8080 can be changed to any other):

`"url" : "<address_to_hub>:8080"`

On the other hand, miners must point to this port too:

`"miningInfo" : "<address_to_hub>:8080",`
` "submission" : "<address_to_hub>:8080"`

**Comment by Creepsky** [comment]
@Axadiw, please see @mpenagar answer, he is absolutely right.
However, the segmentation fault should not happen. I have to debug it - or, if someone is faster, don't hesitate to post the solution or tips ;)

**Comment by Axadiw** [comment]
I have changed <adress_to_hub> to real IP address on hub's configuration, but the problem persists.

The same logs, the same behaviour :(

**Comment by Pascal66** [comment]
Bug of VS2015 and /O2 ?
[Bug VS2015](https://developercommunity.visualstudio.com/content/problem/2130/binary-crashes-if-compiled-with-o2-due-to-segmenta.html)

**Comment by Axadiw** [comment]
Don't think so, I using creepminer on linux :)

**Comment by Creepsky** [comment]
@Pascal66, @Axadiw, @mpenagar it was a dereference of a null pointer. Thanks all for your help.
