### ISSUE TITLE
Add v2-pool compatibility

### ISSUE THREAD

**Issue by Creepsky** [Creepsky/creepMiner#97]
V2 pools use a different API for pool interactions.

1. Get mining info: ```GET /pool/getMiningInfo```
2. Submitting nonces: 
```
POST /pool/submitWork
<accountId>:<nonce>:<blockheight>
```

Would be nice if the miner can automatically find out if the pool is v1/v2.
Example implementation:
```
// on first get mining info:
if (getMiningInfoV1()) --> v1 pool
else if (getMiningInfoV2()) --> v2 pool
else --> unknown pool API
```

Alternative:
New setting: ```"mining"."getMiningInfoRequest"``` and ```"mining"."submitNonceRequest"```,
with use of variables (%nonce%, %accountId%, %blockheight%, ...) and HTTP methods (GET, POST, PUT, ...).

Would be future proofed but very bloated for such a small miner.

**Comment by Pascal66** [comment]
There's no submitWork and no blockheight parameter (in my side, and according the actual API)

**Comment by Creepsky** [comment]
Hey Pascal,
may be that I'm wrong :grin: but as long as I understood it, there are two versions of pools with different APIs.
But thanks for saying this, will figure it out.

**Comment by Pascal66** [comment]
Are you talking about Ninja pools wich are called V1
And Uray's wich are called V2 ?
I'm sure that the coders of Ninja have already modified the code to adapt this evolution for all miners.
Wich pool use the old V1 version ?

**Comment by Creepsky** [comment]
Then it's obsolete.

**Comment by Pascal66** [comment]
Then you can take time you :)
